### ISSUE TITLE
Is there an uwp version?

### ISSUE THREAD

**Issue by pardont** [rotorgames/Rg.Plugins.Popup#10]
Hi, your Popup component works great, but is there an uwp version? 

Thanks

**Comment by rotorgames** [comment]
@pardont Hi friend. Sorry, Popup plugin not supported uwp. Im not have time, for writing uwp version. You can fork my repository and write uwp version themselves.

**Comment by pardont** [comment]
@rotorgames  sorry for the late reply, I will take a try.

Thank you.

**Comment by EmilAlipiev** [comment]
This plugin is awsome. I tried many other plugins for xamarin but definetly the best one. I really wish that it supports winphone 8.1 and uwp as well. I appreciate if anyone can find a solution. I am looking forward to it.

**Comment by rotorgames** [comment]
@EmilAlipiev Hi friend. At this point, I have no time. I am engaged in commercial project. Once I'm released, first and foremost, writing version UWP (WindowsPhone).

**Comment by rotorgames** [comment]
@pardont @EmilAlipiev Hi friends. You can now try the version for Windows Phone and UWP in the pre release.

I would be grateful if, after testing, you write here about the result. Thank you

https://www.nuget.org/packages/Rg.Plugins.Popup/1.0.0-pre1
