### ISSUE TITLE
Spacing on the top of the PopupPage

### ISSUE THREAD

**Issue by stringo** [rotorgames/Rg.Plugins.Popup#100]
Hi, thanks for your fantastic plugin.

I have a doubt on the styles of the PopupPage, this is the scenario:

I have a PoupPage with a custom navigation bar made from a ContentView, I do this in some other Pages (not PopUp) along my application. In the case of the PopUp pages, a blank space is being set in the top of the PopUp. I would like to know if this has something to do with the styles of the PoupPage and how can I remove it.

Please refer to the following image:
https://ibb.co/cHavLa

PS: If this has nothing to do with the styles of the PopUp page feel free to close the issue.

**Comment by rotorgames** [comment]
@stringo Hi. You can do it if you set `HasSystemPadding` of PopupPage to `false`. But then maybe PopupPage will not be able to change layout when keyboard will be opened. I will fix it in the next version.
