### ISSUE TITLE
SystemOffsetPage

### ISSUE THREAD

**Issue by dhanasekaranns** [rotorgames/Rg.Plugins.Popup#103]
am getting a error in systemoffset page error:"object not sets to an instance of an object'....am used a same code that ur used in systemoffset  page...can u figure out y am getting this error

can u help me..

thanks
dhanasekaran

**Comment by rotorgames** [comment]
@dhanasekaranns Hi. Sorry for long answer. Did you install nuget package in droid, ios and UWP projects or did you install only in PCL

**Comment by dhanasekaranns** [comment]
installed in droid and pcl...I unloaded other projects

**Comment by rotorgames** [comment]
@dhanasekaranns Can you show stack trace?
