### ISSUE TITLE
Exception when opening pop page

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [rotorgames/Rg.Plugins.Popup#104]
Hi,
I downloaded sample. It's working fine. 
Now I created new project and copied loginpopuppage code into MyPopPage and made neccessary changes(like x:class, ctor..)

I have a button in main page,when clicked should open pop up page.
But I am getting following exception

**System.TypeInitializationException: The type initializer for 'Rg.Plugins.Popup.Services.PopupNavigation' threw an exception. ---> System.MethodAccessException: Method `Rg.Plugins.Popup.Services.PopupNavigation:.cctor ()' is inaccessible from method `Rg.Plugins.Popup.Platform.Renderers.Loader:Load ()'**

I am navigating as follows 
```
        private async void PopUp_ClickedAsync(object sender, EventArgs e)
        {
            var page = new MyPopupPage();

            await Navigation.PushPopupAsync(page);

            // await PopupNavigation.PushAsync(page);
        }
```

MyPopUpPage is exact copy of Loginpopuppage with few changes mentioned above.

I am using v1.0.4 with XF 2.3.3.193

**Comment by CodeSpeak11** [comment]
Install via nuget to pick and device projects 

Patrick

**Comment by rotorgames** [comment]
@avinashramireddy-rapidd Hi, sorry for long answer. Did you use nuget packages?

**Comment by avinashramireddy-rapidd** [comment]
No, I did manual copying of your files.

**Comment by rotorgames** [comment]
It will not be work that. You should use nuget package or clone this repository
