### ISSUE TITLE
[Feature request] OnDismissed method

### ISSUE THREAD

**Issue by chaselal** [rotorgames/Rg.Plugins.Popup#106]
I'm interested in adding a `virtual void OnDismissed` method to `PopupPage`. Basically, it would be called when the popup is completely closed. So I think it should be called immediately after `Animation.Disappearing` completes. @rotorgames any objection to this? I can work on it and PR if you are okay with it.

I want this feature because I need to show a popup with a Cancel button. If the user touches Cancel, then the popup should close and I should raise an event saying the popup closed. I need to do the same thing if the popup is dismissed by pressing the back button.

**Comment by rotorgames** [comment]
@chaselal Hi. Sorry for long answer. You can use OnDissapearing method.
