### ISSUE TITLE
different behaviour between iOS and Android

### ISSUE THREAD

**Issue by aconte80** [rotorgames/Rg.Plugins.Popup#107]
I'm developing an Xamarin.Forms app (build against API LEVEL 25 on Android and SDK 10.3 on iOS) consisting in a main page (Forms) acting as NavigationPage that can navigate to a native second page (Form2Native with PageRenderer on each platform). 
Rg.Popup is used both on forms pages and native pages to show popups (acting as 'message boxes').

What i'm facing is that:
- on IOS all works fine, popup pages is shown correctly (topmost, modal etc)
- on ANDROID I've no errors but popup won't be shown. Looking further for possible causes i see that popup is showed but UNDER second activity.. so when I close (Finish()) it, coming back to forms popup became visible.

What can I do?

**Comment by CodeSpeak11** [comment]
I'm compiling my android project using 7.1 and minimum Android to target 4.0.3 API level 15 Ice Cream Sandwich. Not seeing any problems on emulator (Android 4.4-API 19) or MotoE physical device running Android 5.1.  Might need to provide more information about what you are doing. 

Code to show popup:
   var page = new GroupList(viewModel);
   page.Opacity = 80;
   page.BackgroundColor = Color.Silver;
   await PopupNavigation.PushAsync(page);

Code to hide popup:
   PopupNavigation.PopAllAsync(true);

**Comment by aconte80** [comment]
@CodeSpeak11 it's not a problem of showing popup in Android.. my working situation in more complicated, I'll try to exemplify it:

Entry points:
Xamarin.Android: MainActivity
Xamarin.iOS: AppDelegate

both of them call LoadApplication(new App())  

Xamarin.Forms:

public App()
		{
			// The root page of your application
			MainPage = new NavigationPage(new Page1());
		}


Page1 is a ContentPage.

In 'Forms' I have also a MessageBox (with full namespace MyApp.Shared and classname MessageBox : PopupPage ). Your code, await PopupNavigation.PushAsync()... ,is inside method Show() of MessageBox class).

So, if I call from Page1 MyApp.Shared.MessageBox.Show() all works fine and popup will appear.

But, now I want to navigate to a second NATIVE page:

Xamarin.Android: SecondPageActivity
Xamarin.iOS: SecondPageViewController

and I use 'Form2Native' tecnique (I create a page renderer and so on...): it works, from Page1 i can navigate to SecondPage (android or ios depending on runtime).

Now, from SecondPage, I call Shared.MessageBox.Show(): 
- on iOS all works fine and i can see my messagebox (rg.plugin) popup on top of SecondPageViewController
- on ANDROID i can't see it because it goes UNDER SecondPageActivity and when I call Finish() i return on Page1 and i can see messagebox still visibile.

**Comment by rotorgames** [comment]
@aconte80 Hi. Sorry for long answer. Rg.Plugins.Popup uses DecorView in android that to open popup pages. If you open new Activity, then you can't see PopupPage because it will be in previous Activity.
