### ISSUE TITLE
PopupNavigation.PopAsync() doesn't let OnAppearing method on parent page to be executed

### ISSUE THREAD

**Issue by miladtai** [rotorgames/Rg.Plugins.Popup#109]
PopupNavigation.PopAsync() doesn't let OnAppearing method on parent page to be executed.
How can i do refresh/update elements on parent/background page immediately when the PopupPage is disappeared ?

**Comment by acaliaro** [comment]
I think you can usa a MessagingCenter from Popup to PreviousPage

**Comment by miladtai** [comment]
how ?  :/

**Comment by rotorgames** [comment]
See #51
