### ISSUE TITLE
Label not binding

### ISSUE THREAD

**Issue by kfchengkf** [rotorgames/Rg.Plugins.Popup#111]
I have a simple Popup with the xaml looks like this:
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             x:Class="ExpenseManager2.KeyPad">
  <StackLayout VerticalOptions="Center" HorizontalOptions="Center" Padding="0" Margin="0">
    <Frame Margin="0" Padding="5" BackgroundColor="Green">
      <Frame.Content>
        <StackLayout Padding="5" Margin="2" BackgroundColor="White" Orientation="Vertical">
          <Label Text="{Binding MainText}" VerticalOptions="Center" HorizontalOptions="Center" TextColor="Black" />
          <Label Text="Static Text here" VerticalOptions="Center" HorizontalOptions="Center" />
          <Button Command="{Binding AddCommand}" Text="Add"></Button>
        </StackLayout>
      </Frame.Content>
    </Frame>
  </StackLayout>
</pages:PopupPage>

and the code behind class looks like this (portion)
    public partial class KeyPad : PopupPage
    {
        public string MainText { get; set; }
        private RelayCommand _addExpenseCommand;
        public RelayCommand AddCommand => _addExpenseCommand ?? (_addExpenseCommand = new RelayCommand(Add));

        public KeyPad()
        {
            InitializeComponent();
            BindingContext = this;
            MainText = "This is a pad very long gog go go !!!!";
        }

        protected override void OnAppearing()
        {
            MainText = "Changed to second version a pad very long gog go go !!!!";
            base.OnAppearing();
        }

        public void Add()
        {
            PopupNavigation.PopAsync();
        }

    }

The first Label binding to MainText does not work, no matter whether I set it in constructor or OnAppearing.

However, the add command binding does work. Also, the "Static Text here" is showing.

Do you know why ?

Thanks.

**Comment by rotorgames** [comment]
@kfchengkf It is not working because you should use PropertyChanged. It doesn't relate to Popup plugin.

**Comment by kfchengkf** [comment]
Thanks for the hint. I will investigate. But I have other normal pages that uses the same/similar MainText (default generated by VS2015) and they all shown up on the page properly.

**Comment by rotorgames** [comment]
@kfchengkf They has worked because MainText could be setted before loading page. But you set MainText in OnAppearing methods when page was loaded. MainText just property and it doesn't invoce OnPropertyChanged so Label doesn't know that text was changed;
