### ISSUE TITLE
Popups are invisible in Plugin 1.1.0-pre1

### ISSUE THREAD

**Issue by alezhuk** [rotorgames/Rg.Plugins.Popup#119]
Found the issue in iOS 8.4.1, which is reproducible on device/simulator. When try to show popup it is not visible, but popup stack is filled.

**Comment by rotorgames** [comment]
@alezhuk I pushed changes. Please review new 11.1.0-pre2 version and tell me about results.

**Comment by alezhuk** [comment]
@rotorgames Fixed in 1.1.0-pre2. Thanks!

**Comment by rotorgames** [comment]
@alezhuk You are welcome. Closed
