### ISSUE TITLE
Windows Phone

### ISSUE THREAD

**Issue by cpmd** [rotorgames/Rg.Plugins.Popup#12]
Hi ,

    Can you please update when windows phone will be support.

Thanks
cpmdteam

**Comment by rotorgames** [comment]
@cpmd Hi friend. You can now try the version for Windows Phone and UWP in the pre release.

I would be grateful if, after testing, you write here about the result. Thank you

https://www.nuget.org/packages/Rg.Plugins.Popup/1.0.0-pre1

**Comment by EmilAlipiev** [comment]
i update both UWP and XF projects with the new release but unfortunately didnt work. i get error message as 

```
System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
   at Xamarin.Forms.Plat
```

**Comment by rotorgames** [comment]
@EmilAlipiev please try it. [Link](http://stackoverflow.com/questions/13361199/error-hresult-e-fail-has-been-returned-from-a-call-to-a-com-component-vs2012-whe)

**Comment by rotorgames** [comment]
@EmilAlipiev P.S. Create new project and try in it.

**Comment by belandsoft** [comment]
Please can you update the documentation? I mean, windows version needs some kind of initialization like iOS or nothing like Android?

**Comment by rotorgames** [comment]
@belandsoft WP and UWP don't initialize. Documentation comming soon

**Comment by rotorgames** [comment]
@belandsoft [WP and UWP documentation in v1.0.0-pre3](https://github.com/rotorgames/Rg.Plugins.Popup/blob/v1.0.0/README.md)

**Comment by belandsoft** [comment]
Thank you! I think it will be usefull even to other devs.
