### ISSUE TITLE
Crash when pressing back button on Android

### ISSUE THREAD

**Issue by jderrough** [rotorgames/Rg.Plugins.Popup#120]
Hi,

I'm experiencing crashes from PopupNavigationDroid.OnBackPressed:

```
Caused by android.runtime.JavaProxyThrowable: System.IndexOutOfRangeException: There is not page in PopupStack at Rg.Plugins.Popup.Services.PopupNavigation.PopAsync (System.Boolean animate) [0x0000c] in <e4a0d036d16d43a8a07fbef673df812b>:0 at Rg.Plugins.Popup.Droid.Impl.PopupNavigationDroid+<>c+<<OnBackPressed>b__5_0>d.MoveNext () [0x0000a] in <6a73fa7e881340e5abe759d8a2e8a50e>:0
```

I believe that the conditions to reproduce it are to press the back button when popping a popup from somewhere in the code at the same time.
Both would execute the pop on the UI thread, but I think PopupNavigationDroid.OnBackPressed should check the size of the stack on the UI thread right before executing the pop.

Hope this makes sense.

Best,
Jonathan

**Comment by rotorgames** [comment]
@jderrough Thank you for report. I will fix it.

**Comment by rotorgames** [comment]
@jderrough I pushed changes. Please review new 11.1.0-pre2 version and tell me about results.

**Comment by jderrough** [comment]
Thanks, @rotorgames! I'll take a look.

**Comment by jderrough** [comment]
Seems fixed to me. Thanks again!

**Comment by rotorgames** [comment]
@jderrough You are welcome. Closed
