### ISSUE TITLE
background click doesnt close popup in UWP

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#126]
I am using latest stable version and  I recognized when I click on background, popup doesnt close in UWP. this works fine in Android. Am I missing something?

**Comment by rotorgames** [comment]
@EmilAlipiev Please try to use last pre release.

**Comment by EmilAlipiev** [comment]
@rotorgames thanks for quick response. as I read that you solved memory issue on pre, is it correct? is there any know issue prevents me to go live with pre release issue?

**Comment by rotorgames** [comment]
@EmilAlipiev Memory leaks have been on all previous versions before v1.1.0-pre. You can go to last pre. It fixs a lot of bugs. For more information see the log in the nuget.

**Comment by EmilAlipiev** [comment]
@rotorgames  tried latest pre-release but problem is still there. UWP background click is not closing. Tested on Local PC and emulator

**Comment by rotorgames** [comment]
@EmilAlipiev Ok, I will review it.

**Comment by EmilAlipiev** [comment]
using InputTransparent worked on UWP.
