### ISSUE TITLE
BackgroundClicked doesn't close Popup  in IOS 

### ISSUE THREAD

**Issue by MuruganDurai** [rotorgames/Rg.Plugins.Popup#127]
i used this popup to open when the  toolbar items clicked in the page 
But, its does n't work properly
onBackgroundClicked event not triggered in  ios
In Android running Smoothly on Toolbar items and page buttons

**Comment by EmilAlipiev** [comment]
which version are you using? see the issue I created for uwp. he suggested to use pre release version.

**Comment by KarthikeyanSekar93** [comment]
after update app will crash on IOS only

**Comment by rotorgames** [comment]
@KarthikeyanSekar93 What version are you using now? What crashes do you have on iOS now?

**Comment by KarthikeyanSekar93** [comment]
1.0.4

**Comment by rotorgames** [comment]
How toolbar items do you meand? Can you show a screenshot or capture a video with a problem?

**Comment by KarthikeyanSekar93** [comment]
![c2](https://user-images.githubusercontent.com/12829801/26886822-0d4ffbf4-4bc4-11e7-8086-546b89c88c58.png)
![c1](https://user-images.githubusercontent.com/12829801/26886831-12700a0c-4bc4-11e7-96fb-e239d05c3b6d.png)
These are the two images.

**Comment by rotorgames** [comment]
Can you update the plugin to 1.0.0-pre3. I think that it will fix your problems with background

**Comment by KarthikeyanSekar93** [comment]
when i using  1.0.0-pre3 **Object reference not set to an instance of an object** error thrown for all the popup window

**Comment by EmilAlipiev** [comment]
I dont see pre-3 on nuget. is it not published yet?

**Comment by rotorgames** [comment]
@KarthikeyanSekar93 @EmilAlipiev  Sorry. I have not yet published pre3. Please wait. 

P.S. @EmilAlipiev BackgroundClicked will work only if a content of PopupPage doesn't fill on all page.

**Comment by KarthikeyanSekar93** [comment]
1.0.0 pre-3 is there @EmilAlipiev  & @rotorgames  on visual studio
![rgpopup](https://user-images.githubusercontent.com/12829801/26924202-69a9a0fa-4c62-11e7-9df9-b7676b092556.png)

**Comment by rotorgames** [comment]
@KarthikeyanSekar93 there is not pre3 in the visual studio. You should wait new release.

**Comment by EmilAlipiev** [comment]
@rotorgames  I am not sure why you mean by all page. My popup fills the page but background is totally transparent like @KarthikeyanSekar93 sample and I thought It should close the popup when I click the transparent part like @KarthikeyanSekar93 indicated. This is how it works fine on android

**Comment by EmilAlipiev** [comment]
It looks something like this on UWP. as you see totally transparent

![image](https://user-images.githubusercontent.com/10422347/26924346-b9dd4fb2-4c45-11e7-80d7-8a210f001a39.png)

**Comment by rotorgames** [comment]
@EmilAlipiev Even if your content of PopupPage has transparent background but the content fills all page, BackgroundClicked will not work. If you want to have working BackgroundClicked then you should add Margin to your content or set VerticalOption or HorizontalOption to Start, End or Center. Also you can try to set InputTransparent to the content but I can't promise that it will work.

**Comment by EmilAlipiev** [comment]
@rotorgames ok I will try that but strange why it works on android.

**Comment by rotorgames** [comment]
@KarthikeyanSekar93 Please give me the stack trace which is thrown when you use pre2 "Object reference not set to an instance of an object"

**Comment by rotorgames** [comment]
@EmilAlipiev iOS and Android have different touch behaviors. Also the popup plugin uses UIWindow for  showing popups on iOS. I think that it is source of the problem.

**Comment by KarthikeyanSekar93** [comment]
@EmilAlipiev please set bg-color for your content page if you fully occupied the window use **GestureRecognizers** **Tapped="onTappedBackgroundClicked"**

[private void onTappedBackgroundClicked(object sender, EventArgs e)
        {
            Navigation.PopPopupAsync();
        }](url)

**Comment by KarthikeyanSekar93** [comment]
@rotorgames  when i used 1.0.0 pre-3 error thrown. but latest pre release does not show any error .Now am using latest stable version.

**Comment by rotorgames** [comment]
@KarthikeyanSekar93 pre-3 doesn't exist. Please, update plugin to pre-2 and give me the stack trace of error if it is.

**Comment by KarthikeyanSekar93** [comment]
@rotorgames  are u talking about 1.0.0-pre3 or 1.1.0-pre3 .. U will Suggest  this version

> Can you update the plugin to 1.0.0-pre3. I think that it will fix your problems with background

**Comment by rotorgames** [comment]
@KarthikeyanSekar93 sorry, I have said about v1.1.0-pre2

**Comment by KarthikeyanSekar93** [comment]
@rotorgames  What is the solution ?

**Comment by rotorgames** [comment]
You should understand that if a `View` in `PopupPage.Content` has `HorizontalOptions` and `VerticalOptions` = `Fill` or `FillAndExpand` then this content will catch all touches and `PopupPage.OnBackgroundClicked` will not be invoked. Set `HorizontalOptions` and `VerticalOptions` to `Center` and you will be able to see that `PopupPage.OnBackgroundClicked` will be invoked.

**Comment by ravinderjangra** [comment]
I'm using the latest version and the same code is working on Android but not on iOS. I'm using EndAndExpand not file or expand. Any solution?

**Comment by rotorgames** [comment]
@ravinderjangra I need more details and examples to understand what's wrong.
