### ISSUE TITLE
Title bar missing in Contentpage

### ISSUE THREAD

**Issue by MuruganDurai** [rotorgames/Rg.Plugins.Popup#128]
Hi, I just re-used your code for navigation transition animation between content pages to avoid default navigation. It's working like a charm but the thing is that I could not get the navigation bar working (missing). Is there anyway to make it work like default navigation ( bars with back icon, page title).

**Comment by MuruganDurai** [comment]
Hi @rotorgames Any update on this?

**Comment by rotorgames** [comment]
@MuruganDurai Hi. The popup plugin doesn't support NavigationPage and Toolbar. You can open only PopupPage.

**Comment by MuruganDurai** [comment]
@rotorgames  How to add NavigationPage & toolbar with this component? Can you please shed some light?

**Comment by rotorgames** [comment]
@MuruganDurai this is impossible!

**Comment by rotorgames** [comment]
I have added a NavigationPage support to the backlog. Maybe I will create a support if I can.
