### ISSUE TITLE
web view not woring

### ISSUE THREAD

**Issue by maxdiable** [rotorgames/Rg.Plugins.Popup#129]
hi,

I created a "PopupPage" page, I put a webview, I set the source but the web view does not show anything.
this is my code:
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             xmlns:controls="clr-namespace:XLabs.Forms.Controls;assembly=XLabs.Forms"
             x:Class="PayAndShare.Views.Common.InfoPage">

    <AbsoluteLayout VerticalOptions="FillAndExpand">
        <Frame Margin="15" HorizontalOptions="Center" BackgroundColor="White">
            <StackLayout Orientation="Vertical">
                <StackLayout Orientation="Horizontal" VerticalOptions="Start">
                    <Label Text="Non visualizzare più" TextColor="#0477B3" VerticalOptions="Center" HorizontalOptions="StartAndExpand" />
                    <Switch HorizontalOptions="End" VerticalOptions="Center" IsToggled="{Binding IsNotShowInfo, Mode=TwoWay}" Toggled="SwitchShowInfo_Toggled" />
                </StackLayout>
                <StackLayout VerticalOptions="CenterAndExpand">
                    <BoxView HorizontalOptions="Fill" HeightRequest="1" BackgroundColor="#0477B3"></BoxView>
                    <WebView x:Name="_webView" Source="http://www.go9gle.com" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"></WebView>
                    <BoxView HorizontalOptions="Fill" HeightRequest="1" BackgroundColor="#0477B3"></BoxView>
                </StackLayout>
                <StackLayout Orientation="Horizontal" VerticalOptions="End">
                    <Button BackgroundColor="#0477B3" Text="Chiudi" TextColor="White" Command="{Binding CloseCommand}" BorderRadius="2" BorderWidth="1" BorderColor="White">
                    </Button>
                    <Button BackgroundColor="#0477B3" Text="Scopri di più" TextColor="White" Command="{Binding OtherInfoCommand}" BorderRadius="2" BorderWidth="1" BorderColor="White">
                    </Button>
                    <Button BackgroundColor="#0477B3" Text="Registrati" TextColor="White" Command="{Binding RegisterCommand}" BorderRadius="2" BorderWidth="1" BorderColor="White">
                    </Button>
                </StackLayout>
            </StackLayout>
        </Frame>
    </AbsoluteLayout>

</pages:PopupPage>

any help?

br
max

**Comment by rotorgames** [comment]
@maxdiable Hi. Did you try to use this xaml code without the popup plugin?

**Comment by maxdiable** [comment]
i just call the page: PopupNavigation.PushAsync(new InfoPage());
but ust this page, other page is ok

**Comment by maxdiable** [comment]
Hi, I solved by deleting the page and re-creating it with another name
br
max

**Comment by rotorgames** [comment]
@maxdiable Nice to hear it. Closed
