### ISSUE TITLE
Nuget Package Exception for Plugin Reference 

### ISSUE THREAD

**Issue by KathirveluM** [rotorgames/Rg.Plugins.Popup#13]
Hi, 
I have created sample application to check the Popup layout and added the Nuget Reference to "Rg.Plugins.Popup" Library .
After adding the reference it throws the Exceptions for "package Android.support.v7.internal.widget"
But we have updated the SDK Manager with All latest versions(up to 23) . Please refer the error screenshot for reference. 

[Android Package Error](https://drive.google.com/file/d/0B6bG1xe08IeXTjM4SGpXTEk5YU0/view)

Kindly help me to resolve the issue.

**Comment by rotorgames** [comment]
Hi friend.

Write this information

Version Xamarin.
Version Xamarin Forms
The version of Android SDK, Max, min and target
Popup plugin version

**Comment by KathirveluM** [comment]
Hi Rotorgames,

Thanks for your support  rotorgames.
We have fixed the below error. The error is occurred due to long source path mapped for updating the Android java inflator files. 

This is for your information:
Version Visual Studio : 4.0.3.214
Version Xamarin studio: 5.10.1(build 6)
Version Xamarin Forms: 2.2.0.31
Android SDK:-
Compile : API Version 23
Target : API Version 23
Minimum : API Version 19
Popup plugin version:0.0.16

**Comment by KathirveluM** [comment]
Hi,

Please remove this post.
https://github.com/rotorgames/Rg.Plugins.Popup/issues/14

I have found the property which you have used in your GitHub source Library
for the question.

Property Name: IsCloseOnBackgroundClick

Its working fine as expected.

Sorry for the trouble.
