### ISSUE TITLE
Question: How to determine popup is pushed?

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#130]
How can I understand if there is an active popup? is there built in method like "Popup.IsActive".
Based on this I would like to change Page in the background.

**Comment by rotorgames** [comment]
@EmilAlipiev You can do `PopupNavigation.PopupStack.Any()`. If it is true then there are popups in the screen.

**Comment by EmilAlipiev** [comment]
Thanks. this is workiing

**Comment by EmilAlipiev** [comment]
Just to update. this is obselete and new syntax is Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Any()
