### ISSUE TITLE
Login form need double tap to submit form when soft Keyboard is present in iOS

### ISSUE THREAD

**Issue by koland** [rotorgames/Rg.Plugins.Popup#133]
Login form need double tap to submit form when soft Keyboard is present in iOS.

How can I fix that?

**Comment by alezhuk** [comment]
@koland Try to use **v1.1.0-pre2**

**Comment by koland** [comment]
Thx, will try and then give feedback to you

**Comment by koland** [comment]
Cool!!! Now all works!!!! Thx, man!

**Comment by rotorgames** [comment]
@koland I glad to see that you have resolved your problem. Good luck.
