### ISSUE TITLE
PushPopupAsync doesn't work in UWP release mode. Also it crashes. Work perfectly in debug mode

### ISSUE THREAD

**Issue by RenjithPr90** [rotorgames/Rg.Plugins.Popup#137]
Hi, 

  I am using "Rg.Plugins.Popup" version="1.0.4". Pushpopupasync is not working in UWP release mode. It works in debug mode. Am i missing anything. Error getting is Arg_NullReferenceException. I have also added Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies(); in mainpage in uwp, but still it doesn't work

**Comment by rotorgames** [comment]
@RenjithPr90 See https://github.com/rotorgames/Rg.Plugins.Popup#uwp-example

**Comment by RenjithPr90** [comment]
@rotorgames  yes its working. My mistake i added Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies() in mainpage instead of app.xaml.cs. Thank you. b/w it's a great plugin
