### ISSUE TITLE
[iOS simulator] PopupNavigation.PushAsync and Navigation.PushPopupAsync methods not found in base type exception

### ISSUE THREAD

**Issue by Progdrasil** [rotorgames/Rg.Plugins.Popup#138]
Running a listview popup on iOS simulator returns the error described in the title. However the popup works like a charm on android simulator and a physical iOS device.

## Steps to reproduce:
* clone Demo.Pages.ListViewPage.xaml and .xaml.cs
* create new ListViewPage in main page.
* on button click await PopupNavigation.PushAsync(page); or Navigation.PushPopupAsync(page);
* select ios as Startup project
* debug in iPhoneSimulator, iPhone 7 iOS 10.3.1

**Comment by rotorgames** [comment]
@Progdrasil Please give me full stack trace

**Comment by Progdrasil** [comment]
I use version 1.0.4, however i cant give stack trace because the demo is giving me a build error in russian

**Comment by rotorgames** [comment]
@Progdrasil Sorry for long answer. Did you install the popup plugin to each project (Android, iOS)? If you exactly sure that you have done it then please, remove the popup plugin from each project, remove `packages` folder from the project and install the popup plugin again to each project.

P.S. You can try to use v1.1.0-pre2 if you want

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.
