### ISSUE TITLE
The memory is not released on Android

### ISSUE THREAD

**Issue by willowvil** [rotorgames/Rg.Plugins.Popup#139]
Hi,

After open and close a simple popup several times, I have noticed that the memory consumed is increasing and never released. I have tried to use GC.Collect() with no exit.

Thanks in advance.

**Comment by willowvil** [comment]
It seems v1.1.0-pre2 solves the problem

**Comment by EmilAlipiev** [comment]
are you sure that it solves the problem? for me it seems that still memory usage is quite high when popup is on the screen.

**Comment by EmilAlipiev** [comment]
There is still cycle appears in android as shown below. it doesnt looke like problem is not solved. how is your profiling results?

![image](https://user-images.githubusercontent.com/10422347/33692410-6fbcb1de-daed-11e7-9951-018090384a28.png)

**Comment by rotorgames** [comment]
@EmilAlipiev Hi. Can you give me your profiler file?
