### ISSUE TITLE
[iOS] Popup content shifted up in 1.1.0-pre2

### ISSUE THREAD

**Issue by MichaelRumpler** [rotorgames/Rg.Plugins.Popup#142]
When I updated from 1.1.0-pre1 to 1.1.0-pre2, the content of my popup was shifted up.

This is how it looked in pre1:
![1 1 0-pre1](https://user-images.githubusercontent.com/8309363/27476045-8b9ed29c-5807-11e7-9ece-dba00c4de28d.jpg)

And in pre2 it is too far up:
![1 1 0-pre2](https://user-images.githubusercontent.com/8309363/27476067-9b542c0a-5807-11e7-99b3-38d67b019bcf.jpg)

I'm trying this on an iPad Pro with iOS 10.3.2. The popup does not use any animation.
The Label gets the focus on appearing. If I close the keyboard, then the contents are shown at the correct position, but when I set the focus to the Label to show the keyboard again, the content will be shifted up once more.

I tried setting SystemPadding, but that had no effect. Setting HasSystemPadding="false" did not shift the popup up when the keyboard was opened.

**Comment by rotorgames** [comment]
@MichaelRumpler Give me your xaml code which you use in PopupPage please.

**Comment by MichaelRumpler** [comment]
I added a repro page to https://github.com/MichaelRumpler/Rg.Plugins.Popup/tree/Repro_142
The xaml for this specific page is in https://github.com/MichaelRumpler/Rg.Plugins.Popup/blob/Repro_142/src/Demo/Demo/Pages/ReproPage.xaml

It's the complete page just to be sure.

**Comment by rotorgames** [comment]
@MichaelRumpler Thank you for examples. I will look it soon.

**Comment by shineon84** [comment]
Any update about this? Thanks

**Comment by rotorgames** [comment]
@shineon84 I will work on it soon.

**Comment by MichaelRumpler** [comment]
I updated my branch to the current master. This represents Rg.Plugins.Popup 1.1.4 and uses Xamarin.Forms 3.0. It still has the same problem.
The content is shifted up when I hold the iPad in landscape and tap the Label to show the keyboard.

**Comment by rotorgames** [comment]
@MichaelRumpler I have reviewed this issue and I can say that it is not popup's problem. Xamrin.Forms contains special class `KeyboardInsetTracker` which changes `ContentOffset`of `UIScrollView` or `UITableView` when a keyboard appears. I can avoid this behavior only if I use Reflecion but I don't want to do it. Now I'm creating special properties for PopupPage which will allow to avoid resizing a popup when keyboard appears. They will be available for using in the next version.

**Comment by MichaelRumpler** [comment]
I'm ok with a workaround.
I do understand that you don't want to use Reflection in your library. Could you tell me what I need to do to work around it on my end?

Until now I just sticked with version 1.1.0-pre1, but I switched my PCL to .NET Standard now and that complains when I want to install that old version.

**Comment by rotorgames** [comment]
@MichaelRumpler try to use [v1.1.5.180](https://github.com/rotorgames/Rg.Plugins.Popup/releases/tag/v1.1.5.180) and to set `HasKeyboardOffset` of `PopupPage` to `false`. It will be default xamarin.forms behavior.

**Comment by MichaelRumpler** [comment]
Unfortunately this makes it even worse. The popup doesn't move up now and part of the popup is also overlayed by the keyboard.
![img_0137](https://user-images.githubusercontent.com/8309363/49428049-4a1ed800-f7a5-11e8-8b4d-a01d2e35569e.PNG)

The popup itself should move up, but it's contents shouldn't move out of it. See the title bar in the very first screenshot.

**Comment by rotorgames** [comment]
@MichaelRumpler You need to keep all elements inside ScrollView, and set VerticalOptions=Fill for ScrollView and Center for Content of ScrollView

**Comment by MichaelRumpler** [comment]
This makes the popup full height even without keyboard.
![img_0138](https://user-images.githubusercontent.com/8309363/49432566-4fcdeb00-f7b0-11e8-9c1f-c2f1ecd525f4.PNG)
It should only be as high as its content from the Title to the Cancel/OK buttons.

I updated the repro in https://github.com/MichaelRumpler/Rg.Plugins.Popup/blob/Repro_142/src/Demo/Demo/Pages/ReproPage.xaml#L81

**Comment by rotorgames** [comment]
@MichaelRumpler You set `BackgroundColor="White"` for `ScrollView`, move it to `StackLayout` and the page will look good.

**Comment by MichaelRumpler** [comment]
This is funny! Any reason why this caused problems?

Many thanks, now everything works as it should. Let me know if you come to Vienna/Austria. I owe you something.

**Comment by rotorgames** [comment]
@MichaelRumpler You are welcome. It happens because of `KeyboardInsetTracker`, it is an internal class in Xamarin.Forms, you can see how it works [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs#L75). This class detects a keyboard appearing and add bottom offset for `ScrollView` and `ListView`. I can't avoid this behavior because it is the internal Xamarin.Forms behavior. We only can ask the team of Xamarin.Forms to create special platform-specific methods which will allow disabling this behavior.

**Comment by MichaelRumpler** [comment]
Yes, but why does it change when I move the `BackgroundColor` property to a different element?

**Comment by rotorgames** [comment]
@MichaelRumpler Because `ScrollView` had `Fill` vertical size and you saw white `BackgroundColor` of `ScrollView` but when I moved `BackgroundColor` to `StackLayout` it was ok because `StackLayout` had `Center` vertical size and didn't fill all vertical space.
