### ISSUE TITLE
Support macOS with Xamarin.Forms 2.5 on Xamarin.Mac V2.0

### ISSUE THREAD

**Issue by YZahringer** [rotorgames/Rg.Plugins.Popup#143]
Currently support for macOS by Xamarin is in beta with version 2.3.5. Would it be possible to provide a pre-release with macOS support?

**Comment by rotorgames** [comment]
@YZahringer Thank you for question. I will think about support Xamarin.Forms for MacOS

**Comment by YZahringer** [comment]
@rotorgames Thank's. Any news for macOS support?

**Comment by rotorgames** [comment]
@YZahringer Hi. I'm so sorry but I have a lot of work to fix bugs from this project. I should fix bugs and only then I can begin to create support other platforms. 

Thank you.

**Comment by LuckyDucko** [comment]
Bump @martijn00 
I believe Rg.plugins.popups works on [MacOS](https://github.com/rotorgames/Rg.Plugins.Popup/commit/d823f3ddac83e368aab9614a9e936536c562f32f#diff-04c6e90faac2675aa89e2176d2eec7d8)
