### ISSUE TITLE
Popups not appearing with Iphone 6plus running iOS 8.4

### ISSUE THREAD

**Issue by CodeSpeak11** [rotorgames/Rg.Plugins.Popup#144]
Working fine on iOS 9.3.5 running on IPAD 2, and iPhone 6Plus running 10.3.2. I will check with the other plugins I'm using but it seems this information should be included in the readme. I couldn't find any mention of iOS or android versions supported.

**Comment by rotorgames** [comment]
@CodeSpeak11 Hello. Thank you for question. What version of the popup plugin do you use? I think that if you update to 1.1.0-pre2 then you can fix your problem.

**Comment by rotorgames** [comment]
@CodeSpeak11 It has been fixed #119
