### ISSUE TITLE
await App.Navigation.PushPopupAsync() doesn't work

### ISSUE THREAD

**Issue by cat-cat** [rotorgames/Rg.Plugins.Popup#146]
this code

await App.Navigation.PushPopupAsync(new pgEditMessage(this));

at this line

https://github.com/cat-cat/SharpMessenger/blob/45747a3ec2ed4a1ff998a3c520d1df845d6d9a72/client/ChatClient/Core/ChatClient.Core.UI/ViewModels/BaseViewModel.cs#L72

doesn't show popup without any error messages. Checked on both iOS and Android with version 1.1.0-pre2 of this plugin.

**Comment by rotorgames** [comment]
@cat-cat Please, give me your xaml code for PopupPage

**Comment by cat-cat** [comment]
here is the xaml of the popup page

https://github.com/cat-cat/SharpMessenger/blob/f02d3c57b9d93c8d26646fb409ee56d0827bf6dd/client/ChatClient/Core/ChatClient.Core.UI/PopupPages/pgEditMessage.xaml

**Comment by rotorgames** [comment]
@cat-cat Set `VerticalOption` and `HorizontalOption` for ScrollView = Fill

**Comment by cat-cat** [comment]
Unfortunately did not help. I used this popup in several places in the program, but calling only from this place didn't work and there are no any errors shown or logged. In all other places it's fine.

**Comment by rotorgames** [comment]
@cat-cat Then try to use `Device.BeginInvokeInMainThread`

**Comment by cat-cat** [comment]
works. thank you.

**Comment by cat-cat** [comment]
works for iOS, Android but not for UWP platform. On UWP doesn't happen anything.

**Comment by rotorgames** [comment]
@cat-cat Try to update to v1.1.0-pre5

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.
