### ISSUE TITLE
Will this library support .Net Standard ??

### ISSUE THREAD

**Issue by assassin316** [rotorgames/Rg.Plugins.Popup#147]
I've tried installing this package but doesn't work in a .Net Standard 1.4 library. Will this be updated in the near future?

**Comment by gcadmes** [comment]
Do you mean "NETStandard.Library": "1.6.0" or netstandard1.4 that appears in the frameworks section?

 "frameworks": {
    "netstandard1.4": {
      "imports": "portable-net45+win8+wp8"
    }
  }

I'm using  "NETStandard.Library": "1.6.0", and netstandard1.4 and it works fine.

**Comment by assassin316** [comment]
@gcadmes Here is the error I get when attempting to install the nuget package into a .Net Standard 1.4 library (for a Xamarin Forms project):

	Package Rg.Plugins.Popup 1.0.4 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Rg.Plugins.Popup 1.0.4 supports:
	  - monoandroid (MonoAndroid,Version=v0.0)
	  - monotouch (MonoTouch,Version=v0.0)
	  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
	  - uap10.0 (UAP,Version=v10.0)
	  - wpa81 (WindowsPhoneApp,Version=v8.1)
	  - xamarinios (Xamarin.iOS,Version=v0.0)
	Package Xamarin.Forms 2.3.0.49 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Xamarin.Forms 2.3.0.49 supports:
	  - monoandroid10 (MonoAndroid,Version=v1.0)
	  - monotouch10 (MonoTouch,Version=v1.0)
	  - portable-monoandroid10+monotouch10+net45+win+win81+wp8+wpa81+xamarinios10 (.NETPortable,Version=v0.0,Profile=win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10)
	  - uap10.0 (UAP,Version=v10.0)
	  - win81 (Windows,Version=v8.1)
	  - wp8 (WindowsPhone,Version=v8.0)
	  - wpa81 (WindowsPhoneApp,Version=v8.1)
	  - xamarinios10 (Xamarin.iOS,Version=v1.0)
	One or more packages are incompatible with .NETStandard,Version=v1.4.
	Package restore failed. Rolling back package changes for 'TestApp'.

**Comment by gcadmes** [comment]
@assassin316
Here is a copy of my project.json file. (I'm not using the old packages.config file)
Does your 'frameworks' section have the 'imports' property set like so? "imports": "portable-net45+win8+wp8"

```
{
  "supports": {},
  "dependencies": {
    "Ansuria.XFGloss": "1.0.6.59",
    "FAB.Forms": "2.1.1",
    "FormsToolkit": "1.1.18",
    "MvvmLightLibs": "5.3.0",
    "NETStandard.Library": "1.6.0",
    "Newtonsoft.Json": "10.0.2",
    "Plugin.Permissions": "1.2.1",
    "Plugin.Share": "5.0.0",
    "Rg.Plugins.Popup":  "1.1.0-pre2",
    "SlideOverKit": "2.1.4",
    "Xam.Plugin.DeviceInfo": "2.1.2",
    "Xam.Plugins.Forms.ImageCircle": "1.8.0.5",
    "Xam.Plugins.Settings": "2.5.4",
    "Xamarin.FFImageLoading.Forms": "2.2.10-pre-408",
    "Xamarin.Forms": "2.3.4.231",
    "Xamarin.Forms.CarouselView": "2.3.0-pre2"
  },
  "frameworks": {
    "netstandard1.4": {
      "imports": "portable-net45+win8+wp8"
    }
  }
}
```

**Comment by assassin316** [comment]
@gcadmes No I didn't have that, I added it in and now I'm able to add all my references!   👍 

Can you please explain that in detail? Why does it work with the "imports" property?

**Comment by gcadmes** [comment]
@assassin316  This is required to tell NuGet that specified TFM is compatible. Specifically for the Nuget packages that have not yet been updated to use netstandard directly.

Essentially it's like including a specific profile, profile259 for example

TFM = Target Framework Moniker.

**Comment by assassin316** [comment]
@gcadmes  Great, thanks for the info!  :)

**Comment by Screech129** [comment]
To support .NET Standard 2.0 where there is no longer a projects.json you can put 
`<PackageTargetFallback>$(PackageTargetFallback);portable-win+net45+wp8+win81+wpa8</PackageTargetFallback>`

under the property group section in your csproj file as mentioned here: 
[https://xamarinhelp.com/visual-studio-2017-net-standard-xamarin/](https://xamarinhelp.com/visual-studio-2017-net-standard-xamarin/)
