### ISSUE TITLE
PopupPage does not appear if passing 'true' to PushPopupAsync, or get removed using the remove api.

### ISSUE THREAD

**Issue by gcadmes** [rotorgames/Rg.Plugins.Popup#148]
My device is Nexus 7, running Android 6.0.1

When I invoke PushPopupAsync, I'm passing 'false' for the 2nd parameter, which means I don't want the page to animate. Since upgrading to 1.1.0 pre2, I am forced to pass 'false' because if I pass 'true', the PopupPage does not show. 

So for now, I'm using a temporary work around, but my UX team at my company is insisting on using animation.   Please let me know if I can help or if you can suggest another workaround.

Looking forward to 1.1.0. pre3. Do you know how soon before that is released?

Thank you kindly.

**Comment by gcadmes** [comment]
Actually, I see there is a new property public IPopupAnimation Animation { get; set; } on the PopupPage class. Am I supposed to set that property? Am I missing something?

**Comment by rotorgames** [comment]
@gcadmes Hi. Sorry for a long answer. Was Android system animation enabled?

**Comment by rotorgames** [comment]
Duplicate #159 

I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.
