### ISSUE TITLE
ContextActions from ListView in PopupPage aren't accessible

### ISSUE THREAD

**Issue by mggx** [rotorgames/Rg.Plugins.Popup#149]
Hello..

I am using Rg.Plugins.PopupPage to display an dialog. In the dialog is a listview and the listview has a ContextAction to delete the selected entry. If you hold down the entry on android, the context action menu will be up in the navigationbar. Because of the popup, the user can not access the context action menu.

Am i doing something wrong or is there a workaround?

thanks

**Comment by rotorgames** [comment]
@mggx I knew about this problem but I can't do anything because it is Android behavior. You should create your context menu for android.
