### ISSUE TITLE
[iOS] Unable to call DisplayAlert() or DisplayActionSheet while opening PopupPage on a Push-Modal Page

### ISSUE THREAD

**Issue by ShahmanTeh** [rotorgames/Rg.Plugins.Popup#15]
Calling a DisplayAlert() or DisplayActionSheet() in PopupPage in iOS will not show any alertViewController. Instead a warning message is shown as below.

`Warning: Attempt to present * on *  which is already presenting (null)`

This works on Android as it only use AlertDialog.

**Comment by rotorgames** [comment]
![clip2net_160516085504](https://cloud.githubusercontent.com/assets/1790504/15280652/ea11cc14-1b43-11e6-9f1b-b1eb534feacf.png)
@ShahmanTeh Hi friend, i dont understand you problem. In my, all working. I can open popup page, together DisplayActionSheet and DisplayAlert

**Comment by ShahmanTeh** [comment]
Hi @rotorgames (Kirill),

I apologized earlier for not making any sense in my previous report. I will explain the details of the issue.

I have a ContentPage_A where it is calling `PushModalAsync()` to ContentPage_B, and from there, I have a called a `PushPopupPage()`. from PopupPage_A, and here, calling DisplayAlert will not show any UIAlertView dialog.

The log is shown as the following:
`Warning: Attempt to present <UIAlertController: *>  on <Xamarin_Forms_Platform_iOS_PageRenderer: *> which is already presenting (null)`

The following the version that I used to test the issue:
Rg.Plugins.Popup.0.0.16
Xamarin 4.0.3.214
Xamarin.iOS 9.6.1.8
Xamarin.Forms.2.2.0.31
iOS SDK 9.2:	(13C75)
IOS Device iPhone 6s Plus iOS 9.2 (simulator)


Here is the video that displays the said issue.
http://screencast.com/t/CSqCvlWiNB7G

attached here is a sample project that I created to replicate the issue.
[TestPopup.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/265722/TestPopup.zip)

**Comment by rotorgames** [comment]
@ShahmanTeh Confirmed

**Comment by ShahmanTeh** [comment]
@rotorgames any progress/updates on the issue?

**Comment by rotorgames** [comment]
@ShahmanTeh It will take many time. Xamarin.Forms architecture is not support `DisplayAlert` or `DisplayActionSheet` with `Popup` plugin. I can add reflections code but it is bad practice. 

Please, wait. Maybe I will find solution coming soon. Thx

**Comment by rotorgames** [comment]
Fix in `v1.0.0`
