### ISSUE TITLE
Cannot convert to Rg.Plugins.Popup.Pages.PopupPage

### ISSUE THREAD

**Issue by einc** [rotorgames/Rg.Plugins.Popup#150]
I'm following the code in the demo and have all of the references added at the top of my code and have installed the nuget package 1.0.4.

This is my code for the button:
        private async void OnOpenPupup(object sender, EventArgs e)
        {
            var page = new MyPopupPage();
            **await Navigation.PushPopupAsync(page);**
        }
I get the error
Argument 2: cannot convert from 'Xam1.MyPopupPage' to 'Rg.Plugins.Popup.Pages.PopupPage' on the bolded code
I have made a MyPopupPage that has one label inside it. How should I fix this?

**Comment by Gigex42** [comment]
Your page you want to navigate to has to be of the type Rg.Plugins.Popup.Pages.PopupPage.

**Comment by trix0** [comment]
Make sure to clean the solution. Sometimes VS wont just pick it up.

**Comment by yusufmsalh** [comment]
just make sure to change your page.cs to

public partial class page: PopupPage
{
}

[Stackoverflow](https://stackoverflow.com/questions/53946706/issues-with-displaying-a-popup)
