### ISSUE TITLE
Rg.Plugins.Popup 1.1 pre2 not show on android

### ISSUE THREAD

**Issue by Mutasem1980** [rotorgames/Rg.Plugins.Popup#151]
hi,
many thanks for your greate work

i just  use Rg.Plugins.Popup 1.1 pre2 on my xamarin forms 
on ios works fine but on android dialog not showing
Debug:
7-22 16:58:42.731 D/ViewRootImpl(28052): ViewPostImeInputStage processPointer 0
07-22 16:58:42.811 D/ViewRootImpl(28052): ViewPostImeInputStage processPointer 1
07-22 16:58:42.941 D/ViewRootImpl(28052): ViewPostImeInputStage processPointer 0
07-22 16:58:43.201 D/Mono    (28052): Unloading image System.Net.Http.dll [0x936c8f00].
07-22 16:58:43.201 D/Mono    (28052): Image addref System.Net.Http[0x979ab2c0] -> System.Net.Http.dll[0x9a018100]: 7
07-22 16:58:43.201 D/Mono    (28052): Config attempting to parse: 'System.Net.Http.dll.config'.
07-22 16:58:43.201 D/Mono    (28052): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Net.Http/System.Net.Http.config'.
07-22 16:58:43.341 D/ViewRootImpl(28052): ViewPostImeInputStage processPointer 1
07-22 16:58:43.421 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:43.441 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:43.461 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:43.471 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:43.491 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:43.511 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:43.521 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:43.531 W/OpenGLRenderer(28052): Dirty -1083.00  0.00 -3.00 1920.00 doesn't intersect with 0 0 1080 1920 ?
07-22 16:58:44.261 W/DisplayListCanvas(28052): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)

**Comment by Mutasem1980** [comment]
previous version 1.0.4 work fine on IOS AND Android

**Comment by EmilAlipiev** [comment]
@Mutasem1980 I am using also 1.1 pre2 and it works fine for me. maybe try clean the things or resintall, delete nuget folder etc.

**Comment by rotorgames** [comment]
@Mutasem1980 Hi. Try to update to v1.1.0-pre8 please.

**Comment by manishkumarmm93** [comment]
![popup issue page](https://user-images.githubusercontent.com/17898167/34862027-1b2cf562-f78e-11e7-8108-9420bd8ce13e.png)

Hi ,

 I am using also 1.0.4 and it not working for me . Please help me

**Comment by EmilAlipiev** [comment]
Try latest pre Release after installing clean your obj bin folders and rebuild vs

**Comment by rotorgames** [comment]
@manishkumarmm93 Update to the last pre release

**Comment by manishkumarmm93** [comment]
@rotorgames @EmilAlipiev  thank you for your response.
