### ISSUE TITLE
RG.Plugins.Popup v1.0.4 crashes in release mode for UWP

### ISSUE THREAD

**Issue by kbiasci** [rotorgames/Rg.Plugins.Popup#152]
Hi there, 

it seems to be exactly the same issue than here:
https://github.com/rotorgames/Rg.Plugins.Popup/issues/9 

But this time it is for UWP on Windows 10 desktop and mobile (it works well for Win 8.1 mobile).

Do you think you could re-do your magic with this plaftorm?

Cheers,

Kevin

**Comment by iupchris10** [comment]
Did you remember to add assemblies into the initializer? I forgot to do this initially but it worked afterwards. See highlighted line in screenshot...

![screen shot 2017-07-24 at 9 09 45 am](https://user-images.githubusercontent.com/5750525/28524864-39e2405e-7050-11e7-8ca2-2d838b67fe7d.png)

**Comment by kbiasci** [comment]
Yep, the line is present. As I mentionned it is working in DEBUG mode only.
Any other type of release (Release / Ad-Hoc / AppStore) will see the popup crashing violenty.
Trying to catch it only leads to a null exception (so no message/context).

**Comment by iupchris10** [comment]
Yep that'll do it. Glad to help.
