### ISSUE TITLE
Should we pop and remove popup in OnClose method?

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#153]
Quick question, I am doing code below inside my popuppage, is this neccessary to ensure popup is removed from stack? I remember that previous version had some memory problem and I used it as below. newest version or pre version, does it required?

```
 private async void OnClose(object sender, EventArgs e)
        {
            try
            {
               await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAsync();
               await Rg.Plugins.Popup.Services.PopupNavigation.Instance.RemovePageAsync(this);
                this.Parent = null;
            }
            catch (Exception ex)
            {
                 
            }

        }    
```

**Comment by rotorgames** [comment]
@EmilAlipiev Hi. Versions higher than v1.1.0-pre2 don't have problems with memory. You should not do RemovePageAsync or set Parent to null.
