### ISSUE TITLE
iOS crash (1.1.0-pre2) - suggested fix.

### ISSUE THREAD

**Issue by philmoz** [rotorgames/Rg.Plugins.Popup#154]
There is an issue with the iOS code that causes random crashes when the popups are being dismissed.

In the ViewDidLayoutSubviews method of PopupPageRenderer.cs (iOS), the Superview property of View can become null between the check on line 141 and the subsequent usage on line 144. This happens right when the view has finished disappearing.

The code for ViewDidLayoutSubviews below seems to fix the issue for me:
`
        public override void ViewDidLayoutSubviews()
        {
            base.ViewDidLayoutSubviews();

            var superviewFrame = View?.Superview?.Frame;

            if (superviewFrame.HasValue)
            {
                var applicationFrame = UIScreen.MainScreen.ApplicationFrame;
                var systemPadding = new Thickness
                {
                    Left = applicationFrame.Left,
                    Top = applicationFrame.Top,
                    Right = applicationFrame.Right - applicationFrame.Width - applicationFrame.Left,
                    Bottom = applicationFrame.Bottom - applicationFrame.Height - applicationFrame.Top
                };

                CurrentElement.BatchBegin();

                CurrentElement.SystemPadding = systemPadding;
                SetElementSize(new Size(superviewFrame.Value.Width, superviewFrame.Value.Height));

                CurrentElement.BatchCommit();
            }
        }
`

**Comment by Szymaniuk** [comment]
Isn't it releated - https://github.com/rotorgames/Rg.Plugins.Popup/issues/122 ?
@rotorgames any change to include this fix in next release?

**Comment by philmoz** [comment]
Yes, still happening for me - thought I'd fixed it, back to the drawing board.
If you set IsAnimating to false in your popup pages do you still get the crash?

**Comment by Szymaniuk** [comment]
Is it working for you, with setting IsAnimating to false? If so, I'd also give it a try ;).

**Comment by Szymaniuk** [comment]
Well, I've just surrounded whole **ViewDidLayoutSubviews** code with try/catch, and seems, that it's at least not crashing for now.

**Comment by philmoz** [comment]
The random nature of the crash makes it hard to tell if a fix is working. I thought my change in the original post worked as it went for two days before I had a crash.
At the moment I suspect the way the code is handling animation, hence the suggestion to set IsAnimating to false. So far it has not crashed for me with this; but that doesn't really prove anything.

**Comment by Szymaniuk** [comment]
Just tested in whole day, from morning, and I though, that try/catch + your suggested IsAnimated = false would do the trick, but It crashed just right now.
The puck is this issue -.-

**Comment by philmoz** [comment]
I've spent too much time on this already, and I can't find any way to fix the iOS crashes. It seems that no matter how you handle the native popup view on iOS sooner or later Xamarin/Mono will crash. 

I suspect that some change in the Xamarin Forms library has made it very difficult (if not impossible) to mess with the views the way the plugin wants to. 

It's a pity since it was a good solution. Hopefully there is a way to fix it and a stable version will eventually appear.

I've managed to implement an alternative using a custom Content Page and forcing all pages in my apps to derive from this.

**Comment by iupchris10** [comment]
I'm running into this issue also. The animation seems to have something wrong. I disabled the animation for a Production release of my app and crashes went way down (according to iTunes connect). I turned it back on in a recent release and the crashes are flooding back in again.  I symbolicated the crash logs and they all point to Rg Popup:

```
....
12  [redacted]             	0x00000001003e20f8 throw_exception + 168
13  [redacted]             	0x000000010185a2a4 xamarin_process_managed_exception (runtime.m:2132)
14  [redacted]             	0x00000001016dbf68 native_to_managed_trampoline_7(objc_object*, objc_selector*, _MonoMethod**, unsigned int) (registrar.m:288)
15  [redacted]             	0x00000001016fd158 -[Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer viewDidLayoutSubviews](registrar.m:15236)
16  UIKit                         	0x00000001882b9d38 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1320
17  QuartzCore                    	0x00000001854aa274 -[CALayer layoutSublayers] + 148
18  QuartzCore                    	0x000000018549ede8 CA::Layer::layout_if_needed(CA::Transaction*) + 292
19  QuartzCore                    	0x000000018549eca8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
20  QuartzCore                    	0x000000018541a34c CA::Context::commit_transaction(CA::Transaction*) + 252
21  QuartzCore                    	0x00000001854413ac CA::Transaction::commit() + 504
.....
```

**Comment by rotorgames** [comment]
Duplicate #122
