### ISSUE TITLE
Add option to disable the iOS keyboard layout handling.

### ISSUE THREAD

**Issue by philmoz** [rotorgames/Rg.Plugins.Popup#155]
I would like an option that completely disables the code in the iOS renderer that tries to resize the view when it detects the presence/removal of the on-screen keyboard.

This does not work reliably and often results in the popup view being squashed or positioned badly.

I prefer to simply wrap the popup content in a ScrollView which then allows iOS to properly handle positioning when the keyboard if displayed/removed. This works consistently and also works across iOS, Android and UWP.

**Comment by rotorgames** [comment]
@philmoz Hi. Thank you for supporting. It is a good idea. I think that I will add it in the plugin. Thank you.

**Comment by rotorgames** [comment]
@philmoz P.S. You can set HasSystemPadding="False" right now then popup page will not be resized when a keyboard will appear. 

I will think about changing the SystemPadding logic. Thanks

**Comment by clovs** [comment]
Hello,

Seems that when keyboard appear my Popup disappear on IOS.
Maybe it's moving outside of the view

HasSystemPadding="false" ou "true" seems to not work to.

let me know if you used to that issue
thanks,

**Comment by seanyda** [comment]
Hi @rotorgames,

Having a similar issue here I think. I have a PopupPage with the settings HasSystemPadding = false, but when keyboard appears it breaks my layout and doesn't respect the Grid height. Do you know any other workarounds?

Cheers!

**Comment by seanyda** [comment]
This issue seems to be sorted in 1.1.4.158-pre2. Cheers!

**Comment by rotorgames** [comment]
Is was implemented. See [documentation](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/PopupPage#properties): `HasKeyboardOffset` and `KeyboardOffset`

**Comment by Phenek** [comment]
Many thanks!
