### ISSUE TITLE
Background position and color

### ISSUE THREAD

**Issue by Eiskaltereistee** [rotorgames/Rg.Plugins.Popup#161]
Hi,

I want a overlay in front of the webview, if the webview is loading. So I created a popup without any content.

But how can I set the color and position of the background layer? Or is there any better way to do so?

![simulator screen shot 10 08 2017 09 26 32](https://user-images.githubusercontent.com/9147768/29159209-0521257c-7dae-11e7-835f-f2d593d8c981.png)

**Comment by rotorgames** [comment]
@Eiskaltereistee Hi. I didn't understand your question. What would you like to do?

**Comment by rotorgames** [comment]
Need more information
