### ISSUE TITLE
HasSystemPadding option gets ignored on 5.x & 6.x

### ISSUE THREAD

**Issue by 207713** [rotorgames/Rg.Plugins.Popup#162]
I have just found this awesome plugin and it really works like a charm, but if i try to use the HasSystemPadding option, it gets ignored on my A3(2017) 6.0 and J3(2016) 5.1.1

However, it is perfect on my S6e 7.0 and also, on the emulator, which is running 6.0 as well!

**Comment by rotorgames** [comment]
@207713 Hi. Sorry for the long answer. Can you show a screenshot where SystemPadding is enabled?

**Comment by JKennedy24** [comment]
I am seeing this on a Moto G phone V7.0 and Nexus 9 V7.1.1

**Comment by rotorgames** [comment]
@JKennedy24 Ok. I have added it to the todo list.

**Comment by rotorgames** [comment]
@207713 Please try to test 1.1.3.120-beta from development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

And notify me about results. Thanks

**Comment by JKennedy24** [comment]
I've tried out the latest beta and it didn't fix the issue unfortunately

**Comment by rotorgames** [comment]
@JKennedy24 Could you reproduce it in a simulator?
