### ISSUE TITLE
Listview selected item not highlighted even it is selected

### ISSUE THREAD

**Issue by jitendrajadav** [rotorgames/Rg.Plugins.Popup#164]
Inside Popup ListView SelectedItem is not getting highlighted until and unless we manually select Item then it is going to highlighted but default it is not?

**Comment by kayjoekahmann** [comment]
Are you maybe using a costumRenderer for your Listview?

**Comment by rotorgames** [comment]
@jitendrajadav Can you create a simple project which has this problem for an example?

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.
