### ISSUE TITLE
Keyboard changes height of dialog instead of overlapping it

### ISSUE THREAD

**Issue by codebeaulieu** [rotorgames/Rg.Plugins.Popup#166]
I'm having an issue across multiple apps when the keyboard is displayed. When the keyboard is activated the controls within the dialog are either smashed to accommodate the keyboard or disappear entirely as the height of the dialog is reduced.

![keyboard](https://user-images.githubusercontent.com/9411281/30029819-647dde42-9150-11e7-9676-990b15ceb596.gif)

Is anyone else experiencing this? And is there a way to stop this from happening?

**Comment by timahrentlov** [comment]
Put the entry fields in a scrollview?

**Comment by codebeaulieu** [comment]
@timahrentlov that worked. I don't know why that didn't seem intuitive to me. I'll close this. For anyone else (in the future) wondering what I did to fix this, I did this:

    ```
        var container = new RoundCornerView
            {
                Margin = Values.Layout.DoublePadding,
                VerticalOptions = LayoutOptions.Center,
                HorizontalOptions = LayoutOptions.Center,
                BackgroundColor = Values.Colors.White,
                HeightRequest = 450,
                WidthRequest = 325,
                Padding = 0,
                Content = _mainLayout
            };

            Content = new ScrollView
            {
				HeightRequest = 450,
				WidthRequest = 325,
				Padding = 0,
                Content = container
            };
```
