### ISSUE TITLE
Popup window is transparent when it should be solid

### ISSUE THREAD

**Issue by PolarBearOC** [rotorgames/Rg.Plugins.Popup#169]
Hello :)

I'm a first-time user of this plugin. I was trying to create a popup window that displays a dice and allows you to re-roll it.

For a reason unknown to me, it keeps appearing transparent in any point except the in and out animations. I used [this sample](https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Demo/Demo/Pages/LoginPopupPage.xaml) as a template to understand how things should work.

[Here's a screenshot](https://ibb.co/mKFZ65) (Android, but same happens in UWP)

And here's my code:
`
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             x:Class="NDLPCalc.DicePopupPage">
    
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation
      PositionIn="Bottom"
      PositionOut="Center"
      ScaleIn="1"
      ScaleOut="0.7"
      DurationIn="700"
      EasingIn="BounceOut"/>
    </pages:PopupPage.Animation>

   
        <AbsoluteLayout
            HorizontalOptions="Center"
            VerticalOptions="Center">
            <Frame
        x:Name="FrameContainer"
        Margin="15"
        HorizontalOptions="Center"
        BackgroundColor="White">
        <StackLayout
            IsClippedToBounds="True"
            Padding="10, 5"
            Spacing="3">
                <Image HorizontalOptions="Center" 
                           x:Name="Dice" Margin="10" 
                           HeightRequest="150"  
                           WidthRequest="150" 
                           Source="{Binding DiceSource}"/>

                <Button Margin="10, 5" 
                        Clicked="OnReRoll"
                        HorizontalOptions="Fill" 
                        x:Name="ReRoll" 
                        Text="Re-Roll">
                        <Button.HeightRequest>
                            <OnPlatform x:TypeArguments="x:Double" Android="50" iOS="30" WinPhone="30"/>
                        </Button.HeightRequest>
                    </Button>
                </StackLayout>
            </Frame>
            
        </AbsoluteLayout>
</pages:PopupPage>
`

Any help would be much appreciated!
Thanks!!

**Comment by Luis-FJS** [comment]
Hello,
I found this same problem, I solved by commenting the OnAppearingAnimationEnd() and the OnDisappearingAnimationBegin() tasks from the cs file. These actions returned Content.FadeTo(##), so I figured it has something to do with the Popup being Opaque.

**Comment by PolarBearOC** [comment]
Works well, thanks Luis-FJS!
