### ISSUE TITLE
Popup displayed fullscreen problem

### ISSUE THREAD

**Issue by RimVo** [rotorgames/Rg.Plugins.Popup#17]
I've try to use your popup plugin to create a popup, but the popup display fullscreen that is not my expectation. Here my source:
![image](https://cloud.githubusercontent.com/assets/19484386/15418132/e7b4458c-1e86-11e6-965e-5916c6dda8cf.png)

![image](https://cloud.githubusercontent.com/assets/19484386/15418122/d2e36e9e-1e86-11e6-9ff6-3a6d8bea584e.png)
My result:
![image](https://cloud.githubusercontent.com/assets/19484386/15418175/59a1bb84-1e87-11e6-9d1e-44e2144d3976.png)
Please help me to resolve this issue.Thanks.

**Comment by rotorgames** [comment]
@RimVo Hi friend. Please for StackLayout set to vertical and horizontal options - Center.

**Comment by RimVo** [comment]
@rotorgames Yeah. it works fine now. Thanks!

**Comment by rotorgames** [comment]
@RimVo  Good luck.
