### ISSUE TITLE
Problem with the animation. Xamarin.forms 2.3.4.270

### ISSUE THREAD

**Issue by HugoTruffe** [rotorgames/Rg.Plugins.Popup#170]
I am using the library (version 1.0.4) in a project Xamarin.

Today, I updated xamarin.forms and PopupPage is not working correctly.

Maybe there is a one update for "Rg.Plugins.Popup" that it resolved this problem

Thank!

**Comment by CarlosAganzo** [comment]
Hi Hugo! 
Did you get your problem sorted? We're seeing similar issues with animations on 1.0.4 with Xamarin Forms 2.3.4

**Comment by rotorgames** [comment]
Hi there. Do you try to test it with v1.1.0-pre3?

**Comment by Ofaim** [comment]
I'm trying version v1.1.3.73-pre on Xamarin.Forms 2.5.0.121934,
No animation is working. The popup enters and exits from the bottom of the screen :(

Help?

**Comment by rotorgames** [comment]
@Ofaim Can you capture a video when you will be showing the problem?

**Comment by Ofaim** [comment]
Hi there!
I'm actually new to Xamarin, and not sure I'm using your library correctly. So before further discussing the issue I wonder whether you've got a minute to check if I'm doing the right things, hope it's not too rude:

In the calling screen:
```
var popupPage = new EmailPopup(webSite);
await Navigation.PushModalAsync(popupPage);
```
The popup:
```
<pages:PopupPage 
    ...
    Title="Email popup"
    BackgroundColor="Transparent"
    CloseWhenBackgroundIsClicked="True">
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation
         .../>
    </pages:PopupPage.Animation>
    <Frame HorizontalOptions="Center" VerticalOptions="Center"
           BackgroundColor="White"...>
        <StackLayout>
            <Image .../>
            <Entry .../>
            <Label .../>
            <Button .../>
        </StackLayout>
    </Frame>
</pages:PopupPage>
```
Nothing special in the code behind so didn't paste it. I just want the frame to pop over the calling screen (without any background and using the proper animation). Instead I've got this (background color = calling screen background color, instead of transpperant):
![image](https://user-images.githubusercontent.com/34773792/34781494-a6429cd0-f62e-11e7-9286-992b27cc8d89.png)

BTW, `Rg.Plugins.Popup.Popup.Init(this, bundle);` in the Android project's `MainActivity.cs` crashes the app on startup. Do I need to check something different on my environment? Maybe THAT's the issue?

Sorry, and hope you can help me!
This plugin seems awesome, but not very easy to use as one might think....

**Comment by rotorgames** [comment]
@Ofaim Hi. What an exception do you get when you initialize this plugin?

**Comment by Ofaim** [comment]
Actually, the Visual Studio just says "`An unhandled exception occured.`" and when checking the logcat there's no ERROR. But without the `Rg.Plugins.Popup.Popup.Init(this, bundle);` command everything is running smoothly.
Those are all the `Rg.Plugins.Popup.`-related logcat lines. It almost means nothing to me, it seems normal:

```
01-14 14:35:55.641 D/Mono    ( 6431): Image addref Rg.Plugins.Popup[0xb82b1610] -> Rg.Plugins.Popup.dll[0xb837d1d8]: 2
01-14 14:35:55.641 D/Mono    ( 6431): Prepared to set up assembly 'Rg.Plugins.Popup' (Rg.Plugins.Popup.dll)
01-14 14:35:55.641 D/Mono    ( 6431): Assembly Rg.Plugins.Popup[0xb82b1610] added to domain RootDomain, ref_count=1
01-14 14:35:55.641 D/Mono    ( 6431): AOT: image 'Rg.Plugins.Popup.dll.so' not found: dlopen failed: library "/data/app/com.adcd.AllProbe-1/lib/arm/libaot-Rg.Plugins.Popup.dll.so" not found
01-14 14:35:55.641 D/Mono    ( 6431): AOT: image '/usr/local/lib/mono/aot-cache/arm/Rg.Plugins.Popup.dll.so' not found: dlopen failed: library "/data/app/com.adcd.AllProbe-1/lib/arm/libaot-Rg.Plugins.Popup.dll.so" not found
01-14 14:35:55.641 D/Mono    ( 6431): Config attempting to parse: 'Rg.Plugins.Popup.dll.config'.
01-14 14:35:55.641 D/Mono    ( 6431): Config attempting to parse: '/usr/local/etc/mono/assemblies/Rg.Plugins.Popup/Rg.Plugins.Popup.config'.
01-14 14:35:55.641 D/Mono    ( 6431): Image addref Rg.Plugins.Popup.Droid[0xb82a79e0] -> Rg.Plugins.Popup.Droid.dll[0xb837d650]: 2
01-14 14:35:55.641 D/Mono    ( 6431): Prepared to set up assembly 'Rg.Plugins.Popup.Droid' (Rg.Plugins.Popup.Droid.dll)
01-14 14:35:55.641 D/Mono    ( 6431): Assembly Rg.Plugins.Popup.Droid[0xb82a79e0] added to domain RootDomain, ref_count=1
01-14 14:35:55.641 D/Mono    ( 6431): AOT: image 'Rg.Plugins.Popup.Droid.dll.so' not found: dlopen failed: library "/data/app/com.adcd.AllProbe-1/lib/arm/libaot-Rg.Plugins.Popup.Droid.dll.so" not found
01-14 14:35:55.641 D/Mono    ( 6431): AOT: image '/usr/local/lib/mono/aot-cache/arm/Rg.Plugins.Popup.Droid.dll.so' not found: dlopen failed: library "/data/app/com.adcd.AllProbe-1/lib/arm/libaot-Rg.Plugins.Popup.Droid.dll.so" not found
01-14 14:35:55.641 D/Mono    ( 6431): Config attempting to parse: 'Rg.Plugins.Popup.Droid.dll.config'.
01-14 14:35:55.641 D/Mono    ( 6431): Config attempting to parse: '/usr/local/etc/mono/assemblies/Rg.Plugins.Popup.Droid/Rg.Plugins.Popup.Droid.config'.

<Some other stuff...>

01-14 14:35:57.391 D/Mono    ( 6431): Unloading image Rg.Plugins.Popup.Droid.dll [0xb8631930].
01-14 14:35:57.391 D/Mono    ( 6431): Image addref Rg.Plugins.Popup.Droid[0xb8606168] -> Rg.Plugins.Popup.Droid.dll[0xb837d650]: 5
01-14 14:35:57.391 D/Mono    ( 6431): Config attempting to parse: 'Rg.Plugins.Popup.Droid.dll.config'.
01-14 14:35:57.391 D/Mono    ( 6431): Config attempting to parse: '/usr/local/etc/mono/assemblies/Rg.Plugins.Popup.Droid/Rg.Plugins.Popup.Droid.config'.
01-14 14:35:57.391 D/Mono    ( 6431): Assembly Ref addref AllProbe[0xb82b1420] -> Rg.Plugins.Popup.Droid[0xb82a79e0]: 2
An unhandled exception occured.
```

`Allprobe` is the name of the app.

**Comment by rotorgames** [comment]
@Ofaim Clean your project, remove each bin and obj folder in the solution, also check that each project in the solution use an one version of the plugin.

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.
