### ISSUE TITLE
Margin for PopupPage

### ISSUE THREAD

**Issue by nor0x** [rotorgames/Rg.Plugins.Popup#171]
I'm using a popup to fill my page below the navigationbar in my application. I'm working on dismissing the popup by pressing a button on the navigationbar, so I have set `InputTransparent = true` and `Padding` accordingly. Furthermore I set `BackgroundColor = Color.Transparent`. Dismissing the popup via a button click is working fine, however touching a control in the PopupPage doesn't work because of `InputTransparent = true`. Is there a possibility to set a margin for the whole `PopupPage` so that it start right below the navigation bar which should still be clickable?

Thanks

**Comment by rotorgames** [comment]
@nor0x Hi. You can't install Margin for PopupPage right now, but you can use Padding.

**Comment by nor0x** [comment]
Thank you
