### ISSUE TITLE
PopAsync clear all pages on Navigation Stack (1.1.0-pre2)

### ISSUE THREAD

**Issue by tdduy** [rotorgames/Rg.Plugins.Popup#174]
If i pop a normal page after pop a popup page like that:
```
await PopupNavigation.Instance.PopAsync();
await Navigation.PopAsync();
```
An exception raise at Navigation.PopAsync because after i pop the popup page, the Navigation Stack is empty.
But if i exchange order of method like that:
```
await Navigation.PopAsync();
await PopupNavigation.Instance.PopAsync();
```
The app works normaly.
I'm using Xamarin.Forms 2.4.0.282.

**Comment by rotorgames** [comment]
Hi. Please, show an exception's stack trace

**Comment by tdduy** [comment]
Thanks for your response.
This is exception
`System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Xamarin.Forms.Internals.NavigationProxy.Pop()
   at Xamarin.Forms.Internals.NavigationProxy.OnPopAsync(Boolean animated)
   at Xamarin.Forms.Internals.NavigationProxy.PopAsync()
   at Odyssee.Views.MultiOrder.Popups.CustomersSelect.<<initUI>b__3_0>d.MoveNext() in D:\ODS\odyssee.native\Odyssee\Odyssee\Views\MultiOrder\Popups\CustomersSelect.cs:line 57
`

**Comment by rotorgames** [comment]
@tdduy This exception is not of this plugin. You did `PopAsync` when there were not any pages in the `NavigationStack`. You should check are there any pages in the `NavigationStack` and only then invoke `PopAsync`

**Comment by tdduy** [comment]
I sure there are many pages in the NavigationStack before PopupNavigation.Instance.PopAsync() called.
I also have to try with version 1.0.4 and everything is ok.
So i think this is an issue of version 1.1.0-pre2.

**Comment by rotorgames** [comment]
@tdduy You can see in a stack trace that there are not any mentions about Rg.Plugins.Popup in it. `Navigation.PopAsync();` throws this exception.

**Comment by tdduy** [comment]
@rotorgames 
I think there is an issue with PopupNavigation.Instance.PopAsync method because it made NavigationStack empty. If i downgrade to version 1.0.4, the issue is gone.

**Comment by rotorgames** [comment]
@tdduy If you look these classes you will see that they don't use any methods of Navigation.

https://github.com/rotorgames/Rg.Plugins.Popup/blob/v1.1.0/src/Rg.Plugins.Popup/Services/PopupNavigation.cs
https://github.com/rotorgames/Rg.Plugins.Popup/blob/v1.1.0/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs

Can you upload your project to github and give me?

**Comment by EmilAlipiev** [comment]
I agree with @tdduy. I am trying remove a page from the navigationstack but code below is null because Navigation.NavigationStack has no item although I am sure that testpage is in the NavigationStack because when I press backbutton I land on testpage. Reason  Navigation.NavigationStack is empty because just before checking this code I had a popup and I popped this popup. It looks like that popup is clearing NavigationStack. 

`  var excistingPages = Navigation.NavigationStack.Where(p => p is TestPage);`

**Comment by rotorgames** [comment]
@EmilAlipiev Ok I will review it but it is oddly

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.

**Comment by Lincolnerson** [comment]
Hi, 
I am going from Page 1 > Page 2 > Page 3
Once process completed then using following code to return on Page 2:
`Navigation.RemovePage(Navigation.NavigationStack[Navigation.NavigationStack.Count - 1])`

Then again from Page 2 moving to Page3, but this time same above code is throwing below exception:
UNHANDLED EXCEPTION:
02-05 17:00:39.083 I/MonoDroid( 1102): System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
02-05 17:00:39.083 I/MonoDroid( 1102): Parameter name: index
02-05 17:00:39.083 I/MonoDroid( 1102):   at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
02-05 17:00:39.083 I/MonoDroid( 1102):   at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
02-05 17:00:39.083 I/MonoDroid( 1102):   at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
02-05 17:00:39.083 I/MonoDroid( 1102):   at CTS_CPR.View.Test.AcceleroMeterFinal.OnButtonPressed () [0x0002a] in D:\WorkSpace\Mobile\CPR\CTS-CPR\CTS-CPR\CTS_CPR\View\Test\AcceleroMeterFinal.xaml.cs:192

**Comment by rotorgames** [comment]
@Lincolnerson These issues are only about Pg.Plugins.Popup, not about Xamarin.Forms. You can create an issue here (https://github.com/xamarin/Xamarin.Forms/issues) or here (https://bugzilla.xamarin.com/)
