### ISSUE TITLE
How does the plugin work?

### ISSUE THREAD

**Issue by opcodewriter** [rotorgames/Rg.Plugins.Popup#177]
I tried creating a simple PopupPage like this:

```
    public class PopupPage : ContentPage
    {
        public PopupPage()
        {
            BackgroundColor = Color.FromHex("#80000000");
        }
    }


public class MyPopupPage: PopupPage
{
}
```

And made a custom renderer like this:

```
class PopupPageRenderer : PageRenderer
{
}
```

but I am not able to see through the popup's background, it is opaque... What I want is to be able to see the previous page in the background since the popup page background has transparency.
How does this plugin does it?

**Comment by lengk** [comment]
100% — FF
95% — F2
90% — E6
85% — D9
80% — CC
75% — BF
70% — B3
65% — A6
60% — 99
55% — 8C
50% — 80
45% — 73
40% — 66
35% — 59
30% — 4D
25% — 40
20% — 33
15% — 26
10% — 1A
5% — 0D
0% — 00

E.g. 
`BackgroundColor = "4D000000"`
