### ISSUE TITLE
How to use is not self explanatory 

### ISSUE THREAD

**Issue by Dridou** [rotorgames/Rg.Plugins.Popup#178]
"Task PushAsync(PopupPage page, bool animate = true) // Navigation.PushPopupAsync"
That line displays errors into any IDE. First, why do you say in com that PushPopup comes from Navigation, put it directly into the code? Second, PushAsync returns a Task, so I guess that line is more a prototype than a real using example.
I propose that kind of explanation : 
`var newPage = new ContentPage();`
`Task task = Navigation.PushAsync(newPage, true);`
that code works

**Comment by rotorgames** [comment]
@Dridou Hi. Thank you for your improvements. I will update docs soon. Thanks.

P.S. PushAsync is used with `Rg.Plugins.Popup.Services.PopupNavigation`

**Comment by rotorgames** [comment]
I added an item to todo list about updating documentation. Thanks
