### ISSUE TITLE
RG.Plugins.Popup v1.0.4 crashes in debug mode for iOS 

### ISSUE THREAD

**Issue by rk2022** [rotorgames/Rg.Plugins.Popup#179]
Hi,
I'm having the same issue in debug mode, when calling PushPopupAsync(), the app crashes on iOS, on Android everything is fine and i get the desired popup, but on iOS the app crashes, I don't get any errors nor exception, the IDE just terminates the app! can anybody help please? I really need this

**Comment by rotorgames** [comment]
@rk2022 Hi. Try to remove this plugin from each project and reinstall again.

**Comment by rk2022** [comment]
Thank you so much, it worked although i had to install v1.1.0-pre2 for my ios project

**Comment by rotorgames** [comment]
@rk2022 Nice to hear it. And I would like to say that v1.1.0-pre3 will be soon.

**Comment by rk2022** [comment]
good
