### ISSUE TITLE
Tapping Background doesn't dismiss popup

### ISSUE THREAD

**Issue by ChaseFlorell** [rotorgames/Rg.Plugins.Popup#180]
Since Xamarin has released Xamarin.Forms 2.4, the act of tapping the background of a popup no longer dismisses the popup. We're left with writing our own handler to do it, or use the back button.

I'm not sure if Xamarin patched a bug or introduced a regression (Tap Gestures has had issues in the 2.4 release), but I'm wondering if this plugin needs to address it?

**Comment by rotorgames** [comment]
@ChaseFlorell it is problem of Xamarin.Forms 2.4 but I have resolved it in v1.1.0-pre3.

Duplicate #173

**Comment by ChaseFlorell** [comment]
doh, thanks. I missed the other thread on the topic.
