### ISSUE TITLE
Button click event doesn't work on first time when keyboard is open in iOS.

### ISSUE THREAD

**Issue by vivekshah-zymr** [rotorgames/Rg.Plugins.Popup#181]
I am implementing the popup like LoginPopupPage as per example. But when the keyboard is open and we press Login button click event doesn't occur and just keyboard gets close. So We have to press Login button again.  How can I implement Login click event properly with a single click even when the keyboard is open.

**Comment by rotorgames** [comment]
@vivekshah-zymr What version of a plugin do you use?

**Comment by vivekshah-zymr** [comment]
version 1.0.4

**Comment by rotorgames** [comment]
@vivekshah-zymr try to use 1.1.0-pre3

**Comment by vivekshah-zymr** [comment]
OK, yes it's working with 1.1.0-pre3. Thanks (y)

**Comment by rotorgames** [comment]
You are welcome
