### ISSUE TITLE
Rg Plugin Popoup

### ISSUE THREAD

**Issue by Rakuchetu** [rotorgames/Rg.Plugins.Popup#182]
![screenshot_1509038587](https://user-images.githubusercontent.com/33131869/32067376-a210528e-baa0-11e7-8a08-eca5dbb6d8ef.png)
Hi, I am using version1.1.0 pre3
when click on button my popup background 
![screenshot_1509038557](https://user-images.githubusercontent.com/33131869/32067374-a1c2d7e8-baa0-11e7-9bce-276ade017817.png)
is dissapper in android not in ios.

**Comment by Rakuchetu** [comment]
And i'am using MVVM pattern

**Comment by rotorgames** [comment]
@Rakuchetu Hi. Can you explain your problem more?

**Comment by Rakuchetu** [comment]
Hi,
when we press a button for a long time my popup background is disappearing. How to resolve it
![screenshot_1509038587](https://user-images.githubusercontent.com/33131869/32095836-2ac3e376-bb22-11e7-8782-8f86ed8c95d0.png)
![screenshot_1509038557](https://user-images.githubusercontent.com/33131869/32095850-364c4f62-bb22-11e7-839a-1bf8dd17e264.png)

**Comment by rotorgames** [comment]
@Rakuchetu Are these default buttons of Android?

**Comment by Rakuchetu** [comment]
Hi,

Thanks
its button issue because i am using custom render button. I already solve it. its mine issue not plugin.

**Comment by rotorgames** [comment]
@Rakuchetu Nice to hear it. Good luck.
