### ISSUE TITLE
Xamarin Updation

### ISSUE THREAD

**Issue by ankita-uttam** [rotorgames/Rg.Plugins.Popup#183]
Hi can you please update the Xamarin version of ur package to latest i.e. v2.4.0.282. We have updated the Xamarin version of our project to latest, henceforth some of your plugin features such as (closing popup on background click) are not compatible which is resulting in inconvenience due to version conflict. Kindly look into it.

**Comment by Szymaniuk** [comment]
https://github.com/rotorgames/Rg.Plugins.Popup/issues/173 isn't it exactly this one?

**Comment by ankita-uttam** [comment]
Oh my mistake i didnt notice the ticjet was already raised.

**Comment by rotorgames** [comment]
Duplicate #173
