### ISSUE TITLE
Lottie Animations do not play in Popup on iOS with latest 1.1.0-pre3

### ISSUE THREAD

**Issue by steveoleary** [rotorgames/Rg.Plugins.Popup#184]
Hi,

When playing Lottie animations using Lottie for Xamarin forms (using the forms API) within a popup on iOS the animation does not play, or plays partially and then freezes. This works with the latest stable release 1.0.4, but stops working as of 1.1.0-pre1. I'll try and put a demo project together soon, but just flagging this up here for now

**Comment by steveoleary** [comment]
Found out that the animation plays fine if Autoplay on the Lottie animation is disabled and play is called in the OnAppearing method of the Popup page.

**Comment by rotorgames** [comment]
@steveoleary Hi. 1.1.0-pre3 uses UIWindow. It can be source of the problem. But I don't think that it is a big problem. You can start animation yourself in OnAppearing method.

**Comment by steveoleary** [comment]
Yeah agreed, it's not a big issue and for my needs I'm happy to just call play in the OnAppearing method. This plugin is great btw 👍

**Comment by rotorgames** [comment]
I will watch out for Xamarin.Forms and when XF will fix this problem I will update this issues.

**Comment by Umar3x** [comment]
Thanks for sharing this tp @steveoleary , saved me a lot of time.

**Comment by matt-goldman** [comment]
I'm having this same problem with the current version (1.1.5.188). However calling play from the OnAppearing method doesn't work. Animations play fine on other XAML (non-popup) pages.

**Comment by matt-goldman** [comment]
Further to this I've found that its actually when using a <Frame> and not when using the popup.
