### ISSUE TITLE
Close Button Behind Frame

### ISSUE THREAD

**Issue by JoshDiDuca** [rotorgames/Rg.Plugins.Popup#186]
I seem to be having this issue in the Android version of Rg.Plugins.Popup.

![croppedscreenshot](https://user-images.githubusercontent.com/24326522/32443117-ca1d30f0-c2f5-11e7-9825-fd619a16c7ef.png)

My Design Code:
```
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             x:Class="Proj.MessagePopupPage"
             CloseWhenBackgroundIsClicked="True">
  <pages:PopupPage.Resources>
    <ResourceDictionary>
      <Style x:Key="EntryStyle" TargetType="Entry">
        <Setter Property="PlaceholderColor" Value="#9cdaf1" />
        <Setter Property="TextColor" Value="#7dbbe6" />
      </Style>
    </ResourceDictionary>
  </pages:PopupPage.Resources>
  <pages:PopupPage.Animation>
    <animations:ScaleAnimation
      PositionIn="Bottom"
      PositionOut="Center"
      ScaleIn="1"
      ScaleOut="0.7"
      DurationIn="700"
      EasingIn="BounceOut"/>
  </pages:PopupPage.Animation>
  <ScrollView
    HorizontalOptions="Center"
    VerticalOptions="Center">
    <AbsoluteLayout>
      <Frame x:Name="FrameContainer" Margin="5"  HorizontalOptions="Center" BackgroundColor="White">
        <StackLayout IsClippedToBounds="True" Padding="10, 5" Spacing="3">
          <Label Text="To:" x:Name="ToLabel" />
          <Entry />
          <Label Text="Message:" x:Name="MessageLabel" />
          <Editor
            HorizontalOptions="Center"
            WidthRequest="200"
            HeightRequest="100"
            x:Name="MessageEntry"
            Style="{StaticResource EntryStyle}" />
          <Button
            BackgroundColor="#227FC8"
            HorizontalOptions="Fill"
            TextColor="White"
            WidthRequest="200"
            Clicked="OnSend"
            x:Name="SendButton"
            Text="Send">
            <Button.HeightRequest>
              <OnPlatform x:TypeArguments="x:Double" Android="50" iOS="30" WinPhone="30" />
            </Button.HeightRequest>
          </Button>
        </StackLayout>
      </Frame>
      <ContentView
          AbsoluteLayout.LayoutFlags="PositionProportional"
          AbsoluteLayout.LayoutBounds="1, 0, -1, -1">
        <ContentView.GestureRecognizers>
          <TapGestureRecognizer Tapped="OnCloseButtonTapped"/>
        </ContentView.GestureRecognizers>
        <Image
          x:Name="CloseImage"
          HeightRequest="30"
          WidthRequest="30">
          <Image.Source>
            <OnPlatform
              x:TypeArguments="ImageSource"
              Android="close_circle_button.png"
              iOS="close_circle_button.png"
              WinPhone="Assets/close_circle_button.png"/>
          </Image.Source>
        </Image>
      </ContentView>
    </AbsoluteLayout>
  </ScrollView>
</pages:PopupPage>
```
Which is based around the pop up login page.

I have tried 1.1.0-pre3 but that didn't work.

**Comment by yannick-tchegho** [comment]
I also have this issue ,I tried raiseChild and lowerchild in code behind but nothing change ,
is anybody has  the solution?

**Comment by higher-faster-better** [comment]
I am also facing same issue. Any updates here?

**Comment by rotorgames** [comment]
@JoshDiDuca Hi. It there this bug only in PopupPage? Does Xamarin forms pages have this problem?

**Comment by JoshDiDuca** [comment]
@rotorgames Hi, Xamarin forms pages do not have this problem, only PopupPage.

**Comment by butler1233** [comment]
I'm experiencing a similar issue on normal pages. I dont think it's PopupPage specific. 

I've laid out a label and a frame in the same grid, and in the xaml the label is written after the frame, yet, the frame still shows above the labels.

See this examnple (each table entry is a ViewCell)
![asd](https://user-images.githubusercontent.com/15906013/34161064-43a8bd0c-e4c7-11e7-8a5c-d55ea1b0004f.png)

And here's the xaml for the viewcells contents. Are other people having this issue?
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="1*"/>
            <ColumnDefinition Width="1*"/>
            <ColumnDefinition Width="1*"/>
            <ColumnDefinition Width="1*"/>
            <ColumnDefinition Width="1*"/>
            
            <ColumnDefinition Width="1*" x:Name="FinalColumn"/>
        </Grid.ColumnDefinitions>

        
        <Frame VerticalOptions="Center" HorizontalOptions="Fill" Grid.Column="0" BackgroundColor="#99404050"  Margin="25,7,0,7" Grid.ColumnSpan="6"/>
        <Frame VerticalOptions="Fill" HorizontalOptions="Fill" Grid.Column="0" BackgroundColor="#4545A6" Margin="4"/>

        
        <Label HorizontalOptions="Center" VerticalOptions="Center" Grid.Column="0" x:Name="ZoneLabel" FontSize="20" Text="1" TextColor="White"/>
        <Label HorizontalOptions="Center" VerticalOptions="Center" Grid.Column="1" x:Name="TotalLabel"  FontSize="18" Text="1" TextColor="White"/>
        <Label HorizontalOptions="Center" VerticalOptions="Center" Grid.Column="2" x:Name="RetailLabel" FontSize="18"  Text="1" TextColor="White"/>
        <Label HorizontalOptions="Center" VerticalOptions="Center" Grid.Column="3" x:Name="PrepackLabel" FontSize="18" Text="1" TextColor="White"/>
        <Label HorizontalOptions="Center" VerticalOptions="Center" Grid.Column="4" x:Name="PrepackPercLabel" FontSize="18" Text="1" TextColor="White"/>
        <Label HorizontalOptions="Center" VerticalOptions="Center" Grid.Column="5" x:Name="PicksPerLabel" FontSize="18" Text="1" TextColor="White"/>
     
    </Grid>

**Comment by butler1233** [comment]
(It was edited so many times because the code tag was not being friendly for me.)

**Comment by higher-faster-better** [comment]
Xamarin forms pages have this issue. I'v tested so many time in several ways but I couldn't fix it.

**Comment by EmilAlipiev** [comment]
see this question and answer on stackoverflow. it is problem of xamarin.forms

https://stackoverflow.com/questions/45427276/absolutelayout-doesnt-align-controls-as-expected-when-positions-are-same
