### ISSUE TITLE
How to prevent dialogs from automatically resizing

### ISSUE THREAD

**Issue by MarcelJurtz** [rotorgames/Rg.Plugins.Popup#187]
Is there an option to prevent the dialogs from resizing?

In my case, I use a DevExpress Grid to display information, and when the user filters data, the dialog resizes due to the size change of the grid. Can I set the initial size of the dialog to "fixed" to prevent this from happening?

Thanks!

**Comment by rotorgames** [comment]
@MarcelJurtz Hi. I don't understand what "resizing" you mean. Can you explain more or give a screenshot?

**Comment by MarcelJurtz** [comment]
I use the dialog to display a table and confirmation buttonss. The user can select entries from the table and leave the dialog with one of the buttons "abort" or "ok".

The user also has the possibility to filter the table. This reduces the contents of the table, which also reduces the overall size of the dialog. If you filter the contents of the table, the entire dialogs size is reduced vertically. I want to prevent this change in size.

I currently can't provide a screenshot, but I hope the attached schema helps.
![sample](https://user-images.githubusercontent.com/15068888/33009344-dcf90460-cdd6-11e7-9c0f-ce4220a7ae6c.png)

**Comment by rotorgames** [comment]
@MarcelJurtz You can set VerticalOptions Fill for Content of PopupPage and set top and button margin for it. Then your popup will not be vertical resized.
