### ISSUE TITLE
Margin (padding) not fully respected on UWP (BUG)

### ISSUE THREAD

**Issue by E75** [rotorgames/Rg.Plugins.Popup#188]
The following XAML displays as expected on iOS + Android:

	<ScrollView>
		<StackLayout Margin="20,20,20,20">
                   .....
		</StackLayout>
	</ScrollView>

Specifically, the Margin is respected and so the buttons aren't touching the left side of the screen on iOS + Android. However, on UWP it is.

**Comment by rotorgames** [comment]
@E75 Can you show a screenshot?

**Comment by E75** [comment]
Android Padding:
![padding android](https://user-images.githubusercontent.com/9724772/33007175-cfa835dc-cdcd-11e7-80c1-4ea8a5e9b629.png)

UWP Padding:
![wrongpadding uwp](https://user-images.githubusercontent.com/9724772/33007163-c1140190-cdcd-11e7-829f-9cb1f1fdf6bb.png)

**Comment by rotorgames** [comment]
@E75 Could you create a simple project which has this problem for an example?

**Comment by rotorgames** [comment]
Need more information
