### ISSUE TITLE
[UWP] Application crashes when setting RowHeight with ListView inside Popup page 

### ISSUE THREAD

**Issue by OmniaHussain92** [rotorgames/Rg.Plugins.Popup#189]
When setting RowHeight="60" inside listview it gives the following exception in UWP only but it works fine for Android:

> Exception thrown: 'System.Runtime.InteropServices.COMException' in Xamarin.Forms.Platform.UAP.dll

```
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             x:Class="Demo.Pages.ListViewPage">
  <StackLayout VerticalOptions="Center" HorizontalOptions="FillAndExpand" Padding="20, 20, 20, 20">
    <StackLayout BackgroundColor="White">
      <ListView x:Name="listView" RowHeight="60">
        <ListView.ItemTemplate>
          <DataTemplate>
            <TextCell TextColor="Black" Text="{Binding .}"></TextCell>
          </DataTemplate>
        </ListView.ItemTemplate>
      </ListView>
    </StackLayout>
    <Button Text="Close" TextColor="#A9D1DE" Clicked="OnClose"></Button>
  </StackLayout>
</pages:PopupPage>
```

**Comment by rotorgames** [comment]
@OmniaHussain92 Hi. Did you try to reproduce it with a default Xamarin.Forms page?

**Comment by OmniaHussain92** [comment]
@rotorgames yes, I have tried the same sample with the default Xamarin.Forms page and it works fine in UWP.

**Comment by rotorgames** [comment]
@OmniaHussain92 Ok. I will review it.

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.

**Comment by JKennedy24** [comment]
I am also seeing this issue with version 1.1.5.188

Has this fix been merged into stable branch and released?

**Comment by JKennedy24** [comment]
The only workaround I found for this was to put a style in the code behind like so:

            //workaround for this issue https://github.com/rotorgames/Rg.Plugins.Popup/issues/189 for mileage popup
            var milageStyle = new Style(typeof(ListView));
            if (Xamarin.Forms.Device.RuntimePlatform != Xamarin.Forms.Device.UWP)
            {
                milageStyle.Setters.Add(new Setter() { Property = ListView.RowHeightProperty, Value = 60 });
            }
            Application.Current.Resources.Add("listviewpopup", milageStyle);

and then use this on the listview contained in the popuppage:

`<ListView x:Name="listview" Grid.Row="1" ItemsSource="{Binding Milage}" Style="{StaticResource listviewpopup}">`
