### ISSUE TITLE
Question : confirmation popup ?

### ISSUE THREAD

**Issue by Pirate911** [rotorgames/Rg.Plugins.Popup#190]
Hi , 
Thanks for the great control . My question : is it possible to use this control as confirmation popup that has Yes/No style ? 

Thanks

**Comment by rotorgames** [comment]
@Pirate911 Hi. Yes of course but a style will not look like default popup style in platform.

**Comment by EmilAlipiev** [comment]
it is possible. you can add 1 label for text 2 buttons and return value from button. @rotorgames  already wrote how to return value from popup. search inside issues how to return value from popup.
