### ISSUE TITLE
CloseWhenBackgroundIsClicked not works on Android with Xamarin.Forms 2.5.0.91635 when used with other third party libraries

### ISSUE THREAD

**Issue by ankita-uttam** [rotorgames/Rg.Plugins.Popup#194]
Hi this issue is still happening in my project. I am not able to close popup on background click.. I dont think xamarin version is a problem here since I tried this plugin with simple xamarin project and it was working fine. Is this plugin dependent on any third party libraries as well? We are using some third party libraries in our project like Xlabs.

**Comment by robintschroeder** [comment]
+1 
I am experiencing the same thing without Xlabs. Not sure what is going on. I did a quick workaround by wiring up a way to pop it off the stack.

**Comment by ErickDuarte** [comment]
Hi,

In my case, I use the same version of Xamarin.Forms and the plugin Rg.Plugins.Popup: 1.1.0-pre5 and it has worked well for me.
[https://www.nuget.org/packages/Rg.Plugins.Popup/1.1.0-pre5](url)

Then try to clean the solution and remove bin and obj folders from each project and that's it.

I hope this helps you.

**Comment by rotorgames** [comment]
Fixed in v1.1.0-pre5

**Comment by EmilAlipiev** [comment]
@rotorgames  is there some breaking changes? this was working with 1.1.0-pre5 but not using latest pre 1.1.3.73pre, it doesnt work again on Android.

**Comment by rotorgames** [comment]
@EmilAlipiev InputTransparent works so bad. You can see a behavior like this in a default Xamarin.Forms.Page. I will have to do a lot of work that the InputTransparent works.
