### ISSUE TITLE
In UserDialog Alert, when push new rg.popup this appear over the Alert IOS

### ISSUE THREAD

**Issue by FranciscoSS** [rotorgames/Rg.Plugins.Popup#196]
`UserDialogs.Instance.Alert("Ok 1");
await PopupNavigation.PushAsync(new PopupPageTest());`

![simulator screen shot - iphone 8 - 2017-12-06 at 15 12 57](https://user-images.githubusercontent.com/5408812/33685661-f3aa1186-da97-11e7-810f-284b62badd6b.png)

**Comment by jcgaribayr** [comment]
Does anyone have a work around for this?

**Comment by rotorgames** [comment]
@jcgaribayr Hi. What version of popup plugin do you use? Could you update this plugin to v1.1.0-pre5?

**Comment by jcgaribayr** [comment]
I was using version 1.0.4. I'm updating to version 1.1.0-pre5.

**Comment by rotorgames** [comment]
@jcgaribayr It should be fixed in v1.1.0-pre5 or higher

**Comment by rotorgames** [comment]
I advise to use the last beta release that will not have this problem.

Not afraid to reopen this issue if you have this problem again. 

Thanks
