### ISSUE TITLE
AutoHeight Popup

### ISSUE THREAD

**Issue by jrahma** [rotorgames/Rg.Plugins.Popup#197]
Hi,

I have below simple popup with a Label, Entry and Button

I want the popup to be adjusted according the controls on it instead of showing full page.

Is there any way to make it AutiHeight or I only have to manually set the height of it?

```
<?xml version="1.0" encoding="UTF-8"?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Zeera.ZeeraPopupNewMerchantCategory"
    xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
    xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup">
  <!--Animations use example-->
  <pages:PopupPage.Animation>
    <animations:ScaleAnimation 
      PositionIn="Bottom"
      PositionOut="Center"
      ScaleIn="1"
      ScaleOut="0.7"
      DurationIn="700"
      DurationOut="500"
      EasingIn="BounceOut" />
  </pages:PopupPage.Animation>
  <!-- Content -->
    <StackLayout Margin="20" Padding="10" BackgroundColor="White">
        <Label Text="New Category" />
        <Entry x:Name="txtNewMerchantCategoryName" Placeholder="Category Name" />
        <Button x:Name="btnNewMerchantCategoryName" Text="Save" />
    </StackLayout>
</pages:PopupPage>

```
Thank,
Jassim

**Comment by rotorgames** [comment]
@jrahma Hi. You can create auto height popup if you set VerticalOptions to Start, Center or End

**Comment by Ofaim** [comment]
I'm not what you've meant, "VerticalOptions" to which item.
I've tried 
`<StackLayout VerticalOptions="Center">`
and it filled the entire screen.

**Comment by rotorgames** [comment]
@Ofaim You should set VerticalOptions to element which you add to PopupPage.Content

**Comment by EmilAlipiev** [comment]
I think that this question has nothing to do with the popup. it is xamarin forms basics. you should look for your solution on xamarin forms. best to use a datagrid. Stacklayout will take the size of the children. please read the layouts on xamarin forms documentation
