### ISSUE TITLE
"Platform is not created" when create a PopUp on firstpage on TabbedPage

### ISSUE THREAD

**Issue by marcelinhovt** [rotorgames/Rg.Plugins.Popup#199]
So, my app the user logs in, so i create a TabbedPage with 4 childrens... the first page that opens, i call:
LoadingPage popupPage = new LoadingPage("Getting Data...");
PopupNavigation.PushAsync(popupPage, true);

I want this popup for when i am getting some data from API...i Cannot use on OnAppearing() because i don´t need to refresh all the time that this page is opened....just the first time. So, i call this after             InitializeComponent()

At the anothers pages worked normally. But at the first page is not working...how to fix it ?

I also tryed:
PopupNavigation.PushAsync(new LoadingPage(), true);

And also tryed with Await

Always the same error "Platform is not created"

I am using the version 1.1.0-pre5 !

**Comment by marcelinhovt** [comment]
Today i tried :

private bool first = true;

protected override void OnAppearing()
        {
           
            base.OnAppearing();
            
            if (first)
            {
                   PopupNavigation.PushAsync(new LoadingPage("Refreshing data..."));
            }
            first=false;
       }


Don´t work as well. Don´t show the popup

**Comment by rotorgames** [comment]
@marcelinhovt Hi. You can push your popup page only when an Application class will be created and when a LoadApplication method will be finished. If you get this exception then you push a popup page too early.

**Comment by Adlbert** [comment]
Hi
I am getting the same Error. Doesn't matter where I am calling `PopupNavigation`.
Xamarin.Froms 2.5.0.121934
Rg.Plugins.Popup 1.1.0-pre5

Again, downgrading XF to 2.4.0.38779 solves the Problem, however I dont to be stuck with this version. 
This problem only occurs in Android.

I have tried to run 
`activityType.GetField("_platform", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)?.GetValue(Xamarin.Forms.Forms.Context);`

after `global::Xamarin.Forms.Forms.Init(this, bundle);`

I am using `FormsAppCompatActivity`.

But the function always returns null not depending on which XF version I am using.

**Comment by rotorgames** [comment]
@marcelinhovt @Adlbert Please try to use v1.1.2.x-pre

**Comment by marcelinhovt** [comment]
I will give a try! Thanks...
It just happens with the TabbedPage in my case... I tried with singles contentspage before and show the popup. When i try to show the Pop before call the TabbedPage, don´t work.

**Comment by marcelinhovt** [comment]
I cannot install the version 1.1.2.x-pre !! I am receiving a error when trying

**Comment by rotorgames** [comment]
@marcelinhovt Install the last pre release v1.1.3.73-pre for example.

**Comment by marcelinhovt** [comment]
I tried... but not success... Instead of success, i got other error... But
i will try again after the new year.

Thanks for the attention and happy new year matte!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-29 4:28 GMT-02:00 Kirill <notifications@github.com>:

**Comment by rotorgames** [comment]
@marcelinhovt Happy new year. When you have time please send me a stack trace of the exception.

**Comment by Adlbert** [comment]
I am using: 

`
LoadApplication(new App());
`
`
Rg.Plugins.Popup.Popup.Init(this, bundle);
`

And it works just fine. Previous I asumed to use Popup.Init after Xamarin.Init.

**Comment by rotorgames** [comment]
@Adlbert I should use `Rg.Plugins.Popup.Popup.Init` before `LoadApplication`

**Comment by marcelinhovt** [comment]
@Adlbert wich version of popup plugin and XF are u using ?

**Comment by marcelinhovt** [comment]
I upgraded to the version 1.1.3.73-pre

I have one pre screen with a login and popup works nicelly...
Then, i have another login screen, that is optionally for the user... After this, i load the Main TabbedPage. Here, the popup don´t work. Don´t appear.

public void DenieLoginFacebook(object sender, EventArgs e)
        {
            PopupNavigation.PushAsync(popupPageDenie, true);

            BindingContext = this;
            App.Current.MainPage = new NavigationPage(new TabsPage(accountInsta) ) { BarBackgroundColor = Color.FromHex("4BA0FB"), BarTextColor = Color.White };
            Navigation.RemovePopupPageAsync(popupPageDenie, true);

        }
