### ISSUE TITLE
Error in Demo

### ISSUE THREAD

**Issue by acaliaro** [rotorgames/Rg.Plugins.Popup#2]
I have tried to use your Demo. This is the problem

https://www.dropbox.com/s/cktm5tdn0v7qt2g/Screenshot%202016-02-22%2022.50.16.png?dl=0

**Comment by rotorgames** [comment]
@acaliaro Hey. Before starting the 'Demo', you need to install nuget packages. For all projects make Restore Nuget package.
http://clip2net.com/s/3uGqR3H

**Comment by acaliaro** [comment]
Thanks @rotorgames, I try. Does the popup disable the background page or I have to disable controls one by one?

**Comment by rotorgames** [comment]
@acaliaro I dont understand you. You wanna disable background or hide PopupPage?

**Comment by acaliaro** [comment]
Sorry my English is orrible, I know. The page in background is disabled?

**Comment by rotorgames** [comment]
@acaliaro Yes, you can make transparent background. 

```csharp
// Constructor you popup page
public MyPopupPage()
{
  BackgroundColor = Color.Transparent;
  // or if yot wanna transparent 50%
  BackgroundColor = Color.FromRgba(0, 0, 0, 128);
}
````
or in xaml
```xml
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             BackgroundColor="#00000000" // Transprent
             BackgroundColor="#00000000" // Transprent 50%
             >
```

You can blend transparent and color. For example, #80FF0000. This color is red and opacity 50%.

For more information, see help of `PopupPage` [Properties](https://github.com/rotorgames/Rg.Plugins.Popup#popuppage-properties)

**Comment by acaliaro** [comment]
about my "build" problem, nothing to do. update packages, restored packages, but the problem is present.

**Comment by rotorgames** [comment]
@acaliaro Why you want demo project? You can install PopupPlugin of nuget.

**Comment by acaliaro** [comment]
yes of course, but I would like to do some tests and with a project already created it's more simple.
No problem, I'll do in another way.
Thanks

**Comment by rotorgames** [comment]
@acaliaro What is your native language?

**Comment by acaliaro** [comment]
Are you talking about Italian or about C#? ;)
Another last question: is your popup working only with a NavigationPage?

if I have a

`Main = new PageX();`

can I create a popup for PageX ?

**Comment by rotorgames** [comment]
> if I have a
> 
> Main = new PageX();
> 
> can I create a popup for PageX ?

Yes, you can make it.

Only requirement, MainPage must by installed.

**Comment by acaliaro** [comment]
Do I have to use always 

`await Navigation.PushPopupAsync(page);`
?

**Comment by rotorgames** [comment]
@acaliaro You can use `await Navigation.PushPopupAsync(page)` or `PopupNavigation.PushAsync(page)`

**Comment by acaliaro** [comment]
Ok thanks, I try
