### ISSUE TITLE
[iOS] - the background color is lost when trying to re-use the PopupPage instance

### ISSUE THREAD

**Issue by jamesatgithub** [rotorgames/Rg.Plugins.Popup#20]
in the constructor of subclass of PopupPage, I set customized background color, the colors works first time the instance of this class to be popuped by Rg.Plugins.Popup.Services.PopupNavigation.PushAsync method, but after closed and using same method to popup same instance, the background color gone. (opacity property seems has same bug)

**Comment by rotorgames** [comment]
@jamesatgithub Hi friend. Will be fixed in 1.0.0 version. Now, please, create new instance PopupPage before as opening.

**Comment by rotorgames** [comment]
Fix in [v1.0.0-pre3](https://www.nuget.org/packages/Rg.Plugins.Popup/1.0.0-pre3)
