### ISSUE TITLE
Object reference not set on intialising on iOS

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#200]
I have seen an error coming back from my clients running on Iphone 6s

Exception:  - Object reference not set to an instance of an object   at Rg.Plugins.Popup.IOS.Impl.PopupNavigationIOS.GetTopViewController () <0x107cd6320 + 0x0002c> in <f0c2f165454f4412a2b16a9f4bf28a4f#e023f66b6d348f0dfa8eac155581de10>:0    at Rg.Plugins.Popup.IOS.Impl.PopupNavigationIOS.AddPopup (Rg.Plugins.Popup.Pages.PopupPage page) <0x107cd60c0 + 0x00023> in <f0c2f165454f4412a2b16a9f4bf28a4f#e023f66b6d348f0dfa8eac155581de10>:0    at Rg.Plugins.Popup.Services.PopupNavigation.PushAsync (Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) <0x107cc2570 + 0x001eb> in <e4a0d036d16d43a8a07fbef673df812b#e023f66b6d348f0dfa8eac155581de10>:0    at FieldStrikeMove.Core.Services.PageOperations+<>c__DisplayClass11_0+<<ShowDialog>b__0>d.MoveNext () <0x106b6d580 + 0x00043> in <94c3f63aafb349fa9f00b9967bc1d96d#e023f66b6d348f0dfa8eac155581de10>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x1052e4540 + 0x00028> in <1f5960abbfdf4434802d3b8a03ded4fa#e023f66b6d348f0dfa8eac155581de10>:0    at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) <0x1052e6fb0 + 0x00053> in <1f5960abbfdf4434802d3b8a03ded4fa#e023f66b6d348f0dfa8eac155581de10>:0    at UIKit.UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 () <0x106431950 + 0x00027> in <af01d8cf05c449d38c6437c2d0d8808c#e023f66b6d348f0dfa8eac155581de10>:0    at Foundation.NSAsyncActionDispatcher.Apply () <0x106404690 + 0x00023> in <af01d8cf05c449d38c6437c2d0d8808c#e023f66b6d348f0dfa8eac155581de10>:0    at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)   at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) <0x106433f30 + 0x0002b> in <af01d8cf05c449d38c6437c2d0d8808c#e023f66b6d348f0dfa8eac155581de10>:0    at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x106433e70 + 0x000ab> in <af01d8cf05c449d38c6437c2d0d8808c#e023f66b6d348f0dfa8eac155581de10>:0 

I'm affraid I dont have any more information than that. But inspecting the stack trace is it possible to find the error?

**Comment by JKennedy24** [comment]
This could be pushing the first page. Could be a race condition where popup page tries to display before initial page

**Comment by rotorgames** [comment]
@JKennedy24 Thank you for issues. Can you give version of plugin, iOS SDK and iOS on device?

**Comment by bijington** [comment]
Just to hopefully try and add some help. I also saw this issue however it was because I hadn't added the package to my iOS project as well as the PCL one.

**Comment by JKennedy24** [comment]
I haven't seen this error pop up for a while (excuse the pun). I may have fixed it by pushing new popup pages on the main thread.

I will close it off and re-open if I get it again with more info
