### ISSUE TITLE
Unit Testing PushPopUpAsync

### ISSUE THREAD

**Issue by mayesa** [rotorgames/Rg.Plugins.Popup#201]
Hi! 

I'm trying to unit test a view model method that uses `Navigation.PushPopupAsync(somePage);`

With 1.0.4 it fails with
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Rg.Plugins.Popup.Services.PopupNavigation.PushAsync (Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) [0x00043] in <e4a0d036d16d43a8a07fbef673df812b>:0 
```

With 1.1.0-pre5 fails with
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<AddAsync>d__9.MoveNext () [0x00028] in <241c5b42c38e4199875a15fcb780e7e3>:0 
```
I have added the plugin to my nunit project. Do I need to do something else?

Thx

**Comment by rotorgames** [comment]
@mayesa Hi. What would you like to test?

**Comment by rotorgames** [comment]
@mayesa P.S. If you would like to test your view model. You should implement your instance of `IPopupNavigation`.

**Comment by mayesa** [comment]
Hi @rotorgames ! I was trying to mock the instance, but I'm getting an error. 
The relevant code is something like:
```
Mock<INavigation> NavigationMock = new Mock<INavigation>();
NavigationMock.Setup(mock => mock.PushPopupAsync(It.IsAny<MyPopupPage>(), true)).Returns(Task.FromResult(true));
var viewModel = new MyViewModel()
{
    Navigation = NavigationMock.Object
};
viewModel.MyCommand.Execute(null);
NavigationMock.Verify(mock => mock.PushPopupAsync(It.IsAny<MyPopupPage>(), true));
```
In the Setup line, I'm getting an error that prevents the unit test suite to run.

If I comment out the Setup line, I'm getting the Fatal Exception I mentioned in my first comment.

Thx!

**Comment by rotorgames** [comment]
@mayesa for using unit tests you should update the plugin to v1.1.0-preX. After it you should implement `Rg.Plugins.Popup.Contracts.IPopupNavigation` for tests. For production you should use PopupNavigation.Instance for dependency injection.

**Comment by mayesa** [comment]
oh thx for the heads up! I'll give it a try and let you know :)

**Comment by rotorgames** [comment]
@mayesa You are welcome

**Comment by EmilAlipiev** [comment]
@mayesa  can you please give a feedback and close the ticket if it works?

**Comment by mayesa** [comment]
@EmilAlipiev I haven't had time to test it yet.

**Comment by rotorgames** [comment]
@mayesa I close this issues. If you have a problem, reopen this issues.

**Comment by mayesa** [comment]
Hi! I upgraded to 1.1.1.57 and when running my unit tests I'm getting this error

`FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: You MUST install Rg.Plugins.Popup to each project and call Rg.Plugins.Popup.Popup.Init(); prior to using it.`

I have the plugin installed in the unit test project, but how can I initialize it? I could not find the instructions in https://github.com/rotorgames/Rg.Plugins.Popup/tree/master#initialization

thx

**Comment by rotorgames** [comment]
@mayesa Hi. What would you like to test? My plugin? If not you should not initialize my plugin. Just use `Rg.Plugins.Popup.Contracts.IPopupNavigation` in your tests and don't use `Rg.Plugins.Popup.Services.PopupNavigation` or `Rg.Plugins.Popup.Services.PopupNavigation.Instance`. Your tests must test only your code, not my.

Thanks.

**Comment by mayesa** [comment]
Sorry @rotorgames I've just found a line in the code that's directly using `Rg.Plugins.Popup.Services.PopupNavigation`. Thx!

**Comment by rotorgames** [comment]
@mayesa You are welcome

**Comment by PrvnKmr** [comment]
I am facing the same issue mentioned here. In my tests, I have a view model method which uses INavigation.PushPopupAsync() to display a popup. Here, when runnig the test for the method, it fails with the error 

FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: You MUST install Rg.Plugins.Popup to each project and call Rg.Plugins.Popup.Popup.Init(); prior to using it.

Thanks.
