### ISSUE TITLE
V1.1.0 pre 5 - Re displaying popup that contains images crashes

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#202]
I have a popup page on android that contains an image

I show this popup page and cache the page in my app.

I then close the page and then redisplay it using the cached version.

App crashes with `Stream cannot be accessed after it is disposed`

**Comment by JKennedy24** [comment]
(using FastRenderers)

**Comment by rotorgames** [comment]
@JKennedy24 Can you give a full stack trace of exception? If you disable FastRenderers an exception will not be thrown?

**Comment by rotorgames** [comment]
@JKennedy24 I understood your problem. It is not plugin problem. Your can't use an one instance of 
the Stream twice. Check your code.

**Comment by JKennedy24** [comment]
I don't think this is a problem with my code. Nothing has changed between using latest stable rg.popup and upgrading to 1.1.1-pre.

I would say something in the way the pages are disposed must have changed.

Stacktrace:
System.ObjectDisposedException: Cannot access a closed Stream.

12-20 10:55:44.288 I/MonoDroid(12031): UNHANDLED EXCEPTION:
12-20 10:55:44.322 I/MonoDroid(12031): System.ObjectDisposedException: Cannot access a closed Stream.
12-20 10:55:44.322 I/MonoDroid(12031):   at System.IO.__Error.StreamIsClosed () [0x0000b] in <657aa8fea4454dc898a9e5f379c58734>:0 
12-20 10:55:44.322 I/MonoDroid(12031):   at System.IO.MemoryStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0006a] in <657aa8fea4454dc898a9e5f379c58734>:0 
12-20 10:55:44.322 I/MonoDroid(12031):   at Android.Runtime.InputStreamAdapter.Read (System.Byte[] bytes, System.Int32 offset, System.Int32 length) [0x00006] in <28e323a707a2414f8b493f6d4bb27c8d>:0 
12-20 10:55:44.322 I/MonoDroid(12031):   at Java.IO.InputStream.n_Read_arrayBII (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_b, System.Int32 off, System.Int32 len) [0x00019] in <28e323a707a2414f8b493f6d4bb27c8d>:0 
12-20 10:55:44.322 I/MonoDroid(12031):   at (wrapper dynamic-method) System.Object:0a1c0ba7-d73c-4ad0-a0b9-8704a8160c57 (intptr,intptr,intptr,int,int)
12-20 10:55:44.330 I/Choreographer(12031): Skipped 393 frames!  The application may be doing too much work on its main thread.
12-20 10:55:44.335 I/MonoDroid(12031): System.ObjectDisposedException: Cannot access a closed Stream.
12-20 10:55:44.335 I/MonoDroid(12031):   at System.IO.__Error.StreamIsClosed () [0x0000b] in <657aa8fea4454dc898a9e5f379c58734>:0 
12-20 10:55:44.335 I/MonoDroid(12031):   at System.IO.MemoryStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0006a] in <657aa8fea4454dc898a9e5f379c58734>:0 
12-20 10:55:44.335 I/MonoDroid(12031):   at Android.Runtime.InputStreamAdapter.Read (System.Byte[] bytes, System.Int32 offset, System.Int32 length) [0x00006] in <28e323a707a2414f8b493f6d4bb27c8d>:0 
12-20 10:55:44.335 I/MonoDroid(12031):   at Java.IO.InputStream.n_Read_arrayBII (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_b, System.Int32 off, System.Int32 len) [0x00019] in <28e323a707a2414f8b493f6d4bb27c8d>:0 
12-20 10:55:44.335 I/MonoDroid(12031):   at (wrapper dynamic-method) System.Object:0a1c0ba7-d73c-4ad0-a0b9-8704a8160c57 (intptr,intptr,intptr,int,int)

**Comment by JKennedy24** [comment]
still broken with "fastRenderers" turned off

**Comment by JKennedy24** [comment]
You can reproduce this on Android

-have a page that you cache and redisplay.
- add an image that is bound to a property that uses a memory stream

display page twice and crashes with above exception.

using popup 1.1.1-pre
XF 2.4.0

**Comment by JKennedy24** [comment]
Actually forget the above:

Fixed by changing property to:

  private ImageSource _companyLogo;

  public ImageSource CompanyLogo
  {
      get
      {
          _companyLogo = ImageSource.FromStream(() => new MemoryStream(companyLogo););
          return _companyLogo;
      }
  }

**Comment by rotorgames** [comment]
@JKennedy24 You will get this exception even if you use ContentPage of Xamarin.Forms. It is not Popup plugin's exceptions.

**Comment by rotorgames** [comment]
@JKennedy24 When CompanyLogo is set to the Image.Source a stream will be disposed because you have this exception.
