### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MsXam** [rotorgames/Rg.Plugins.Popup#204]
I have moved over to v1.1.0-pre7 because of the issue in 1.0.4 with Android whereby clicking on the background didnt close the popup. The pre7 fixed the issue in Android. However - the pre7 causes issues in iOS that worked in 1.0.4. The issue I am now seeing is  which occurs on all popups is :

_System.NullReferenceException: Object reference not set to an instance of an object
C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs, line 78_

and full stack log being :

### Rg.Plugins.Popup.Services.PopupNavigationImpl.<AddAsync>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()exceptionservicescommon.cs:152
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)TaskAwaiter.cs:187
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)TaskAwaiter.cs:156
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)TaskAwaiter.cs:128
System.Runtime.CompilerServices.TaskAwaiter.GetResult()TaskAwaiter.cs:113
Rg.Plugins.Popup.Services.PopupNavigationImpl.<PushAsync>d__5.MoveNext()
Prism.Navigation.PopupExtensions.PushPopupPageAsync()<37b28110804d4d8b9cde60c2d8d2132f>:0

**Comment by rotorgames** [comment]
@MsXam What version of Xamarin.Forms do you use?

**Comment by MsXam** [comment]
Sorry - I forgot to add that I'm using **XF 2.5.0.91635**

**Comment by rotorgames** [comment]
@MsXam Did you update all project in your solution to v1.1.0-pre7?

**Comment by MsXam** [comment]
Yes, all projects have been updated to include this new version. Android works for me , its just iOS  - i've just noticed you have a pre 8 - i will try that

**Comment by rotorgames** [comment]
@MsXam Update to v1.1.0-pre8 or pre9 when it will be released, after it clear your solution and remove each bin and obj folders in your solution and try again.

**Comment by MsXam** [comment]
Thanks , I'm updating all projects to v1.10-pre8 now and will then clean and remove all projects bin/obj then do a full rebuild and post back the result ...

**Comment by MsXam** [comment]
v1.1.0-pre8 , clean bin/obj and full rebuild fixes the issue.
Many thanks.

**Comment by chrisfoulds** [comment]
Will you be doing a non-prerelease build with these fixes ?
