### ISSUE TITLE
Android first run performance issue

### ISSUE THREAD

**Issue by yuv4ik** [rotorgames/Rg.Plugins.Popup#205]
Hello,

I am experiencing a very poor performance on Android, PushPopUpAsync() takes at least 7 seconds for the popup to appear for a very first time. Next executions are much faster.
Successfully reproduced with an empty popup without any animations applied.

Both a real device SM-G388F with Android 5.1.1 and Emulator with Android 7.1 are affected.

Could you please suggest some tips on optimisation?

Xamarin.Forms: 2.3.4.270
Rg.Plugins.Popup: 1.0.4

P.S.: Thank you for a great plugin, I am using it quite a lot in my projects.

**Comment by rotorgames** [comment]
@yuv4ik Hi. Update Xamarin.Forms to the last stable version and update this plugin to v1.1.0-pre8 or pre9 and notify me about results. Thanks.

**Comment by yuv4ik** [comment]
@rotorgames  seems like the performance was affected by third party libraries. Nothing to do with the Rg.Plugins.Popup.
