### ISSUE TITLE
Interact with behind page when popup is active

### ISSUE THREAD

**Issue by luccasclezar** [rotorgames/Rg.Plugins.Popup#206]
I want to create a Snackbar-like control and I want it to be on top of everything else (Drawer, TabbedPage, etc), so I can't use an AbsoluteLayout or something like that.

The only problem that I'm encountering is that the PopupPage's background is preventing me of interacting with the behind page while the Snackbar is active, and if I set InputTransparent on the PopupPage I can't interact with the Snackbar.

I don't know if there's a way to set only the page's background to InputTransparent but I think that the best solution would be to implement a way of adding single views to the PopupStack instead of Pages, like a Grid, a StackLayout or something like that.

**Comment by rotorgames** [comment]
@luccasclezar Hi. InputTransparent should work in v1.1.0-pre5 or higher on Android and UWP. iOS version can no work [but I have added this task to the todo list](https://github.com/rotorgames/Rg.Plugins.Popup/projects/1#card-6244443).

**Comment by luccasclezar** [comment]
Hi!

Actually, InputTransparent works, but if set, I can't interact with the PopupPage itself, only with the page behind the PopupPage.

But I managed to workaround this issue by setting the snackbar on the PopupPage's top and Translating the Y axis of the page down to the bottom by using native methods.


    var translation = ToPxFloat(Height - s.Height);
    var renderer = this.GetOrCreateRenderer() as PageRenderer;

    #if __ANDROID__

    renderer.SetY(translation);

    #elif WINDOWS_UWP

    renderer.Margin = new Windows.UI.Xaml.Thickness(0, translation, 0, 0);

    #elif __IOS__

    renderer.View.LayoutMargins = new UIKit.UIEdgeInsets(translation, 0, 0, 0);

    #endif

I didn't test translation on iOS but it should work.

So, right now, I think that it would be nice if we could add views instead of Pages as Popups, but I don't think it's a big deal.

Thanks!

**Comment by rotorgames** [comment]
@luccasclezar I have thought about it and I think that it will be a good idea. I will add it to todo list. Thanks.
