### ISSUE TITLE
Popup doesn't resize when the app resumes

### ISSUE THREAD

**Issue by luccasclezar** [rotorgames/Rg.Plugins.Popup#209]
Steps to reproduce:
- Display a Popup and click on some editor to open the Soft Keyboard
- Go to Home Screen
- Go back to the app

You'll see that where the keyboard should be, now there's the page behind the popup.
![device-2017-12-27-131059](https://user-images.githubusercontent.com/12024080/34385295-bf254d5a-eb08-11e7-9fd7-912c66c06380.png)

I think that the correct approach would be either re-open the keyboard or resize the popup.

**Comment by rotorgames** [comment]
@luccasclezar Hi. What version of popup plugin and xamarin forms did you use? Is it Android or iOS?

**Comment by luccasclezar** [comment]
Xamarin.Forms: 2.5.0.121934
Rg.Plugins.Popup: 1.1.0-pre5

I only tested on Android.

**Comment by EmilAlipiev** [comment]
Ok this occurs also on the latest pre release as well on Android. Best to test with the device.

**Comment by rotorgames** [comment]
@luccasclezar @EmilAlipiev Could you test it with the last beta build (>=1.1.3.120-beta) from Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99? 

I will be so grateful.

**Comment by luccasclezar** [comment]
Tested with 1.1.3.120-beta and the issue persists.

**Comment by rotorgames** [comment]
@luccasclezar What version of Android did you use?

**Comment by EmilAlipiev** [comment]
I tested on Android 6 device sony Xperia z3, it doesnt occur for me anymore

**Comment by rotorgames** [comment]
Confirmed on Android 7.0+

**Comment by rotorgames** [comment]
I have fixed it in the beta release v1.1.3.127-beta. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

P.S. Not afraid to reopen this issue if you have this problem again.

Thanks

**Comment by luccasclezar** [comment]
Yeah, I can confirm it's really fixed!

Thanks!

**Comment by rotorgames** [comment]
@luccasclezar Thank you for your report.
