### ISSUE TITLE
Pop up window is not strictly modal

### ISSUE THREAD

**Issue by msmrajesh** [rotorgames/Rg.Plugins.Popup#21]
Hi,
While this is a good implementation of showing a pop up window that is smaller in size than the parent it lacks one important feature viz. showing the pop up as a modal window. If I tap anywhere outside the pop up window it closes which is not the correct behavior. This pop up window should be strictly modal until the user  taps the button to dismiss it.

Can this be fixed because that is one important behavior to follow when implementing pop ups.

Regards,

Rajesh.

**Comment by rotorgames** [comment]
@msmrajesh Hi friend. Yes, you can disable close on background click. Use IsCloseOnBackgroundClick = false property, in PopupPage

**Comment by msmrajesh** [comment]
Thanks a lot. Very nice control and it serves my purpose.
