### ISSUE TITLE
All versions(even the pre-release 5) is crashing on ios with the following stacktrace: 

### ISSUE THREAD

**Issue by PauloJoseBR** [rotorgames/Rg.Plugins.Popup#210]
> Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.UpdateElementSize()
> Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.ViewDidLayoutSubviews()
> ObjCRuntime.Messaging.objc_msgSend(intptr, intptr)(wrapper managed-to-native)
> CoreAnimation.CATransaction.Commit()
> Xamarin.Forms.Platform.iOS.CADisplayLinkTicker.StartThread()
> System.Threading.ThreadHelper.ThreadStart_Context(object state)
> System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
> System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
> System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state)
> System.Threading.ThreadHelper.ThreadStart()

**Comment by rotorgames** [comment]
@PauloJoseBR Hi. Try to update the plugin to v1.1.3.73-pre. Thanks
