### ISSUE TITLE
UWP-Android breaking change on 1.1.3,73-pre

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#211]
I just upgraded to latest pre although i cant find any release notes. what are the changes and fixes? can you please tell me?

Beside that Below code was working for previous versions now it is not recognized in this version in UWP application

`      assembliesToInclude.AddRange(Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies());`

Does Android need from this version? before It was working without init

 `   Rg.Plugins.Popup.Popup.Init(this, bundle);`

**Comment by EmilAlipiev** [comment]
Ok i see that You update documentation [here](
https://github.com/rotorgames/Rg.Plugins.Popup/commit/271f8c989e866c5cb0c04a9cb95cda10a2d7a34b#diff-04c6e90faac2675aa89e2176d2eec7d8)

So it means that in every platform we need to init now. what for is that change required? does it cause app start up time longer in Android. thank you

**Comment by rotorgames** [comment]
@EmilAlipiev Hi. It is needed because the plugin should know exactly when an activity is created again. Also the plugin uses Forms.Context which is deprecated in Xamarin.Forms 2.5. Also creating Inits methods lets to don't use Stubs projects and lets to remove some dlls. Many plugins are require to be initialized. I think that it is not bad solution.

Thanks

**Comment by EmilAlipiev** [comment]
thank you for clarifying

**Comment by EmilAlipiev** [comment]
@rotorgames I cant find        `    Rg.Plugins.Popup.Popup.Init();` in 1.1.3,73-pre version using UWP?

**Comment by EmilAlipiev** [comment]
@rotorgames Documentation is wrong for UWP i think. there is only   init as below  `Rg.Plugins.Popup.Windows.Popup.Init(); `
but warning says that it is obsolete use getextraessemblies.

**Comment by EmilAlipiev** [comment]
please ignore. i cleared nuget cache, bin, obj and it recognizes init method now :)
