### ISSUE TITLE
PopupNavigation.PopAsync() requires delay to clear the stack

### ISSUE THREAD

**Issue by mofadevs** [rotorgames/Rg.Plugins.Popup#212]
Good Day rotorgames
First of all, great piece of work. This has saved us a lot of time. 
I have a PopupPage with the contents like the below:
```<ContentPage.Content>
    <Frame x:Name="stkMain" OutlineColor="Transparent" Padding="0" CornerRadius="10" HasShadow="False">
      <ActivityIndicator IsRunning="True" x:Name="actLoad" HorizontalOptions="Center" VerticalOptions="Center">
      </ActivityIndicator>
    </Frame>
  </ContentPage.Content>
```
I am showing it like a wait dialog, using the below:
```await PopupNavigation.PushAsync(myPopupPageInstance);//myPopupPageInstance is the object```
And hiding it like:
```await PopupNavigation.PopAsync();```
In between I am doing some processing. But sometimes when processing does not a take lot of time, the PopAsync() has no effect and the popup is still there.

So as a workaround I tried to give intentional delay in between and it worked, like the following:

```
await PopupNavigation.PushAsync(myPopupPageInstance);//myPopupPageInstance is the object
//Do some processing
await Task.Delay(1000);//:( does not look good
await PopupNavigation.PopAsync();
```

Please advise.

**Comment by rotorgames** [comment]
@mofadevs Hi. It is Android, iOS or UWP?

**Comment by mofadevs** [comment]
Hi
It's happening on both.

**Comment by rotorgames** [comment]
@mofadevs What version of plugin did you use?

**Comment by mofadevs** [comment]
1.0.4. The current one.

**Comment by rotorgames** [comment]
@mofadevs Try to test the last pre release v1.1.3.73-pre

**Comment by CamelCaseMaster** [comment]
Same problem here poppup won't close no matter what

**Comment by rotorgames** [comment]
@CamelCaseMaster What version of plugin do you use?

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.
