### ISSUE TITLE
Navigation is stuck after updating pre-released version: 1.1.3.73-pre

### ISSUE THREAD

**Issue by PauloJoseBR** [rotorgames/Rg.Plugins.Popup#214]
Hi,
I updated the plugin to solve the crash mentioned in the issue below:

https://github.com/rotorgames/Rg.Plugins.Popup/issues/210

After the update, the crash disappeared(Thank you so much), however, the navigation(from the Xamarin VisualElement Class) on the app got problems, sometimes the PushAsync method is not pushing any page and the page gets stuck inside that method. 

I don't have any clue about what's going on, I debug to figure that problem out but I didn't find anything. I'd be glad if you could help me with this issue.

Thanks.

**Comment by EmilAlipiev** [comment]
Is it IOS only? I can confirm in Android works fine for me. I tested on 5,6,7,8 versions of Android

**Comment by PauloJoseBR** [comment]
@EmilAlipiev , Yes, It's iOS only. In iOS the issue is not happening.

**Comment by EmilAlipiev** [comment]
I cant comment about IOS as I am not doing right now but sometimes weird errors appear due to nuget packages. always try to clean obj, bin and nuget folders and rebuild your application to see if it solves.
