### ISSUE TITLE
iOS : No touch input, goes to underlaying page

### ISSUE THREAD

**Issue by Umar3x** [rotorgames/Rg.Plugins.Popup#215]
Hello,

On iOS when pushing a popup page, everything works fine, the popup shows and its content too.

However I got buttons in this popup page, and I noticed that when I click in the popuppage (wherever, on buttons or anywhere else) it does not receive user input/gesture but the underlaying page receives it ... So its just like if it was only displaying but user can not interact with popup.

This popupPage shows on a MasterPageDetail with a MapPage (wrapped in a NavigationPage) as Detail page. 

On android, with same code ofc, its working well. 

I'm using latest stable 1.0.4

Thanks.

**Comment by Umar3x** [comment]
OK ... sorry for that ticket. I did forget that inputTransparent was set to TRUE and that on Android it does not work, but on iOS it works so that was the reason why I had no input --'.

**Comment by Umar3x** [comment]
Ok so after a bit of work I noticed one thing : 

InputTransparent set to true on Android : Input in the popupPage still work, and same for the parent element (masterPageDetails)
This is the behavior that I expect.

InputTransparent set to true on iOS : Input in the popupPage does not work, but work for parent.

Why do we have a different behavior ? 

I must say that the popupPage is taking only 1/5 of the page (from the bottom) that's why I want the user to have the possibility to interact with parent element.

What should I do to get the behavior of Android on iOS ? THanks.

**Comment by rotorgames** [comment]
@Umar3x I added it problem to todo list. https://github.com/rotorgames/Rg.Plugins.Popup/projects/1#card-6244443

**Comment by Umar3x** [comment]
Hello,

Sorry for reoponing this issue. But still got some probs only on iOS and wanted to clarify the bug I encounter.

My usage of popup is the following : I am pushing a popup page when a user clicks on a pin, to show him some info at a bottom popup , which takes 1/5 of the page (Which is a masterPageDetails with a Navigation page as details page with a MapPage inside of it). 

I set inputTransparent to false as I have 2 buttons in this page with which the user can interact and do some actions. 

**On Android** its working perfectly, I can continue to interact with the map, scrolling and so, and click on buttons in the popupPage at the bottom. 

**On iOS** when I set inputTransparent to false, the UI is locked, every touch input is going to the popupPage even if its only at the bottom page and still showing the map. I can't even open the menu of the masterPage. 

Thanks !

**Comment by Umar3x** [comment]
This issue is related to this bug I think, and has been fixed => https://bugzilla.xamarin.com/show_bug.cgi?id=50992

Now I got another prob ... as it seems to be fixed (I mean, the different behavior on inputTransparent property between iOS/Android) .

Now if I set InputTransparent to false, the whole page inpuut is focused on the popup while it takes only 1/5 of the page.  I want the user to interact with the page which is below the popup. That's a shame, the bug on Android related to the bugzilla link I put was what I expected for my usage .

**Comment by rotorgames** [comment]
@Umar3x Hi. I know about this problem. It happens because this plugin uses UIWindows on iOS for showing a popup page. I will look for a solution for this problem.

Thanks
