### ISSUE TITLE
System Padding Does not work on Android

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#216]
So I am using the latest `Rg.Plugins V1.1.3.73-pre` with xamarin forms latest `V2.5.0.122203`

On android I have a popup page with `HasSystemPadding=true` set
I have checked the Thickness returned by `SystemPadding` which is `0`

I display a popup page and the top of the page is cut off by the status bar.

**Expected behavior:**
See the whole page appear below the Status bar

I can't seem to work out what is going on here

**Comment by JKennedy24** [comment]
Could potentially be linked to:
https://github.com/rotorgames/Rg.Plugins.Popup/issues/142
or
https://github.com/rotorgames/Rg.Plugins.Popup/issues/162

**Comment by rotorgames** [comment]
@JKennedy24 Hi. What version of Android and device do you test?

**Comment by JKennedy24** [comment]
@rotorgames V7.1.1

**Comment by rotorgames** [comment]
Duplicate #162
