### ISSUE TITLE
UWP does not work when Targeting Windows build 10240

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#217]
I have upgraded to the Latest version of Rg.popup V1.1.3.73-pre and my UWP has a target version and min version of `Windows 10 build 10240`

I then run my program on UWP and I start to get this error:

> "System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)\r\n"

After digging around the internet the only mention of this version of the library I can find is here: https://github.com/dotnet/docs/issues/3644#issuecomment-343339458

Which states:

> The update was only was published as part of Microsoft.NETCore.UniversalWindowsPlatform and you have to target Fall Creator's Update or higher for the APIs I have listed above. That gets you the following version of the assembly (4.0.3.0 is the latest standalone):
> 
> System.Runtime.WindowsRuntime, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

So essentially I think by using API's from this latest version of the library it means that the minimum you can support is `Fall Creators update`

**2 solutions:**
1. take the code that is using the latest API out of the plugin
2. Microsoft release V4.0.14 as a seperate nuget (this would be the best solution as I would imagine there are probably other people / plugins that will be hitting this error pretty soon)

**Comment by JKennedy24** [comment]
by changing these two lines:
https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup.UWP/Rg.Plugins.Popup.UWP.csproj#L14
https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup.UWP/Rg.Plugins.Popup.UWP.csproj#L15

to `10.0.1024.0` and building UWP you will see instantly what API's need to be removed to be able to support lower versions of windows

**Comment by EmilAlipiev** [comment]
yes, please provide a fix for this one. we cant force our app to use min version as fall Creators Update.

**Comment by JKennedy24** [comment]
from the linked comment https://github.com/dotnet/docs/issues/3644#issuecomment-357841269 it seems the only API added was `CreateSafeHandle` so setting the two lines back to lower versions of windows may be enough (though I'm not 100%)

**Comment by EP01** [comment]
@rotorgames A fix for this issue would be greatly appreciated here. I don't want to have to compile my own version just for this quick fix. Currently stuck on `1.1.0-pre5` because of this.

**Comment by EmilAlipiev** [comment]
I am also still holding my uwp update. it is very crucial issue for uwp. thank your for quick update

**Comment by rotorgames** [comment]
@EmilAlipiev @JKennedy24 Try to use this 1.1.3.117-beta

**Comment by JKennedy24** [comment]
@rotorgames that version works. Thanks

**Comment by rotorgames** [comment]
@JKennedy24 You are welcome

**Comment by EP01** [comment]
Just wanted to say thanks for fixing this @rotorgames! Much appreciated!

**Comment by EmilAlipiev** [comment]
@JKennedy24 quick question. are you using .net standard 1.6 or 2.0? if using 2.0, we are forced to use latest uwp version right? we cant use as minimum 10240. I am asking this because i am considering to convert my project in .net standard 2.0 but not sure if 1.6 is maybe more beneficial for uwp

**Comment by JKennedy24** [comment]
@EmilAlipiev  I am using .Net Standard 1.4. The only reason is because I am sharing this library with an old .Net Framework 4.5 project.

If you push your project to .Net Standard 2.0 you are forced to use Creators Fall Update

If you use .Net Standard 1.6. you can support Windows 10 10240 as a minimum.

The only reason I want to support the min version of Windows 10 is so I can say to my clients "it will work on any windows 10 machine" and don't have to follow it up with (only if its fully up to date)

Hope that clarifies
