### ISSUE TITLE
Popup Won't close

### ISSUE THREAD

**Issue by CamelCaseMaster** [rotorgames/Rg.Plugins.Popup#218]
Problem: POPUP WON'T CLOSE when i press the background or when i press return key

**Comment by EmilAlipiev** [comment]
how is that a problem of this plugin? try to google around a bit. there are a lot of posts about this error in SO and xamarin.forms

**Comment by rotorgames** [comment]
@CamelCaseMaster It is xamarin.forms or Xamarin.Android problem but I have fixed it in the last pre release.
