### ISSUE TITLE
[FIXED] almost transparent popup/stuck navigation ANDROID 1.1.3.73-pre

### ISSUE THREAD

**Issue by CamelCaseMaster** [rotorgames/Rg.Plugins.Popup#219]
i had a PCL-based project uusing rg.popup, it worked like a charm did nothing but follow your instrcutions in the project page

recently updated VS
created a new XF project 
downloaded latest Xamarin.Forms nuget
downloaded latest -pre rg.popup nuget 1.1.3.73-pre

followed the same instructions but with the following problems:

when i click a button to show the popup_page : (await PopupNavigation.Instance.PushAsync(new Page_Popup());)

-I can see the popuppage but it's almost transparent (checked animations no good results)
-the navigation is kinda stuck as i cannot go back to the previous page(checked button overrides)

Tested Only On ANDROID

EDIT: 

Disabling Android Animation in Developer Options causes the issue. Enabled them again & now it works as expected.

is there a way to make it work with animations disabled? Some users disable them...

**Comment by CamelCaseMaster** [comment]
Disabling Animations in developer options causes this issue.
Enabled them again & now it works as expected. (has nothing to do with popup animations)

is there a way to make it work with animations disabled?

**Comment by rotorgames** [comment]
@CamelCaseMaster Hi. I think that it will be a priority task because a lot of people write me about it problem.

Thank you for feedback.

**Comment by rotorgames** [comment]
@CamelCaseMaster Hi. I'm working on this problem and I can't reproduce it. I have disabled animations in Android but animation works fine in Demo project. Can you show what animations your have disabled and your Android version. 

Thanks

**Comment by rotorgames** [comment]
I have fixed it in the beta release v1.1.3.121-beta. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

**Comment by CamelCaseMaster** [comment]
What kind of animations I was diasbling? 
-those 3 options:  http://prntscr.com/iaj87d (+the android phone I'm currently using)

I had the problem in the 1.1.3.73-pre version.
Couldn't find the v1.1.3.121-beta instead, i upgraded the nuget to the latest version (time of making this comment). the  v1.1.14.135-beta.

Tested the nuget  v1.1.14.135-beta with 
-both animations enabled/disabled

IT WORKS, thanks a lot (y)

**Comment by rotorgames** [comment]
@CamelCaseMaster Nice to hear it. 

P.S. You can fiend all builds in the Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99
