### ISSUE TITLE
Using a stack of popup pages.

### ISSUE THREAD

**Issue by msmrajesh** [rotorgames/Rg.Plugins.Popup#22]
Hi,
I have a requirement where I need to show three pop pages one after the other (similar to a wizard where you click the next button to navigate to the next page).

The flow is like this. 

User loads the application. Buttons are visible on the home page.
User clicks the first button. A popup page appears.
On a button on this first popup page user call another popup page and it appears on top of the first popup page. 
On a button on this second popup page user call another popup page and it appears on top of the second popup page. 
Now when user click on a button on the third pop up page it should close ALL the popup pages.

How can it be done. I noticed that when calling await Navigation.PopPopupAsync(); on the second popup page it closes ONLY the second popup page and leaves the first popup page open. 

Any idea to achieve this functionality

Thanks.

**Comment by rotorgames** [comment]
@msmrajesh Use `Navigation.PopAllPopup()` or `PopupNavigation.PopAll()`.

**Comment by msmrajesh** [comment]
Thanks a lot for the reply. However I have one more query for this stack of popup windows.

When creating new forms for my assignment, I observed that the popup window would grow in size depending on the controls in each window. And since my three windows contain different number of controls I noticed that all the three popup windows can be seen overlapping each when the third one is on top. Refer to the attachment for a preview how it looks when the three popup windows are stacked over one each other. I have used the same sample from your code to demonstrate this effect. The listview page is seen at the back of the firstpopuppage.

I would like to define the height of each pop up window so that I can set all the three pop up windows to be of the same height and use scroll bars to scroll the content if needed. Kindly let me know if this can be achieved. I am truly impressed with the functionality of this pop up control.

![stackofpopups](https://cloud.githubusercontent.com/assets/18613834/15964899/7371ecfc-2f38-11e6-86be-fb0a3629855d.jpg)

**Comment by rotorgames** [comment]
@msmrajesh Hi friend. This question is not associated with my plugin. The plugin only opens Popup page, everything else, you should do it yourself with the help of xamarin forms of elements.

In your place, I would use AbsoluteLayout, asking him SizeProportional. Thus, all the pages will have the same size.

For a better understanding, learn Xamarin Forms documentation.

https://developer.xamarin.com/api/type/Xamarin.Forms.AbsoluteLayout/

**Comment by msmrajesh** [comment]
Thank you for the hint and suggestions. It would be simpler if this pop up control had the RequestedHeight and RequestedWidth property enabled so that it would fix this once for all. I observed that the popup control would resize itself according to the rows of controls in it.

Will use this hint to use in my assignment.
