### ISSUE TITLE
Start with popup open

### ISSUE THREAD

**Issue by JoshuaNovak919** [rotorgames/Rg.Plugins.Popup#223]
Is there a way to navigate to the page with the popup open or start the app with the popup open?

**Comment by rotorgames** [comment]
@JoshuaNovak919 A popup page will be always on top. You can navigate your pages behind popup page but you can't open xamarin forms page before PopupPage.

**Comment by JoshuaNovak919** [comment]
I'm trying to use it as a splash page, so i'd want it to be open right as the page is shown, and then i'll close it when the page is ready. Does that sound possible at all?

**Comment by rotorgames** [comment]
@JoshuaNovak919  yes you can do it. Just open popup page and close when your page will be loaded.

**Comment by JoshuaNovak919** [comment]
@rotorgames I tried opening the popup in `OnAppearing` for the main page of the app. You see the page behind it briefly before it opens. Is there a way to fix this?

**Comment by rotorgames** [comment]
@JoshuaNovak919 You can open a blank page and open a popup page there. When the popup page is closed you can change MainPage how you want.
