### ISSUE TITLE
.Net Standard Port

### ISSUE THREAD

**Issue by mshenoy83** [rotorgames/Rg.Plugins.Popup#224]
WIll there be a .net standard version for this plugin?

**Comment by dansiegel** [comment]
the latest preview already supports netstandard

**Comment by rraallvv** [comment]
@dansiegel I'm not sure about which one to pick, is it 1.1.3.73? Thanks.

![Imgur](https://i.imgur.com/5bnfMS4.png)

**Comment by dansiegel** [comment]
@rraallvv it was introduced in 1.1.1-pre... so all of the 1.1.1+ packages have netstandard support

**Comment by rraallvv** [comment]
@dansiegel thank you so much!
