### ISSUE TITLE
Is it possible to keep the Popup on top even the keyboard vanish?

### ISSUE THREAD

**Issue by kartalbas** [rotorgames/Rg.Plugins.Popup#225]
Is it possible to keep the Popup on top even the keyboard vanish?

Current behaviour:
 1) popup opens
 2) entry in xamarin forms is focused
 3) **popup moves up** so the keyboard will get its space
 4) focus changes to another entry
 5)  **popup moves down** (keyboard vanished) and when the next entry get its focus **popup moves up**

problem is that the popup is always moving up and down whenever the keyboard appears/disappears

On Android it was possible with fixing dialog Y attribut to a fixed number

`var attributs = Dialog.Window.Attributes;
attributs.Gravity = GravityFlags.Top | GravityFlags.CenterHorizontal;
attributs.Y = 50;
Dialog.Window.SetWindowAnimations(Resource.Style.DialogAnimation);`

thanks a lot for any help 👍

**Comment by kartalbas** [comment]
Okay, I found the solution in [#155](https://github.com/rotorgames/Rg.Plugins.Popup/issues/155)

Setting HasSystemPadding="False" solved it 👍

**Comment by rotorgames** [comment]
@kartalbas 👍
