### ISSUE TITLE
Question : 

### ISSUE THREAD

**Issue by mhdtahawi** [rotorgames/Rg.Plugins.Popup#227]
Can we control the position of the overlay ? 

I would like to use this to create a popup menu when clicking on a button, and so I want the popup overlay to be positioned right under the button. 

I can figure out the X and Y, but not sure how to pass those to the pop up, if possible in the first place ?

**Comment by Umar3x** [comment]
I think you can set the animation such a way it comes from where you want.
Something like animationType should do the trick. You should check the sample, might do something close to your question playing with LayoutOptions of layout inside your popup  : 

https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Demo/Demo/Pages/LoginSuccessPopupPage.xaml

**Comment by rotorgames** [comment]
@mhdtahawi You can create your custom animation for it. See User Animation example.
