### ISSUE TITLE
Page is always transparent 

### ISSUE THREAD

**Issue by Goldstrike** [rotorgames/Rg.Plugins.Popup#229]
Hello,

I encounter a "strange" case in the projet I work on: after having been displayed, the PopupPage is always transparent, even if its content is well visible.

I've done a test by replacing my page with duplicated page of your samples, but the result is always the same and the page stays transparent.

I have remarked that during the animations the  PopupPage is displayed without transparency. So I've commented the related lines in the code-behind:
```
protected override Task OnAppearingAnimationEnd()
{
    return Content.FadeTo(0.5);
}

protected override Task OnDisappearingAnimationBegin()
{
    return Content.FadeTo(1);
}
```
And this time the page is displayed without transparency.

But is this normal?

I use the last version of the plugin (v.1.1.3.117-beta), and I meet the same result on Android and UWP.

**Comment by rotorgames** [comment]
@Goldstrike Hi. Can you give me a screenshot of the transparent popup?

**Comment by Goldstrike** [comment]
Here are there 2 screenshots of the same page:
- [with](https://ibb.co/eXty66) OnAppearingAnimationEnd()/OnDisappearingAnimationBegin()
- [without](https://ibb.co/i44SzR) OnAppearingAnimationEnd()/OnDisappearingAnimationBegin()

**Comment by rotorgames** [comment]
@Goldstrike Can you create a simple blank project with this problem and give me?

**Comment by Goldstrike** [comment]
I tried to create a sample that get the same architecture, but it doesn't seem to be possible. In my project, we use a PCL class. But actually, we can only choose between Shared Project or .Net Standard for new projets.

**Comment by rotorgames** [comment]
@Goldstrike Create .NET Standard. It is like PCL

**Comment by rotorgames** [comment]
@Goldstrike Do you have this problem with the last pre release `v1.1.4.135-beta`?

**Comment by Goldstrike** [comment]
@rotorgames yes I encounter the problem with the version `1.1.4.135-beta`.

I tried to add the same NuGet package in the "Demo" project of your sample, after this, I get errors on the `OnAppearingAnimationEnd()` and `OnAppearingAnimationBegin()` methods:

> return type must be 'void' to match overridden member 'PopupPage.OnAppearingAnimationEnd()'	Demo	

So I've replaced "Task" by "void" and removed the `return`and the samples work well. However I've noticed that the round close button is no longer displayed on the `FirstPopupPage` after this.

The other remark is that in my project, I don't have the same problem on the `OnAppearingAnimationEnd()` and `OnAppearingAnimationBegin()` methods: I can always use them as Task without any error.

Have you published different versions of the `1.1.4.135-beta` pacakge?

**Comment by Goldstrike** [comment]
@rotorgames
My apologies: all projects weren't up to date!
After having updated to the latest version `1.1.4.135-beta` and having applied the same changes than on your sample, all works fine!

**Comment by rotorgames** [comment]
@Goldstrike Can I close this issue?

**Comment by Goldstrike** [comment]
@rotorgames 
In fact, the problem is still present, I don't understand what happens...
I've tried to update each project of my solution to the same Xamarin.Forms version than in your sample (`2.5.0.121934`), but the page is always transparent...
So I've removed the methods again.
Is there something else that could explain my problem?

**Comment by rotorgames** [comment]
@Goldstrike I will be able to help you if you create a simple blank project witch will have this problem, upload in github and give me a link of the repository.

**Comment by rotorgames** [comment]
I couldn't get enough information to figure out what was wrong. It works fine for me in several production application. If someone has the same issue try to update the plugin to the last version at first.
