### ISSUE TITLE
CloseWhenBackgroundIsClicked not working on Android

### ISSUE THREAD

**Issue by IeuanWalker** [rotorgames/Rg.Plugins.Popup#230]
I have set the CloseWhenBackgroundIsClicked to true and iOS the popup is closed but on Android, nothing happens.

Plugin Version: v1.0.4
Minimum android target: 4.1 (API Level 16 - Jelly Bean)
Running on actual device: android version 7.1.1

**Comment by rotorgames** [comment]
@IeuanWalker What version of the plugin do you use?

**Comment by IeuanWalker** [comment]
@rotorgames the latest one - v1.0.4

**Comment by rotorgames** [comment]
@IeuanWalker Try to use the last pre version v1.1.3.129-beta

**Comment by IeuanWalker** [comment]
@rotorgames i installed the pre version v1.1.3.129-beta but i get the following error 
![image](https://user-images.githubusercontent.com/6544051/35687745-6f1fee66-0767-11e8-9990-c23c5fb6233a.png)
The app launches fine its the minute i navigate to a page (not a popup)

**Comment by IeuanWalker** [comment]
@rotorgames I have even tried using the BackgroundClicked event and using PopupNavigation.PopAllAsync but the event never gets hit

**Comment by rotorgames** [comment]
@IeuanWalker See [Initialization](https://github.com/rotorgames/Rg.Plugins.Popup#initialization) and [Troubleshooting](https://github.com/rotorgames/Rg.Plugins.Popup#troubleshooting) for the v1.1.4.129-beta

**Comment by IeuanWalker** [comment]
@rotorgames hi, i added the initialize cleaned the project and it worked.
But now the animation for the popup isnt working.

**Comment by rotorgames** [comment]
@IeuanWalker What is not working exactly? Popup doesn't appear? Or Popup appear but an animation doesn't play?

**Comment by IeuanWalker** [comment]
@rotorgames popup appears but the animation doesnt play.
This is the aniamtion that should run
![image](https://user-images.githubusercontent.com/6544051/35690595-269ce1a6-076e-11e8-91e9-0584e57b513e.png)

**Comment by rotorgames** [comment]
@IeuanWalker Do you use push, pop, removePage in the main thread? Do you use `await` operator?

**Comment by IeuanWalker** [comment]
@rotorgames Im opening the popup from the ViewModel using a Command
![image](https://user-images.githubusercontent.com/6544051/35690811-bcf5f02a-076e-11e8-99b0-3fe25c2f1781.png)

**Comment by rotorgames** [comment]
@IeuanWalker Where is this problem? Android, iOS, UWP?

**Comment by IeuanWalker** [comment]
@rotorgames  Currently Android, cannot test iOS until tomorrow. But iOS was working completly fine on the none beta NuGet package

**Comment by rotorgames** [comment]
@IeuanWalker Is Android system animation enabled?

**Comment by IeuanWalker** [comment]
@rotorgames The animations used to work on the v1.0.4
How to i check if Android system animation is enabled?

**Comment by rotorgames** [comment]
@IeuanWalker Just see my previous comment. I have added the screenshot.

**Comment by rotorgames** [comment]
@IeuanWalker You should set animation scale 0.5x or bigger only then animation works.

**Comment by IeuanWalker** [comment]
@rotorgames ye its the same as yours animation scale 1x

**Comment by rotorgames** [comment]
@IeuanWalker Please, try to test my demo project from this repository. If you have this problem again, create a simple blank project which has this problem and give me.

Thanks

**Comment by IeuanWalker** [comment]
@rotorgames Ok thanks for all your help, ill let you know whats happening tomorrow.

**Comment by IeuanWalker** [comment]
@rotorgames Hi, I uninstalled the NuGet and re-installed it (v1.1.4.129-beta), and everything seems to be working fine now. Not sure what was going on yesterday but it was strange.

**Comment by rotorgames** [comment]
@IeuanWalker Nice to hear it. Good luck
