### ISSUE TITLE
No animations on Android (>= 1.1.3.73-pre)

### ISSUE THREAD

**Issue by luccasclezar** [rotorgames/Rg.Plugins.Popup#231]
I'm on Android 7.1 and all versions >= 1.1.3.73-pre are not showing any animations of Appearing/Disappearing.

**Comment by rotorgames** [comment]
@luccasclezar What the last version of plugin works?

**Comment by luccasclezar** [comment]
1.1.1-pre

**Comment by rotorgames** [comment]
@luccasclezar You can show popup but doesn't an animation play? Do you just see a popup without animation?

**Comment by luccasclezar** [comment]
Yes, the popups are showing, but they simply don't animate when appearing/disappearing.

**Comment by rotorgames** [comment]
@luccasclezar I'm getting some problems like this for other people. Can you make a video where is this problem and give me?

**Comment by luccasclezar** [comment]
Sorry, but I can't see a way that a video would add anything to the issue. It's very simple: every time I open a Popup, it shows without animation. Every time I close a popup, it disappears without animation.

If you really think a video would help though, I can make it.

**Comment by rotorgames** [comment]
@luccasclezar Maybe you can create a simple blank project witch will have this problem and give me? Just I can't reproduce it

**Comment by luccasclezar** [comment]
Ok, I'll do it. But I think it's worth mentioning that the same app on UWP is working fine, the issue is only happening on Android (and I only tested on 7.1).

**Comment by luccasclezar** [comment]
I made the project. Tested on a Motorola Z2 Play with Android 7.1.


[PopupAnimationTest.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/1687334/PopupAnimationTest.zip)

**Comment by rotorgames** [comment]
@luccasclezar I have downloaded your project and built. I don't see any problems, animations work.

![2018-02-02 8 11 12 2](https://user-images.githubusercontent.com/1790504/35716258-223e7c22-07f1-11e8-81cc-cad8d2596bcb.gif)

**Comment by luccasclezar** [comment]
Probably this issue only happens on physical devices. I'll investigate and if I discover anything new I'll update you.

**Comment by rotorgames** [comment]
@luccasclezar Thank you. I will wait news from you

**Comment by luccasclezar** [comment]
Found it! Line 142 of PopupPlatformDroid (GetIsSystemAnimationEnabled) is returning 0 for AnimatorDurationScale. 

https://github.com/rotorgames/Rg.Plugins.Popup/blob/793a6c8eb9a61487f3c634a80c207772d47edf87/src/Rg.Plugins.Popup.Droid/Impl/PopupPlatformDroid.cs#L142

I tried to modify the default value from 0 to 1 (line 145 and 152) and its working. I think the default value should be 1 right? It's the most common value for AnimatorDurationScale.

**Comment by IeuanWalker** [comment]
@luccasclezar @rotorgames try v1.1.4.129-beta.
I was having this issue yesterday but seems fine after uninstalling and reinstalling the NuGet package.
#230

**Comment by luccasclezar** [comment]
Hey @IeuanWalker! 

Thanks for the suggestion, but it's not the same problem as the one you linked and I have already tried to reinstall.

**Comment by rotorgames** [comment]
@luccasclezar A value of `animationScale` must be more than 0 that an animation works. If Settings.Global.AnimatorDurationScale is 0 that the system animation is disabled. You should turn on the system animation.

**Comment by luccasclezar** [comment]
Yeah, I know that :)

This is exactly why I'm saying that I think the default value should be 1. This value should reflect the default of all devices, that is, if you don't manually change the animationScale, it's 1, not 0.

**Comment by rotorgames** [comment]
@luccasclezar What is default value in your device? You can see that if value is more than 0 then animation works. I think that your device returns <=0

**Comment by luccasclezar** [comment]
Yeah, my device is returning 0, I actually said this when I said that I found the issue. But I didn't change the animationScale setting, it's 1.

What I'm trying to say, is that the last "0" in the `GetFloat` method is the default value that will get returned is the setting (animationScale) is not found. Changing this from "0" to "1", fixes the issue. Because the default value already should be "1", not "0".

**Comment by rotorgames** [comment]
@luccasclezar Yeah, you are right. I'm forgot to change default value for AnimatorDurationScale. Thank you for your vigilance and your help. I'm changing it now. Give me a minute.

**Comment by rotorgames** [comment]
@luccasclezar You can try to test v1.1.4.132-beta from Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

**Comment by luccasclezar** [comment]
@rotorgames no problem! Thank you for quickly fixing the issue. :)
