### ISSUE TITLE
Using font size doesn't re-size the popup window

### ISSUE THREAD

**Issue by IeuanWalker** [rotorgames/Rg.Plugins.Popup#235]
Plugin: v1..4.135-beta

When using the font size attribute on a label inside a popup, the popup size doesn't change resulting in element overlapping the popup

![screenshot_20180205-103823](https://user-images.githubusercontent.com/6544051/35801174-3f69ce54-0a63-11e8-88b3-e0c2c494359a.jpg) ![screenshot_20180205-104020](https://user-images.githubusercontent.com/6544051/35801175-3f9315ac-0a63-11e8-9060-f694286bddfd.jpg)

**Comment by rotorgames** [comment]
@IeuanWalker Hi. Give me your xaml and c# code of this popup for an example

**Comment by IeuanWalker** [comment]
Here are the files, just to let you know, I have a normal contentPage that opens the popup on appearing (this was to fix some navigation issues)

[Example.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/1694860/Example.zip)

**Comment by IeuanWalker** [comment]
@rotorgames there's one other thing, I have tried to mimic your login page with the 'X' in the corner but I just can't get it to appear on top of the frame.

**Comment by rotorgames** [comment]
@IeuanWalker 

> When using the font size attribute on a label inside a popup, the popup size doesn't change resulting in element overlapping the popup

It happens because you use AbsoluteLayout. AbsoluteLayout is not resized after a size of content is changed. It is not this plugin bug.

> there's one other thing, I have tried to mimic your login page with the 'X' in the corner but I just can't get it to appear on top of the frame.

I'm too. This is AppCompat behavior and Xamarin.Froms problem.

**Comment by IeuanWalker** [comment]
@rotorgames Ahh ok thanks for working this out for me.
For now, I have removed the AbsoluteLayout and have added a close button at the top of the frame.

**Comment by rotorgames** [comment]
@IeuanWalker Nice to hear it. Good luck.
