### ISSUE TITLE
Plugin doesn't run in UWP

### ISSUE THREAD

**Issue by JuanDahCM** [rotorgames/Rg.Plugins.Popup#238]
When I go to initialize in UWP I just type "Rg.Plugins.Popup" then the plugin doesn't run in UWP
I check the plugain and said The project use NETStandart vs 2.0
but the version's plugins use NETFramerwork version 4.6.1
What can I do?

**Comment by rotorgames** [comment]
@JuanDahCM I didn't understand you. My plugin uses netstandard 1.0 for PCL and min version for UWP 10.0.10240.0.

**Comment by JuanDahCM** [comment]
Thank you, but I solve de issue. the problem was the way I inicializate the plugin and how I call it.

**Comment by rotorgames** [comment]
@JuanDahCM Nice to hear it. Can I close this issue?

**Comment by JuanDahCM** [comment]
yes, of course

**Comment by rotorgames** [comment]
@JuanDahCM Good luck.
