### ISSUE TITLE
PopupNavigation System.NullReferenceException

### ISSUE THREAD

**Issue by Parker3306** [rotorgames/Rg.Plugins.Popup#24]
I've got an issue I've managed to reproduce with small project while trying to navigate to a user animation popup page. It should be pretty simple and I can't get it to work. I don't know if its a bug or if I'm missing something but there seems to always be a problem with SystemPadding. Here is the link to the project: https://github.com/Parker3306/PopupTest

Thanks for the help.

Edit: this is on Android only so far, by the way. Xamarin.Forms 2.2.0.31 Tested on Google Nexus 6 5.0.0 API 21

**Comment by rotorgames** [comment]
@Parker3306  Confirmed. Please, wait, coming be 1.0 version, where fix this problem.

**Comment by rotorgames** [comment]
@Parker3306 Hi friend. You not install Rg.Plugin.Popup in Droid project!
