### ISSUE TITLE
hi i have a question.

### ISSUE THREAD

**Issue by meerkat86** [rotorgames/Rg.Plugins.Popup#242]
Hi i'm new to Xamarin development and ... i'm sorry for my English is not good. 
My problem is: 
I installed Plugin ver.1.04, but there's no "OnDisappearingAnimationBeginAsync()", "OnAppearingAnimationBegin()" and etc.. functions to override. 
I re-installed plugin several times, but there's no suitable method found to override. 

please help me T.T

**Comment by rotorgames** [comment]
@meerkat86 Hi. Current documentation is for v1.1.x. Please, install the last pre release and see https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Migration-from-v1.0.x-to-v1.1.x

**Comment by meerkat86** [comment]
thanks, it works!!
