### ISSUE TITLE
The type or namespace Popup does not exist in the namespace Rg.Plugins.Popup

### ISSUE THREAD

**Issue by sebastianortizvelez** [rotorgames/Rg.Plugins.Popup#243]
I followed all the steps, installing the plugin in PCL and each native projects, but when I want to initialize the plugin on iOS with:

`Rg.Plugins.Popup.Popup.Init();
`

The Visual Studio shows me that error.

I also do a clean / rebuild and delete obj/bin folders

**Comment by rotorgames** [comment]
@sebastianortizvelez Hi. Please, update this library to the last pre release. This documentation is about the last pre release. 

P.S. I will publish a new stable release soon.
