### ISSUE TITLE
[Android] Crash when starting another activity by shortcut with a Popup opened

### ISSUE THREAD

**Issue by luccasclezar** [rotorgames/Rg.Plugins.Popup#244]
Sorry for the big title, I couldn't think of anything smaller.

About the bug, I attached a project to demonstrate it. Steps to reproduce:

1. Open the app
2. Click on the Popup button
3. Go to Home Screen
4. Click on the shortcut "Second Page"

[PopupShortcutBug.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/1724405/PopupShortcutBug.zip)

I already tried to debug the library and I found out that the problem is coming from this line: 
https://github.com/rotorgames/Rg.Plugins.Popup/blob/833a71af47a2a8fde89f496e2937e183ad4ed203/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs#L52

When I unchecked "Just My Code" debugging, I found out that the exception was being thrown when Xamarin.Forms tried to remove all views from the previously displayed Popup.

Then I tried to remove the call to the `Dispose` method on this line (because this is where the Popup's `Dispose` method is being called):

https://github.com/rotorgames/Rg.Plugins.Popup/blob/833a71af47a2a8fde89f496e2937e183ad4ed203/src/Rg.Plugins.Popup.Droid/Impl/PopupPlatformDroid.cs#L57

and an exception was thrown in `GetPlatform` helper method with this Stack Trace:

```
PlatformHelper.GetPlatform () C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup.Droid\Helpers\PlatformHelper.cs:43
PlatformHelper.GetHandleBackPressed[TDelegate] () C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup.Droid\Helpers\PlatformHelper.cs:13
PopupPlatformDroid.UpdateListeners (System.Boolean isAdd) C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup.Droid\Impl\PopupPlatformDroid.cs:95
PopupPlatformDroid+<RemoveAsync>d__12.MoveNext () C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup.Droid\Impl\PopupPlatformDroid.cs:66
```

After that, I couldn't manage to find anything useful.

**Comment by rotorgames** [comment]
@luccasclezar Hi. Please, update this plugin to the last pre release and see [getting started](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started)

**Comment by luccasclezar** [comment]
Sorry, but I don't think you read my issue correctly. The Popups are working fine, all initializations are set, that's not the problem.

The problem only happens when you start a minimized app that already has a Popup opened, from a shortcut to another page.

Did you download the project and followed the repro steps?

**Comment by rotorgames** [comment]
@luccasclezar I'm sorry but I have closed it issues correctly. I can see that there is PlatformHelper.GetPlatform in the stack trace but I have removed it in v1.1.4.145-pre. Please, update this plugin to v1.1.4.145-pre.

Thanks.

**Comment by luccasclezar** [comment]
Actually, I had the latest version installed, but VS cached the previous version. I had to delete bin and obj folders and re-deploy, now it's working.

Sorry for the trouble! :)
