### ISSUE TITLE
[Question] Setting position and size of popup

### ISSUE THREAD

**Issue by uzername** [rotorgames/Rg.Plugins.Popup#245]
I need to design a popup that appears below/above the certain button on screen (not in center). Is it possible to set size and position of popup?

**Comment by uzername** [comment]
I mean, I need to implement this functionality: https://developer.xamarin.com/guides/android/user_interface/controls/popup-menu/
but in a crossplatform manner with this plugin.

**Comment by rotorgames** [comment]
@uzername Yes you can. You can set `VerticalOptions` for a main view to `Start` and set `Margin` or `TransitionY` for changing a popup's position. Also you can set `InputTransparent` to `True` for `PopupPage` that touches will be passed to views which will be behind a popup page.

**Comment by uzername** [comment]
Great, it worked. Here is a bunch of code:

```
// SynchronizeMenu synchroPage is an instance of popup page I want to display as menu
            synchroPage.BackgroundColor = Xamarin.Forms.Color.Transparent; //and set color of buttons container in xaml
            await Navigation.PushPopupAsync(synchroPage);
           synchroPage.InputTransparent = true;
            double currentMenuHeight = synchroPage.getContentBoxHeight();
            double currentButtonHeight = ((Xamarin.Forms.Button)sender).Height;
            //get pair of numbers: https://stackoverflow.com/a/36436255/
            // https://forums.xamarin.com/discussion/24042/how-can-i-get-absolute-position-of-element-view-in-xamarin-forms
            (double firstX, double secondY) = StaticDefinitions.GetScreenCoordinates((Xamarin.Forms.Button)sender);
            synchroPage.TranslationX = firstX;
            synchroPage.TranslationY = secondY - currentMenuHeight;
```

**Comment by agharium** [comment]
[This answer on Stackoverflow](https://stackoverflow.com/a/51422564/8072300) really helped me getting the exact coordinates of where I should set my popup.
