### ISSUE TITLE
[Request] Better Android error messaging on improper initialization

### ISSUE THREAD

**Issue by pingzing** [rotorgames/Rg.Plugins.Popup#246]
Hi! I've been using this library in my Xamarin Forms application, and ran into an issue where things worked fine in UWP, but were failing at runtime on Android with an inexplicable System.InvalidCastException.

Ultimately, the issue ended up being [this line here](https://github.com/rotorgames/Rg.Plugins.Popup/blob/833a71af47a2a8fde89f496e2937e183ad4ed203/src/Rg.Plugins.Popup.Droid/Impl/PopupPlatformDroid.cs#L24), where the `Context` gets cast into an `Activity`. The issue was that I had incorrectly initialized the plugin like so:

```C#
//MainActivity.cs
Popup.Init(this.Context, bundle);
```

While this was entirely my fault, it would have made debugging the issue much easier had it: a.) failed earlier or b.) given me more information about why it was failing. 

Would it make sense to do some sanity-checking on initialization, to make sure that the passed `Context` object is actually an `Activity`, for example?

**Comment by rotorgames** [comment]
@pingzing Hi. Can you give me a full stack trace?

**Comment by rotorgames** [comment]
I prepared [the good documentation](https://github.com/rotorgames/Rg.Plugins.Popup/wiki) to avoid similar issues. I suppose it is not necessary to check if it is Activity or not because it will be able to be not only Activity in the future. 

Thank you for your opinion.
