### ISSUE TITLE
Question: is it possible to add the PopupPage in the "global" NavigationStack?

### ISSUE THREAD

**Issue by Goldstrike** [rotorgames/Rg.Plugins.Popup#247]
Hello,

I would like to know if there is a way to manage a `PopupPage` as a  ContentPage, regarding to the `NavigationStack`.

I work on app that has used until now `ContentPage` and `NavigationPage`, to manage the **user's buy choice**:
- from a **ListProducts** page, that is the root of the NavigationPage, the user selects a product
- he navigates to a **DetailsProduct** page, where he can select options and validate his choice
- then he navigates on **AdditionalProducts** pages, where he can selects optional products related to the main product
- when he has finished, he returns to the main **ListProducts** page, or he is redirected to the **Cart** page

The app works on smartphones and tablet, but with some differences, so there are 3 projets in the solution:
- a common project, for the common view, viewmodels, ...
- a mobile project, for the mobile specific views
- a tablet project, for the tablet specific views

On the tablet only, the client would like to show the **DetailsProduct** page through a `PopupPage`. I've tried to done this through through **RgPopup** and this works well.

However I've a problem, as I have to write a lot of specific code, as the **DetailsProduct** page is no longer into the `NavigationStack` for the tablet...

**_I would like to know if there is another way to manage it, to add the PopupPage in the NavigationStack. For example, this could allow users to coming back to the Detail page from the AdditionalProducts page. Of course, the PopupPage will no display the NavigationBar._**

I don't know if my explanations are very clear, don't hesitate to ask me more details if necessary...

**Comment by rotorgames** [comment]
@Goldstrike No. You can't add a PopupPage to the NavigationStack. You should implement a custom navigation for it.

**Comment by Goldstrike** [comment]
@rotorgames  thanks for your feedback.
So we have to manage "handly" the case where users are returning to the **DetailsProduct** `PopupPage`.

**Comment by rotorgames** [comment]
I have read this issues today again and I can give more information aboit it now. 

You can use `PopupPage` for `NavigationStack` or `ModalStack` of Xamarin.Forms using `PushAsync` and `PushModalAsync`. I guess it must be fine but I didn't test it and you can do it at your own risk.
