### ISSUE TITLE
Please, upgrade version of your plugin in main Nuget

### ISSUE THREAD

**Issue by uzername** [rotorgames/Rg.Plugins.Popup#248]
Hello. I am using a package manager Nuget in Visual Studio to obtain the plugin (from main access point https://www.nuget.org/packages/Rg.Plugins.Popup/ ). The latest version there is 1.0.4 which is dated by November 2016. Seems like that the author has done enough work to publish the new upgrade of this plugin.

Thanks for your work.

**Comment by cunnpole** [comment]
Seconded! Very handy plugin, would be nice if I didn't have to build from source as I seem to have to do with most projects these days.

**Comment by danilkurkin1** [comment]
Want to join comments above - latest stable version release required

**Comment by sangeetanaik** [comment]
This is a very useful plugin. Updating it would be really helpful. Thank you.

**Comment by rotorgames** [comment]
Hi guys. I'm working on the new stable release and it should be soon.
