### ISSUE TITLE
IsCloseOnBackgroundClick and BackgroundClicked doesn't work.

### ISSUE THREAD

**Issue by Clowning** [rotorgames/Rg.Plugins.Popup#25]
Hello, 

i'm trying to implement Popup plugin into my Xamarin application but i have some trouble ! BackgroundClicked and IsCloseOnBackgroundClick doesn't work... And i don't why, can you help me ? 

My code : 

`	public class JobRemote : PopupPage
	{

		public JobRemote(QRCode qr)
		{

			this.BackgroundClicked += () => {

				System.Diagnostics.Debug.WriteLine("AIE");
			};

			IsCloseOnBackgroundClick = true;

			var lol = new RelativeLayout();

			lol.Children.Add(new BoxView { BackgroundColor = Color.White }, Constraint.RelativeToParent((parent) =>
			{
				return parent.X;
			}), Constraint.RelativeToParent((parent) =>
			{
				return parent.Y * .15;
			}), Constraint.RelativeToParent((parent) =>
			{
				return parent.Width;
			}), Constraint.RelativeToParent((parent) =>
			{
				return parent.Height * .8;
			}));

			Content = lol;

		}

		protected override void OnAppearing()
		{
			base.OnAppearing();
		}

		protected override void OnDisappearing()
		{
			base.OnDisappearing();
		}

		protected override bool OnBackButtonPressed()
		{
			return true;
		}
	}`

**Comment by rotorgames** [comment]
@Clowning Hi friend. Please write you versions:

Rg.Plugins.Popup
Xamarin.Forms 
Xamarin.VS or Xamarin Studio verions
Android or ios version

**Comment by Clowning** [comment]
Hey, 

**Rg.Plugins.Popup :** 0.0.17
**Xamarin.Forms :** 2.3.0.49 (I have a note to upgrade to 2.3.0.107)
**Xamarin Studio version :** 6.0 (Build : 5166)
**Android Version :** XamarinAndroid10 (Ref to *)
**iOS version :**XamariniOS 10 (Ref to *)

*But i'm not sure if its the good version ! I don't found any other information ! and if you means version on emulator / iphone :

iOS Version : 9.2
Android Version : 6


Thanks

**Comment by rotorgames** [comment]
@Clowning This bug only on android or ios also?

**Comment by Clowning** [comment]
No only on IOS !

**Comment by rotorgames** [comment]
@Clowning RelativeLayout intercepts all touches, as RelativeLayout fill on all page.

**Comment by Clowning** [comment]
Arf... Do you have an other solution ? Because my relativelayout is in gridlayout!

**Comment by rotorgames** [comment]
@Clowning 

```csharp

public class JobRemote : PopupPage
	{

		public JobRemote(QRCode qr)
		{

			IsCloseOnBackgroundClick = false;

            var lol = new RelativeLayout();

            var gesture = new TapGestureRecognizer();

            gesture.Command = new Command(() =>
            {
                // Executed when background clicked
            });

            var clickableView = new BoxView();

            clickableView.GestureRecognizers.Add(gesture);

            lol.Children.Add(clickableView, Constraint.RelativeToParent((parent) =>
            {
                return parent.X;
            }), Constraint.RelativeToParent((parent) =>
            {
                return parent.Y;
            }), Constraint.RelativeToParent((parent) =>
            {
                return parent.Width;
            }), Constraint.RelativeToParent((parent) =>
            {
                return parent.Height;
            }));

            lol.Children.Add(new BoxView
            {
                BackgroundColor = Color.White
            }, Constraint.RelativeToParent((parent) =>
            {
                return parent.X;
            }), Constraint.RelativeToParent((parent) =>
            {
                return parent.Y * .15;
            }), Constraint.RelativeToParent((parent) =>
            {
                return parent.Width;
            }), Constraint.RelativeToParent((parent) =>
            {
                return parent.Height * .8;
            }));

            Content = lol;
		}


		protected override void OnAppearing()
		{
			base.OnAppearing();
		}

		protected override void OnDisappearing()
		{
			base.OnDisappearing();
		}

		protected override bool OnBackButtonPressed()
		{
			return true;
		}
	}

```

**Comment by Clowning** [comment]
Perfect ! Thank you :-) ! 👍
