### ISSUE TITLE
CloseWhenBackgroundIsClicked true or false

### ISSUE THREAD

**Issue by clovs** [rotorgames/Rg.Plugins.Popup#254]
Hello,
Seems that even if I put CloseWhenBackgroundIsClicked to true or false.
IOS close the PopPup, and Android don't.

What have I to do to make it works?

Version Rg.plugin.PopUp --> 1.0.4

**Comment by zany1** [comment]
Upgrade to the latest pre-version 1.1.4.145-pre it fixes a lot of problems
