### ISSUE TITLE
Please support .net standard official

### ISSUE THREAD

**Issue by JaeWLee** [rotorgames/Rg.Plugins.Popup#257]
I'm using your project very well
Thanks guys but... I want to support .net standard 2.0 for official
beta version is now supported but official please too

**Comment by rotorgames** [comment]
@JaeWLee I have returned to work recently and I will create new stable release soon. Please wait.

**Comment by dansiegel** [comment]
Would love to see the Tizen and macOS PRs merged for that stable release. @rotorgames if there is something the community can do to support you in getting out a stable release please let us know.

**Comment by rotorgames** [comment]
@dansiegel @krunalc Sorry I was so busy. I think that I will publish the stable release without macOS and Tizen. I will work on macOS and Tizen only after stable release

**Comment by dansiegel** [comment]
@rotorgames any update on this? would really love to see a new stable release

**Comment by jhonatanfernando** [comment]
I am also waiting for this new version.

**Comment by JamesDejaegere** [comment]
@rotorgames any progress on this?

**Comment by Boltarok** [comment]
@rotorgames any news? I am also waiting for this new version.

**Comment by eman1986** [comment]
I'm using it on NetStandard 2 just fine

**Comment by rotorgames** [comment]
Done
