### ISSUE TITLE
Use Prism Navigation method to pass variables

### ISSUE THREAD

**Issue by kalkotekedar** [rotorgames/Rg.Plugins.Popup#258]
Can we Use Navigation methods for passing the variables

**Comment by rotorgames** [comment]
@kalkotekedar You can find some libraries in nuget that allow you to use the prism navigation for this plugin.

**Comment by dansiegel** [comment]
@kalkotekedar See [Prism.Plugin.Popups](https://www.nuget.org/packages/Prism.Plugin.Popups/) note that 2.0.0-pre6 is targeting the latest 7.0 release of Prism while 2.0.0.528-pre is targeting the 7.1 preview both target the latest pre release of Rg.Plugins.Popup
