### ISSUE TITLE
OnAppearingAnimationBegin not found

### ISSUE THREAD

**Issue by geedsen** [rotorgames/Rg.Plugins.Popup#259]
protected override void OnAppearingAnimationBegin()
        {
            base.OnAppearingAnimationBegin();

            FrameContainer.HeightRequest = -1;
        }

This code works fine in Android. In an iOS app I get the runtime error:

/Users/Ben/Projects/QTNC/FCM/FCM.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Rg.Plugins.Popup.Pages.PopupPage::OnAppearingAnimationBegin()', referenced from the method 'System.Void FCM.NETStandard.Views.ProductListPage::OnAppearingAnimationBegin()' in 'Rg.Plugins.Popup, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (FCM.iOS)

**Comment by geedsen** [comment]
OK, Haven't completely figured it out. But I used the source code for Rg  in Android and the 1.0.4 nugget package for iOS. And the package does indeed not have these OnAppearing.... Is that correct?

**Comment by geedsen** [comment]
I resolved the problems by installing the latest preview packages.

**Comment by EeKay** [comment]
Can conform @geedsen's answer: version 1.1.4.145-pre did the trick.

The official 1.0.4 release told me iOS didn't need the init() and the compiler couldn't find all the event functions as indicated in this thread.

**Comment by rotorgames** [comment]
Use the newest version of the plugin to use all features in the documentation.
