### ISSUE TITLE
[Android]OutOfMemory when open/close popup  multi times

### ISSUE THREAD

**Issue by yz1311** [rotorgames/Rg.Plugins.Popup#26]
The times depend on the device's memory

**Comment by rotorgames** [comment]
@yz1311 Hi friend. Please, write version:

Rg.Plugins.Popup
Xamarin.Forms
Xamarin.VS (or Xamarin Studio)
Android SDK

and stack trace error

**Comment by yz1311** [comment]
Rg.Plugins.Popup  1.0.0-pre1
Xamarin.Forms      2.3.0.107/2.2.0.31
-----------------------------------------------------------
Xamarin Studio Community
Version 6.0.1 (build 9)
Installation UUID: cb0cc74d-00a8-4456-bfd9-dbdcc267d5b2
Runtime:
	Microsoft .NET 4.0.30319.42000
	GTK+ 2.24.26 (Light theme)
	GTK# 2.12.38

Xamarin.Profiler
Not Installed

Xamarin.Android
Version: 6.1.1.0 (Xamarin Studio Community)
Android SDK: D:\android-sdk-windows
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.2   (API level 17)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)

SDK Tools Version: 24.3.4
SDK Platform Tools Version: 23.1
SDK Build Tools Version: 24.0.0

Java SDK: C:\Program Files\Java\jdk1.8.0_91

------------------------------------------------------------------
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.OutOfMemoryError: Failed to allocate a 5552076 byte allocation with 5516812 free bytes and 5MB until OOM
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[MonoDroid]   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/3415/ffca580c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x0001b] in /Users/builder/data/lanes/3415/ffca580c/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 
[MonoDroid]   at Android.Graphics.Bitmap.CreateBitmap (Int32 width, Int32 height, Android.Graphics.Config config) [0x00054] in /Users/builder/data/lanes/3415/ffca580c/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.Bitmap.cs:670 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FrameRenderer+FrameDrawable.CreateBitmap (Boolean pressed, Int32 width, Int32 height) [0x00006] in C:\BuildAgent\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\Renderers\FrameRenderer.cs:126 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FrameRenderer+FrameDrawable.Draw (Android.Graphics.Canvas canvas) [0x00079] in C:\BuildAgent\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\Renderers\FrameRenderer.cs:86 
[MonoDroid]   at Android.Graphics.Drawables.Drawable.n_Draw_Landroid_graphics_Canvas_ (IntPtr jnienv, IntPtr native__this, IntPtr native_canvas) [0x00011] in /Users/builder/data/lanes/3415/ffca580c/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.Drawables.Drawable.cs:1301 
[MonoDroid]   at (wrapper dynamic-method) System.Object:446c5f4d-fcb5-4d8a-89af-4039189a089f (intptr,intptr,intptr)
[MonoDroid]   --- End of managed exception stack trace ---
------------------------------------------------------------------------

**Comment by yz1311** [comment]
According to the  stack trace ,it seems that the Frame causes the problem.yes,i use a Frame as the popup container.
I also tries your demo,the situation occurred but the growth speed of the memory consumption is much slower(0.2M per time,i have a more complex view )

**Comment by rotorgames** [comment]
@yz1311 You use `Xamarin.Forms.Image` in PopupPage?

**Comment by yz1311** [comment]
`<ControlTemplate x:Key="DialogWithTitleTemplate">
				<StackLayout Orientation="Vertical" VerticalOptions="Center"   Padding="{StaticResource 9PerDialogPadding}" >
				<Frame BackgroundColor="White" Padding="0">
						<ContentPresenter />
				</Frame>
				</StackLayout>
			</ControlTemplate>`
no image,just listview,lablel,entry....,but the container is a Frame

**Comment by rotorgames** [comment]
@yz1311 Please, show all xaml code

**Comment by yz1311** [comment]
Sorry for late reply.
I have recorded a video: [https://www.youtube.com/watch?v=tjnFRlxQmOU&feature=youtu.be](url)
I just tried the fix,it has the same problem.
I do not know if it's a normal situation.

**Comment by rotorgames** [comment]
@yz1311 Hmm, please, try this test on Xamarin.Forms.ContentPage, and PushAsync.

Android also crash on OutOfMemory?

**Comment by AntoninMartin** [comment]
Hello,

Same issue here. Working with a Xamarin.Forms.Image in the popup page. And crash is on Android app (I've not tried on ios yet).

Does a solution exist for this problem ? 

Thanks !

**Comment by rotorgames** [comment]
@AntoninMartin Hi friend. Charsh only on PopupPage or ContentPage (PushAsync) also?

**Comment by AntoninMartin** [comment]
Hi ! I need to do more tests to confirm but it seems that ContentPage crash too. Have you any idea to fix this problem ?

**Comment by rotorgames** [comment]
@AntoninMartin This is problem xamarin forms.

**Comment by AntoninMartin** [comment]
Yes it looks like. So it could be better to give this information to user on main wiki page, even if this problem doesn't come from your plugin (which is great ;) ) .

**Comment by mofadevs** [comment]
I had the same issue when I started using it. After a few times of showing and hiding a very simple popup, the app was crashing with OOM exception on android. I fixed it by keeping the popup object alive during the lifetime of the parent view. Do not re-initialize the popup every time. Just initialize it first time, and then keep on showing or hiding it.
After trying the above, I tested more than 100 times to show and hide a popup and no crash.

**Comment by rotorgames** [comment]
@mofadevs Hi. You have memory error now?
Which version of the plugin you use?

**Comment by yz1311** [comment]
@mofadevs  
Could you post your code?
I have keeped the popup object alive ,but background shadow is invisible  when the popup is pushed at the second time
`private BasePopupPage _accountlistPage;

		private Command _userSwitchCommand;
		public Command UserSwitchCommand
		{
			get{
				return _userSwitchCommand??( _userSwitchCommand = new Command(async ()=>{

					if (_accountlistPage == null)
					{
						_accountlistPage = new Accountlist()
						{
							BindingContext = this
						};
					}
					await PopupNavigation.PushAsync(_accountlistPage);`

**Comment by mofadevs** [comment]
@yz1311
Yes, you need to reset the background color before pushing the page:
`sDialog.BackgroundColor = Color.FromHex("#80000000");`
`await PopupNavigation.PushAsync(svDialog);`
So what about the OOM exception now?
@rotorgames 
I do not face OOM exception now and I am using 0.0.15

**Comment by rotorgames** [comment]
@mofadevs 0.0.15 is very old build. It was published six months ago.

You must use v1.0.0-pre5 for best work and performance

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre. Please test it and tell me about your tests. Thank you.
