### ISSUE TITLE
System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by CostaTC** [rotorgames/Rg.Plugins.Popup#261]
Having a random issue where occasionally an exception occurs when calling PushPopupAsync.

Stack trace shows that it happens when retrieving decoreView.
0x0 in Rg.Plugins.Popup.Droid.Impl.PopupNavigationDroid.get__decoreView
0xB in Rg.Plugins.Popup.Droid.Impl.PopupNavigationDroid.RemovePopup

This issue seems to happen at total random as I can only reproduce by spamming PushPopAsync until it topples over.

**Comment by rotorgames** [comment]
@CostaTC What version of this plugin do you use?

**Comment by CostaTC** [comment]
v1.0.4

**Comment by rotorgames** [comment]
@CostaTC in first please update the plugin to the last pre/beta version and check it again.

**Comment by PierreLucB** [comment]
I'm working with the 1.1.5.180 version, I have the problem all the time in Android. It works very well in UWP by the way.

The error appears when I do a PushAsync() : 

            var popup = new LoadingPopup();
            await PopupNavigation.Instance.PushAsync(popup);

**Comment by rotorgames** [comment]
@PierreLucB What error do you get?

**Comment by PierreLucB** [comment]
Sorry I did not remove my comment. I migrated from a old version of the plugin and did not initialize Android project like it was in the documentation.
It works on Android too.
Thank you.
