### ISSUE TITLE
Popup popover style

### ISSUE THREAD

**Issue by Glabenwitt** [rotorgames/Rg.Plugins.Popup#262]
Is it possible to add an option or a different presentation method to show an ios popover like popup (with arrow and pointing to a control or a rectangle).

**Comment by rotorgames** [comment]
@Glabenwitt Sorry but you should set a position of the popup yourself with using `TranslationX` and `TranslationY` or `AbsoluteLayout`

**Comment by Bejasc** [comment]
@rotorgames will there ever be any extension to the plugin to draw the arrow/triangle from a defined position, similar to how an iOS Popover works. If not, are there any suggestions you could offer to achieve the same effect? 

![image](https://user-images.githubusercontent.com/12091874/41019313-3e191b6a-699d-11e8-9bf4-0612e6c219da.png)

**Comment by rotorgames** [comment]
@Bejasc You can implement it yourself. This plugin only allows to show the page as popup.
