### ISSUE TITLE
Android has problem in closing the Pop up when background is clicked using the version 1.0.4 of Rg.Plugins.Popup.

### ISSUE THREAD

**Issue by vidhyaanbalagan** [rotorgames/Rg.Plugins.Popup#263]
Android has problem in closing the Pop up when background is clicked using the version 1.0.4 of Rg.Plugins.Popup. The attribute CloseWhenBackGroundClicked is set to true, but never closes when background is clicked.

**Comment by Gamass** [comment]
Try to edit MainActivity.cs in this way:
public override void OnBackPressed() => Rg.Plugins.Popup.Popup.SendBackPressed(base.OnBackPressed);

**Comment by jcmanke** [comment]
Seems to be fixed as of 1.1.3 prerelease.

Also @Gamass - `Rg.Plugins.Popup.Popup` wasn't added until 1.1.2.

**Comment by yajirobe-byob** [comment]
CloseWhenBackgroundIsClicked still does not work

**Comment by masiri201** [comment]
I had the same problem, I added a stacklayout covering the whole background and then added gesture recognizer and when the tap event was triggered I close the popup, i was in a rush so I came up with that.

**Comment by rotorgames** [comment]
The PopupPage can't catch a background click if a view in PopupPage.Content fills all PopupPage.

Also update this plugin to the last pre/beta release version
