### ISSUE TITLE
NavigationPage for PopUpPage

### ISSUE THREAD

**Issue by Trivias91** [rotorgames/Rg.Plugins.Popup#265]
Hi, this isn't so much an issue as a question.  You currently have one PopUpPage that inherits from ContentPage.  Would it be possible to make a different type of PopUpPage that inherited from NavigationPage so you could have navigation inside the popup or would one of the native implementation prevent it?

**Comment by Gamass** [comment]
Nope, PopUpPage can be only layer above the NavigationPage stack

**Comment by rotorgames** [comment]
Duplicate #247
