### ISSUE TITLE
Issue at runtime in Xamarin forms android project

### ISSUE THREAD

**Issue by ali-h2010** [rotorgames/Rg.Plugins.Popup#266]
I installed the library and it's build fine on all projects. but when I run the android app I get this runtime error:

Could not resolve type with token 01000002 (from typeref, class/assembly Rg.Plugins.Popup.Popup, Rg.Plugins.Popup.Droid, Version=1.1.4.145, Culture=neutral, PublicKeyToken=null)

I made sure that all the version is the same on all projects
Can someone help me with this?

Many thanks

**Comment by ali-h2010** [comment]
I should mention that the issue only occurs on release mode

**Comment by rotorgames** [comment]
@ali-h2010 Hi. In the first see https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started
if it will not help you see https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Troubleshooting

Also please update the plugin to the lest pre/beta release
