### ISSUE TITLE
Android: Prevent Keyboard from causing the Popup to re-layout

### ISSUE THREAD

**Issue by sonic1015** [rotorgames/Rg.Plugins.Popup#268]
I'd like the Keyboard to overlay overtop of the popup when I show a prompt dialog, but it is resizing (which is causing other problems, but I digress...). My Main page is behaving properly in the background, but the popup is resizing. Is there a setting, override, or work-a-round that would solve my problem?

**Comment by Gamass** [comment]
Just use property: HasSystemPadding="False"

**Comment by sonic1015** [comment]
That did it, thanks.

**Comment by v88NoahJerreel** [comment]
Thanks for this @Gamass :)

**Comment by mo-kml** [comment]
Hi
I Did try to set HasSystemPadding to false but it didn't work
what should i Do?
![image](https://user-images.githubusercontent.com/14197053/52261848-dda88c80-293f-11e9-9886-aedeb184b25d.png)

**Comment by rotorgames** [comment]
@mo-kml You have to use `HasKeyboardOffset` in new versions. https://github.com/rotorgames/Rg.Plugins.Popup/wiki/PopupPage#properties
