### ISSUE TITLE
System.TypeLoadException: Could not resolve type with token 01000037

### ISSUE THREAD

**Issue by wireless-r** [rotorgames/Rg.Plugins.Popup#269]
When debugging my Android app, this exception is thrown. Tried with version 1.1.4 and 1.1.3.

>03-27 11:12:09.498 I/MonoDroid(26896): UNHANDLED EXCEPTION:
>03-27 11:12:09.574 I/MonoDroid(26896): System.TypeLoadException: Could not resolve type with token 01000037 (from typeref, class/assembly Rg.Plugins.Popup.Popup, Rg.Plugins.Popup.Droid, Version=1.1.4.145, Culture=neutral, PublicKeyToken=null)
>03-27 11:12:09.574 I/MonoDroid(26896):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
>03-27 11:12:09.574 I/MonoDroid(26896):   at (wrapper dynamic-method) System.Object.0ad1d382-2da6-44ca-8a2a-fff2be434b2e(intptr,intptr,intptr)

![screenshot_1](https://user-images.githubusercontent.com/28116634/37957982-9110341e-31af-11e8-9fbd-a1a7d107f15d.png)

**Comment by wireless-r** [comment]
Also tried [this solution on StackOverflow](https://stackoverflow.com/a/40144478/7885142).

**Comment by wireless-r** [comment]
I removed the plugin from my project, then the TypeLoadException appeared for other types where it didn't appear before. Then I cleaned the project and deleted the app and debugged without errors. Then I added the Rg.Plugins.Popup again, cleaned the project and deleted the app. Now it works fine.

**Comment by wireless-r** [comment]
The same thing happened when I referenced another external project in my solution. So the error may not related be to this plugin.

**Comment by rotorgames** [comment]
@wireless-r I like a programming it's fun)
