### ISSUE TITLE
Use Popup with FreshMvvM Framework

### ISSUE THREAD

**Issue by KathirveluM** [rotorgames/Rg.Plugins.Popup#27]
Hi,
I want to use Rg.Plugins.Popup Component with FreshMvvm framework. 

To trigger the popup page, you have mentioned to call the  Rg.Plugins.Popup.Extensions.NavigationExtension.PushPopupAsync through Navigation class. 
But we want use this feature from the Page Model Class(FreshBasePageModel). 

Thanks you so much for your support. 
Best Regards,
Kathirvelu M

**Comment by rotorgames** [comment]
@KathirveluM Hey. You have to realize the navigation for FreshMvvm

**Comment by KathirveluM** [comment]
@rotorgames , The same is posted in Freshmvvm framework  and responded as "it's likely to be a issue with the PopUps, not to do with FreshMvvm." 
[https://github.com/rid00z/FreshMvvm/issues/78](url)

**Comment by rotorgames** [comment]
@KathirveluM Rg.Plugins.Popup, it is dependent only on Xamarin.Forms. For all other libraries, you should write a wrapper yourself.

**Comment by EmilAlipiev** [comment]
Did you find solution for this? I am also using freshmvvm and cant figure out how to navigate from viewmodel

**Comment by KathirveluM** [comment]
No, i haven't found solution to use this. 
So we customized the Content Page "Scrollview" Layout as popup dialog.

**Comment by rotorgames** [comment]
I will create plugin for FreshMvvm soon.

**Comment by KathirveluM** [comment]
@rotorgames , any update on the plugin to support FreshMvvm!!

**Comment by Ed156** [comment]
I would also be interested in such a plugin.

**Comment by rotorgames** [comment]
Hi everyone. I'm busy to fix importan bugs, when I fix them I will create FreshMvvm wrapper. Thank you.

**Comment by VahidShir** [comment]
I would definitely look forward to it.

**Comment by swapnil591** [comment]
Its possible to invoke Reverseinit method after Pop Popup page.

**Comment by formosus19** [comment]
@rotorgames 
Any update on the plugin to support FreshMvvm ??

**Comment by formosus19** [comment]
@KathirveluM 
Could you please share your customized popup dialog which you integrated with freshmvvm??

**Comment by dotnetpete** [comment]
Not sure if this is a good approach, but I created my own FreshNavigationContainer (could also be with the other FreshMVVM Navigation Containers), and modified the PushPage method. Works nicely for me.

public virtual Task PushPage(Xamarin.Forms.Page page, FreshBasePageModel model, bool modal = false, bool animate = true)
        {
            if (modal)
            {
                if (page is PopupPage)
                {
                    return Navigation.PushPopupAsync(page as PopupPage, animate);
                }
                else
                {
                    return Navigation.PushModalAsync(CreateContainerPageSafe(page), animate);
                }
            }

            return Navigation.PushAsync(page, animate);
        }

**Comment by LeoJHarris** [comment]
@dotnetpete Hi would like to know how your Custom FreshNavigationContainer look like exactly for this, am facing the same issue of using popup with FreshMvvm and no luck but trying to use your included code above. Thanks

**Comment by libin85** [comment]
A bit late to the party but if anyone wants the support please try this: https://github.com/libin85/FreshMvvm.Popup/ and let me know your feedback

**Comment by rejy11** [comment]
@libin85 your library works perfectly although you cannot pass data back through PopPopupPageModel (meaning ReverseInit is also not called) as well as OnViewAppearing not being called in the previous page model.

**Comment by kwabenaowusujnr** [comment]
> A bit late to the party but if anyone wants the support please try this: https://github.com/libin85/FreshMvvm.Popup/ and let me know your feedback

if getting this error with **Rg.Plugins.Popup 1.2.0.223** , **Xamarin Forms 4.2.0.848062**
**System.InvalidOperationException
  Message=The page has not been pushed yet or has been removed already** on await CoreMethods.PushPopupPageModel<MyPersonPageModel>(true);
