### ISSUE TITLE
IsAnimationEnabled doesnt exist in current context

### ISSUE THREAD

**Issue by dfsRony** [rotorgames/Rg.Plugins.Popup#271]
I tried to copy your demo code (LoginPopupPage) to my project, but I can't really use it because "IsAnimationEnabled doesn't exist in current context" always come. I don't know how to fix this. Everything works fine if I rune your DemoProject. If I do ctrl+click on IsAnimationEnabled on your demo project, it opens a file called PopupPages.cs in Rg.Plugins.Popup.Pages. I already add "use Rg.Plugins.Popup.Pages" to my page library but it seems not fixing the problem. Any suggestion?

**Comment by rotorgames** [comment]
@dfsRony Just update this plugin to the last pre release version.
