### ISSUE TITLE
How to detect when back from the PopupPage ?

### ISSUE THREAD

**Issue by marcelinhovt** [rotorgames/Rg.Plugins.Popup#273]
I call the PopupPage, but i am not able to detect when i am back from. The method OnAppearing() is not fired. How can i detect ? I need to do a action when return from the popup. 

I am using:
```
NMPage nmpage = new NMPage ();
await PopupNavigation.PushAsync(nmpage);
```

**Comment by rotorgames** [comment]
@marcelinhovt You can use OnDisappearing in PopupPage.
