### ISSUE TITLE
ListView goes "blank" after I re-open a PopupPage

### ISSUE THREAD

**Issue by georgikoemdzhiev** [rotorgames/Rg.Plugins.Popup#275]
This is an issue which started occurring after my team updated Xamarin.Forms to version  **2.5.1.444934**. In the previous version, it was working fine which was **2.5.0.280555**. 

In a nutshell, we have a custom control DetailedLookup which is essentially a Listview with several options to select and 2 buttons "OK", "Cancel" at the bottom which close the lookup and populates a label with the selected values.

This is it unopened:
![lu1](https://user-images.githubusercontent.com/11027608/38543840-9da68cca-3c9d-11e8-9704-83ad55df7be5.PNG)
During selection:
![lu2](https://user-images.githubusercontent.com/11027608/38543858-b024ebbc-3c9d-11e8-9438-4298e3a92745.PNG)
After selection:
![lu3](https://user-images.githubusercontent.com/11027608/38543871-b79c4020-3c9d-11e8-8103-fcc0b4e1b702.PNG)

The problem that started to occur after updating to Xamarin Forms **2.5.1.444934** broke the Listview data. What happens now is the first time I open the lookup, the ListView will have data. I close the lookup (press OK) and re-open it and it is blank:
![lu4](https://user-images.githubusercontent.com/11027608/38543968-05b028bc-3c9e-11e8-944a-ef40aa40689a.PNG)

That was not occuring before the update. I confirmed that by reverting back to version **2.5.0.280555** of Xamarin Forms and the control works fine.

Hopefully, that helps. Please let me know if I can help further.

**Comment by rotorgames** [comment]
@georgikoemdzhiev Hi. Are you sure that it is problem of this plugin. Did you try to use your control in Xamarin.Forms.Page (not PopupPage)?

**Comment by georgikoemdzhiev** [comment]
Hi! Thank you for spending time on that. I will try that and get back to you.

**Comment by georgikoemdzhiev** [comment]
@rotorgames  Sorry for the delay. I was able to test out control as a ContentPage (As if not using this library) and the problem was still there. So it is not a problem with this library. 

Thank you for your time and suggestion. That cleared the picture. I am closing the ticket now.
