### ISSUE TITLE
Blur effect on background

### ISSUE THREAD

**Issue by masiri201** [rotorgames/Rg.Plugins.Popup#277]
Is there any chance that we can have a opacity property and also a blur property on the background of the popup?, that way we can see through to other pages but with a nice blur effect, i think it would be a nice feature on this package.

**Comment by zany1** [comment]
You can use Skia Sharp which is supported by xamarin, this class [https://developer.xamarin.com/api/type/SkiaSharp.SKMaskFilter/](url)  will help you achive it , just draw a canvas on the background property of this plugin.

**Comment by AnimaOleg** [comment]
Broken url. More info at https://learn.microsoft.com/es-es/xamarin/xamarin-forms/user-interface/graphics/skiasharp/
