### ISSUE TITLE
OnAppearingAnimationEndAsync is not called on version 1.1.4.145-pre

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#278]
I have a popup page and OnAppearingAnimationEndAsync is never called on V1.1.4.145-pre

**Comment by JKennedy24** [comment]
ps. I was testing this on android if this makes a difference

**Comment by rotorgames** [comment]
@JKennedy24 OnAppearingAnimationEndAsync will not be invoked if `PopupPage.IsAnimationEnabled `is false or if system animation of Android is disabled.

**Comment by rotorgames** [comment]
@JKennedy24 I just have tested the demo project and `OnAppearingAnimationEndAsync` works fine. Can you check it in the demo project?

**Comment by JKennedy24** [comment]
after checking again this does get called. I don't know whether this was device specific. If I see it again I will investigate more. But looks like it does work correctly
