### ISSUE TITLE
ImageSource binding doesn't update on popup UI until tapped

### ISSUE THREAD

**Issue by borbmizzet** [rotorgames/Rg.Plugins.Popup#279]
When changing a property of type ImageSource in a FlowListView or ListView bound to an Image or FFImageLoading:CachedImage within the popup view, the Image doesn't update until you tap somewhere in the ListView. (I tried this with both a ListView and a FlowListView)  Though I could be wrong and the problem is with an changing an IsVisible property instead of an Image Source.  Either way, when I downgrade to version Rg.Plugins.Popup 1.0.4, the UI starts updating properly again.  When I upgrade back up to the latest prerelease, the problem reappears.   A project demonstrating the bug is attached.  Ignore the name of my demo project, it was originally created to demo a bug in a different project but I modified it to demonstrate this one.

Problem version: Rg.Plugins.Popup 1.1.4.145-pre
Last working version: Rg.Plugins.Popup 1.0.4

[EditorCrash.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/1899665/EditorCrash.zip)

**Comment by rotorgames** [comment]
@borbmizzet Try to test v1.1.4.148-pre from Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

**Comment by borbmizzet** [comment]
Works like a charm.  Thanks.

**Comment by rotorgames** [comment]
@borbmizzet You are welcome.
