### ISSUE TITLE
Navigation.PushPopupAsync crashes on Android

### ISSUE THREAD

**Issue by mr5z** [rotorgames/Rg.Plugins.Popup#280]
The page contains a ListView with groupings enabled. Calling the Navigation.PushPopupAsync throws a `Java.Lang.NullPointerException`

Full stacktrace:
``
MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <3cb12bce834a498199b2be6cd3e00922>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <3cb12bce834a498199b2be6cd3e00922>:0 
[MonoDroid]   at Android.Widget.ListView.AddHeaderView (Android.Views.View v) [0x00031] in <0f4fdd9de5d4461ca741cbb9871ad0ce>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.ListViewAdapter.OnDataChanged () [0x00075] in D:\agent_work\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:573 
[MonoDroid]   at Xamarin.Forms.Platform.Android.ListViewAdapter.OnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00000] in D:\agent_work\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:553 
[MonoDroid]   at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0000a] in D:\agent_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:771 
[MonoDroid]   at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnProxyCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e, System.Boolean fixWindows) [0x0047b] in D:\agent_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:1114 
[MonoDroid]   at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnProxyCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00000] in D:\agent_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:968 
[MonoDroid]   at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnItemsSourceChanged (System.Boolean fromGrouping) [0x00061] in D:\agent_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:949 
[MonoDroid]   at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].BindableOnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00020] in D:\agent_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:661 
[MonoDroid]   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
[MonoDroid]   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in D:\agent_work\1\s\Xamarin.Forms.Core\BindableObject.cs:146 
[MonoDroid]   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\agent_work\1\s\Xamarin.Forms.Core\Element.cs:401 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00107] in D:\agent_work\1\s\Xamarin.Forms.Core\BindableObject.cs:602 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent_work\1\s\Xamarin.Forms.Core\BindableObject.cs:399 
[MonoDroid]   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in D:\agent_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:174 
[MonoDroid]   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in D:\agent_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:56 
[MonoDroid]   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__47_0 () [0x00000] in D:\agent_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:547 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <0f4fdd9de5d4461ca741cbb9871ad0ce>:0 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <0f4fdd9de5d4461ca741cbb9871ad0ce>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.22785064-d761-4e1b-a032-f9a4fbc08b58(intptr,intptr)
[MonoDroid]   --- End of managed Java.Lang.NullPointerException stack trace ---
[MonoDroid] java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
[MonoDroid] 	at android.widget.ListView.addHeaderView(ListView.java:341)
[MonoDroid] 	at android.widget.ListView.addHeaderView(ListView.java:383)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:790)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:164)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[MonoDroid] 
[mono] 
[mono] Unhandled Exception:
[mono] Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
[mono]   at (wrapper dynamic-method) System.Object.22785064-d761-4e1b-a032-f9a4fbc08b58(intptr,intptr)
[mono]   --- End of managed Java.Lang.NullPointerException stack trace ---
[mono] java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
[mono] 	at android.widget.ListView.addHeaderView(ListView.java:341)
[mono] 	at android.widget.ListView.addHeaderView(ListView.java:383)
[mono] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[mono] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[mono] 	at android.os.Handler.handleCallback(Handler.java:790)
[mono] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono] 	at android.os.Looper.loop(Looper.java:164)
[mono] 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[mono] 	at java.lang.reflect.Method.invoke(Native Method)
[mono] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[mono] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[mono] 
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
[mono-rt]   at (wrapper dynamic-method) System.Object.22785064-d761-4e1b-a032-f9a4fbc08b58(intptr,intptr)
[mono-rt]   --- End of managed Java.Lang.NullPointerException stack trace ---
[mono-rt] java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
[mono-rt] 	at android.widget.ListView.addHeaderView(ListView.java:341)
[mono-rt] 	at android.widget.ListView.addHeaderView(ListView.java:383)
[mono-rt] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[mono-rt] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:790)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono-rt] 	at android.os.Looper.loop(Looper.java:164)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[mono-rt] 
``

**Comment by mr5z** [comment]
Solved it by **specifically** targeting to version 1.1.1.57
I wasn't able to find this stable release on NuGet listings so I was using the v1.0.4 and some pre-release versions

**Comment by rotorgames** [comment]
@mr5z in first try to update this plugin to the last pre/beta version. If it doesn't help you then show me your code.

**Comment by rotorgames** [comment]
The last stable version must fix this bug. Don't be afraid to reopen this issue if you still have this issue.
