### ISSUE TITLE
Memory Issue- It consumes more memory(The memory level not coming Down)

### ISSUE THREAD

**Issue by balaameex** [rotorgames/Rg.Plugins.Popup#281]
Hi, 

I used this popup in my app to show some user information. I analyzed the app for memory usage and found that whenever we are opening the popup the memory is increasing and not at all coming down. if you open the popup continuously for multiple time then the memory will go high and crash the app in Android.

Could you please fix this issue.
Balakrishnan.S

**Comment by rotorgames** [comment]
@balaameex It was corrected. Update this plugin to the last pre/beta version

**Comment by balaameex** [comment]
Thanks, It solves the issue
