### ISSUE TITLE
Live player

### ISSUE THREAD

**Issue by axeira** [rotorgames/Rg.Plugins.Popup#282]
Can this plugin be used with Live player? Tried with IOS but it seems that crashes when popup window opens.

**Comment by rotorgames** [comment]
@axeira I didn't test the plugin with Live player. I think the plugin doesn't work with it.

**Comment by dansiegel** [comment]
@axeira the Live Player is meant as a learning tool. The messaging about what it is capable of, and is good for, has been way off base... pretty much any common library you may be using from Prism to Rg.Plugins.Popup, to RX are not supported and will never be supported by the Live Player. 

While this plugin doesn't work with the Previewer in the IDE currently, I can say that I have had some discussions with the team on how we can support this and other libraries.

**Comment by axeira** [comment]
It's a shame because Live player run quite smooth. Until it needs the plugin, then crashes! 
To develop in IOS do I have to buy a mac? I have a iPhone and an ipad, not enough though. :-/

**Comment by dansiegel** [comment]
I have seen developers with VirtualBox running a OSX VM on Windows. You could also look at a service like https://www.macincloud.com or https://xcloud.me/. Or what a lot of people who prefer to work on Windows do is get a Mac Mini. That would allow you to connect your real devices and set them to work wirelessly.

**Comment by axeira** [comment]
Thank you for all the advice.

**Comment by dansiegel** [comment]
I strongly suggest that you look at Live Reload from the Xamarin team if you’re using Visual Studio 2017. It really solves a lot of problems. Plus if you’re using a MVVM design pattern it keeps state on reloads.
