### ISSUE TITLE
Using Rg.Plugins.Popup with Prism

### ISSUE THREAD

**Issue by genilsonmm** [rotorgames/Rg.Plugins.Popup#283]
Is possible use the library with prism framework? It is not working in my project because it does not work with navigationService.NavigateAsync and

**Comment by dansiegel** [comment]
Yes it is possible to use this with Prism if you are using [Prism.Plugin.Popups](/dansiegel/Prism.Plugin.Popups). You'll want to use the 2.0 preview. Keep in mind that pre6 is targeting Prism 7.0 while the latest preview is targeting the Prism 7.1 preview, so you will need to pick the one that best fits your needs. The only new requirement that you'll have is to add

```cs
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.RegisterPopupNavigationService();
}
```

**Comment by rotorgames** [comment]
@dansiegel have a good extension for prism. Use it.

**Comment by lorfer** [comment]
Hey broh' im new using this plugin and i want to use it for navigation come back but i cant, plis you can help me
