### ISSUE TITLE
No Android Popup class present when installing through NuGet in VS2017

### ISSUE THREAD

**Issue by InnerScript** [rotorgames/Rg.Plugins.Popup#284]
Using Visual Studio 2017 Community, latest Xamarin/Xamarin Forms libraries and installing through the nuget.org on an existing Android/iOS projects.

In the Android and iOS project, editing the main classes and attempting to add the required lines for each respective project type:

_Rg.Plugins.Popup.Popup.Init(this, bundle);_  //Added to Android MainActivity
_Rg.Plugins.Popup.Popup.Init();_ //Added to iOS AppDelegate

**Results in the following syntax error:** "The type or namespace "Popup" doesn't exist in the namespace Rg.Plugins.Popup"

Either that class was removed and is no longer needed, and the documentation needs to be updated OR there is an issue building the NuGet package.

I have attempted all 1.0.x version of packages with the same result. VS bin/obj folders were cleared, VS restarted.

**Comment by rotorgames** [comment]
@InnerScript use the last pre/beta release v1.1.x
