### ISSUE TITLE
Using Rg.Plugins.Popup with Prism

### ISSUE THREAD

**Issue by maherzaidoune** [rotorgames/Rg.Plugins.Popup#286]
is it possible to use Rg.Plugins.Popup with freshMVVM library ?

**Comment by dansiegel** [comment]
It's not the responsibility of this plugin to work with any MVVM Framework. It's only the responsibility of this library to work with Xamarin Forms. If you're wanting support for FreshMVVM type navigation with PopupPage's I suggest you either raise the issue with @rid00z or write an extension to FreshMVVM that enables it, much like what I've done for Prism with [Prism.Plugin.Popups](/dansiegel/Prism.Plugin.Popups).

**Comment by maherzaidoune** [comment]
hey @dansiegel , my  question is more about mvvm pattern than freshmmvm itself  , i can't decouple PopupPage views and  logic  as Page and  pageModel , i can't use  commands  on pages:PopupPage elements

**Comment by LeoJHarris** [comment]
@maherzaidoune yes it is https://github.com/libin85/FreshMvvm.Popup/ you just need to call the appropriate push and pop extension methods.
