### ISSUE TITLE
Would like to make a PopupView version of this to keep the page separated

### ISSUE THREAD

**Issue by marcusts** [rotorgames/Rg.Plugins.Popup#288]
Hi, I pulled the source and commented out enough to make this work as a PopupView (rendering ViewRenderer), which decoupled it from ContentPage. This is extremely helpful for most of us who might otherwise not be able to derive all of our pages from your page.  Obviously, this defeats navigation.  But it also makes the popup useful in every app imaginable, without redesigning from the ground up.

I didn't get it working under IOS because the renderer seems to need the Page, at least as it is currently laid out.

I can send you the source via GoogleDrive if you wish. I didn't fork because my changes would alter your original purpose.  So maybe this could become a second component in your suite.  

Thanks for the amazing work!

**Comment by rotorgames** [comment]
@marcusts Hi. Thank you for your work. I would like to see your code. Also I don't see any different between PopupPage and PopupView. What is it need? They will work same but I will need to support more code because of it.

**Comment by marcusts** [comment]
Hi,

The goal is to make your *great* popup more easily usable in more
situations.

Most programmers will not be able to rederive their pages from your
PopUpPage.  But they can more easily adapt some of their views with a
PopUpView, since that doesn't interfere with their existing page and
navigation strategy.

MVVM frameworks make this quite difficult as well, and they are
getting popular.

Navigation is a major topic that one should not venture into casually.  Yor
pp works very well without navigation.

I am sending you the code today via Google Drive.  I could also use DropBox
if you wish.

Please send an email which I should use for the file transfer.

Stephen Marcus

**Comment by rotorgames** [comment]
@marcusts Still you have your changes? I can't find your email.

**Comment by rotorgames** [comment]
@marcusts Yeap too long. Just I had a lot of issues and I didn't have time to make big improvements. After one year do you change your opinion about this issue?

**Comment by marcusts** [comment]
No, just moved on to other issues... sorry, my friend...
