### ISSUE TITLE
popup screens not working with accessibility

### ISSUE THREAD

**Issue by raymondjstone** [rotorgames/Rg.Plugins.Popup#289]
It looks like the way that the popup screens are implemented breaks when accessibility options are switched on.

My initial testing has been switching on voiceover (on android) and it looks like text on popups is not being recognised well, the close icon is not being picked up consistently, clicking off the popup (to close) does not function and items on the screen below the popup can be selected.

**Comment by rotorgames** [comment]
@raymondjstone What version of the plugin do you use?

**Comment by raymondjstone** [comment]
I'm not at work to check, but it's whatever the current nget version is

**Comment by rotorgames** [comment]
@raymondjstone I need to know exactly what version do you use. Try to install the last pre/beta release from nuget.

**Comment by raymondjstone** [comment]
1.0.4 is the version used. I can't try pre/beta versions at this time due to work policies.

**Comment by rotorgames** [comment]
@raymondjstone I will try to public a new stable version soon and you will be able to test it.

**Comment by rotorgames** [comment]
Try to use the last stable version.
