### ISSUE TITLE
Create interface IPopupPage abstraction for device implementation

### ISSUE THREAD

**Issue by lreading** [rotorgames/Rg.Plugins.Popup#29]
First, I absolutely love this plugin.  Fantastic job!

I'd suggest creating an interface for the popup page, and having the PushPopupAsync method accept the IPopupPage as the argument rather than the concrete PopupPage type.

The reason for this suggestion is that I needed to make a device-specific implementation using Xamarin's DI.  

As a work-around, I created my own interface and am casting it to a popuppage on the fly, but I thought it would be pretty cool if we could do that without the extra cast.

Ex:

```
            var loginPopup = DependencyService.Get<ILogInPopup>();
            // Currently doing this
            await Navigation.PushPopupAsync((loginPopup as PopupPage), true);
```

I'd love to contribute if I can, but I wanted to float the idea before putting in the work.

Thanks!

**Comment by lreading** [comment]
Seems as though there may be a problem with my implementation...

> [402:159961] Warning: Attempt to present <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x140ab8d70>  on <Xamarin_Forms_Platform_iOS_PhoneMasterDetailRenderer: 0x14074e640> which is already presenting (null)


This is happening when I pop a popup off of the stack, and then attempt to push another one.  The end result is that nothing is displayed.

**Comment by rotorgames** [comment]
> First, I absolutely love this plugin. Fantastic job!
> 
> I'd suggest creating an interface for the popup page, and having the PushPopupAsync method accept the IPopupPage as the argument rather than the concrete PopupPage type.
> 
> The reason for this suggestion is that I needed to make a device-specific implementation using Xamarin's DI.
> 
> As a work-around, I created my own interface and am casting it to a popuppage on the fly, but I thought it would be pretty cool if we could do that without the extra cast.

Hi friend. It's impossible. `PopupPage` uses internal methods to control animations and other features. The interface allows you to implement only public methods.

To create a Popup, extend from PopupPage in the PCL project and PopupPageRenderer in platform dependent projects.

> Seems as though there may be a problem with my implementation on iOS.
> I could make this a new issue, but I think it may be because of how I'm implementing it rather than an inherent issue with the library.
> 
> ```
> [402:159961] Warning: Attempt to present <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x140ab8d70> on <Xamarin_Forms_Platform_iOS_PhoneMasterDetailRenderer: 0x14074e640> which is already presenting (null)
> ```

This will be fixed in version 1.0.0

**Comment by lreading** [comment]
> Hi friend. It's impossible. PopupPage uses internal methods to control animations and other features. The interface allows you to implement only public methods.

It's definitely not impossible, but it is a design decision.  If you program the PopupPage against the interface, then any class that extends from Popup page will be implementing that interface.  This would allow for very easy device specific implementation using the Dependency service.

If you want, I could make a pull request with an example of what I'm talking about to see if you like it/agree, if you don't like the idea, that's fine too.

Thanks!

**Comment by rotorgames** [comment]
@lreading Probably, I incorrectly expressed. Of course it is possible. But I do not understand why it can be necessary?

What would make your Popup, you need to inherit from PopupPage in PCL, and from PopupPageRenderer in platform dependent code.

Also, PopupPage must inherit from VisualElement, that would have been possible to get the renderer (native elements).

Explain why you need this as easy as possible, I'm not very good at English. And I think, is it worth doing or not.

Thank you.
