### ISSUE TITLE
It's possible using Rg.Plugins.Popup with MvvmCross ?

### ISSUE THREAD

**Issue by juanagu** [rotorgames/Rg.Plugins.Popup#290]

**Comment by rotorgames** [comment]
You should use Xamarin.Forms for it.

**Comment by juanagu** [comment]
Yes thanks, It works! :)

**Comment by PoLaKoSz** [comment]
Hi!

Its not clear for me what do You mean by `You should use Xamarin.Forms for it`. Can You give me a hint how should i implement it?

Thank You!
