### ISSUE TITLE
'Rg.Plugins.Popup.IOS.Platform.PopupWindow' does not have a constructor that takes one IntPtr argument

### ISSUE THREAD

**Issue by vecalion** [rotorgames/Rg.Plugins.Popup#294]
One of our QA engineers found a crash in Rg.Plugins.Popup.IOS.Platform.PopupWindow (unfortunately without repro steps). The following exception was thrown when the app tried to display a popup. Is it something known? 

> EditUserViewModel+<Init>d__135.MoveNext ()
System.Exception: Failed to marshal the Objective-C object 0x124be70c0 (type: Rg_Plugins_Popup_IOS_Platform_PopupWindow). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Rg.Plugins.Popup.IOS.Platform.PopupWindow' does not have a constructor that takes one IntPtr argument).
Runtime.MissingCtor (System.IntPtr ptr, System.IntPtr klass, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution resolution)
Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution)
Runtime.GetINativeObject[T] (System.IntPtr ptr, System.Boolean owns)
NSArray.UnsafeGetItem[T] (System.IntPtr handle, System.nuint index)
NSArray.ArrayFromHandle[T] (System.IntPtr handle)
UIApplication.get_Windows ()
ProgressHUD.ShowProgressWorker (System.Single progress, System.String status, BigTed.ProgressHUD+MaskType maskType, System.Boolean textOnly, BigTed.ProgressHUD+ToastPosition toastPosition, System.String cancelCaption, System.Action cancelCallback, System.Double timeoutMs, System.Boolean showContinuousProgress, UIKit.UIImage displayContinuousImage)
ProgressHUD+<>c__DisplayClass18_0.<Show>b__0 ()
NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging:objc_msgSend (intptr,intptr,intptr,intptr,bool)
NSObject.InvokeOnMainThread (System.Action action)
ProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType, System.Double timeoutMs)
BTProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType)
ProgressDialog+<>c__DisplayClass17_0.<Refresh>b__0 ()
NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging:objc_msgSend (intptr,intptr,intptr,intptr,bool)
NSObject.InvokeOnMainThread (System.Action action)
ProgressDialog.Refresh ()
ProgressDialog.Show ()
AbstractUserDialogs.Progress (Acr.UserDialogs.ProgressDialogConfig config)
AbstractUserDialogs.Loading (System.String title, System.Action onCancel, System.String cancelText, System.Boolean show, System.Nullable`1[T] maskType)
AbstractUserDialogs.ShowLoading (System.String title, System.Nullable`1[T] maskType)
EditUserViewModel+<Init>d__135.MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter.GetResult ()
EditUserPage+<OnAppearing>d__3.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 ()
NSAsyncActionDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
Collapse

**Comment by ParticularEric** [comment]
Got exactly the same. It happens when calling code from ACR.Userdialogs (ShowLoading) even though no code of the Popup Plugin is executed at that time. Cant properly reproduce it, too. Did you find a solution for it yet?

**Comment by goldnarms** [comment]
+1

**Comment by rotorgames** [comment]
Guys, what version of the popup plugin do you use, and can somebody create a simple project which will reproduce this issue?

**Comment by rotorgames** [comment]
@bacheric Thank you for your answer. I hope I have fixed it and nobody will get this issue. 

I'm going to close this issue but don't be afraid to reopen it if you still have the same issue.
