### ISSUE TITLE
Exception in UWP opening popup window only in Release builds

### ISSUE THREAD

**Issue by luis-barreira** [rotorgames/Rg.Plugins.Popup#295]
Hi,
I get an exception whenever the app tries to open a popup in a UWP application, there is no error in Android and iOS. The error only occurs when the application is packaged and installed from that package, there is no error when the application in started from Visual Studio using Release or Debug builds. I tried to update to the last version of the library, but the error is still there.

Te exception details are pasted below:

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {System.InvalidCastException: Specified cast is not valid.    at Rg.Plugins.Popup.WinPhone.Impl.PopupPlatformWinPhone.<AddAsync>d__11.MoveNext() in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup.WinShared\Impl\PopupPlatformWinPhone.cs:line 73    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 63    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 121    at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 397    at Rg.Plugins.Popup.Services.PopupNavigationImpl.<AddAsync>d__11.MoveNext() in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:line 111    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 63    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 121    at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 397    at Rg.Plugins.Popup.Services.PopupNavigationImpl.<PushAsync>d__7.MoveNext()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 63    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 182    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 150    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 121    at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 397    at KisenseMobile.Popups.ConfirmAlarmPopup.<GetAlarmConfirmation>d__1.MoveNext() in D:\Work\Projectos\KisenseMobile\03 Development\Source\KisenseMobile\KisenseMobile\Popups\ConfirmAlarmPopup.xaml.cs:line 21} | System.InvalidCastException

**Comment by maurelio97** [comment]
Same with me. 

I'm using version 1.1.4.154-pre and this issue only occurs in UWP Release when **.NET Native tool chain option** is checked in UWP project properties (which is required to package UWP apps to Windows Store).

**Comment by qbus00** [comment]
Hello,
I've got the exactly the same issue on 1.1.4-154-pre. Plugin does not want to work in Native tool chain compliation mode.

**Comment by qbus00** [comment]
Update - I have checked the PopupPlatformWinPhone class and it looks that on GetOrCreateRenderer returns standard PageRenderer (instead of PopupPageRenderer) even there's assembly registration in in Init method of Xamarin Forms.

**Comment by luis-barreira** [comment]
After digging for a while in the source code, I found a solution to this:

The plugin initialization in **_App.xaml.cs_** (in the UWP project) must be changed from

```
Rg.Plugins.Popup.Popup.Init();
Xamarin.Forms.Forms.Init(e);
```
to

```
Rg.Plugins.Popup.Popup.Init();
Xamarin.Forms.Forms.Init(e, Popup.GetExtraAssemblies());
```

**Comment by rotorgames** [comment]
See https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Troubleshooting#uwp-troubleshooting
