### ISSUE TITLE
How I can catch it the onbackgroundclicked event?

### ISSUE THREAD

**Issue by CarlosAyala** [rotorgames/Rg.Plugins.Popup#296]
Hi!,

I have the CloseWhenBackgroundIsClicked attribute in "True". 
How can I catch the closed event when the user clicks on the background?

**Comment by rotorgames** [comment]
@CarlosAyala you can use for it `PopupPage.BackgroundClicked` event or you can override `PopupPage.OnBackgroundClicked` virtual method.

**Comment by SuyRoadtoSilver** [comment]
Hello :)
 the OnBackgroundClicked is private isn't it? 
mb i just did not find it but in PopupPageRenderer.cs Line 213 : 

`private void OnBackgroundClick(object sender, MotionEvent e)`

it seems that you can´t override it anymore?

any other solutions?

**Comment by rotorgames** [comment]
@sayaleepote it's protected. https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup/Pages/PopupPage.cs#L150

**Comment by rotorgames** [comment]
@SuyRoadtoSilver it's protected virtual: https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup/Pages/PopupPage.cs#L280
