### ISSUE TITLE
Popup is not centred on screen transparent background

### ISSUE THREAD

**Issue by veletron2** [rotorgames/Rg.Plugins.Popup#300]
Hi

I use this package to provide some self-clearing error popups in my App. I call it both when my MainActivity is displayed, but also in response to an intent NFC, BLE etc when my MainActivity is not displayed and I wish to display an error message over the top of whatever happens to be on-screen at the time. This is all on Android.

When displaying the popup over the top of my MainActivity, it works just fine, centred perfectly, however when I display it over the top of the android desktop or over the top of another (unrelated) app, it is not centred properly. For the latter case, I set a transparent theme, while the former has my normal theme.

Any idea how I can ensure that it is always centred on-screen no matter the background content?

XAML is below, screenshots are attached

<?xml version="1.0" encoding="utf-8" ?>
    <pages:PopupPage 
        xmlns="http://xamarin.com/schemas/2014/forms"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
        xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
        xmlns:controls="clr-namespace:ProteusPatientApp.Controls;assembly=ProteusPatientApp"
        x:Class="ProteusPatientApp.PopupViews.PopupErrorPage"
        InputTransparent="True"
        BackgroundColor="Transparent"
        NavigationPage.HasNavigationBar="false">

        
        <pages:PopupPage.Animation>
            <animations:FadeAnimation 
                DurationIn="400"
                DurationOut="100"
                HasBackgroundAnimation="false"/>
        </pages:PopupPage.Animation>
        
        <Frame 
            x:Name="PopUpDialogLayout"
            HorizontalOptions="CenterAndExpand" 
            VerticalOptions="CenterAndExpand" 
            OutlineColor="Black"
            CornerRadius="10"
            HasShadow="true"
            Margin="2"
            Padding="0">
            <StackLayout Orientation="Vertical" Padding="20,20,20,20" Spacing="30" VerticalOptions="Center" HorizontalOptions="Center">
                <Label Text="{Binding ErrorTitle}" TextColor="Black" FontSize="30" VerticalOptions="Start" HorizontalTextAlignment="Center"/>
                <Label Text="{Binding ErrorDescription}"  TextColor="Black" FontSize="15" HorizontalTextAlignment="Center" />
            </StackLayout>
        </Frame>
    </pages:PopupPage>

![overdesktop](https://user-images.githubusercontent.com/34792184/39819194-c24d6d64-539a-11e8-9416-a7e2cc69168e.png)

![overapp](https://user-images.githubusercontent.com/34792184/39819202-c8b46bda-539a-11e8-978c-bc738c56ed59.png)

**Comment by veletron2** [comment]
Hi

Just to say that I have now got this working with the following style:

 <style name="ProteusPopupTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="windowNoTitle">true</item>
    <item name="windowActionBar">false</item>
    <item name="android:windowIsTranslucent">true</item>
    <item name="android:windowBackground">@android:color/transparent</item>
    <item name="android:backgroundDimEnabled">true</item>
    <item name="android:statusBarColor">@android:color/transparent</item>
  </style>

The style is set prior to calling OnCreate.Base() in MainActivity once I know that the intent is to cause a popup error rather than display a page etc. The only thing I still cant get working is the outline for the popup dialog when its on a transparent background, but I guess I will live with that!

[Xamarin.Android MainActivity.cs]

Rg.Plugins.Popup.Popup.Init(this, bundle);
var payload = choosePageToLoad(false, Intent);
if (payload.RequestedPageId == PageId.RequestedPageId.ErrorScreen)
    Theme.ApplyStyle(Resource.Style.ProteusPopupTheme, true);
else
    Theme.ApplyStyle(Resource.Style.MainTheme_Base, true);

base.OnCreate(bundle);
LoadApplication(new App(payload));

Where the intent arrives as a newIntent to an already active activity, I switch the page using the MessagingCenter thus:

 protected override void OnNewIntent(Intent intent)
 {
       var payload = choosePageToLoad(true,intent);
       MessagingCenter.Send("ProteusPatientApp", "SwitchPage", payload);
            
       base.OnNewIntent(intent);
 }

In the shared app, App.xaml.cs, I have:

public App(NativeToFormsDataPayload payload
{
     InitializeComponent();
     //Subscribe to the app-global messages to switch the current page and allow patient event entry
     MessagingCenter.Subscribe<string, NativeToFormsDataPayload>("ProteusPatientApp", "SwitchPage", (sender, nativeToFormsDataPayload) => selectPage(nativeToFormsDataPayload));
            
     selectPage(payload);
}

selectPage method switched on payload.RequestedPageId (my own class), with the following done for the error popup using Rg.Plugins.popup:

```
case PageId.RequestedPageId.ErrorScreen:

     if (payload.LaunchedViaIntent)
     {
            await PopupNavigation.Instance.PushAsync(new PopupErrorPage(payload.ErrorScreenData, 
payload.LaunchedViaIntent));
            //we  dont set _currentPageId for this as its a popup
     }
     else
     {
             MainPage = new PopupErrorPage(payload.ErrorScreenData, payload.LaunchedViaIntent);
             _currentPageId = payload.RequestedPageId;
     }
    break;

Maybe this helps someone

**Comment by rotorgames** [comment]
@veletron2 I have closed this issue if you still have problem please reopen this issue.
