### ISSUE TITLE
Why the last version in Mac is 1.0.4?

### ISSUE THREAD

**Issue by jobuit** [rotorgames/Rg.Plugins.Popup#301]
![captura de pantalla 2018-05-11 a la s 10 59 18 a m](https://user-images.githubusercontent.com/28201079/39934375-2fb85fe6-550b-11e8-97ae-0ec4d724d7ea.png)

**Comment by jobuit** [comment]
How can i do it? @dansiegel

**Comment by leeanpeng** [comment]
@jobuit checked the checkbox on the bottom left
