### ISSUE TITLE
Please Update Nuget Package for UWP

### ISSUE THREAD

**Issue by stefan-stanca** [rotorgames/Rg.Plugins.Popup#308]
Hello,
I have installed nuget package version 1.0.4 targeting profile 111 on PCL (portable-win+net45+wp8+win8+wpa81) , using Xamarin forms 2.5.1. The version I am getting is the one where Rg.Plugins.Popup.Windows.Popup.Init() is not available and it is not registering the depencency service. I am not able to register it manually as the implementation is internal to the project.

**Comment by rotorgames** [comment]
@stefan-stanca Please, update this plugin to the last pre/beta version.
