### ISSUE TITLE
Popup initialization issue

### ISSUE THREAD

**Issue by denmusic1992** [rotorgames/Rg.Plugins.Popup#309]
Hello! Here is the issue:

I've updated package to 1.1.4.158pre and now I can't initialize a popup page.
I have an exception:

> Unhandled Exception: 
System.TypeInitializationException: The type initializer for 
 Rg.Plugins.Popup.Services.PopupNavigation' threw an exception. 

It happens after I call method` Navigation.PushPopupPage(..).`

My LoadingPopupPage.xaml:
`<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             x:Class="CommonClassesLibrary.LoadingPopupPage" 
                 CloseWhenBackgroundIsClicked="True">
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation
      PositionIn="Center"
      PositionOut="Center"
      ScaleIn="1.2"
      ScaleOut="0.8"
      EasingIn="SinOut"
      EasingOut="SinIn"
      HasBackgroundAnimation="True"/>
    </pages:PopupPage.Animation>
    <StackLayout VerticalOptions="Center" HorizontalOptions="Center" Padding="20, 20, 20, 20">
        <StackLayout BackgroundColor="White" Orientation="Horizontal" Padding="20, 20, 20, 20">
            
            <Label HorizontalOptions="Center" VerticalOptions="Center" x:Name="MyTextLoading"/>
        </StackLayout>
    </StackLayout>
</pages:PopupPage>`

The LoadingPopupPage.cs is simple...

So what colud it be? Maybe I should use another prerelease?

**Comment by stefan-stanca** [comment]
Have you initialized the plugin ?

**Comment by rotorgames** [comment]
@denmusic1992 See https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#initialization
