### ISSUE TITLE
Not supporting in  UWP  for Release Mode. there is exception every time 

### ISSUE THREAD

**Issue by AryanVerma** [rotorgames/Rg.Plugins.Popup#31]
I am using this plugin in UWP and it's working fine in debug mode but in release giving exception.

**Comment by rotorgames** [comment]
@AryanVerma any exception? Which version Xamarin.Forms and plugin?

**Comment by AryanVerma** [comment]
Xamarin Froms 2.3.0.49 I am using and Rg plugin version is 0.0.17

**Comment by rotorgames** [comment]
@AryanVerma write stack trace please

**Comment by AryanVerma** [comment]
everytime getting unhandled exception

**Comment by AryanVerma** [comment]
This is my animation class
  public class UserAnimation : IPopupAnimation
    {
        public void Preparing(View content, PopupPage page)
        {
            content.Opacity = 0;
        }

        public void Disposing(View content, PopupPage page)
        {

        }

        public async Task Appearing(View content, PopupPage page)
        {
            var topOffset = GetTopOffset(content, page);
            content.TranslationY = topOffset;
            content.Opacity = 1;

            await content.TranslateTo(0, 0, easing: Easing.CubicOut);
        }

        public async Task Disappearing(View content, PopupPage page)
        {
            var topOffset = GetTopOffset(content, page);

            await content.TranslateTo(0, topOffset, easing: Easing.CubicIn);
        }

        private int GetTopOffset(View content, Page page)
        {
            return (int)(content.Height + page.Height) / 2;
        }
    }

**Comment by AryanVerma** [comment]
Xaml Desgin
---------------------------
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms" 
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
                 x:Class="TallySoftShared.ClearCurrentPopup" 
                 xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"                 
                 Padding = "0, 0, 0, 0">
    <StackLayout VerticalOptions="Center" HorizontalOptions="Center" Padding = "15, 0, 15, 0" Opacity = "0">
        <Frame BackgroundColor="White">
            <StackLayout Spacing="10">
                <Image x:Name="CheckOrUnCheckImg" Source="uncheck.png" WidthRequest="24" HeightRequest="21" HorizontalOptions="Start" TranslationX="50" TranslationY="30">
                    <Image.GestureRecognizers>
                        <TapGestureRecognizer Tapped="CheckMarkTapped"  NumberOfTapsRequired="1" />
                    </Image.GestureRecognizers>
                </Image>
                <Label x:Name="ClearFileInfoLabel"  FontSize="25"
                           HorizontalOptions="StartAndExpand"
                           TranslationX="80">
                    <Label.FormattedText>
                        <FormattedString>
                            <FormattedString.Spans>
                                <Span FontAttributes="Bold"
                      ForegroundColor="Black"
                      Text="Clear the file" />
                            </FormattedString.Spans>
                        </FormattedString>
                    </Label.FormattedText>
                </Label>
                <Label FontSize="16"
               HorizontalOptions="StartAndExpand"
               VerticalOptions="StartAndExpand">
                    <Label.FormattedText>
                        <FormattedString>
                            <FormattedString.Spans>
                                <Span ForegroundColor="Gray" Text="Check to  confirm action and keep the  current file name but clear all data in the  cycle count." />
                            </FormattedString.Spans>
                        </FormattedString>
                    </Label.FormattedText>
                </Label>
                <StackLayout x:Name="btnLayout"  Margin="5"
                                 HorizontalOptions="CenterAndExpand"
                                 Orientation="Horizontal"
                                 VerticalOptions="End">
                    <Button x:Name="OKButton"
                  BackgroundColor="Silver"
                  Clicked="OnOk"
                  Font="15"
                  FontAttributes="Bold"
                  HorizontalOptions="Start"
                  Text="OK"
                  TextColor="White"
                  WidthRequest="80"
                  HeightRequest="35" IsEnabled="false"/>
                    <Button x:Name="CancelButton1"  BackgroundColor="#70B856"
                  Clicked="OnCancel"
                  Font="15"
                  FontAttributes="Bold"
                  HorizontalOptions="End"
                  Text="Cancel"
                  TextColor="White"
                  WidthRequest="80"
                  HeightRequest="35" />
                </StackLayout>
            </StackLayout>
        </Frame>
    </StackLayout>
</pages:PopupPage>

Code Side
-----------------------
 public partial class ClearCurrentPopup : PopupPage
    {
        bool imageTapped = false;       
        public ClearCurrentPopup()
        {
            InitializeComponent();
            NavigationPage.SetHasBackButton(this, false);
            NavigationPage.SetHasNavigationBar(this, false);
            Animation = new UserAnimation();
        }

		protected override void OnAppearing()
		{
			if (Device.OS == TargetPlatform.Android) {
				CheckOrUnCheckImg.TranslationX = 90;
				ClearFileInfoLabel.FontSize = 30;
				ClearFileInfoLabel.TranslationX = 120;
			}
            if (Device.OS == TargetPlatform.Windows || Device.OS == TargetPlatform.WinPhone)
            {
                OKButton.IsEnabled = false;
                if (OKButton.IsEnabled)
                {
                    btnLayout.BackgroundColor = Color.Green;
                }
                OKButton.WidthRequest = 100;
                CancelButton1.WidthRequest = 100;
                ClearFileInfoLabel.TranslationX = 130;
                CheckOrUnCheckImg.TranslationX = 100;
            }
                    
            base.OnAppearing ();
		}

		private async void OnOk(object sender, EventArgs e)
		{

            if (imageTapped == true)
            {
              
                await App.DatabaseRepo.DeleteCurrentFileRecord(App.currentFileID);
                App.dataModifiedAndSaved = false;
                App.dataModifiedAndSaveAndEnd = false;
                MainMenu.openBtn.Source = ImageSource.FromFile("open_current.png");
                //MainMenu.firstGesture.CommandParameter = "disable";
                MainMenu.openBtnGesture.CommandParameter = "enable";
                MainMenu.clearBtn.Source = ImageSource.FromFile("disableclear_current.png");
                MainMenu.clearBtnGesture.CommandParameter = "disable";
                MainMenu.fileManagerBtn.Source = ImageSource.FromFile("newbtn.png");
                MainMenu.fileManagerBtnGesture.CommandParameter = "enable";
            }

            if (Device.OS == TargetPlatform.iOS)
            {
                await PopupNavigation.PopAsync(false);
            }
            else
            {
                await PopupNavigation.PopAsync(false);
            }
            
           
		}

		private async void OnCancel(object sender, EventArgs e)
		{
            if (Device.OS == TargetPlatform.iOS)
            {
                await PopupNavigation.PopAsync(false);
            }
            else
            {
                await PopupNavigation.PopAsync(false);
            }
        }
        private async void OnClose(object sender, EventArgs e)
        {
            await PopupNavigation.PopAsync();
        }
        void CheckMarkTapped(object sender, EventArgs args)
        {
            if (imageTapped == false)
            {
                CheckOrUnCheckImg.Source = "check.png";
                imageTapped = true;
                OKButton.BackgroundColor = Color.FromHex("70B856");
                OKButton.IsEnabled = true;
            }

            else
            {
                OKButton.IsEnabled = false;
                OKButton.BackgroundColor = Color.Silver;
                CheckOrUnCheckImg.Source = "uncheck.png";
                imageTapped = false;
            }
        }        
	}

**Comment by rotorgames** [comment]
@AryanVerma I can not help you until I see the stack trace (console)

**Comment by AryanVerma** [comment]
> 
![exce](https://cloud.githubusercontent.com/assets/6337392/17328013/dff9649e-58d8-11e6-91c2-02ea7cfba06b.jpg)

**Comment by rotorgames** [comment]
@AryanVerma Sorry, 0.0 17 not support WP and UWP. Use 1.0.0-pre3

**Comment by AryanVerma** [comment]
Use 1.0.0-pre3 is supporting only in debug mode not in release

**Comment by rotorgames** [comment]
@AryanVerma Please send me solution. Zip or github

**Comment by AryanVerma** [comment]
tell me you gmail id I will share with over that

**Comment by AryanVerma** [comment]
Hope you have got complete source in zip and pls replace to clearpopup cs file with individual download

**Comment by AryanVerma** [comment]
apart from this , I have mail from gmail over .ru domain

**Comment by AryanVerma** [comment]
@rotorgames  Did you see the issue?

**Comment by AryanVerma** [comment]
Today I tried to see the respository source and compiled then publish release in window phone then Same issue is also in Rg.Plugins.Popup-1.0.0 source  I found.

**Comment by pawanvermadreamorbit** [comment]
Today I tried to see the respository source and compiled then publish release in window phone then Same issue is also in Rg.Plugins.Popup-1.0.0 source I found. UWP In debug mode working but in release not working

**Comment by pawanvermadreamorbit** [comment]
This method is giving exception
 public static Task PushAsync(PopupPage page, bool animate = true)
        {
            var task = new TaskCompletionSource<bool>();
            var parent = GetParentPage();
            page.Parent = parent;
            if (animate)
            {
                page.PreparingAnimation();
                page.ExecuteWhenAppearingOnce(async () =>
                {
                    await page.AppearingAnimation();
                    task.TrySetResult(true);
                });
            }
            BeginInvokeOnMainThreadIfNeed(() =>
            {
                DependencyService.Get<IPopupNavigation>().AddPopup(page);
            });
            _popupStack.Add(page);
            if(!animate) task.TrySetResult(true);
            return task.Task;
        }

**Comment by rotorgames** [comment]
@pawanvermadreamorbit error only on devices or emulatoe also?

**Comment by pawanvermadreamorbit** [comment]
I am not testing with emulator only over device

**Comment by pawanvermadreamorbit** [comment]
Window 10 phone

**Comment by pawanvermadreamorbit** [comment]
Demo Window phone RT source code is working  fine in debug and release However, Demo UWP is it not working of Rg.Plugins.Popup-1.0.0 in release

**Comment by rotorgames** [comment]
@pawanvermadreamorbit Please wait. I test

**Comment by pawanvermadreamorbit** [comment]
:) Thanks , Please test it, My train has stucked on this issue track.

**Comment by pawanvermadreamorbit** [comment]
Hi @rotorgames  Did test it?

**Comment by rotorgames** [comment]
@AryanVerma @pawanvermadreamorbit Do you see it?

https://forums.xamarin.com/discussion/57179/uwp-immediate-crash-in-release-mode

**Comment by pawanvermadreamorbit** [comment]
@rotorgames  no I did see it

**Comment by rotorgames** [comment]
@AryanVerma @pawanvermadreamorbit fix in 1.0.0-pre4. 

Please install 1.0.0-pre4 from nuget. And add initialize code for UWP in App.xaml.cs.

[Initialize documentation](https://github.com/rotorgames/Rg.Plugins.Popup/blob/v1.0.0/README.md#uwp)

**Comment by pawanvermadreamorbit** [comment]
ok , I try with it and let you know within 15 min

**Comment by pawanvermadreamorbit** [comment]
great , hurrrrrrrrrrrrrra :) Thanks @rotorgames  , it's working in release. by the way, why we have to pass this line of coee  in init method?

**Comment by rotorgames** [comment]
@pawanvermadreamorbit 

> If your UWP app is referencing multiple assemblies (for example third party control libraries, or your application itself is split into multiple PCLs), Xamarin.Forms may be unable to load objects from those assemblies (such as custom renderers).
> 
> This might occur when using the Compile with .NET Native tool chain which is an option for UWP apps in the Properties > Build > General window for the project.

https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/#Troubleshooting

**Comment by pawanvermadreamorbit** [comment]
ok

**Comment by rotorgames** [comment]
@AryanVerma @pawanvermadreamorbit Please. Update to 1.0.0-pre5. I add new init method.

[Doc](https://github.com/rotorgames/Rg.Plugins.Popup/tree/v1.0.0#wp-uwp)
