### ISSUE TITLE
Does it support .net standard?

### ISSUE THREAD

**Issue by JimmyPun610** [rotorgames/Rg.Plugins.Popup#313]
As Microsoft turn down PCL project, does this library support .net standard Xamarin project?

**Comment by jcesarmm** [comment]
Yes, It might be great if you update the plugin to .NET Standard! :)

**Comment by dansiegel** [comment]
@JimmyPun610 @jcesarmm it might be great if you update. This plugin has had netstandard support for a while. https://www.nuget.org/packages/Rg.Plugins.Popup/1.1.4.158-pre

**Comment by JimmyPun610** [comment]
@dansiegel Thanks. But i am now using Xamarin Form 2.4 due to Android version limitation. Does 1.1.0 or 1.0.4 support? I tried 1.0.4, it can install and use but it seems the popup always consume the whole screen in android.

**Comment by JimmyPun610** [comment]
I found out that the background color of the Popup control should not be set.
