### ISSUE TITLE
Xamarin.Forms.Xaml.XamlParseException

### ISSUE THREAD

**Issue by Nandulucky** [rotorgames/Rg.Plugins.Popup#314]
Hi,

When tap popup page I got below issue.

_**"Type Animations:UserAnimation not found in xmlns clr-namespace:TestPopUp.Animation;assembly=TestPopUp"**_

And I wrote the code like below.

<pages:PopupPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:pages="clr-namespace:DASH.Pages;assembly=DASH"
    xmlns:Animations="clr-namespace:DASH.Animation;assembly=DASH" 
    x:Class="DASH.ForceResetPasswordPage">
    <pages:PopupPage.Animation>
        <Animations:UserAnimation />
    </pages:PopupPage.Animation>
</pages:PopupPage >

Thanks
Nandu K

**Comment by dblookup** [comment]
Please make sure there is UserAnimation.cs at (DASH.Animation).
See the example below (it works perfectly):

[Demo with UserAnimation](https://github.com/rotorgames/Rg.Plugins.Popup/tree/master/src/Demo/Demo)

**Comment by Nandulucky** [comment]
you said,
xmlns:Animations="clr-namespace:DASH.Animation;assembly=DASH"
into
xmlns:Animations="clr-namespace:UserAnimation;assembly=DASH"

still not working

**Comment by Nandulucky** [comment]
And also

'INavigation' does not contain a definition for 'PushPopupAsync' and no extension method 'PushPopupAsync' accepting a first argument of type 'INavigation' could be found (are you missing a using directive or an assembly reference?) (CS1061) (DASH.iOS)

**Comment by rotorgames** [comment]
I need more information about it. It looks like you implemented `UserAnimation` incorrect. Don't be afraid to reopen this issue.
