### ISSUE TITLE
Popup initialization issue when app is initialing through one notification at background (PendingIntent)

### ISSUE THREAD

**Issue by dblookup** [rotorgames/Rg.Plugins.Popup#315]
I'm trying to use the Popup in Android however I've identified a problem that I cannot solve.
I'm initialing the popup with Rg.Plugins.Popup.Popup.Init (this, bundle) and everything works perfectly except when I activate the app through of one notification when it's in background.
After touching on the notification, the app opens throwing the exception "Unable to activate instance" at initialization Rg.Plugins.Popup.Popup.Init(this, bundle).

I created a variable to indicate that the popup is initialized in the background and prevent it from initializing again, but as expected, the error does not occur but the popup also does not work.

Anyone have any ideas how to solve this?

Thank for any help.

**Comment by rotorgames** [comment]
@dblookup Please create a simple project which will have this issues and give me.

**Comment by dblookup** [comment]
@rotorgames  the problem was not in the popup. The problem was that I was tried initial a static class through the notification pendent. I do not know why but the exception occurred at the initialization line of the popup but the popup is not problem. You can close this issues. Thank you so much for your assistance!
