### ISSUE TITLE
Getting .net standered warning and an error 'pages' doesn't exist

### ISSUE THREAD

**Issue by DevendraMaran** [rotorgames/Rg.Plugins.Popup#316]
### Description
1) Warning NU1701: Package 'Rg.Plugins.Popup 1.0.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. (NU1701) 

2) Error CS0234: The type or namespace name 'pages' does not exist in the namespace 'Xamarin.Forms' (are you missing an assembly reference?) (CS0234) 
### Steps to Reproduce

1. **Waring** occurs when I add the NuGet package in my project for each platforms.
2. **Error** occurs When I tried to build the app.
3. Is this plugin support the below-mentioned configuration version  

Xamarin.forms version 3.0.0.446417, Visual Studio (7.5.1) on mac,

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.iOS
Version: 11.10.1.178 (Visual Studio Community)
Hash: 408d3574
Branch: d15-7
Build date: 2018-05-08 18:56:30-0400

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/devmaran/Documents/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 28 rc2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by dansiegel** [comment]
The issue is simple. Update to the latest preview. 1.0.4 does not have a netstandard target.

**Comment by DevendraMaran** [comment]
when I tried to update it I am getting a message "Rg.Plugins.Popup is up to date"

**Comment by henrikweimenhog** [comment]
@DevendraMaran did you tick "show pre-release packages" in the add package dialog? or else you cant update to what dansiegel refers to as "preview"

**Comment by DevendraMaran** [comment]
@dansiegel @henrikweimenhog You both are right. The plugin is now working. Thanks
