### ISSUE TITLE
The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup'

### ISSUE THREAD

**Issue by cabauman** [rotorgames/Rg.Plugins.Popup#317]
I installed the plugin in all projects but I'm receiving this compile error when trying to call Rg.Plugins.Popup.Popup.Init(this, bundle) for Android (and for iOS). I tried versions 1.0.4. 1.0.3, 1.0.2 with the same results. The other namespaces are found.

**Comment by thejakeofink** [comment]
Found `Rg.Plugins.Popup.IOS.Popup.Init()` seems like the docs need to be updated to show the platform specific namespaces now.

**Comment by Mrgove10** [comment]
On my side I get : ![image](https://user-images.githubusercontent.com/25491408/41161046-bc182a98-6b31-11e8-981d-eb076beb9087.png)

**Comment by mahapatraprabhanjan** [comment]
I didn't find the Rg.Plugins.Popup.Droid.Popup.Init().
Popup is not available in Droid namespace.

![image](https://user-images.githubusercontent.com/40223741/41328860-f51700bc-6ee7-11e8-80e9-0b01c1da4487.png)

**Comment by acaliaro** [comment]
I think you have to install last PRE and delete all bin and obj directories

**Comment by michaelrbrown** [comment]
Same for me I can work around the iOS (and suppres warning by pragma), but Rg is not found for Droid even with the assemblies referenced.  Any ideas?

![image](https://user-images.githubusercontent.com/3219007/41422731-8daddd5c-6fc7-11e8-8ecc-f0f2cfa9fd00.png)

**Comment by bo3po** [comment]
hi. did this issue come back in the latest 2.0 version? i get the same errors as above. in android. ios works fine.

**Comment by martijn00** [comment]
@bo3po update your android target to 10

**Comment by ortegaeu** [comment]
Updated target to 10 but still PopUp cant be found on namespace Rg.Plugins.Popup for Android nor UWP. It wotks on iOS tho.

**Comment by ortegaeu** [comment]
It work change target to 10 for Android, but still cant make it work for UWP (App.xaml.cs)

**Comment by martijn00** [comment]
On uwp you need to use the newer version as well. See the readme.

**Comment by njale** [comment]
> On uwp you need to use the newer version as well. See the readme.

I done exactly as in the README and I just upgraded to the newest UWP version 2.0.0.2 from April 9 and started getting "The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?"

If I try to press "Go to the implementation" on the namespace, it gives me option to browse to the Mac or Android version. This is very weird. For iOS and Android it compiles fine. 

Edit:
Found the problem. Looking in the nuget/packages folder I noticed the UWP version was located in folder uap10.0.17763. My target version was higher, but changing my minimum build version to 10.0.17763 fixed it. I suggest you document this better in your docs.

**Comment by SteCa15** [comment]
Thanks @njale I had the same problem after I upgraded to version 2.0.0.2.  And now it works with your suggestion.

**Comment by JTOne123** [comment]
the same on UWP

**Comment by AdrianoBinhara** [comment]
Still not working, even with the latest version set on UWP

**Comment by zilimuk** [comment]
> Update to latest pre-release version and you'll find `Rg.Plugins.Popup.Popup.Init()` taking a context and a bundle:
> 
> ```cs
> Rg.Plugins.Popup.Popup.Init(this, bundle);
> ```
> 
> In my case, it is version 1.1.4.158-pre

Thank you! This served me a lot but without overloading the method just like this "Rg.Plugins.Popup.Popup.Init(this)"
