### ISSUE TITLE
Nexus 5: Popup with text field hides copy/cut control

### ISSUE THREAD

**Issue by iupchris10** [rotorgames/Rg.Plugins.Popup#32]
See the screenshots below. On Nexus phone, when text is highlighted, a copy/cut control appears at the top of the screen. I have an Rg Popup with a text field. When I try to highlight text for copy I can see that the copy/cut control is hidden underneath the Rg Popup.

1st screenshot:  Copy control clearly visible in Google Chrome
2nd screenshot: Rg Popup with copy control hidden underneath

I'm not sure if this is a Xamarin issue or Rg Popup issue, but figured I'd bring it to your attention.

![fullsizerender 8](https://cloud.githubusercontent.com/assets/5750525/17446488/872c3e40-5b17-11e6-954a-ba6de14b8c50.jpg)
![fullsizerender  #9](https://cloud.githubusercontent.com/assets/5750525/17446487/87271aaa-5b17-11e6-9cc8-da5c8fe0f1ec.jpg)

**Comment by rotorgames** [comment]
@iupchris10 Hi friend. If you need toolbar control buttons, you dont need use Rg.Plugins.Popup.

Or, you can create custom button bar for android.

**Comment by iupchris10** [comment]
I'm using a Popup here for the user to enter long text. I did not make the clipboard toolbar. It is something built into the Android OS on Nexus phones. The Popup is covering up this toolbar. I think the reason may be because the Rg Popup is being added to the Window DecorView, rather than the Activity view.

![screen shot 2016-08-05 at 4 37 14 pm](https://cloud.githubusercontent.com/assets/5750525/17449839/159e9584-5b2b-11e6-9802-0350f1128aeb.png)

**Comment by iupchris10** [comment]
The reason I am using Rg Popup is so the user can enter long text in a comment box.  I did not create the clipboard toolbar. It is built into Android on Nexus phones.

I think the issue is that the popup is added to Window.DecorView, which will basically lay overtop of everything in the app, including the clipboard toolbar.

This issue is minor. If I get some time, I may tinker with the code to see if I can come up with a fix.

**Comment by rotorgames** [comment]
@iupchris10 `Rg.Plugins.Popup` closes a full screen. That's the whole point. If you do not like it, you can use other plug-ins or write your own popup by AbsoluteLayout.

**Comment by iupchris10** [comment]
That's fine. I wasn't sure if this was intentional behavior or not. I am not trying to be critical, I like Rg Popup and am simply reporting my findings.
