### ISSUE TITLE
Page await for the popup to pop.

### ISSUE THREAD

**Issue by masiri201** [rotorgames/Rg.Plugins.Popup#329]
Is there a way to make the parent page await for the pop of the popup like a regular DisplayAlert popup?

I want to do a custom login success popup, it shows fine but the code of the page keeps running instead of awaiting for the popup to close. Is there a easy and clean way to do this without a messaging center or something like that?

**Comment by pfaucon** [comment]
you could make a task completion source in the child view and await it from the parent.  essentially create the view, in the child constructor generate the task completion source, then whenever you call a dismiss (or in the ondisappearing), set the completion source result.

**Comment by EmilAlipiev** [comment]
yes there is an issue for that. search for how to return value from popup page. Owner of the library explains it very well with some code there.

**Comment by EmilAlipiev** [comment]
https://github.com/rotorgames/Rg.Plugins.Popup/issues/14
