### ISSUE TITLE
Can't control Content margins

### ISSUE THREAD

**Issue by henrik6** [rotorgames/Rg.Plugins.Popup#33]
I'm facing the problem that I can't seem to be able to control the margin of the content (at least on iOS on iphone6 ). Basically it is too much margin, even when I set all Paddings and Margins to 0, the Content can only consume about 1/2 of the screen height and about 2/3 of the screen width, which is too narrow in many cases. And even if I set only a BoxView as the Content  with MinWidth/MinHeightRequest set to  90% of  width /height (using absolute values) the BoxView is displayed much smaller that expected/requested. Any tips ?

**Comment by rotorgames** [comment]
@henrik6 use VerticalOptions, HirizontalOptions - Fill in BoxView

**Comment by henrik6** [comment]
thanks. It works now as expected!
