### ISSUE TITLE
PushPopupPageAsync is very slow in showing a popup page, even though I use it multiple times

### ISSUE THREAD

**Issue by UnreachableCode** [rotorgames/Rg.Plugins.Popup#333]
I am using both of the stable Packages, Rg.Plugins.Popup 1.0.4 and Prism.Plugin.Popups.Unity 1.1.0. When I get a popup with a very simple content to show on screen using PushPopupPageAsync, it only slides in the background. The content itself experiences a delay when loading. Does anyone else experience this issue? Has it been fixed in any pre-release?

**Comment by rynzlery** [comment]
Same problem with PopupNavigation.PushAsync. Popup and his content are very slow (about 100-200 frames skipped on main thread) on any click/tapped event.

**Comment by rotorgames** [comment]
It is depended on your layout. If the layout is difficult it is possible to skip some frames to render and draw the layout. But it is not a problem of the plugin, Xamarin.Forms and even native platforms have a similar issue. Keep you layout light and easy and then it is fast.
