### ISSUE TITLE
Popup v1.1.4.158 -pre System.TypeLoadException

### ISSUE THREAD

**Issue by Daxton47** [rotorgames/Rg.Plugins.Popup#335]
After being unable to properly call Rg.Plugs.Popup.Popup.Forms.Init with v1.1.4; I installed the pre-release v1.1.4.158 -pre. The namespace is now working fine, but before the the app loads, it throws a System.TypeLoadException:

System.TypeLoadException: Could not resolve type with token 01000064 (from typeref, class/assembly Rg.Plugins.Popup.Popup, Rg.Plugins.Popup.Droid, Version=1.1.4.158, Culture=neutral, PublicKeyToken=null)

I'm running XF 3.1.0.583944
Any help would be appreciated, thanks!

**Comment by Dabbel** [comment]
Gettings the same error with 1.1.4.168

**Comment by rotorgames** [comment]
@Dabbel Can you give me a stack trace and create a simple project which has the same issue?

**Comment by Dabbel** [comment]
@rotorgames It looks like that this is a internal bug in Xamarin or MSBuild. After i restarted Visual Studio several times and deleted the local nuget cache everything works fine.
