### ISSUE TITLE
[Xamarin Forms] Popups stop opening after some time

### ISSUE THREAD

**Issue by Kizari** [rotorgames/Rg.Plugins.Popup#336]
Just reaching out in case anyone has an idea of why this is happening, or has experienced this before.

The issue quite simply is that after a while of app usage, sometimes the popups will stop working.

I have multiple controls that will push a popup as a prompt. All of these buttons are still responsive, but the popups no longer appear once the bug occurs. There is nothing that will make them start appearing again short of closing down the app and relaunching it.

If it helps at all, I have the latest version of Xamarin Forms, and the latest version of Rg.Plugin.Popups. This issue has occurred previously on earlier versions of Xamarin Forms. The popups are all animated, but it has also occurred when none of them were animated.

There are situations in the app where I will be pushing and popping a lot of popups in quick succession. In earlier versions of my app this was uncontrolled, but I thought I had solved it in this version by having a static helper that acquires a lock (SemaphoreSlim in this case as the pushing and popping is awaited) to do any pushing and popping in case of any conflicts.

Unfortunately I am currently unable to provide a reproduction project as I cannot consistently reproduce the issue, I just know it occurs every now and then, and even once happened during a client presentation.

**Comment by paul-charlton** [comment]
I'm also seeing this behaviour, and again it seems random.

Is there anything in the Popup namespace I can investigate to see why it's not showing?

**Comment by rotorgames** [comment]
It can be a problem if a new activity has been created but you have not initialized plugin. Then the plugin try to open a new popup using an old context (Activity) which has been destroyed.
