### ISSUE TITLE
button click fires wrong event handler

### ISSUE THREAD

**Issue by drznathou** [rotorgames/Rg.Plugins.Popup#337]
button click fires OnBackgroundClicked instead of event handler when Keyboard is shown

Plateform = IOS
Xamarin.IOS = 11.8.0.20
Xamarin.Forms = 2.5.0.280555

`<StackLayout Orientation="Horizontal" HorizontalOptions="Center">
<Label x:Name="SearchLabel" Text="blablabla" TextColor="#FF7400" FontSize="Medium" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"  HorizontalOptions="LayoutOptions.Center"/>
<Button Image="info.png" Clicked="InfoButton_Clicked" x:Name="InfoButton" BackgroundColor="White"></Button>
</StackLayout>`

`<StackLayout x:Name="InfoStack" IsVisible="False" HorizontalOptions="Center">
<Label Text="Rechercher par:" TextColor="LightGray" FontSize="Small" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"  HorizontalOptions="Start"/>
<<Label Text=" • balbla" TextColor="Black" FontSize="Small" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"  HorizontalOptions="Start"/>
<Label Text=" • balbla" TextColor="Black" FontSize="Small" HorizontalTextAlignment="Start" VerticalTextAlignment="Center"  HorizontalOptions="Start"/>
<Label Text=" • balbla" TextColor="Black" FontSize="Small" HorizontalTextAlignment="Start" VerticalTextAlignment="Center"  HorizontalOptions="Start"/>       
<Label Text=" • balbla" TextColor="Black" FontSize="Small" HorizontalTextAlignment="Start" VerticalTextAlignment="Center"  HorizontalOptions="Start"/>
</StackLayout>`

`private void InfoButton_Clicked(object sender, EventArgs e)
 {
            InfoStack.IsVisible = !InfoStack.IsVisible;
 }`

`protected override bool OnBackgroundClicked()
{
            CloseAllPopup();
            return true;
}
`

**Comment by EmilAlipiev** [comment]
this has nothing to do with this library. it is your coding mistake. either you didnt handle InputTransparacency correctly or something else. from your issue description nothing is understandable.

**Comment by apy534** [comment]
Yes, I'm also facing the same issue when we have an entry in the popup and the keyboard is showing.
The keyboard gets dismissed but the event won't trigger.
If in case the keyboard is not showing, it is working fine.

**Comment by rotorgames** [comment]
I can't see any problems also. If you still have this issue, don't be afraid to reopen it again.
