### ISSUE TITLE
Getting started page is out of date

### ISSUE THREAD

**Issue by FoggyFinder** [rotorgames/Rg.Plugins.Popup#338]
[Getting-started](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started) page is a bit out of date.

For example, the line below doesn't compile

```csharp
Rg.Plugins.Popup.Popup.Init();
```

That's obvious how to replace it, but I guess better to update this information.

**Comment by ncarandini** [comment]
Yes, the actual one is `Rg.Plugins.Popup.IOS.Popup.Init();` put the green squiggle says that `Popup.Init()` is deprecated and iOS initialization is not required in iOS project.

**Comment by FoggyFinder** [comment]
> But this happens only if you use the latest stable version (at the time of writing 1.0.4).

Thank you for point it out.

**Comment by EmilAlipiev** [comment]
please close this ticket. you can always provide a PR if you want to add more information into the documentation but just keeping an issue  as open makes other peoples live harder when others have real issues. Owner of the project has, I am sure regular work to do and not providing free service for you people. thats why it is open source and if you found something missing give a PR please. thanks.

**Comment by FoggyFinder** [comment]
@EmilAlipiev thank you for your response.

I don't see any reason for closing the issue now. As it was saying:

> this should be better explained and specified in the Getting-started page, at least until a stable version v1.1.x became available.

---

Regarding making PR with edit of the page. By default only collaborators have permission to edit wiki . 
[About GitHub Wikis](https://help.github.com/articles/about-github-wikis/)

**Comment by nebula2** [comment]
I am having this issue too. For me it is not obvious how to fix this. Can someone tell me Please?

**Comment by FoggyFinder** [comment]
> I am having this issue too. For me it is not obvious how to fix this. 

@nebula2  I suggest you to use new version of package (it provides more useful exception message and so on) instead.

> Please?

I don't remember exactly but something like this

```csharp
Xamarin.Forms.Forms.Init(e, Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies());
```

**Comment by nebula2** [comment]
@FoggyFinder Thank you. Updating to prerelease indeed solved this issue for me :+1:

**Comment by rotorgames** [comment]
Today the plugin beings in the stable public version and the documentation is agreed with the last public release. I close this issue.
