### ISSUE TITLE
how to pop the popup using mvvm?

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#34]
Is it possible to close/pop the popup using mvvm binding? Basically I have a button in my popup and when user clicks the button, I am doing some operations and i would like to pop the popup once all finished but I couldnt figure out how to call             PopupNavigation.PopAsync();  method.

One other question, If I navigate to page from popup, is it automatically popped from the modal stack or I have to pop it?

**Comment by rotorgames** [comment]
> but I couldnt figure out how to call PopupNavigation.PopAsync(); method.

What exactly does not work for you?

> One other question, If I navigate to page from popup, is it automatically popped from the modal stack or I have to pop it?

Before opening any page (except popup) you must call `Popup Navigation.PopAsync ();` or `Navigation.PopPopupAsync ();`

**Comment by EmilAlipiev** [comment]
Sorry my bad. this is actually working fine. thank you :)
