### ISSUE TITLE
Can we use this library as userdialog /activity indicator?

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#341]
Hi @rotorgames 

I was wondering what do you think to use this library as a userdialog or activity indicator? I recently created a simple activity indicator popup using this library and works fine for me. It is even better than acr.userdialogs package because it doesnt run if function or code is asny-awaited. but using rg popup, it works in any case. I simply
 raise popup with activity indicator and once work is finished popall. what do you think about this? do you think it might be a bad practice? 

```
        var page = new LoadingPage();
                await _navigation.PushPopupAsync(page);

 ---do something

         await _navigation.PopAllPopupAsync();
```

**Comment by rotorgames** [comment]
I think that it is the good solution because the popup page always is on top before other pages.

**Comment by EmilAlipiev** [comment]
how do you mean by abstraction methods? you mean using the interfaces, I should go the native level?

**Comment by rotorgames** [comment]
@EmilAlipiev I think you should create ShowLoading and HideLoading and create, push and pop a popup page in them.
