### ISSUE TITLE
Popup Page's OnBackButtonPressed not being called when tapping back button.

### ISSUE THREAD

**Issue by LeoJHarris** [rotorgames/Rg.Plugins.Popup#345]
Calling PopPopupAsync() is closing my app when in fact it should be going back to the previous page that called the pushpopupasync... seems like a bug from the new version.

Page A (Root page) calls:

`Navigation.PushPopupAsync(new ConfigPage())`

Then having overridden the back button on the ConfigPage I pop the popup:

 `
protected override bool OnBackButtonPressed()
        {
            Navigation.PopPopupAsync();
            return base.OnBackButtonPressed();
        }
`
App is getting closed, should return me to the root page.

**Comment by pinoelefante** [comment]
It seems the right behavior. You are popping the popup and then asking to go back. You should return true instead of base. OnBackButtonPressed

**Comment by LeoJHarris** [comment]
Sorry your 100% correct regarding the base method being invoked.. That being said I remove it to look like this:

`  protected override bool OnBackButtonPressed()
        {
            Navigation.PopPopupAsync();
            return true;
        }`

Simple enough, however still closing the app.

I put a break point in OnBackButtonPressed() of the root page of the app that is calling Navigation.PushPopupAsync() and then I hit the device back button in the popup page and that overridden back button function is being called in the root page and hence closes the app... is this the expected behavior? The OnBackButtonPressed() in the popup page is not being called

**Comment by pinoelefante** [comment]
are you using Rg.Plugins.Popup.Contracts.IPopupNavigation?

`Rg.Plugins.Popup.Contracts.IPopupNavigation popupNavigation = PopupNavigation.Instance;
popupNavigation.PopAsync(animate);`

**Comment by LeoJHarris** [comment]
Just did and still closing the app

using:

` protected override bool OnBackButtonPressed()
        {
            Device.BeginInvokeOnMainThread(async () =>
            {
                Rg.Plugins.Popup.Contracts.IPopupNavigation popupNavigation = PopupNavigation.Instance; await popupNavigation.PopAsync(true);
            });

            return true;
        }`

**Comment by rotorgames** [comment]
@LeoJHarris See https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#android-back-button
