### ISSUE TITLE
Version 1.1.4 is built with Xamarin.Forms 3.0 but nuspec lists dependency on 2.5.0

### ISSUE THREAD

**Issue by jcmanke** [rotorgames/Rg.Plugins.Popup#347]
May cause issues with anyone still using Xamarin.Forms 2.5.0 or 2.5.1 who takes the latest update.

**Comment by rotorgames** [comment]
@jcmanke Do you have specific problem or it is only your thoughts? I have tested 1.1.4 with 2.5 and 3.0 the version works fine.

**Comment by rotorgames** [comment]
I don't see any problems to support Xamarin.Forms 2.5. I tested the plugin with 2.5 and 3.x and the one works fine.
