### ISSUE TITLE
MoveAnimation from a specific location

### ISSUE THREAD

**Issue by AlessandroDelSole** [rotorgames/Rg.Plugins.Popup#351]
I have tried the MoveAnimation object to get a left-to-right popup entrance with navigation, and it works.
However, the popup enters from the left side of the screen, but if you use the PopupPage to build a modal dialog, it would be preferable to have it enter from the left of the modal itself (which I get using Margin), not the side of the screen.

Is it possible to achieve this? Thanks!

**Comment by rotorgames** [comment]
@AlessandroDelSole You can implement your own animation for it. Read more information in [the animation documentation](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Animations).
