### ISSUE TITLE
Popup flickers when trying to Focus an entry by code on iOS 11 and above.

### ISSUE THREAD

**Issue by Omarkth** [rotorgames/Rg.Plugins.Popup#352]
Place a button on your page with the following click handler, and run the app. 
```
        private async void Button_Clicked(object sender, EventArgs e)
        {
            var entry = new Entry();

            var popup = new PopupPage()
            {
                Padding = 20,
                Content = new StackLayout()
                {
                    BackgroundColor = Color.LightBlue,
                    Padding = 10,
                    Children = {
                            new Button{ Text = "Focus", Command = new Command(() => entry.Focus()) },
                            entry
                        }
                }
            };

            await PopupNavigation.Instance.PushAsync(popup);
        }
```
When you tap the button, the popup will appear normally, now when you tap the "Focus" button inside the popup to focus the entry, the popup will flickers before the entry is actually focused and the keyboard is shown, check the GIF below.
![rgpopup](https://user-images.githubusercontent.com/822615/43831481-f510875e-9b0c-11e8-8a61-3c1b822706f0.gif)
This only happens once on each app run, and then it's back to normal.

In my real world scenario, I need to focus the entry immediately after showing the popup using:
`popup.Appearing += async (s, e) => { await Task.Delay(200); entry.Focus(); };`
But in my example above, I used a button to better show the problem.

**Comment by rotorgames** [comment]
@Omarkth I can't reproduce this issue. Can you create a simple project which will have this issue and upload on GitHub for me? Also, try to update the plugin to the last stable version before.

**Comment by Omarkth** [comment]
Thank you @rotorgames, I can confirm that this issue is fixed now without updating the plugin, only with after updating the Xamarin.Forms version to the latest (3.0.0.561731 -> 3.4.0.1029999).

**Comment by rotorgames** [comment]
@Omarkth Nice to hear it. Good luck.
