### ISSUE TITLE
Issue with pop popup pages on back button

### ISSUE THREAD

**Issue by denmusic1992** [rotorgames/Rg.Plugins.Popup#356]
Hello!

When I click hardware back button with opened popup page, the popup page closed and the contentpage closed too. But I need to close only popuppage firstly. What should i do?

I've updated the Nuget package and did all that was written in [here](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Migration-from-v1.0.x-to-v1.1.x) and [here](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#android-back-button).

**Comment by denmusic1992** [comment]
@rotorgames Ok, that worked, thank you!
And what about if i don't want to close popup on hardware back button press?

**Comment by denmusic1992** [comment]
@rotorgames Sorry, lame question, already found an answer :)

**Comment by dalton5** [comment]
Hi,

"And what about if i don't want to close popup on hardware back button press?"

How do you do it please?

**Comment by LuckyDucko** [comment]
By default, it shouldn't work I believe 
https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#android-back-button

However, these may help

```csharp
        protected override bool OnBackButtonPressed()
        {
            return base.OnBackButtonPressed(); //Normal Behaviour
        }

        protected override bool OnBackgroundClicked()
        {
            return base.OnBackgroundClicked(); // Normal Behaviour
        }
```csharp
