### ISSUE TITLE
Issue with await Navigator.PushPopupAsync 

### ISSUE THREAD

**Issue by wpanduka** [rotorgames/Rg.Plugins.Popup#359]
in my project i use dependency injection and i use as below 
```
_popup = new ItemNotePopup();
_popup.AddonsSelected += OnAddonsSelected;
await Navigator.PushPopupAsync(_popup, true);
```
but it gives an error in navigating method of PushPopupAsync, help will be highly appreciated , thanks

**Comment by pfaucon** [comment]
maybe you can provide more information? What is ItemNotePopup (do you have the declaration for it?).  Also I'm using PopupNavigation.Instance.PushAsync, perhaps you could try that instead?

**Comment by wpanduka** [comment]
Hi, Christophe , Thank you so much for the support i have got it solved , because i have to go through the vewmodel of popuppage and ( not passing parameters , so for example as below 

 ```
_popup = new ItemNotePopup();
_popup.AddonsSelected += OnAddonsSelected;
await Navigator.PushPopupAsync<ItemNoteViewModel>();
```

**Comment by pfaucon** [comment]
That's awesome! Maybe you can close the issue then?
