### ISSUE TITLE
Feature Request: Ability to swipe to close popup

### ISSUE THREAD

**Issue by eman1986** [rotorgames/Rg.Plugins.Popup#363]
It would be great if there was a way to swipe the modal away.

**Comment by rotorgames** [comment]
@eman1986 You should implement this behavior yourself. I'm not going to add this one to the roadmap soon. Thanks for understanding.

**Comment by JimmyPun610** [comment]
It is a bit late but I just made a behaviour on it which is for swipe down to close
Hope it could help anyone who are doing this.

https://gist.github.com/JimmyPun610/6d04f3ac59c0f1b1f5520d50f6d9714f

**Comment by eman1986** [comment]
I've since went to xamarin native but hope it helps someone else who wants this
