### ISSUE TITLE
App crashes on Android 7.0 Moto G4 and LGE LG-H872 device

### ISSUE THREAD

**Issue by Deba22** [rotorgames/Rg.Plugins.Popup#364]
I have created an app.I have used the Rg.Plugins.Popup plugin from nuget package manager.When I try to open the popup it crashes on my Moto G4 and LGE LG-H872 Android device.I am opening the popup using the follo. code
```
                    NavigationParameters oNavParams = new NavigationParameters();
                    oNavParams.Add("Mode", "MainPageLocation");
                    oNavParams.Add("selectedItem", Value);
                    await _navigationService.NavigateAsync("MyrgModal", oNavParams);
```
After opening the popup it just gets stuck and crashes.I am not able to find the reason of the crash.It seems to be working on other versions of Android OS.

Details:
Rg.Plugins.Popup-1.1.3.73-pre
Xamarin.Forms-2.5.0.280555
Android OS-7.0
Device Model-Moto G4 and LGE LG-H872

**Comment by Deba22** [comment]
I Updated the Rg.Plugins.Popup plugin from Nuget Manager to latest stable version 1.1.4.168.The debug version of my app seems to be working on Android and iOS devices.But the release version of the app crashes on Android devices.
Please help me resolve this issue

**Comment by taublast** [comment]
Have you added the nuget to every native project, and not only to shared forms project? Release crashes usually when you have issues with linking dependencies that are stripped from release and you might be crashing due to wrong thread for animated stuff: try move some code to: 

            Device.BeginInvokeOnMainThread(() =>
            {
                // Update the UI here
                // might want to use try-catch too for animations
            });

**Comment by taublast** [comment]
Also you might want to disable popup and page transitions animations on lower android versions, what i do usually.

**Comment by Deba22** [comment]
OK.Yes it has been added to my PCL, Droid and iOS project.I will try pushing the modal on main thread.
How do I disable page and popup transitions?

**Comment by Deba22** [comment]
I was able to get it working.I created a new project from scratch and updated the Rg.Plugins.Popup to 1.1.4.168.Instead of using **pages:PopupPage**  I used **popup:PopupPage** in my XAML.
This is how my XAML looks:
```
<?xml version="1.0" encoding="utf-8" ?>
<popup:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:popup="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             xmlns:local="clr-namespace:MyApp"
             prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="MyApp.Views.PopupBox">
<StackLayout VerticalOptions="Center" HorizontalOptions="Center">
                    <StackLayout Orientation="Vertical" HeightRequest="200" WidthRequest="300" BackgroundColor="White">
                        <ListView x:Name="sampleList">
                        </ListView>
                    </StackLayout>
</StackLayout>
</popup:PopupPage>
```

Now it seems to working in Release mode too.Thank you for the help

**Comment by LuisDev99** [comment]
@Deba22  i fix the problem by just putting Rg.Plugins.Popup.Popup.Init(this, bundle); in MainActivity in the android project (In previous version, i didnt have the need to put it but i guess its needed now). I discover that putting pages:PopupPage and the one you suggested which is popup:PopupPage, both do the job.
