### ISSUE TITLE
Starting On Location of Floating Action Button

### ISSUE THREAD

**Issue by Abraxelx** [rotorgames/Rg.Plugins.Popup#369]
Hello I'm so sorry for disturbing. I have an example, i want to do same animation. I was already put my FAB but cannot set the setting of Animation to Popup. I will left .gif here please anybody can help me? Thats so important for me...
 I didnt see anything in documentation about starting popup from an object's location (x,y). I want to know and getting some help if possible. Thanks.

[gifImage](https://github.com/gowong/material-sheet-fab/blob/master/art/bgmonitor.gif)

**Comment by rotorgames** [comment]
@Abraxelx You have to implement your own animation for it. You can find how to do it in [the animation documentation](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Animations)
