### ISSUE TITLE
Displaying a popup page on ios 10 simulator when no on screen keyboard gives strange sizing

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#37]
On ios 10 simulator the on screen keyboard is not visible (because it uses the macs keyboard)

This will also be true for any tablet with a bluetooth keyboard.

1. open a popup page on the simulator containing an Entry control
2. click the entry control, the popup page will resize to allow room for the on screen keyboard, but the onscreen keyboard doesnt exist as we are using the mac or bluetooth keyboard

**Comment by rotorgames** [comment]
@JKennedy24 Hi friend. I can't repeat your problem. Make screenshot and show it for me please.

**Comment by JKennedy24** [comment]
@rotorgames  Hi, I have attached a screenshot below 
<img width="777" alt="screen shot 2016-10-04 at 08 45 39" src="https://cloud.githubusercontent.com/assets/9284438/19068964/9b41b1c4-8a1c-11e6-8f44-d7a22d965049.png">

I am using the IPad air 2 simulator running ios 10 and the Popup Page Plugin... 1.0.0-pre1 version of this package from nuget.

What the screen shot shows is on the right a popup page containing a "SearchBox" and a "list" of customers.
When I click the "SearchBox" the popup page resizes to allow room for the keyboard, showing the "ListView" which is on the page below.

I can't upgrade to pre5 because the "AnimationName" property seems to have dissapeared off the "popup page"

**Comment by rotorgames** [comment]
@JKennedy24 

> I can't upgrade to pre5 because the "AnimationName" property seems to have dissapeared off the "popup page"

1.0.0-pre5 and later is used [new animations](https://github.com/rotorgames/Rg.Plugins.Popup/blob/v1.0.0/README.md#animations). 

> When I click the "SearchBox" the popup page resizes to allow room for the keyboard, showing the "ListView" which is on the page below.

This is only in simulator or real device has also this problem?

I tested in simulator with hardware keyboard and I don't have this problem. Please, say me, how you got this problem?

**Comment by JKennedy24** [comment]
@rotorgames I havent been able to test it on a real device with a bluetooth keyboard so only on a simulator with hardware keyboard.

This is my popup page:

```
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:busyindicator="clr-namespace:Syncfusion.SfBusyIndicator.XForms;assembly=Syncfusion.SfBusyIndicator.XForms"
             x:Class="MyProject.SideTrayPage"
             AnimationName="MoveRightLeft">
  <Grid RowSpacing="0" ColumnSpacing="0">
    <Grid.ColumnDefinitions>
      <ColumnDefinition/>
      <ColumnDefinition x:Name="TrayColumn" />
    </Grid.ColumnDefinitions>
    <Grid Grid.Column="0"  x:Name="ClickGrid"/>   
    <Grid Grid.Column="1" RowSpacing="0" ColumnSpacing="0" Style="{DynamicResource DefaultGridStyle}">
      <Grid Padding="10" Style="{DynamicResource ContentGridStyle}">
        <Grid x:Name="ContentGrid"/>
      </Grid>
    </Grid>
  </Grid>
</pages:PopupPage>
```

and your SideTray content is in the Grid named "ContentGrid"

this may be a Xamarin.Forms issue if it is not a popup page issue

**Comment by rotorgames** [comment]
@JKennedy24 Sorry, I don't have bluetooth keyboard, How I can tested in simulator?

**Comment by JKennedy24** [comment]
@rotorgames I just launched the simulator and clicked an entry box. It must be something to do with

this method: https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/Src/Rg.Plugins.Popup.IOS/Renderers/PopupPageRenderer.cs#L83
 
I'd imagine, either Xamarin.Forms is sending a Keyboard notification eventhough the keyboard is not being displayed, probably needs some extra checks to see if the keyboard is actually displayed or whether the notification is a false positive

**Comment by rotorgames** [comment]
@JKennedy24 Hmm. When I clicked on entry I have keyboard on simulator but if I disabled hardware keyboard than Popup is not resized. 

Maybe your problem only in simulator and in real devices is not exist?

**Comment by JKennedy24** [comment]
@rotorgames you could be right, the problem may only be on a simulator. I will have to get myself a bluetooth keyboard and test it.

I will close this bug for now and when I have more time to investigate I will have a look and submit a pull request if I find a problem.

Thanks

**Comment by rotorgames** [comment]
@JKennedy24 Tnx
