### ISSUE TITLE
Close Button (image) is behind frame.

### ISSUE THREAD

**Issue by marcelocferdeveloper** [rotorgames/Rg.Plugins.Popup#370]
I copy and past your xaml, but my icon X to close the popup is not in front of the White frame...

**Comment by michelzsiqueira** [comment]
I have the same problem.

**Comment by PaoloLeva** [comment]
Same screenshot for Android:
![screenshot_1538298003](https://user-images.githubusercontent.com/11208831/46255671-00adc600-c4a0-11e8-93d1-d0cfc7fea020.png)

**Comment by chrisfoulds** [comment]
I see it, but it's behind - some kind of behavioural change in xamarin forms

**Comment by chrisfoulds** [comment]
Fixed it with advice from here , it's a Xamarin forms bug - for now I have just turned the shadow off on the frame view. https://github.com/xamarin/Xamarin.Forms/issues/1508
