### ISSUE TITLE
After upgrade Xamarin Forms 3.3.0 gave a bug

### ISSUE THREAD

**Issue by michelzsiqueira** [rotorgames/Rg.Plugins.Popup#371]
After upgrading xamarin forms to version 3.3.0 the Rg.Plugins.Popup package stopped working.

**Comment by tlhintoq** [comment]
> 
> 
> After upgrading xamarin forms to version 3.3.0 the Rg.Plugins.Popup package stopped working.
You might consider linking that report to Xamarin while 3.3. is still pre-release.  They are more likely to look into it before it is finalized as stable..  They do have a responsibility to not break pre-existing working code.

**Comment by michelzsiqueira** [comment]
right

**Comment by MHDuke** [comment]
> After upgrading xamarin forms to version 3.3.0 the Rg.Plugins.Popup package stopped working.

it's working alright

**Comment by rotorgames** [comment]
@michelzsiqueira How does it works now? Do I need to review this issues?

**Comment by michelzsiqueira** [comment]
yes solved
