### ISSUE TITLE
Exception No constructor found for Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer

### ISSUE THREAD

**Issue by AmitManchanda** [rotorgames/Rg.Plugins.Popup#372]
I am getting this issue on production for Android device with OS version **Android 7.1.1**

Stack Trace:

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
  --- End of managed Java.Lang.Error stack trace ---
java.lang.Error: Java callstack:
at md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.n_onWindowVisibilityChanged(Native Method)
at md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.onWindowVisibilityChanged(PopupPageRenderer.java:74)\n\tat android.view.View.dispatchWindowVisibilityChanged(View.java:11280)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1293)
at com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged(DecorView.java:461)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1877)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7296) 
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930) 
at android.view.Choreographer.doCallbacks(Choreographer.java:705) 
at android.view.Choreographer.doFrame(Choreographer.java:640)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6823)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by rotorgames** [comment]
@AmitManchanda How can I reproduce it?

**Comment by xleon** [comment]
Found this very same issue, though I have a bigger stacktrace.
You can reproduce it by opening a popup, leave it there and then put the app in the background for a while. Then resume the app and BOOM.

```
Message: Unable to activate instance of type Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer from native handle 0xffbc234c (key_handle 0xc60b047).
Java.Interop.TypeManager.CreateInstance(System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0
Java.Lang.Object.GetObject(System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0
Java.Lang.Object._GetObject[T](System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0
Java.Lang.Object.GetObject[T](System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0
Java.Lang.Object.GetObject[T](System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0
Android.Views.View.n_OnWindowVisibilityChanged_I(System.IntPtr jnienv, System.IntPtr native__this, System.Int32 native_visibility) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0

Message: No constructor found for Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
Java.Interop.TypeManager.CreateProxy(System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0
Java.Interop.TypeManager.CreateInstance(System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) in <e8bbdb36e88f424cb94e3c22a74e7e49>:0

Message: Exception of type 'Java.Interop.JavaLocationException' was thrown.
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.n_onWindowVisibilityChanged(Native Method):null
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.onWindowVisibilityChanged in PopupPageRenderer.java:74
android.view.View.dispatchWindowVisibilityChanged in View.java:12902
android.view.ViewGroup.dispatchWindowVisibilityChanged in ViewGroup.java:1480
android.view.ViewGroup.dispatchWindowVisibilityChanged in ViewGroup.java:1484
com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged in DecorView.java:3188
android.view.ViewRootImpl.performTraversals in ViewRootImpl.java:2090
android.view.ViewRootImpl.doTraversal in ViewRootImpl.java:1779
android.view.ViewRootImpl$TraversalRunnable.run in ViewRootImpl.java:7810
android.view.Choreographer$CallbackRecord.run in Choreographer.java:911
android.view.Choreographer.doCallbacks in Choreographer.java:723
android.view.Choreographer.doFrame in Choreographer.java:658
android.view.Choreographer$FrameDisplayEventReceiver.run in Choreographer.java:897
android.os.Handler.handleCallback in Handler.java:789
android.os.Handler.dispatchMessage in Handler.java:98
android.os.Looper.loop in Looper.java:164
android.app.ActivityThread.main in ActivityThread.java:6938
java.lang.reflect.Method.invoke(Native Method):null
com.android.internal.os.Zygote$MethodAndArgsCaller.run in Zygote.java:327
com.android.internal.os.ZygoteInit.main in ZygoteInit.java:1374
```

**Comment by rotorgames** [comment]
@xleon Can you create a simple project which reproduces this issue, upload it to GitHub and give me? Or give me more information about steps how to reproduce it.

**Comment by xleon** [comment]
yep, I´ll try that

**Comment by boubkermasaou** [comment]
@rotorgames i am getting the same stack trace on production for some Android devices (OS 7.1.1, 8.0.0 and 8.1.0).
Is there any news or solution for that issue?

**Comment by devopsone** [comment]
Hi, i have the same problem any news on this?

**Comment by wtheronjones** [comment]
Here's another version of this stack trace in case that's helpful.   
From version 1.1.5.180 of reg.plugins.popup.
Android 6.0 device (Motorola Moto G4 Play).

Got this from a crash report when submitting to the Google Play Store.

System.NotSupportedException: Unable to activate instance of type Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer from native handle 0x100019 (key_handle 0xd0e6bcb). 
 ---> System.MissingMethodException: No constructor found for Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) 
 ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
 --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <a98db510961b43d885d52e3608900fc3>:0 
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <a98db510961b43d885d52e3608900fc3>:0 
   --- End of inner exception stack trace ---
Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <a98db510961b43d885d52e3608900fc3>:0 
 at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <a98db510961b43d885d52e3608900fc3>:0 
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <a98db510961b43d885d52e3608900fc3>:0 
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <a98db510961b43d885d52e3608900fc3>:0 
  at Android.Views.ViewGroup.GetChildAt (System.Int32 index) [0x00036] in <a98db510961b43d885d52e3608900fc3>:0 
at Xamarin.Forms.Platform.Android.PlatformRenderer.OnMeasure (System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00024] in <1f1ac5a50b9e4d3eae81420e31a86a99>:0 
 at Android.Views.View.n_OnMeasure_II (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00009] in <a98db510961b43d885d52e3608900fc3>:0 
  at (wrapper dynamic-method) System.Object.26(intptr,intptr,int,int)

**Comment by xleon** [comment]
Sorry I didn´t have time to create a sample project, but the stack trace seem pretty obvious. 

`PopupPageRenderer` needs this constructor overload:

    public PopupPageRenderer(IntPtr javaReference, Android.Runtime.JniHandleOwnership transfer) :
            base(javaReference, transfer) { }

**Comment by WilliamWatterson86** [comment]
Hi, I have the same issue.  My stack trace from App Center is:

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.n_onWindowVisibilityChanged(Native Method)
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.onWindowVisibilityChanged(PopupPageRenderer.java:74)
android.view.View.dispatchWindowVisibilityChanged(View.java:10454)
android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1325)

**Comment by wtheronjones** [comment]
@rotorgames 
So I think I found a fix for my scenario.   "HasSystemPadding="False" makes my problem go away.
Basically, if you click on the gap provided by the sytem padding, you are clicking on the background, and that background click causes the exception/crash.

**Comment by rotorgames** [comment]
@wtheronjones Are you sure? It looks like a memory problem. I suppose Android removes `PopupPageRenderer` from memory but when an app tries to reload `PopupPageRenderer` the app can't do it because `PopupPageRenderer` has no `System.IntPtr, Android.Runtime.JniHandleOwnership` parameters.

**Comment by wtheronjones** [comment]
@rotorgames yessir, I do believe it's the case. I can reproduce the crash when HasSystemPadding is true(the default), and I click on the "white space" left by the padding at the top of the screen, but just on Android. 

Can't you just add the constructors it's complaining about?

**Comment by rotorgames** [comment]
@wtheronjones I can, but if I add a constructor it can hide a real problem but not resolve it. Could you create a simple project where I can replicate this issue?

**Comment by xleon** [comment]
I tried to reproduce the issue but I couldn´t do it. At least on my simulator or my device. However I see the crash at Raygun reports for a significant amount of users.

**Comment by MysterDru** [comment]
@wtheronjones / @xleon I've seen this exception most when the xamarin forms application class is a singleton instance rather than being recreated every time the Activity's OnCreate is called.

@rotorgames is correct, it is a memory leak issue with your applications rather than the popup library. Adding that constructor is not the fix to this problem. If you are seeing this crash it is because something in your code is holding onto renderer classes after your activities have been recycled. As a result, when xamarin.forms tries to reload the renderers for a view it uses an existing c# instance. However, that underlying java instance has been disposed by the OS.

Refer to this for more info: https://stackoverflow.com/a/10603714

Source -- i had this same exception occur in 2 different applications that I maintain in the last 6 months.

**Comment by xleon** [comment]
@MysterDru it makes sense that something in my code may be leaking. 
However I always create a new application class on Android´s `OnCreate`. 
Thanks, with that info I can now dig a bit more to find the issue.

**Comment by rotorgames** [comment]
@MysterDru Thank you for a detailed explanation. 

@AmitManchanda @xleon I tried to replicate this issue but I couldn't. I think something in your code can keep a PopupPageRenderer in memory but I'm not sure. Anyway, try to use the last version of the plugin from Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99. It may fix a lot of issues you have.

**Comment by xleon** [comment]
Just for reference. I finally fixed my issue. It was indeed a memory leak.
We initialise XF at many activities (we use Native Forms) and I was subscribing to the event `Forms.ViewInitialized` but never unsubscribing. Once I fixed that part, `No constructor found for Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer` disappeared.

**Comment by darshanio** [comment]
@rotorgames @xleon I think just adding an empty constructor would solve the problem.

https://docs.microsoft.com/en-us/xamarin/android/internals/architecture#Premature_Dispose()_Calls

I don't know how I replicate this one, but seems that I can see a few crash happening because of this in MS AppCenter.

**Comment by Srikanth540-L** [comment]
@xleon  We have same code where we are using Forms.ViewInitialized but removed the event as it is not required for us but even after that we are seeing this crash and we two other events which we are subcribing AppDomain.CurrentDomain.UnhandledException += OnUnhandledException; and TaskScheduler.UnobservedTaskException += OnUnobservedTaskException; in the OnCreate which we are not unsubcribing ,  we would like to know your view if these may cause the crash or not?

**Comment by xleon** [comment]
That could be an issue. Actually you don't need to subscribe to those events within the context of an android Activity, and certainly you only need to do it once per application life-cycle. 
Good places for that: AppDelegate and AndroidApplication
