### ISSUE TITLE
RgPopupPlatformRenderer: is already presenting 

### ISSUE THREAD

**Issue by jveltd** [rotorgames/Rg.Plugins.Popup#373]
Since upgrading to 1.1.4.168 a button on a pop-up to an send email no longer works and results in the following error on iOS:

Warning: Attempt to present <MFMailComposeViewController: 0x10bc8f800>  on <RgPopupPlatformRenderer: 0x11093f8f0> which is already presenting <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x110928480>

I've added this work-around in my code to get things working again...

```
            var window = UIApplication.SharedApplication.KeyWindow;
            var vc = window.RootViewController;
            while (vc.PresentedViewController != null)
            {
                vc = vc.PresentedViewController;
            }

            vc.PresentViewController(controller, true, null);

```

Previous the code was...

`UIApplication.SharedApplication.KeyWindow.RootViewController.PresentViewController(controller, true, null);`

**Comment by rotorgames** [comment]
@jveltd Can you create a simple project where I can reproduce this issie?

**Comment by jangenvher23** [comment]
> Since upgrading to 1.1.4.168 a button on a pop-up to an send email no longer works and results in the following error on iOS:
> 
> Warning: Attempt to present <MFMailComposeViewController: 0x10bc8f800> on <RgPopupPlatformRenderer: 0x11093f8f0> which is already presenting <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x110928480>
> 
> I've added this work-around in my code to get things working again...
> 
> ```
>             var window = UIApplication.SharedApplication.KeyWindow;
>             var vc = window.RootViewController;
>             while (vc.PresentedViewController != null)
>             {
>                 vc = vc.PresentedViewController;
>             }
> 
>             vc.PresentViewController(controller, true, null);
> ```
> 
> Previous the code was...
> 
> `UIApplication.SharedApplication.KeyWindow.RootViewController.PresentViewController(controller, true, null);`

Where did you add this new code? I added this on AppDelegate and the app is automatically closing after launch
