### ISSUE TITLE
How to use PopupNavigation.Instance return bool

### ISSUE THREAD

**Issue by bobbydharrell** [rotorgames/Rg.Plugins.Popup#374]
**IPopupInstance:**
`using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Rg.Plugins.Popup.Pages;

namespace Rg.Plugins.Popup.Contracts
{
    public interface IPopupNavigation
    {
        //List of PopupPages which are in the screen
        IReadOnlyList<PopupPage> PopupStack { get; }

        //Open a PopupPage
        Task<bool> PushAsync(PopupPage page, bool animate = true);

        //Close the last PopupPage in the PopupStck
        Task<bool> PopAsync(bool animate = true);

        //Close all PopupPages in the PopupStack
        Task PopAllAsync(bool animate = true);

        //Close a specific PopupPage in the PopupStack
        Task RemovePageAsync(PopupPage page, bool animate = true);
    }
}`

**Calling Method:**
`bool result = Rg.Plugins.Popup.Services.PopupNavigation.Instance.PushAsync(new PopupControl(message, title, okBtn, exception, showSupport, canCancel));`

**Popup CS File:**
`using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using My.Resources;
using Xamarin.Forms;

namespace My.Controls
{
    public partial class PopupControl : Rg.Plugins.Popup.Pages.PopupPage
    {

        public PopupControl(string message = "", string title = "", string okText = "", Exception exception = null, bool showSupport = false, bool canCancel = false)
        {
            InitializeComponent();

            if (String.IsNullOrWhiteSpace(title))
            {
                title = Strings.error;
            }

            if (String.IsNullOrWhiteSpace(okText))
            {
                okText = Strings.ok;
            }

            popupAdditionalDetails.GestureRecognizers.Add(new TapGestureRecognizer
            {
                Command = new Command(() => AdditionalDetailsClicked()),
            });

            popupTitle.Text = title;
            popupMessage.Text = message;
            btnOk.Text = okText;
            btnClose.Text = okText;
            btnCancel.Text = Strings.cancel;

            if (showSupport) { SupportControls.IsVisible = true; }
            if (canCancel) { hasCancel.IsVisible = true; btnClose.IsVisible = false; }

            if (exception != null)
            {
                popupHiddenMessage.Text = String.IsNullOrWhiteSpace(exception.Message) ? exception.GetBaseException().Message : exception.Message;
                popupAdditionalDetails.Text = "(error: " + exception.HResult.ToString() + ")";
            }

        }

        int tapCount = 0;
        void AdditionalDetailsClicked()
        {
            tapCount++;
            if (tapCount >= 5)
            {
                if (SupportControls.IsVisible)
                {
                    SupportControls.IsVisible = false;
                    popupHiddenMessage.IsVisible = true;
                    tapCount = 0;
                }
                else
                {
                    SupportControls.IsVisible = true;
                    popupHiddenMessage.IsVisible = false;
                    tapCount = 0;
                }
            }
        }

        void Ok_Clicked(object sender, System.EventArgs e) // Needs to return a true
        {
            Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAsync(); // Close the Dialog
            //_tcs?.SetResult(true);
        }

        void Cancel_Clicked(object sender, System.EventArgs e) // Needs to return a false
        {
            Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAsync(); // Close the Dialog
            //_tcs?.SetResult(false);
        }

        //Obsolete - Doesnt work anyways
        //TaskCompletionSource<bool> _tcs = null;
        //public async Task<bool> Show()
        //{
        //    _tcs = new TaskCompletionSource<bool>();
        //    await Rg.Plugins.Popup.Services.PopupNavigation.PushAsync(this);
        //    return await _tcs.Task;
        //}

        void Support_Email_Clicked(object sender, System.EventArgs e)
        {
            
        }

        void Support_Phone_US_Clicked(object sender, System.EventArgs e)
        {

        }

        void Support_Phone_UK_Clicked(object sender, System.EventArgs e)
        {

        }

        void Support_Phone_Other_Clicked(object sender, System.EventArgs e)
        {

        }

        // ### Methods for supporting animations in your popup page ###

        // Invoked before an animation appearing
        protected override void OnAppearingAnimationBegin()
        {
            base.OnAppearingAnimationBegin();
        }

        // Invoked after an animation appearing
        protected override void OnAppearingAnimationEnd()
        {
            base.OnAppearingAnimationEnd();
        }

        // Invoked before an animation disappearing
        protected override void OnDisappearingAnimationBegin()
        {
            base.OnDisappearingAnimationBegin();
        }

        // Invoked after an animation disappearing
        protected override void OnDisappearingAnimationEnd()
        {
            base.OnDisappearingAnimationEnd();
        }

        protected override Task OnAppearingAnimationBeginAsync()
        {
            return base.OnAppearingAnimationBeginAsync();
        }

        protected override Task OnAppearingAnimationEndAsync()
        {
            return base.OnAppearingAnimationEndAsync();
        }

        protected override Task OnDisappearingAnimationBeginAsync()
        {
            return base.OnDisappearingAnimationBeginAsync();
        }

        protected override Task OnDisappearingAnimationEndAsync()
        {
            return base.OnDisappearingAnimationEndAsync();
        }

        // ### Overrided methods which can prevent closing a popup page ###

        // Invoked when a hardware back button is pressed
        protected override bool OnBackButtonPressed()
        {
            // Return true if you don't want to close this popup page when a back button is pressed
            return base.OnBackButtonPressed();
        }

        // Invoked when background is clicked
        protected override bool OnBackgroundClicked()
        {
            // Return false if you don't want to close this popup page when a background of the popup page is clicked
            return base.OnBackgroundClicked();
        }
    }
}`

**Popup XAML Page:**
`<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage 
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:My.UI;"
    xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
    xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
    x:Class="My.Controls.PopupControl">
    
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation 
            PositionIn="Center"
            PositionOut="Center"
            ScaleIn="1.2"
            ScaleOut="0.8"
            DurationIn="400"
            DurationOut="300"
            EasingIn="SinOut"
            EasingOut="SinIn"
            HasBackgroundAnimation="True"/>
    </pages:PopupPage.Animation>
    
    <Frame
        BackgroundColor="{DynamicResource PopupGrayColor}"
        CornerRadius="10"
        OutlineColor="Transparent"
        Padding="0"
            VerticalOptions="Center" 
            HorizontalOptions="Center"
            WidthRequest="300">
        <StackLayout
            VerticalOptions="Center" 
            HorizontalOptions="Center"
            WidthRequest="300">
            
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="*"/>
                </Grid.ColumnDefinitions>
                
                <Label HorizontalOptions="Center" Grid.Column="0" Grid.ColumnSpan="2" Style="{DynamicResource PopupTitleText}" TextColor="Black" x:Name="popupTitle" Margin="12,12,12,0"/>
                
            </Grid>
            
            <Label HorizontalTextAlignment="Start" x:Name="popupMessage" Margin="12,2,12,2" Style="{DynamicResource MediumText}"/>
            
            <Label HorizontalTextAlignment="Start" x:Name="popupAdditionalDetails" Margin="12,2,12,2" Style="{DynamicResource MediumText}"/>
            
            <Label HorizontalTextAlignment="Start" x:Name="popupHiddenMessage" Margin="12,5,12,2" IsVisible="false" Style="{DynamicResource MediumText}"/>
            
            <StackLayout x:Name="SupportControls" IsVisible="false" Margin="12,2,12,2">
                <Button x:Name="emailSupport" Text="{local:Translate support_email}" Clicked="Support_Email_Clicked" HorizontalOptions="Center" BackgroundColor="Transparent" TextColor="{DynamicResource Hyperlink}"/>
                <Button x:Name="callUS" Text="{local:Translate support_phone_US}" Clicked="Support_Phone_US_Clicked" HorizontalOptions="Center" BackgroundColor="Transparent" TextColor="{DynamicResource Hyperlink}"/>
                <Button x:Name="callUK" Text="{local:Translate support_phone_UK}" Clicked="Support_Phone_UK_Clicked" HorizontalOptions="Center" BackgroundColor="Transparent" TextColor="{DynamicResource Hyperlink}"/>
                <Button x:Name="callOther" Text="{local:Translate support_phone_Other}" Clicked="Support_Phone_Other_Clicked" HorizontalOptions="Center" BackgroundColor="Transparent" TextColor="{DynamicResource Hyperlink}"/>
            </StackLayout>
            
            <BoxView BackgroundColor="{DynamicResource ListSeperatorGrey}" HorizontalOptions="CenterAndExpand" WidthRequest="300" HeightRequest="1" Margin="0,0,0,0"/>
            
            <Grid x:Name="hasCancel" IsVisible="false">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="1"/>
                    <ColumnDefinition Width="*"/>
                </Grid.ColumnDefinitions>
                
                <Button HorizontalOptions="Center" Grid.Column="0" x:Name="btnCancel" WidthRequest="100" BackgroundColor="Transparent" TextColor="{DynamicResource PrimaryColor}" Clicked="Cancel_Clicked"/>
                
                <BoxView x:Name="btnDivider" Grid.Column="1" BackgroundColor="{DynamicResource ListSeperatorGrey}" VerticalOptions="CenterAndExpand" WidthRequest="1" Margin="0,0,0,0"/>
                
                <Button HorizontalOptions="Center" Grid.Column="2" x:Name="btnOk" WidthRequest="100" BackgroundColor="Transparent" TextColor="{DynamicResource PrimaryColor}" Clicked="Ok_Clicked"/>
            </Grid>
            
            <Button HorizontalOptions="Center" x:Name="btnClose" WidthRequest="100" BackgroundColor="Transparent" TextColor="{DynamicResource PrimaryColor}" Clicked="Ok_Clicked"/>
            
            
        </StackLayout>
        </Frame>
</pages:PopupPage>`

Any idea or help is appreciated!!

**Comment by EmilAlipiev** [comment]
answer is in this issue. https://github.com/rotorgames/Rg.Plugins.Popup/issues/14
