### ISSUE TITLE
Null Reference Exception on PushAsync and RemovePageAsync ios

### ISSUE THREAD

**Issue by Sanjeev170288** [rotorgames/Rg.Plugins.Popup#377]
In Ios device getting nullreference exception , here is the versions i am using:
**XF:** 3.0.0..482510
**RG Plugin :**  1.1.4.168(stable)
**StackTrace**: 
**_**at Rg.Plugins.Popup.IOS.Impl.PopupPlatformIos+<RemoveAsync>d__10.MoveNext () [0x00165] in /Users/macdev/Downloads/Rg.Plugins.Popup-master/src/Rg.Plugins.Popup.IOS/Impl/PopupPlatformIos.cs:78 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 \n  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<RemoveAsync>d__12.MoveNext () [0x00042] in /Users/macdev/Downloads/Rg.Plugins.Popup-master/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs:117 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 \n  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<RemovePageAsync>d__10.MoveNext () [0x0010f] in /Users/macdev/Downloads/Rg.Plugins.Popup-master/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs:95 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 \n  at ProTrade.OptionsMenuPopup+<HideOptions>d__13.MoveNext () [0x0001b] in /Users/macdev/Desktop/SanjeevWorkspace/protrade/ProTrade/Utility/OptionsMenuPopup.xaml.cs:76 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/
…**_**

**Comment by rotorgames** [comment]
I hope that I fixed it in the last version of the plugin which is available in [the development nuget](https://github.com/rotorgames/Rg.Plugins.Popup#setup) right now. All navigation is invoked in the main thread in the last release whatever how navigation has been invoked in the user's code.

I will be happy if someone can test it with the last version of the plugin >= 1.1.5.184.

Thanks.
