### ISSUE TITLE
Difference in horizontal and vertical sizing

### ISSUE THREAD

**Issue by scastria** [rotorgames/Rg.Plugins.Popup#379]
I am having trouble getting my popup to size correctly.  I am using horizontal/vertical options set to Center so that my popup Grid is centered on the screen.  I am using a combination of Auto and Star in my Grid.  The popup sizes correctly vertically by continuing to grow based on the content I put inside until it reaches the maximum size possible (the vertical size of the screen).  However, this is not the behavior for the horizontal sizing.  It seems to ignore the horizontal size of the content I put inside my grid.  I even tried removing all of my Star column definitions and replaced with Auto and hardcoded the widths of all of my content and it still failed to grow correctly.  I had to force a WidthRequest on the popup Grid itself for it to work.  Any ideas why the sizing behavior is different vertically versus horizontally?

**Comment by rotorgames** [comment]
@scastria Can you reproduce this issue and create a special repository for it that I will be able to test it.

**Comment by scastria** [comment]
Here is a simple test program that demonstrates the problem.  It behaves the same incorrect way on both iOS and Android.  Click the horizontal button to see the color palette button be drawn incorrectly OUTSIDE the containing white dialog popup.  Click the vertical button to see the color palette be drawn correctly where the containing white dialog grows to match the size of its content.

![simulator screen shot - iphone 8 - 2018-11-27 at 12 34 17](https://user-images.githubusercontent.com/4534494/49106580-cadb5280-f240-11e8-912b-4868db1920f3.png)
![simulator screen shot - iphone 8 - 2018-11-27 at 12 34 20](https://user-images.githubusercontent.com/4534494/49106581-cd3dac80-f240-11e8-8831-60b9cafdcaf0.png)

[TestPopup.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/2621572/TestPopup.zip)

**Comment by rotorgames** [comment]
@scastria Why do you think that the problem of this plugin?

**Comment by scastria** [comment]
@rotorgames  Are you saying there is a bug in my sample code?  Please enlighten me.

**Comment by rotorgames** [comment]
@scastria I didn't read your code a lot I just changed `PopupPage` to `ContentPage` and `PopupNavigation.PushAsync` to `Navigation.PushModalAsync` and I got the same issue without the popup plugin

**Comment by scastria** [comment]
@rotorgames  So then it is possible that there is a bug in Xamarin.Forms and that I DO understand how Xamarin.Forms layout works.  Before you accuse someone of being ignorant, please gather some evidence!

**Comment by rotorgames** [comment]
@scastria I'm sorry but I didn't accuse you of being ignorant, I meant that your code didn't work how you wanted and it happend not because of my plugin. If I explain everyone how to work xamarin layouts I don't even have enough time in the world.

You can read this doc to improve your skills of Grid layoyt.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid

**Comment by rotorgames** [comment]
@scastria I have changed only 2 lines in your code and I have got it. Is this behavior which you have wanted to get? 

![simulator screen shot - iphone 6s - 2018-11-29 at 16 18 08](https://user-images.githubusercontent.com/1790504/49200827-91e2df80-f3f2-11e8-8d99-cc64cde89dbf.png)
![simulator screen shot - iphone 6s - 2018-11-29 at 16 17 49](https://user-images.githubusercontent.com/1790504/49200828-91e2df80-f3f2-11e8-9781-36b003579615.png)

**Comment by scastria** [comment]
@rotorgames It is close, the buttons are not centered.  Will you post the changed lines?
