### ISSUE TITLE
Attempting to gather dependency information

### ISSUE THREAD

**Issue by elyfran** [rotorgames/Rg.Plugins.Popup#38]
The problem occurs when beginning the installation using the nuget in .droid.

Attempting to gather dependency information for package 'Rg.Plugins.Popup.1.0.0-pre5' with respect to project 'CpRas.Droid', targeting 'MonoAndroid,Version=v6.0'

**Comment by rotorgames** [comment]
@elyfran Hi friend. This problem is only in Android project?

**Comment by elyfran** [comment]
@rotorgames hi, =D.

Unfortunately only can test the android.

**Comment by rotorgames** [comment]
@elyfran Please, show all console log

**Comment by elyfran** [comment]
It shows only this message.

![erro_po](https://cloud.githubusercontent.com/assets/2677011/19047744/79c0a148-8979-11e6-8b62-056194a61dab.png)
