### ISSUE TITLE
PopupPage.InputTransparent works strange in iOS.

### ISSUE THREAD

**Issue by RadoslawKubas** [rotorgames/Rg.Plugins.Popup#380]
I want to make popup page InputTransparent. 

In Android I noticed that it is impossible to make only part of popup page input transparent in easy way, because this property seems to be ignored in content. Works only if I set property InputTransparent in PopupPag. It's fine, and I guess not exactly PopupPage related.

In iOS it is opposite. It is possible to set InputTransparent for selected content, but strange thing is that if only PopupPage.InputTransparent property is true then input transparency not working anymore. All popup is fully NOT input transparent. For example this not working in iOS (popup is NOT input transparent):

`<PopupPage InputTransparent="True">
 <ContentView InputTransparent="True">
 </ContentView>
</PopupPage>`

but this working as expected:
`<PopupPage>
 <ContentView InputTransparent="True">
 </ContentView>
</PopupPage>`

It is easy to find solution. For example

`<PopupPage>
 <PopupPage.InputTransparent>
  <OnPlatform x:TypeArguments="system:Boolean">
   <On Platform="Android" Value="True"/>
  </OnPlatform>
 <PopupPage.InputTransparent>
 <ContentView InputTransparent="True">
 </ContentView>
</PopupPage>`

But seems to be quite strange behaviour.

**Comment by rotorgames** [comment]
@RadoslawKubas there is the special property "BackgroundInputTransparent" in a PopupPage. Try to use it.

**Comment by rotorgames** [comment]
@RadoslawKubas InputTransparent will work fine in a new version but OnBackgroundClicked will not be invoked if InputTransparent of PopupPage is true.

**Comment by RadoslawKubas** [comment]
Perfect, thank you for fix.
