### ISSUE TITLE
Picker Pops up after Navigation.PopAllPopupAsync()

### ISSUE THREAD

**Issue by sirwes** [rotorgames/Rg.Plugins.Popup#381]
I am using a Rg Popup To hold a simple form containing 2 pickers and 2 buttons. The idea is that they fill in both pickers then hit save or cancel. The buttons navigate away accordingly. After I use the second picker and click one of the buttons to pop the page, the first picker is focused and pops up. Is this a problem with the plugin?
Here is the XML:

`<?xml version="1.0" encoding="UTF-8"?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class=...
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup">`

    <StackLayout BackgroundColor="White" Margin="40,0" Padding="24,10,24,24" VerticalOptions="Center">
        <Label Text="Add" FontSize="Medium" />
        <StackLayout Spacing="-5" Margin="0,30,0,10 ">
            <Label Text="First" />
            <Picker x:Name="firstPicker" Title="Select..." ItemDisplayBinding="{Binding displayName}" />
        </StackLayout>
        <StackLayout Spacing="-5"  Margin="0,10,0,40">
            <Label Text="Second" />
            <Picker x:Name="secondPicker" Title="Select..." SelectedIndex="1" />
        </StackLayout>
        <Button x:Name="addButton" Text="Add" Clicked="addButton_Clicked" />
        <Button x:Name="cancelButton" Text="Cancel" Clicked="cancelButton_Clicked" />
    </StackLayout>
</pages:PopupPage>`

Here is the Page:

`using Rg.Plugins.Popup.Extensions;
using Rg.Plugins.Popup.Pages;
using Rg.Plugins.Popup.Services;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Xamarin.Forms.Xaml;

namespace Foo
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class AddStuffView : PopupPage
    {
        public AddStuffView( )
        {
            InitializeComponent();
            initializeControls();
        }

       private async void initializeControls()
        {
            secondPicker.ItemsSource = Constants.MyList; //MyList is type List<string>
            var list = new ObservableCollection<GameType>();
           //add stuff to 'list'
            firsttPicker.ItemsSource = list;
        }

        private void cancelButton_Clicked(object sender, System.EventArgs e)
        {
            Navigation.PopAllPopupAsync(true);
        }

        private  void addButton_Clicked(object sender, System.EventArgs e)
        {
            if (secondPicker.SelectedIndex > -1 && firstPicker.SelectedIndex> -1)
            {
                //Process their inputs
                    //Update the info
                
                Navigation.PopAllPopupAsync(true);
            }
        }
    }
}`

**Comment by rotorgames** [comment]
@sirwes Where does it happen on android or ios?

**Comment by sirwes** [comment]
I've only tested it in android

**Comment by rotorgames** [comment]
@sirwes you must use `await` operator before `PopAllPopupAsync`

**Comment by shakehar** [comment]
I see this same behavior with Prism

**Comment by shakehar** [comment]
Adding the picker from code behind instead of xaml  fixed this issue for me.

**Comment by danielccunha** [comment]
I'm facing the same issue. Did someone find another solution? I'm not a big fan of working with the code behind.

**Comment by sirwes** [comment]
I put a `firstPicker.Unfocus();` after the navigation, and it seemed to work, but this isn't a solution.
Using the `await` operator before `PopAllPopupAsync` did not work for me
