### ISSUE TITLE
Native Picker opening without click

### ISSUE THREAD

**Issue by danielccunha** [rotorgames/Rg.Plugins.Popup#385]
I'm using Rg.Plugins.Popup for users filter a ListView, and in this filter I'm using a custom picker, with a different appearance (Border, CornerRadius and other stuff). I also have other fields in this page, one custom and and two custom DatePickers, and two buttons for submiting and clearing the form.

The problem is that sometimes when I click any of the buttons, suddenly the first picker opens, without even clicking it. And more, it opens a different picker. It's opening the native one, not the one I implemented.

**Comment by fuorilegge** [comment]
I have this problem too: when you focus an entry and type some text, when you unfocus the entry by clicking, for example, a label, the first item displayed in the popup page receives the focus (picker, entry, datetime picker...). I started have this problem with the latest version of the library.

**Comment by haplios** [comment]
I am also experiencing this same issue specifically with Android. I have an with dropdowns and datetime pickers on it. If you click anywhere on a label or empty space in the popup, and then attempt to close the popup something is focusing the first available input. In the case of dropdowns or datepickers it then attempts to display them as though they were clicked, after the popup is already disposed, which is crashing the app.

**Comment by pizzahead24** [comment]
@rotorgames I just edited this on your source code. Removing line 184 "RequestFocus();" in the droid Renderder Will fix this issue.

**Comment by haplios** [comment]
@danielccunha one of my engineers was able to solve this problem today by pulling down the source code and removing one line of code. 

![image](https://user-images.githubusercontent.com/9308273/50528973-2fdfcd80-0ab7-11e9-9f7d-d3583ddf91a0.png)

`RequestFocus();` seems to be the issue. 

Delete that line and compile the source, use the compiled DLLs instead of the nuget package to fix the issue.

**Comment by rotorgames** [comment]
Duplicate #390. Next discussing will be there.
