### ISSUE TITLE
CloseWhenBackgroundIsClicked is not working.

### ISSUE THREAD

**Issue by marth138** [rotorgames/Rg.Plugins.Popup#386]
I have updated to the newest version of the plugin and it seems like setting the CloseWhenBackgroundIsClicked is not functioning on my Android application.

**Comment by rotorgames** [comment]
@marth138 Can you create a simple project which will reproduce this issue?

**Comment by thekeviv** [comment]
It worked when overided the method OnBackgroundClicked with this:
`protected override bool OnBackgroundClicked()
        {
            // Return false if you don't want to close this popup page when a background of the popup page is clicked
            this.Navigation.RemovePage(this);
            return false;
        }`

**Comment by thekeviv** [comment]
I had the same issue. For me, I was using the regular "Navigation.PushAsync" to create the page and that was causing the issue. It got fixed when I used the function from the imported library (see the demo project in this repo). If you have to use Navigation.PushAsync for some reason, consider overriding the event handlers causing the exceptions.

**Comment by rotorgames** [comment]
I think it was fixed in the last versions.
