### ISSUE TITLE
PopAsync() stops working

### ISSUE THREAD

**Issue by PenguinPero** [rotorgames/Rg.Plugins.Popup#389]
Hello,

I have the following situation:
There is an image and when user taps on it popup page is pushed and shown. (But only one page can be pushed at the time)
Popup page has a list of options and each option will close the popup (also checking that only the first tap will be considered).

But then when quickly opening and closing popups I get into situation where PopAsync stops working.

I've tried using the following code to try to pop the page while there is no difference in the number of pages on the stack:

```
int popupStackCount;
do
{
	popupStackCount = PopupNavigation.PopupStack.Count;
	await PopupNavigation.PopAsync();
} while (PopupNavigation.PopupStack.Count == popupStackCount);
```

That loop runs forever.
However if I disable animations for both push and pop then PopAsync works just fine.

**Comment by rotorgames** [comment]
@PenguinPero What version of the plugin do you use? 

> int popupStackCount;
do
{
	popupStackCount = PopupNavigation.PopupStack.Count;
	await PopupNavigation.PopAsync();
} while (PopupNavigation.PopupStack.Count == popupStackCount);

What exactly do you do in this code? if `PopupNavigation.PopupStack.Count` is 0 you must get exception when you try to call `await PopupNavigation.PopAsync()`. I don't understand your code.

**Comment by PenguinPero** [comment]
This was on the version 1.0.4, haven't checked with the latest one because It was okay for us to use it without animations.

About the code:
I used that piece of code on the popup page, so `PopupNavigation.PopupStack.Count` should be 1 and it was, but after calling `await PopupNavigation.PopAsync();`  `PopupNavigation.PopupStack.Count` remained the same and page was not popped. The condition in the loop was to repeat the popping while the popup stack count was not changed.

**Comment by rotorgames** [comment]
@PenguinPero 1.0.4 is the too old version. There are a lot of changes is in the last version. Try to update it.

**Comment by rotorgames** [comment]
Can someone give more information to me about this issue?

**Comment by accent** [comment]
after update to the latest plugin version, the method PopupNavigation.Instance.PopAllAsync(animated) started causing exception while previously it was fine even if nothing was on the stack.

**Comment by rotorgames** [comment]
@accent That is correct. it was a mistake when the plugin didn't throw an exception if there were not any pages in the PopupStack. For more information see [release notes](https://github.com/rotorgames/Rg.Plugins.Popup/releases/tag/v1.1.5.188)

**Comment by accent** [comment]
That's pitty. That behaviour was quite nice.

**Comment by rotorgames** [comment]
@accent Maybe yes but I hope that this exception will help to make your code better because if you invoke `PopAllAsync` when there are not any pages in `PopupStack` then it is something wrong with your code.

**Comment by EmilAlipiev** [comment]
@rotorgames this somehow messed up with delay problem i mentioned in my other issue. when you push and popall too quick one after another unfortunately push is working slower than pop, i dont know why but  this exception is even crashing the app.

**Comment by rotorgames** [comment]
@EmilAlipiev I'm working on it. I'm going to prepare a behavior which will allow you to check `PopupStack` immediately after invoking the `PushAsync` method. Also, I'm going to make a pushing and a popping safety. I mean you can invoke `PushAsync` and `PopAsync` or `RemovePage` asynchronously from the second thread without any problems. `PopAsync` or `RemovePage` will wait while `PushAsync` is finished and only then will start popping. I think it'll help.

**Comment by rotorgames** [comment]
Moved to #406.
