### ISSUE TITLE
Animation on PopPopupAsync

### ISSUE THREAD

**Issue by LeoJHarris** [rotorgames/Rg.Plugins.Popup#39]
Hi just wondering I'm new to this project, i can get animation on push but the animation is not there when i pop, is just disappears to the next page. In my xml i have this AnimationName="MoveLeft" but how do i get animation when i pop a page? I also created a animation class that extends  IPopupAnimation and set the animation of the popup page to that animation and tried this.

     public async Task Appearing(View content, PopupPage page)
        {
         page.AnimationName = AnimationsName.ScaleCenterDown;
         
        }

    public async Task Disappearing(View content, PopupPage page)
        {
            page.AnimationName = AnimationsName.ScaleCenterUp;
        }
 
How can i get some set the animation for a push and pop using the animation names

**Comment by LeoJHarris** [comment]
Issue resolved, I had false for arg passed in PopPopupAsync, changed xml to just AnimationName="MoveLeft".

**Comment by rotorgames** [comment]
@LeoJHarris Don't use AnimationName. It is depracted in 1.0.0-pre5. 

1.0.0-pre5 use new animations. https://github.com/rotorgames/Rg.Plugins.Popup/blob/v1.0.0/README.md#animations
