### ISSUE TITLE
Input issues on Android

### ISSUE THREAD

**Issue by pizzahead24** [rotorgames/Rg.Plugins.Popup#390]
The issue i'm experiencing happens with a modal that has several inputs in it with save and cancel buttons at the bottom. When tapping into a text editor input (keyboard opens up), then tapping outside on blank space it auto focuses on the next input. When hitting a button in the modal it auto focuses on the first input in the modal. Why this is an issue is because on Android if you focus on a drop down or date picker it opens its own modal for that input. If I click the save or cancel buttons the modal is no longer open meanwhile that input datepicker now opened up and will crash the app. 

STEPS TO REPRODUCE:
This is only on Android. To reproduce create a new pop up modal with a few inputs on it. Have a date picker or a drop down input at the very top. Have a text editor after that, then save buttons at the bottom that just close the pop up. Tap into the text editor input, then tap on any blank space the exit out of the keyboard. Rg auto focuses on another input on its own. When tapping the save button it auto focuses on the first input.

**Comment by pizzahead24** [comment]
@rotorgames I just edited this on your source code. Removing line 184 "RequestFocus();" Will fix this issue.

**Comment by arminrasoulian** [comment]
I have exactly the same problem. When do you plan to release a fixed version?

**Comment by pizzahead24** [comment]
@accent I do not have permissions to push my branched fix to this repository. I just copied the rpopup dll along with the rgpopupdroid dll from my fix over to my other android project and unchecked the rg popup nuget package for that.

**Comment by rotorgames** [comment]
@pizzahead24 Thank you for your attention to this problem. I'll have a look on your PR. `RequestFocus` is used not just like that.
