### ISSUE TITLE
ListView always expand to take all the available space in PopupPage (Only tested with android)

### ISSUE THREAD

**Issue by MathieuFavreau** [rotorgames/Rg.Plugins.Popup#392]
Using a ListView inside a PopupPage will not respect the Horizontal and Vertical options, it will always take all the space available, even if the list is empty. Here is the PopupPage xaml file : 

    <pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms" 
                     xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                     xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
                     x:Class="MyApp.MyPopup">

        <ListView ItemsSource="{Binding ItemsSource}"
                  SelectedItem="{Binding SelectedItem, Mode=TwoWay}"
                  ItemSelected="OnItemSelected"
                  VerticalOptions="Center"/>

    </pages:PopupPage>

I would expect the list height to dynamically change when I add elements to the ItemsSource, but instead it will take the full screen even if empty. 

One way to overcome this problem is for me to change the HeightRequest dynamically based on the number of elements in the list, but it is very inconvenient as I have to set hard coded height values, which I don't think will be consistent over all screen resolutions.

**Comment by rotorgames** [comment]
@MathieuFavreau I think it is not a popup's problem.

> ListView is not intended to always size itself to just fit its contents.

https://forums.xamarin.com/discussion/comment/66248/#Comment_66248
