### ISSUE TITLE
Magnifier glass is showing on tap and hold in input field

### ISSUE THREAD

**Issue by razz-singh** [rotorgames/Rg.Plugins.Popup#393]
![simulator screen shot - ipad air 2 - 2019-01-03 at 15 31 20](https://user-images.githubusercontent.com/17328909/50634006-3963ac80-0f73-11e9-8b5f-46ab95a45bf0.png)

The Popup Page is showing a magnifier glass as shown in the attached screenshot while tapping and hold in any input field of the popup page.

Magnifier glass is showing the content of the previous page on which the popup page has been opened, while it should display the current popup page content in the magnified view.

It will be great if anyone suggests me how to fix it as soon as possible.

**Comment by rotorgames** [comment]
@rotorgames Ok. I'll have a look on this issue.

**Comment by razz-singh** [comment]
Thanks for fixing this issue. I have one query like when should I expect the nuget package update for the same.

**Comment by rotorgames** [comment]
@razz-singh You can get the last nightly version from [the development nuget](https://github.com/rotorgames/Rg.Plugins.Popup#setup).

**Comment by razz-singh** [comment]
Thank you so much to fix the issue. I have tested it and it is absolutely working fine.
here is the screenshot.
![simulator screen shot - ipad air 2 - 2019-02-05 at 00 45 10](https://user-images.githubusercontent.com/17328909/52232015-617f5c00-28e1-11e9-83fc-11cf5d3dfd05.png)
