### ISSUE TITLE
Open Popup fullscreen

### ISSUE THREAD

**Issue by lapoPaolacci** [rotorgames/Rg.Plugins.Popup#394]
Is there a way to present PopupPage fullscreen on small device?

**Comment by rotorgames** [comment]
@lapoPaolacci Can you explain more what would you like to do? Screenshots are welcome.

**Comment by lapoPaolacci** [comment]
@rotorgames if device is phone i would like to push page like contentPage(fullscreen) but if device is tablet i would like to present popoup

**Comment by rotorgames** [comment]
@lapoPaolacci You can do it using this plugin but you have to control how to show page (modal or popup) in your code. This plugin only allows showing popups and nothing else.

**Comment by ehabmsaad** [comment]
you can set this property HasSystemPadding = false so it will appear as full screen, and use a dependency service to get the device type
