### ISSUE TITLE
Question- Xamarin.mac support

### ISSUE THREAD

**Issue by mdonogma** [rotorgames/Rg.Plugins.Popup#395]
Question- Xamarin.mac support

**Comment by happyclan** [comment]
I am interested in a macOS version.  It would take this plugin from "awesome" to "godlike."  
You write really great code.  Please keep up the good work!!

**Comment by charlesroddie** [comment]
Looks like this is done now. Nice work @martijn00 !

**Comment by dansiegel** [comment]
hey credit where credit is due... that wasn't just macOS support but tvOS & watchOS at the same time! Great job and thanks for the quick turn around on this @martijn00
