### ISSUE TITLE
Popup without any background?

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#398]
can we achieve something like below gif? I couldnt figure out how to make the popup without any color. 

 
![overview](https://user-images.githubusercontent.com/10422347/52418695-e095af80-2aee-11e9-9645-387d2f4ad9ae.gif)

**Comment by rotorgames** [comment]
@EmilAlipiev Yes, you can. Just set `BackgroundColor` for `PopupPage` as Color.Transparent.

**Comment by EmilAlipiev** [comment]
@rotorgames when i set that on android, it appears to be like below. i will try to provide you a sample project later.

![image](https://user-images.githubusercontent.com/10422347/53616241-fb38e100-3be1-11e9-873a-a35581a9b4ec.png)

**Comment by EmilAlipiev** [comment]
actually it works :) my mistake was, i was setting backgroundcolor of parent instead of directly setting on the page.
