### ISSUE TITLE
PopupNavigation.Instance.RemovePageAsync results into an exception

### ISSUE THREAD

**Issue by ysmoradi** [rotorgames/Rg.Plugins.Popup#399]
If I run following code:

```cs
if (PopupNavigation.Instance.PopupStack.Contains(_loadingPage))
     PopupNavigation.Instance.RemovePageAsync(_loadingPage, _animate);
```
I'll receive [this exception](https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs#L90) which doesn't make scene at all, because following if

```cs
if (!PopupStack.Any())
     throw new IndexOutOfRangeException("There is not page in PopupStack");
```
is only checked in **PopAll** & **Pop** methods and you've forgotten to check that if in **Remove** method. So why am I getting this exception?! Anyway, I developed following lines of codes to simulate your code using reflection which is similar to your codes, but following code works fine!

```cs
public async Task RemovePageAsync(PopupPage page, bool animate = true)
{
    if (page == null)
        throw new NullReferenceException("Page can not be null");

    // IsBeingDismissed property is not public, so I access/modify it using reflection.
    PropertyInfo IsBeingDismissedProp = _loadingPage.GetType().GetProperty("IsBeingDismissed", BindingFlags.NonPublic | BindingFlags.Instance);

    if ((bool)IsBeingDismissedProp.GetValue(_loadingPage)) // if (page.IsBeingDismissed)
        return;

    // animate = CanBeAnimated(animate); is ignored in my code

    IsBeingDismissedProp.SetValue(_loadingPage, true); // page.IsBeingDismissed = true;

    /*if (animate)
            await page.DisappearingAnimation(); it's ignored in my code */

    await RemoveAsync(_loadingPage);

    /*if (animate)
            page.DisposingAnimation(); it's ignored in my code*/

    IsBeingDismissedProp.SetValue(_loadingPage, false);  // page.IsBeingDismissed = false;
}

async Task RemoveAsync(PopupPage page)
{
    object PopupPlatform = PopupNavigation.Instance.GetType()
        .GetProperty("PopupPlatform", BindingFlags.Instance | BindingFlags.NonPublic)
        .GetValue(PopupNavigation.Instance);

    /*await ((Task)PopupPlatform.GetType()
        .GetMethod("RemoveAsync")
        .Invoke(PopupPlatform, new object[] { _loadingPage }));*/

    // If I await for RemoveAsync of PopupPlatform, I'll receive that damn exception. But If I run that without await as following, I'll see my expected result!

    PopupPlatform.GetType()
        .GetMethod("RemoveAsync")
        .Invoke(PopupPlatform, new object[] { _loadingPage });

    List<PopupPage> popupPages = (List<PopupPage>)PopupNavigation.Instance.GetType()
        .GetField("_popupStack", BindingFlags.NonPublic | BindingFlags.Instance)
        .GetValue(PopupNavigation.Instance);

    popupPages.Remove(page);
}
```

The code snippet is equivalent for [these codes](https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs#L98-L122) **but without animation & InvokeThreadSafe parts**. Note that animation is set to false in all tests I'm performing at the moment! As I described in the codes, there is an [await in your code](https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs#L134) which is not present in my code, and that's why my code is working fine!

I'm trying to create a sample app which demonstrates the issue and I'll provide it soon.

Thanks in advance.

**Comment by Yelnik** [comment]
After updating to v1.1.5.188 `PopAllAsync()` now throws an exception that cannot be caught and crashes the app if there is no page to be removed. I'm not sure if this is the same issue

**Comment by ysmoradi** [comment]
> After updating to v1.1.5.188 `PopAllAsync()` now throws an exception that cannot be caught and crashes the app if there is no page to be removed. I'm not sure if this is the same issue

If you use latest dev nuget package which is published on appveyor, it won't crash!

**Comment by taublast** [comment]
I had theses errors too, until i forked rg.popup, updated all nugets inside, recompiled and suddenly it works now. Might be due to xamarin 3.5 no idea..

**Comment by rotorgames** [comment]
@taublast You can try to use [Development nuget](https://github.com/rotorgames/Rg.Plugins.Popup#setup). I think you will get the same effect.

**Comment by EmilAlipiev** [comment]
@rotorgames  what do you mean by the same effect? it crashes also or it fixes also? did you publish development nuget as pre?

**Comment by EmilAlipiev** [comment]
I have made a few tests and it is impossible to work with this new behavior. i am using code below to pop all pops in my application but this exception is caught as unhandled and crashes Android application. even if you check before any in the popupstack, there are cases where push is slow and pop is called before if you just schedule a pop after a push. Behavior varies also from phone to phone as some phones are slower. I would like to suggest that if there is no popup in the stack, just ignore it, not throw exception. If developer has a bad code, it is his problem. but Application crashes is bigger problem for us. 

```
try
            {
                if (Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Any())
                {
                    return await navigation.PopAllPopupAsync(animate);
                }
            }
            catch (Exception ex)
            {
   
            }
```

**Comment by rotorgames** [comment]
@EmilAlipiev I'm working on it. I'm going to prepare a behavior which will allow checking `PopupStack` intently after invoking the `PushAsync` method. Also, I'm going to make a pushing and a popping safety. I mean you can invoke `PushAsync` and `PopAsync` or `RemovePage` async from the second thread without any problems. `PopAsync` or `RemovePage` will wait while `PushAsync` is finished and only then will start popping. I think it'll help.

**Comment by rotorgames** [comment]
Duplicate #389
