### ISSUE TITLE
Possible deadlock on IOS when removing/popping page

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#406]
Hi @rotorgames,

I am referring to our conversation in this [thread](https://github.com/rotorgames/Rg.Plugins.Popup/issues/344#issuecomment-457845916)

I created a loading pop like full code below. It should basically hide the popup when dispose is called
Usage:

```
   using (Dialogs dialogs = new Dialogs("Loading", _navigation))
            {               
                    await GetData();              
            }

```

this code worked fine in earlier versions but in the latest version, if getdata has no data, basically has nothing to return executes in less than second, and popup remains on the screen because in the function `HideLoading `below, `Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Any()`
return nothing. it looks like Popup is pushed later than this line is executed. How can i achieve it?
I followed your suggestions in the other thread but it seems not working for me. 

```
  public class Dialogs : System.IDisposable
    {
        public Dialogs()
        {

        }
        public Dialogs(string message, INavigation navigation = null)
        {
            var LoadingTask = Task.Run(async () => await LoadingAsync(message, navigation));
        }

        public static async Task HideLoading(INavigation _navigation = null)
        {
            try
            {
                if (Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Any())
                {
                    if (_navigation == null)
                        _navigation = DependencyService.Get<INavigation>();

                    await _navigation.PopAllPopupAsync();
                }
            }
            catch (System.Exception ex)
            {
               
            }
        }
  
        public async Task LoadingAsync(string Message = null, INavigation _navigation = null)
        {
            try
            {
                if (_navigation == null)
                    _navigation = DependencyService.Get<INavigation>();

                if (Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Any())
                {
                    await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAllAsync();
                }
                LoadingPage page = new LoadingPage(Message);
                await _navigation.PushPopupAsync(page);
            }
            catch (System.Exception ex)
            {
                
            }
        }


        public async void Dispose()
        {
            try
            {
                var _navigation = DependencyService.Get<Xamarin.Forms.INavigation>();
                await HideLoading(_navigation);
            }
            catch (System.Exception ex)
            {
                
            }
        }
    }
```

**Comment by rotorgames** [comment]
@EmilAlipiev So, I'm going to do something with this behavior in the next release. I hope you will be available to test it.

**Comment by EmilAlipiev** [comment]
@rotorgames sure i will be able to test it surely. I want to give more information. it appears to be code is working on devices better on android. I dont have IOS device now. I am only testing on simulator, popup appears slower on ios simulator. i will do some more tests on uwp later.

**Comment by EmilAlipiev** [comment]
@rotorgames  do you have any news about this? if we can get any pre-release?

**Comment by rotorgames** [comment]
@PenguinPero @EmilAlipiev Could you test the last develop build (1.1.5.195) from [Development Nuget](https://github.com/rotorgames/Rg.Plugins.Popup#setup)?

I have added some changes to allow checking `PopupStack` immediately after invoking `Push...` even if you don't use `await` operator. Also, I have added transactions which allow you to invoke `Pop(Remove)` even if a page is being in appearing or disappearing progress. Also, you can invoke `Pop(Remove)` two or more times for the one page if the page is being in appearing or disappearing progress and `Pop(Remove)` will be finished only when `Push...` is finished. If you invoke `Pop(Remove)` two or more times then these tasks will be invoked in the same sequence as have been invoked.

**Attention** If you invoke `Push...` twice or `Pop(Remove)` when there is not the page in `PopupStack` you will get an exception. You can use `Pop(Remove)` two or more times only if the page is being in appearing or dissapearing progress. You can't use `Push...` if the appearing or disappearing procces for the page has been started already.

**Comment by rotorgames** [comment]
@EmilAlipiev Did you test last development builds? This issue must be fixed.

**Comment by EmilAlipiev** [comment]
@rotorgames i have cloned develop branch and extended your demo project. See the OnLogin function in the attached project. I changed how you pushed loadingpopup page with an IDisposeable. this code works fine on Android and UWP but not on IOS. loadingpopup is hanging so long, not disposing immediately.

[Demo.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/3189307/Demo.zip)

**Comment by EmilAlipiev** [comment]
this issue might be related also https://github.com/rotorgames/Rg.Plugins.Popup/issues/417
Beside that i recognized in your demo project, there button called "listview page", when you press it and press "close" button, popup is not removed immediately, it is hanging for me.

**Comment by rotorgames** [comment]
@EmilAlipiev it is possible. Garbage collector works with delays. Also if you use breakpoints or keep a reference to a renderer for debugging then Garbage collector will not remove it from memory never. iOS Garbage collector works so. 

I advise you to try using GC.Collect() and try to check again. 

P.S. Dispose method has to be invoked immediately after removing a page from the screen but a renderer of the page can be in memory a lot of time before GC collects it.
