### ISSUE TITLE
Crash when using on Android 9

### ISSUE THREAD

**Issue by DeepakKY** [rotorgames/Rg.Plugins.Popup#407]
I am using Rg Plugins for showing popups in my Xamarin Forms application. The library works absolutely fine upto Android 8. But there are crash in Android 9. The crash seems to occur when I try to close the popup. In debug mode I get an unhandled exception: Java.Lang.IllegalArgumentException: <Timeout exceeded getting exception details> . Below is the log from the debug window.

`Thread started: <Thread Pool> #27
03-05 10:30:45.272 I/MonoDroid( 7455): UNHANDLED EXCEPTION:
Thread started: <Thread Pool> #28
03-05 10:30:45.323 I/MonoDroid( 7455): Java.Lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
03-05 10:30:45.323 I/MonoDroid( 7455):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <8acc8089c2ed40d08469fbaa6710a44c>:0 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <8acc8089c2ed40d08469fbaa6710a44c>:0 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Android.Views.View.set_ScaleX (System.Single value) [0x00018] in /Users/builder/data/lanes/6102/4b951a3e/source/monodroid/external/xamarin-android/src/Mono.Android/obj/Release/android-25/mcw/Android.Views.View.cs:8908 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateScale () [0x00017] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:368 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.Platform.Android.VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0026d] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:149 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.Platform.Android.VisualElementTracker.HandleRedrawNeeded (System.Object sender, Xamarin.Forms.Internals.EventArg`1[T] e) [0x00015] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:171 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.VisualElement.BatchCommit () [0x00024] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:416 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.AnimationExtensions.HandleTweenerUpdated (System.Object o, System.EventArgs args) [0x0004f] in D:\agent\_work\1\s\Xamarin.Forms.Core\AnimationExtensions.cs:284 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.Tweener.<Start>b__22_0 (System.Int64 step) [0x00037] in D:\agent\_work\1\s\Xamarin.Forms.Core\Tweener.cs:78 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.Internals.Ticker.SendSignals (System.Int32 timestep) [0x00050] in D:\agent\_work\1\s\Xamarin.Forms.Core\Internals\Ticker.cs:75 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Xamarin.Forms.Platform.Android.AndroidTicker.OnValOnUpdate (System.Object sender, Android.Animation.ValueAnimator+AnimatorUpdateEventArgs e) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AndroidTicker.cs:41 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Android.Animation.ValueAnimator+IAnimatorUpdateListenerImplementor.OnAnimationUpdate (Android.Animation.ValueAnimator animation) [0x0000a] in /Users/builder/data/lanes/6102/4b951a3e/source/monodroid/external/xamarin-android/src/Mono.Android/obj/Release/android-25/mcw/Android.Animation.ValueAnimator.cs:147 
03-05 10:30:45.323 I/MonoDroid( 7455):   at Android.Animation.ValueAnimator+IAnimatorUpdateListenerInvoker.n_OnAnimationUpdate_Landroid_animation_ValueAnimator_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_animation) [0x00011] in /Users/builder/data/lanes/6102/4b951a3e/source/monodroid/external/xamarin-android/src/Mono.Android/obj/Release/android-25/mcw/Android.Animation.ValueAnimator.cs:95 
03-05 10:30:45.323 I/MonoDroid( 7455):   at (wrapper dynamic-method) System.Object.19(intptr,intptr,intptr)
03-05 10:30:45.323 I/MonoDroid( 7455):   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
03-05 10:30:45.323 I/MonoDroid( 7455): java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.view.View.sanitizeFloatPropertyValue(View.java:15549)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.view.View.sanitizeFloatPropertyValue(View.java:15523)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.view.View.setScaleX(View.java:14912)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at mono.android.animation.ValueAnimator_AnimatorUpdateListenerImplementor.n_onAnimationUpdate(Native Method)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at mono.android.animation.ValueAnimator_AnimatorUpdateListenerImplementor.onAnimationUpdate(ValueAnimator_AnimatorUpdateListenerImplementor.java:30)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:674)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.animation.ValueAnimator.start(ValueAnimator.java:1071)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.animation.ValueAnimator.start(ValueAnimator.java:1088)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.os.Handler.handleCallback(Handler.java:873)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.os.Looper.loop(Looper.java:193)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at java.lang.reflect.Method.invoke(Native Method)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
03-05 10:30:45.323 I/MonoDroid( 7455): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-05 10:30:45.323 I/MonoDroid( 7455): 
`

**Comment by EmilAlipiev** [comment]
which xamarin.forms version? can you also share your popup implementation?

**Comment by rotorgames** [comment]
@DeepakKY What version of Xamarin.Forms and the plugin do you use?

**Comment by EmilAlipiev** [comment]
android 9 version is absolutely working. i tested on samsung s10, it is fine. it should be problem with version you are using or your code

**Comment by zinvob** [comment]
Reproduced on 9 and 11. Fix provided. Please reopen.
https://github.com/rotorgames/Rg.Plugins.Popup/pull/670
@rotorgames
