### ISSUE TITLE
New Pre Release? 

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#408]
I have just downloaded latest code and it seems like Commit 752d7acb fixes problem for 
 issues below. at least it handles to crash application. can we get pre release for this change please?
I have created local nuget for me and test it. it works fine
https://github.com/rotorgames/Rg.Plugins.Popup/issues/389
https://github.com/rotorgames/Rg.Plugins.Popup/issues/406

**Comment by rotorgames** [comment]
If you can see the commit in the develop branch then there are these changes in https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99. You can try to install the last version from this develop nuget but be careful, I can't advise you it in production.

Currently, I'm working on these issues. I figured out how to fix it but I have not published it yet.

**Comment by rotorgames** [comment]
Duplicate #406
