### ISSUE TITLE
Glitch in animation when popping

### ISSUE THREAD

**Issue by LeoJHarris** [rotorgames/Rg.Plugins.Popup#41]
Hi, I think I'm just noticing a small glitch in the animation when popping, it looks like after the page has been popped in my case a centered scale out the page momentarily displays itself at normal scale then disappears after it has scaled out. I'm using the latest v1.0.0 with PopupPage.Animation

**Comment by rotorgames** [comment]
@LeoJHarris Hi. This is only in iOS?

**Comment by rotorgames** [comment]
@LeoJHarris Fix in `v1.0.1`
