### ISSUE TITLE
x86 UWP crash on PopAsync

### ISSUE THREAD

**Issue by jsolivellase** [rotorgames/Rg.Plugins.Popup#413]
I have a problem with PopAsync on UWP platform. PushAsync works fine but not PopAsync. If I run the app with x64 simulator works fine but not with x86 simulator, throws System.AccessViolationException.
 ```
'app.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded '[...]app\bin\x86\Debug\AppX\Microsoft.Graphics.Canvas.winmd'. Module was built without symbols.
An unhandled exception of type 'System.AccessViolationException' occurred in Unknown Module.
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

The program '[6984] app.UWP.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
```

I am using last version of Xamarin.Forms (v3.6.0.264807) and Rg.Plugins.Popup (v1.1.5.188).
Does the library works on x86 architecture? Any idea?

Thanks in advance!

**Comment by ysmoradi** [comment]
My apps are working fine. I'm using latest pre-release

**Comment by m4r10guapito** [comment]
Same problem here. When I to call PopupNavigation.Instance.PushAsync or PopupNavigation.Instance.PopAsync I get System.AccessViolationException. I tried x86 and x64 but it still not working.
In Android project it works fine.
I'm using the last version of everything. Any suggest?

Thanks in advance

**Comment by jsolivellase** [comment]
> Same problem here. When I to call PopupNavigation.Instance.PushAsync or PopupNavigation.Instance.PopAsync I get System.AccessViolationException. I tried x86 and x64 but it still not working.
> In Android project it works fine.
> I'm using the last version of everything. Any suggest?
> 
> Thanks in advance

I found the problem, in my case I have two buttons with Clicked event. Event handlers functions hasn't parameters making UWP crash.
Before:
```
private async void Cancel()
        {
            await PopupNavigation.Instance.PopAsync();
        }
```
After:
```
private async void Cancel(object sender, ClickedEventArgs eventArgs)
        {
            await PopupNavigation.Instance.PopAsync();
        }
```
Same with push if you have another events without parameters.
