### ISSUE TITLE
xaml preview not works with Prism & Prism.Plugin.Popups

### ISSUE THREAD

**Issue by koland** [rotorgames/Rg.Plugins.Popup#414]
![image](https://user-images.githubusercontent.com/24471437/55646736-a1c96080-57e4-11e9-906f-5ebf69e7faf6.png)

**Comment by wangdeshui** [comment]
In windows, the design not works,  in Mac, it can show with a warning!

**Comment by rotorgames** [comment]
@koland I know about this issue. Does it happen only with Android designer, right?

**Comment by rotorgames** [comment]
@koland Did you try to use the last version of Xamarin.Forms (3.6) and Previewer?

**Comment by rotorgames** [comment]
Duplicate #348
