### ISSUE TITLE
How to use with prism

### ISSUE THREAD

**Issue by jmtejada** [rotorgames/Rg.Plugins.Popup#415]
Hi, it's possible to use <a href="https://github.com/rotorgames/Rg.Plugins.Popup"> Rg.Plugins.Popup</a> with <a href="https://www.nuget.org/packages/Prism.Unity.Forms/"> Prism Library</a> in xamarin forms? 
I am using 
` await _navigationService.NavigateAsync(new System.Uri("ErrorMessage", System.UriKind.Relative), useModalNavigation: true); `

but page no displaying :(.

the xaml code for the popup is the follow

![image](https://user-images.githubusercontent.com/23384279/55677841-e9b7b880-58b4-11e9-869c-7c56b14e09c7.png)

I'm already including `containerRegistry.RegisterPopupNavigationService(); ` in the RegisterTypes method and   `Rg.Plugins.Popup.Popup.Init(this, bundle);` in the MainActivity

What can I be doing wrong so that the popup does not show?

thanks for your help

**Comment by agent-reed** [comment]
Have you created a ViewModel for the Popup Page that this XAML represents, and called `RegisterForNavigation` for that ViewModel in Prism's ContainerRegistry?

I.e: `containerRegistry.RegisterForNavigation<ErrorMessage, ErrorMessageViewModel>();`

**Comment by dansiegel** [comment]
have you added Prism.Plugin.Popups? the base Prism Navigation Service has no idea what a PopupPage is. You have to use the Plugin and use the helper to register the PopupNavigationService so that you have a NavigationService that understands how to Push/Pop PopupPages from the Navigation Stack.

**Comment by rotorgames** [comment]
@jmtejada Use Prism.Plugin.Popups library.

**Comment by jmtejada** [comment]
> Have you created a ViewModel for the Popup Page that this XAML represents, and called `RegisterForNavigation` for that ViewModel in Prism's ContainerRegistry?
> 
> I.e: `containerRegistry.RegisterForNavigation<ErrorMessage, ErrorMessageViewModel>();`

it's works for me! thanks!
