### ISSUE TITLE
Rg.Plugins.Popup won't work with Xamarin.Android.Support.v7.AppCompat v28.0.0.1?

### ISSUE THREAD

**Issue by chartierpw** [rotorgames/Rg.Plugins.Popup#416]
When I try to install the plugin I get:

Detected package version outside of dependency constraint: Xamarin.Android.Support.v7.MediaRouter 25.4.0.2 requires Xamarin.Android.Support.v7.AppCompat (= 25.4.0.2) but version Xamarin.Android.Support.v7.AppCompat 28.0.0.1 was resolved

The newer version of Xamarin.Android.Support.v7.AppCompat won't work?

**Comment by EmilAlipiev** [comment]
it surely does.i am using the latest version and it works fine for me. your problem should be something else.

**Comment by chartierpw** [comment]
It refuses to install with amarin.Android.Support.v7.AppCompat 28.0.0.1, a install constraint says it requires Xamarin.Android.Support.v7.AppCompat (= 25.4.0.2), it's not me.

**Comment by xleon** [comment]
Try deleting all packages at your solution and updating the nugets manually by editing csproj rather than nuget manager or console.

**Comment by chartierpw** [comment]
The developer needs to update the install to allow an install with Xamarin.Android.Support.v7.AppCompat greater than or equal to version 25.4.0.2, assuming of course that versions greater than 25.4.0.2 will work and I'm told that it will.

**Comment by xleon** [comment]
I´m using Xamarin.Android.Support.v7.AppCompat v28.0.0.1 in my app together with Rg.Plugins.Popup without issues

**Comment by chartierpw** [comment]
The problem isn't that it won't work with v28.0.0.1, the problem is that it won't INSTALL unless one has 25.4.0.2 installed.  Again, the developer needs to change the INSTALL so that people can install it with v28.0.0.1 (assuming versions greater than 25.4.0.2 with work) .

**Comment by EmilAlipiev** [comment]
this package has no dependency on android support libraries. it is not clear what you are looking for. your problem should be something else but definitely nothing to do with this library. even your error message has no mention on rg.plugins.popup

**Comment by chartierpw** [comment]
I'm not using Xamarin Forms, I'm using Xamarin for Visual Studio (VS 2017).  Rg.Plugins.popup WILL NOT INSTALL from Nuget because of a dependency on Xamarin.Android.Support.v7.MediaRouter 25.4.0.2 which is dependent on Xamarin.Android.Support.v7.AppCompat  (= 25.4.0.2).

**Comment by EmilAlipiev** [comment]
> I'm not using Xamarin Forms, 

seriously? this package is for xamarin.forms. see the nuget description and there is no project type called xamarin for visual studio. see the package dependency below also. do you see any MediaRouter library there? you have different problem and i suggest you to ask your question on stackoverflow or xamarin forum. 

![image](https://user-images.githubusercontent.com/10422347/56448142-23ed7500-630d-11e9-9f74-1d8d0bdcd591.png)

**Comment by chartierpw** [comment]
Sigh ....

Please understand Xamarin.forms, Xamarin.android and Xamarin for Visual Studio are all (basically) the same thing, the current install package of Rg.plugins.popups is not designed (obviously) for a Visual Studios installation of Xamarin.

Consequently, I uninstalled Xamarin.Android.Support.v7.AppCompat v28.0.0.1 and installed Rg.plugins.popups which automatically installed all dependencies and all works as I would expect.  Fortunately I had no dependence on the latest version of  Xamarin.Android.Support.v7.AppCompat, however if I had, I suspect that I could have updated to the latest version once Rg.plugins.popups was installed without a problem.

R/
Prescott ....

**Comment by rotorgames** [comment]
This plugin has a reference only to Xamarin.Forms >=2.5. if you try to install this plugin when there is not a installed Xamarin.Forms library in your project then Xamarin.Forms will be installed automatically but it will be a minimum supported version (2.5). This version refers to the old version of AppCo pat (probably 25) and there is a conflict because of it. It happens because of the settings of Nuget. You can change the default behaviour in settings. 

Finally, install your preferred version of Xamarin.Forms before installing of this plugin to resolve this issue.

Regards.

**Comment by chartierpw** [comment]
The version of Xamarin on Visual Studio 2017 includes all Xamarin options (latest versions), this includes Xamarin.Forms and Xamarin.android.  No need to install anything.
