### ISSUE TITLE
 how to change the index of the popup?

### ISSUE THREAD

**Issue by cristianokiki** [rotorgames/Rg.Plugins.Popup#417]
I have a popup and from it I need to open the camera to read a qrcode, but when I open the camera the modal is still on top, I would like a way to put the modal behind the camera, would anyone have a solution? I tried to run in the main thread but it did not solve, the problem occurs only in ios, in android the camera is normally ahead.

**Comment by rotorgames** [comment]
@cristianokiki A PopupPage always is on top. You can't show Xamarin.Forms pages or modal pages above PopupPage.

**Comment by EmilAlipiev** [comment]
this looks like the similar problem i reported for ios. i think that in some cases, there is a deadlock happening when you try to remove popuppage and popup remains on the screen.
