### ISSUE TITLE
9+1 CTE right after installing the plugin

### ISSUE THREAD

**Issue by ajuanjojjj** [rotorgames/Rg.Plugins.Popup#418]
Right after installing the plugin using nuget, i'm getting 9 compilation time errors on my solution referring to values.xml, and another one "Failed to generate resource table for split" As far as i know this just refers to issues with xml files, wich makes sense given the other errors, hence the "+1" in the title

The others are:
Original attribute defined here.	> Lines 87, 90, 117, 134
Color types not allowed (at 'statusBarBackground' with value '#000000')> 105
Attribute "layout_dodgeInsetEdges/insetEdge/anchorGravity" already defined with incompatible format> 85, 68, 29
Attribute "statusBarBackground" already defined with incompatible format>	13	

Any help would be appreciated,

**Comment by rotorgames** [comment]
@ajuanjojjj Did you try to clean and rebuild the project?

**Comment by ajuanjojjj** [comment]
I honestly cant remember, i think i didnt, I tried to reinstall it and update other plugins. I should be able to give it a try when i go work this monday

**Comment by rotorgames** [comment]
@ajuanjojjj Please, let me know when you try again.

**Comment by ajuanjojjj** [comment]
got even more errors this time, cleaning or rebuilding didnt solve anything :(

`Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		Failed to generate resource table for split '' "Failed to generate resource table for split ''".	Montessori.Android			
Error		Error inesperado en la tarea "LinkAssemblies".
System.IO.FileNotFoundException: Could not load assembly 'Montessori.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
Nombre de archivo: 'Montessori.Android.dll'
   en Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   en Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute()
   en Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   en Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Montessori.Android			
Error		Attribute "statusBarBackground" already defined with incompatible format.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\39\jl\res\values\values.xml	13	
Error		Attribute "layout_anchorGravity" already defined with incompatible format.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\39\jl\res\values\values.xml	29	
Error		Attribute "layout_insetEdge" already defined with incompatible format.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\39\jl\res\values\values.xml	68	
Error		Attribute "layout_dodgeInsetEdges" already defined with incompatible format.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\39\jl\res\values\values.xml	85	
Error		Color types not allowed (at 'statusBarBackground' with value '#000000').	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\39\jl\res\values\values.xml	105	
Error		Original attribute defined here.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\45\jl\res\values\values.xml	87	
Error		Original attribute defined here.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\45\jl\res\values\values.xml	90	
Error		Original attribute defined here.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\45\jl\res\values\values.xml	117	
Error		Original attribute defined here.	Montessori.Android	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori.Android\obj\Debug\90\lp\45\jl\res\values\values.xml	134	
Error		Failed to resolve assembly: 'SuaveControls.FloatingActionButton, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'	Montessori.UWP	C:\Users\Wunderapp\Source\Repos\Montessori\Montessori\Montessori\Views\DailyReportListPage.xaml		
`

**Comment by rotorgames** [comment]
@ajuanjojjj I can't any mentions about this plugin in your stack trace.

**Comment by ajuanjojjj** [comment]
May it be more of a nuget problem then? The problems appear the moment the plugin is installed

Imma try a clean solution to check for different results

**Comment by ajuanjojjj** [comment]
Clean project gave no problems, so i'm assuming its a compatibility issue. The changes in the packages.config are the following, in case you want to take a look on what could be the cause (my xamarin experience is almost nonexistant)

  <package id="Rg.Plugins.Popup" version="1.1.5.188" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Core.Runtime" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.LiveData" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.LiveData.Core" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.ViewModel" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.AsyncLayoutInflater" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Collections" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.CoordinaterLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.CursorAdapter" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.CustomView" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.DocumentFile" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.DrawerLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Interpolator" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Loader" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.LocalBroadcastManager" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Print" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.SlidingPaneLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.SwipeRefreshLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.VersionedParcelable" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.ViewPager" version="28.0.0.1" targetFramework="monoandroid90" />

**Comment by rotorgames** [comment]
@ajuanjojjj I didn't find any problems. I'll close this issue but if you get this problem again, please, reopen this issue.
