### ISSUE TITLE
Push not animating - short delay counting towards animation time

### ISSUE THREAD

**Issue by LeoJHarris** [rotorgames/Rg.Plugins.Popup#42]
Hi,

Just another small issue i have noticed that your animation is not animating when pushing for a scale in center animation on my version 5.1.1 android but works fine on 6.0.1.  When popping both android devices work fine.

**Comment by rotorgames** [comment]
@LeoJHarris Hi friend. I tested it and scale in center is worked. 

Can you show xaml code to me?

**Comment by LeoJHarris** [comment]
Okay so I just tested the xaml (bottom of this) which is correct but the issue I believe is happening is for android animation that scales in (i havent tested other animations) but bassically testing with a shorter duration peroid there is no animation, there seems to be a short delay in the animation pushing and then when the delay is over the page just appears without the animation, i tried doing a long DurationIn and the animation does appear but only after the short delay so it would appear that the delay is counting towards the DurationIn.

<pages:PopupPage.Animation>
    <animations:ScaleAnimation
      PositionIn="Center"
      PositionOut="Center"
      ScaleIn="1.2"
      ScaleOut="1.2"
      DurationIn="300"
      DurationOut="200"
      EasingIn="SinOut"
      EasingOut="SinIn"
      HasBackgroundAnimation="False"/>
  </pages:PopupPage.Animation>
  <pages:PopupPage.Resources>

**Comment by rotorgames** [comment]
@LeoJHarris Hi friend. This is not Popup problem. Xamarin.Forms has delay for creates renderers of page content. I can't change this behaviors.

If you open page again that delay doesn't show?

**Comment by LeoJHarris** [comment]
That's a shame. Opening another page again does not change the delay. Hopefully we wont see this behavior in a later version of Xamarin forms i guess.

**Comment by rotorgames** [comment]
@LeoJHarris Not soon. Xamarin Forms need delay in order to creates many renderers.
