### ISSUE TITLE
Please add PopupNavigation.PagePopped event

### ISSUE THREAD

**Issue by toomasz** [rotorgames/Rg.Plugins.Popup#420]
Currently there is no way to Popup page is popped when it's triggered by user clicking outside of popup. Is it possible to add an event that will fire when page is popped? I would like to dispose my ViewModel when it's not longer needed.

**Comment by EmilAlipiev** [comment]
why do you want to dispose viewmodel and can you not do it within OnDisappearing?

**Comment by rotorgames** [comment]
@toomasz Good idea. I will add it in the roadmap.

**Comment by gutierrezralph** [comment]
use INavigationAware

**Comment by rotorgames** [comment]
It was implemented. You will be able to use it in 1.6.x
