### ISSUE TITLE
Can't build Release version after update to Xamarin.Forms 4.0.0.394984-pre10

### ISSUE THREAD

**Issue by RadoslawKubas** [rotorgames/Rg.Plugins.Popup#422]
I have working solution with Xamarin.Forms 4.0.0.346134-pre9, but after updating Xamarin.Forms to latest version (pre10) I can't build Release anymore (still can build Debug version). After reverting Xamarin.Forms to previous (pre9) it works fine again. It seems to be connected with Rg.Plugins.Popup:

> Can't resolve the reference 'System.String Xamarin.Forms.Page::get_BackgroundImage()', referenced from the method 'System.Void Rg.Plugins.Popup.Animations.Base.FadeBackgroundAnimation::Preparing(Xamarin.Forms.View,Rg.Plugins.Popup.Pages.PopupPage)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by FreshApps** [comment]
Same problem here..

**Comment by arscoloramanfredi** [comment]
Yes same here

**Comment by EBusch** [comment]
Same here.

**Comment by MitchBomcanhao** [comment]
and one more with the same problem...

**Comment by MitchBomcanhao** [comment]
ah, seems like it is an issue with Xamarin forms itself, that will get sorted on the release version of v4.0.0
see https://github.com/rotorgames/Rg.Plugins.Popup/pull/424

**Comment by rotorgames** [comment]
Closed. See #424
