### ISSUE TITLE
Nuspec typo

### ISSUE THREAD

**Issue by mrxten** [rotorgames/Rg.Plugins.Popup#428]
Hi, in nuspec you specified dependency to XF 2.5.0 but your project using XF 3.4 at least six months.

**Comment by rotorgames** [comment]
@mrxten Yes it is but it is not a problem. The plugin works fine with 2.5.0 or 3.6 versions. I keep 2.5.0 version for backward compatibility.

**Comment by mrxten** [comment]
Oh ok, I didn't know that it's acceptable to specify less version than using.
