### ISSUE TITLE
Java.Interop.JavaLocationException

### ISSUE THREAD

**Issue by damienaicheh** [rotorgames/Rg.Plugins.Popup#430]
Hi, I have this bug that is appearing to be random and I can't reproduce it.
However in the stacktrace : 

```
Java.Interop.JavaLocationException
Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
    Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
    java.lang.Error: Java callstack:
    md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.n_onLayout(Native Method)
    md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.onLayout(PopupPageRenderer.java:50)
    android.view.View.layout(View.java:16666)
    android.view.ViewGroup.layout(ViewGroup.java:5438)
    android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
    android.view.View.layout(View.java:16666)
    android.view.ViewGroup.layout(ViewGroup.java:5438)
    android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
    android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
    android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
    android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    android.view.Choreographer.doCallbacks(Choreographer.java:670)
    android.view.Choreographer.doFrame(Choreographer.java:606)
    android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
I see that the problem comes from : ```PopupPageRenderer.onLayout(PopupPageRenderer.java:50)```

And this lines corresponds to this block of code : 
```
protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _disposed = true;

                _gestureDetectorListener.Clicked -= OnBackgroundClick;
                _gestureDetectorListener.Dispose();
                _gestureDetector.Dispose(); // line 50 where the crash appear
            }

            base.Dispose(disposing);
        }
```

I suppose that the `_gestureDetector` was garbage collected at the wrong moment  ?
Thanks for the time you will spend to look at this crazy bug

**Comment by mikepotvin** [comment]
Also getting this same issue

**Comment by florentgoetz** [comment]
I, also, experiencing the problem on my app.
Is there any news on the topic ?

**Comment by rotorgames** [comment]
Did you try to use Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99 guys? 

If not, just try and let me know if you still get this issue.

**Comment by damienaicheh** [comment]
Thanks for your answer, still reproducing the same issue with this version (1.1.5.213): 
```
07-23 17:43:54.522 I/MonoDroid( 1410): System.NotSupportedException: Unable to activate instance of type Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer from native handle 0xbe827d1c (key_handle 0xe9b743d). ---> System.MissingMethodException: No constructor found for Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
07-23 17:43:54.522 I/MonoDroid( 1410):    --- End of inner exception stack trace ---
07-23 17:43:54.522 I/MonoDroid( 1410):   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):    --- End of inner exception stack trace ---
07-23 17:43:54.522 I/MonoDroid( 1410):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):   at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):   at Android.Views.View.n_OnWindowVisibilityChanged_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 native_visibility) [0x00000] in <3921e1c40bf740cab0f47696b3ad1282>:0 
07-23 17:43:54.522 I/MonoDroid( 1410):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.129(intptr,intptr,int)
```

**Comment by rotorgames** [comment]
@damienaicheh I have created a new version of the plugin in Development Nuget. Could you test?

**Comment by damienaicheh** [comment]
Not reproduced, for now. I will reopen it if it happen again, it's difficult to reproduce it in my app.

**Comment by rotorgames** [comment]
@damienaicheh Ok. I'll close it for temporary. Reopen this issue if it happens again.

**Comment by kurianov-pavel** [comment]
Hi I have similar error (1.2.0.223)

Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

`Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.n_onWindowVisibilityChanged(Native Method)
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.onWindowVisibilityChanged PopupPageRenderer.java:74
android.view.View.dispatchWindowVisibilityChanged View.java:12890
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1549
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1553
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:1841
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1523
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:7395
android.view.Choreographer$CallbackRecord.run Choreographer.java:1065
android.view.Choreographer.doCallbacks Choreographer.java:877
android.view.Choreographer.doFrame Choreographer.java:808
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:1051
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:201
android.app.ActivityThread.main ActivityThread.java:6806
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:547
com.android.internal.os.ZygoteInit.main ZygoteInit.java:873`

**Comment by thisisthekap** [comment]
@rotorgames As the issue happened again to @kurianov-pavel and also on our side according to appcenter crash reports, this issue should be reopened.

**Comment by WilliamWatterson86** [comment]
Also seeing the exact same stack trace in App Center crash reports for my app. 

v 1.2.0.223 of the package for me.

**Comment by Burgler-dev** [comment]
Please reopen this issue @rotorgames , we are also experiencing this with the latest version 1.2.0.233:

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
crc6460d2b0234674b457.PopupPageRenderer.n_onWindowVisibilityChanged(Native Method)
crc6460d2b0234674b457.PopupPageRenderer.onWindowVisibilityChanged PopupPageRenderer.java:74
android.view.View.dispatchWindowVisibilityChanged View.java:13866
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1556
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1560
com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged DecorView.java:3459
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2277
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1926
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:8550
android.view.Choreographer$CallbackRecord.run Choreographer.java:986
android.view.Choreographer.doCallbacks Choreographer.java:764
android.view.Choreographer.doFrame Choreographer.java:699
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:965
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7100
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:494
com.android.internal.os.ZygoteInit.main ZygoteInit.java:964

**Comment by Burgler-dev** [comment]
I made a new issue for this, because this one seems to stay closed...

 #509

**Comment by Srikanth540-L** [comment]
@rotorgames We are facing the same crashin the latest version v 1.2.0.223
StackTrace:
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.onWindowVisibilityChanged
PopupPageRenderer.java, line 74
Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.n_onWindowVisibilityChanged(Native Method)
md5b5cbf9a5f989abac95309328170a059b.PopupPageRenderer.onWindowVisibilityChanged PopupPageRenderer.java:74
android.view.View.dispatchWindowVisibilityChanged View.java:13873
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1590
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1594
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2259
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1930
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:8018
android.view.Choreographer$CallbackRecord.run Choreographer.java:1163
android.view.Choreographer.doCallbacks Choreographer.java:986
android.view.Choreographer.doFrame Choreographer.java:902
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:1148
android.os.Handler.handleCallback Handler.java:883
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7682
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:516
com.android.internal.os.ZygoteInit.main ZygoteInit.java:950
