### ISSUE TITLE
'System.String Xamarin.Forms.Page::get_BackgroundImage()', referenced from the method 'System.Void Rg.Plugins.Popup.Animations.Base.FadeBackgroundAnimation::Preparing(Xamarin.Forms.View,Rg.Plugins.Popup.Pages.PopupPage)'

### ISSUE THREAD

**Issue by e5holdingleb** [rotorgames/Rg.Plugins.Popup#431]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Can't resolve the reference 'System.String Xamarin.Forms.Page::get_BackgroundImage()', referenced from the method 'System.Void Rg.Plugins.Popup.Animations.Base.FadeBackgroundAnimation::Preparing(Xamarin.Forms.View,Rg.Plugins.Popup.Pages.PopupPage)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.	AppsHyveXam.iOS			

The project builds in Android, but not in IOS 
![image](https://user-images.githubusercontent.com/43370605/57851353-fd760900-77e8-11e9-8aa9-385866a5e419.png)

I saw a closed issue with same problem, you said it will get resolved when a new update comes, but it didn't get resolved, i have to make a final call if i continue with the library or find an alternative, this is the best library i every used, but if this issue cannot be fixed, can you suggest other alternatives 

thank you

**Comment by mariusgabris** [comment]
I believe this was resolved in [425](https://github.com/rotorgames/Rg.Plugins.Popup/pull/425), we just need a new release for this.

**Comment by e5holdingleb** [comment]
No it did't get resolved, the android won't build with "Link Assemblies on", and the IOS is giving the above error.
The last update for this library was about 3 month ago.

**Comment by mariusgabris** [comment]
> No it did't get resolved, the android won't build with "Link Assemblies on", and the IOS is giving the above error.
> The last update for this library was about 3 month ago.

Yes, but the PR was accepted 13 days ago, so it is not in the latest package from nuget

**Comment by Almazidi** [comment]
any workarounds for now??

**Comment by Almazidi** [comment]
returning to xamarin forms version 4 pre9 solved it

**Comment by e5holdingleb** [comment]
returning to older versions will cause you loss of new security features and other features like IconImageSource in ToolbarItem

**Comment by rotorgames** [comment]
Ok, guys. I can see that BackgroundImage was changed to BackgroundImageSource in Xamarin.Forms. It can be a problem because I would like to keep backward compatibility with Xamarin.Forms 2.5. But I think I can't do it. 

So, I'm going to prepare a new minor version of this plugin to support 4.0 and #432. I'm really sorry that I can't support this plugin for old versions. 

:(

**Comment by e5holdingleb** [comment]
Don't be sorry, you are an awesome smart person, and this is one of the most used plugins, my app relies on this plugin and i wouldn't use any other.

Thanks and respect for you.

**Comment by rotorgames** [comment]
It will be fixed automatically after updating XF to 4.x for this plugin.

I closed it but don't be afraid to reopen it if you still get this issue with a new version of the plugin which higher then 1.1.5.188 (not released at this moment)
