### ISSUE TITLE
Add Xmlns Definition

### ISSUE THREAD

**Issue by dansiegel** [rotorgames/Rg.Plugins.Popup#432]
# Description

Add a XmlnsDefinition attribute to bring in all relevant namespaces in a single easy to use format, instead of having to bring in fully qualified clr-namespaces. This will require direct support for netstandard 2.0 and targeting Xamarin.Forms 3.5+

```cs
#if NETSTANDARD2_0
[assembly: Xamarin.Forms.XmlnsDefinition("http://rotorgames.com", "Rg.Plugins.Popup.Animations")]
[assembly: Xamarin.Forms.XmlnsDefinition("http://rotorgames.com", "Rg.Plugins.Popup.Pages")]
#endif
```

## Existing

```xml
<pages:PopupPage 
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
    xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
    x:Class="MyProject.MyPopupPage">
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation 
            PositionIn="Center"
            PositionOut="Center"
            ScaleIn="1.2"
            ScaleOut="0.8"
            DurationIn="400"
            DurationOut="300"
            EasingIn="SinOut"
            EasingOut="SinIn"
            HasBackgroundAnimation="True"/>
    </pages:PopupPage.Animation>
```

## Proposed

```xml
<rg:PopupPage 
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:rg="http://rotorgames.com"
    x:Class="MyProject.MyPopupPage">
    <rg:PopupPage.Animation>
        <rg:ScaleAnimation 
            PositionIn="Center"
            PositionOut="Center"
            ScaleIn="1.2"
            ScaleOut="0.8"
            DurationIn="400"
            DurationOut="300"
            EasingIn="SinOut"
            EasingOut="SinIn"
            HasBackgroundAnimation="True"/>
    </rg:PopupPage.Animation>
```

**Comment by rotorgames** [comment]
@dansiegel It's a good idea and I like it. I can see only one problem and it's backward compatibility. Currently, this plugin can be installed with Xamarin.Forms 2.5+ and I like it, but I have to set Xamarin.Forms 3.5+ for supporting XmlnsDefinitionAttribute :(

**Comment by dansiegel** [comment]
@rotorgames yes you would have to update to 3.5. That trying to support back to 2.5 is really not worth it. There have been too many breaking changes in their API that have the potential to create problems for people. You're also already building against 3.4 which means that your support back to 2.5 is really theoretical and only because you're using a manually edited nuspec which lets you force your Forms dependency down to 2.5 when it's really 3.4.

**Comment by rotorgames** [comment]
@dansiegel Yes, There is 3.4 in projects but I test this plugin with 2.5 every day and it works fine. Definitely, I think I have to set a minimum version like 3.5 or 4.0 for the next release.
