### ISSUE TITLE
Screen Is Very Dim

### ISSUE THREAD

**Issue by davidbuckleyni** [rotorgames/Rg.Plugins.Popup#433]
I am using the following code to call your popup but it makes the screen very dim unmolst to dark to read the content any ideas andriod 7 stk phone.

`   // Pop the page and show the result
                Device.BeginInvokeOnMainThread(async () =>
                {

                    await Navigation.PopAsync();
                    BomComponentData getInfo = await database.GetBomByBarCode(result.Text);

                    var popup = new FuelStockApp.Views.PopupInputBox("You scanned the item "+ getInfo.Name + "You need to pick " +getInfo.Quantity.ToString());
                    
                    await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PushAsync(popup);
                    
                });`

**Comment by EmilAlipiev** [comment]
library has nothing to do with the screen. it only implements transparent background by default. rest is your UI code and it all depends on your xaml code if you use xaml. your issue description is also not sufficient, you should give screenshot showing your screen without popup and with popup. And your UI implementation for popup
