### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by TimBarton** [rotorgames/Rg.Plugins.Popup#436]

**Comment by TimBarton** [comment]
After upgrading to Xamarin Forms 4.0, I am getting this error when calling await Navigation.PopAsync(true):

`uncaught exception 'System.ArgumentOutOfRangeException', reason: 'System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.'`

When I remove "using Rg.Plugins.Popup.Extensions", My app doesn't crash.  I downgraded to Xamarin Forms 3.6 and all works.

**Comment by veletron2** [comment]
I have similar, but I am on XF3.6.0.344457 and rg.plugins.popup 1.1.5.188

On my App, it works just fine on Android, but Any attempt to close a popup via PopAsync or PopAllAsync on iOS causes it to crash with:

System.IndexOutOfRangeException: There is not page in PopupStack

Nigel

**Comment by rotorgames** [comment]
See https://github.com/rotorgames/Rg.Plugins.Popup/issues/350#issuecomment-423684869

Also, try to use the last version from Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99.
