### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by hoangwy** [rotorgames/Rg.Plugins.Popup#439]
Hi,
Please support for iPhone X.
I got spaces on top and bottom of the screen.
Thanks so much

**Comment by rotorgames** [comment]
It's supported already.

**Comment by hoangwy** [comment]
[https://prnt.sc/nzkbp2](url)

**Comment by rotorgames** [comment]
See (SystemPadding)[https://github.com/rotorgames/Rg.Plugins.Popup/wiki/PopupPage#properties]
