### ISSUE TITLE
Bug in example demo on project app

### ISSUE THREAD

**Issue by ExtremeKaos** [rotorgames/Rg.Plugins.Popup#44]
Hi, in the first example on the project wiki there is no reference to animation assembly.

<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             **xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"**

I think isn't important but for starters (like me) is needed

**Comment by rotorgames** [comment]
@ExtremeKaos Thx
