### ISSUE TITLE
Is it possible to push a new page not async ?

### ISSUE THREAD

**Issue by Kelve17** [rotorgames/Rg.Plugins.Popup#444]
Hi. 

I would like to push a new navigation page but not asynchronously. Because i have tested and when user taps many times in the button to open popup, the window is opened the number of times the user has tapped instead of just 1...
Here is the code of what i am trying.
`        public ICommand AdicionarObjectivoMes
        {
            get => new Command(async () =>
            {
                if (ObjectivosDoMes.Count < 3 && PopupNavigation.Instance.PopupStack.Count == 0)
                    await PopupNavigation.Instance.PushAsync(new NovoObjectivoDoMes(ObjectivosDoMes), true);
                PodeAdicionarObjMes = ObjectivosDoMes.Count < 3 ? true : false;
            });
        }`

In this after popup is pushed the next instruction is right away executed. It does not wait for the async method to complete.
How can i make it wait ?

**Comment by rotorgames** [comment]
@Kelve17 You can control it in your code. You can do it with AsyncCommand (just google it) or something like IsBusy. I think that it is not an issue of this plugin.
