### ISSUE TITLE
iOS UseSafeArea doesn't work - Cut off

### ISSUE THREAD

**Issue by nichojo89** [rotorgames/Rg.Plugins.Popup#448]
On the latest version of XF, using the latest version of this plugin Use Safe Area does not work. It actually seems to push elements further away from the notch rather than closer.

see example code:
`<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Pyx.Mobile.Pages.Chat.ChatDisclosurePage"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:lang="clr-namespace:Pyx.Mobile.Helpers"
             xmlns:renderers="clr-namespace:Pyx.Mobile.Renderers"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
             ios:Page.UseSafeArea="true"
                 >
        <Grid x:Name="DisclosureContainer"
                        Padding="0"
                        Margin="0"
                        HorizontalOptions="FillAndExpand" BackgroundColor="Green"
                        VerticalOptions="FillAndExpand">
                        <BoxView Color="Green" BackgroundColor="Green" HeightRequest="200" WidthRequest="200"
                                 VerticalOptions="StartAndExpand" />
        </Grid>
</pages:PopupPage>`

**Comment by rotorgames** [comment]
@nichojo89 UseSafeArea is not supported for popups. Use SystemPadding for it. https://github.com/rotorgames/Rg.Plugins.Popup/wiki/PopupPage#properties
