### ISSUE TITLE
Initialisation issue on uwp

### ISSUE THREAD

**Issue by al3xmeister** [rotorgames/Rg.Plugins.Popup#449]
Getting issue when initialising on uwp, this line is not permitting the project to compile:

Forms.Init(e, Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies());

Have followed through the troubleshooting article and other suggestions to no conclusion.
The error is that the assembly isnt referenced or found. 

With version 1.1.4 on a XF 2.5 portable project.

Any ideas as to how to fix this?

If I downgrade the package to 1.04 it works fine, however the ios project doesnt initialize the rgpopup and comes back with 'no page in stack' erorrs.
Many thanks in advance.

**Comment by amirvenus** [comment]
BUMP:

Updated to the latest version and now it cannot even init Rg.Plugins.Popup on UWP anymore.
