### ISSUE TITLE
Static resources are not working with the plugin

### ISSUE THREAD

**Issue by mostafamarji** [rotorgames/Rg.Plugins.Popup#45]

**Comment by rotorgames** [comment]
@mostafamarji Hi friend. Please write me version of:

Rg.Plugin.Popup
Xamarin.VS (or Xamarin Studio)
Xamarin.Forms
Xamarin.iOS
Xamarin.Android

What platforms have problems? (Android, iOS, WP, UWP)

**Comment by rotorgames** [comment]
P.S. I tested it on Android and iOS now, and I don't see problems. 
Please, show your xaml code.

**Comment by rotorgames** [comment]
It is not confirmed

**Comment by mostafamarji** [comment]
Hi @rotorgames I got the latest update and the bug is fixed thanks .
