### ISSUE TITLE
Can we use this to open popup instead of full page when tab bar item tap?

### ISSUE THREAD

**Issue by viral105** [rotorgames/Rg.Plugins.Popup#457]

**Comment by viral105** [comment]
Whenever we click any item of tab bar(bottom bar) i want to open only popup not whole page. popup will open on any previously selected tab bar item. For example We have 5 tab bar item.
tb item 1 (Page1)
tb item 2 (Page2)
tb item 3 (No page but popup only) 
tb item 4 (Page4)
tb item 5 (Page5)

If i am on tb item 1 (Page1) and click on tb item 3 it will open popup over tb item 1 (Page1).

**Comment by rotorgames** [comment]
@viral105 Yes, you can, if you override the default behavior of TabbedPage. But this question is not about the plugin. You should ask about in [Xamarin.Forms Page](https://github.com/xamarin/Xamarin.Forms)
