### ISSUE TITLE
Release compatible with Xamarin Forms 4.0+

### ISSUE THREAD

**Issue by IoTFier** [rotorgames/Rg.Plugins.Popup#458]
Hi @rotorgames ,

Is there any plan on releasing a nuget package that's compiled against XF 4.0+ ?

Thanks

**Comment by ysmoradi** [comment]
What's the point?

**Comment by IoTFier** [comment]
To stay current with XF and have the Nuget package maintained the source.

**Comment by IoTFier** [comment]
any thoughts ?

**Comment by TechGuyGeek** [comment]
I take it thats a no then?

**Comment by xleon** [comment]
I´m using the plugin with XF 4+ without issues

**Comment by TechGuyGeek** [comment]
Yeah thanks problem has past since recent VS update thanks

**Comment by IoTFier** [comment]
Requesting attn : @rotorgames , @ysmoradi 
Barring the open issue in XF 4.2 - https://github.com/xamarin/Xamarin.Forms/issues/6907
I will request the core team to consider releasing an updated Nuget package (as frequently as possible). 

It might be great to have a Azure pipeline set up that updates this package as new XF forms versions are released. I don't have a handle on that front yet, otherwise would have certainly contributed in any manners as I could have.

Thank you.
