### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by MitchBomcanhao** [rotorgames/Rg.Plugins.Popup#460]
We've updated our app's Xamarin Forms package from 4.1.0 to 4.2.0, and all seems ok but the app's pre-launch report on google play had a few devices occasionally fail with System.IndexOutOfRangeException: There is not page in PopupStack .

We've done no other relevant code changes, and all instances of the Pop are done as such:

if (PopupNavigation.Instance.PopupStack.Any())
{
     await PopupNavigation.Instance.PopAllAsync(true);
}

I've not been able to reproduce this locally yet (maybe it'll only fail sometimes on some devices?). @rotorgames mentioned that there were fixes for this in his dev builds and that a new production version would be released as soon as possible. any news on that?

**Comment by rotorgames** [comment]
Try to use the last version from Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99 to fix this issue. I will publish a public release when I can.

**Comment by MitchBomcanhao** [comment]
I've tried the latest package on that nuget source, still having issues with it.
I'm thinking that this may have to do with multiple threads trying to pop the stack at the same time, and am trying out some changes to the way we call PopAllAsync.

**Comment by MitchBomcanhao** [comment]
Adding a lock around the popup code seems to have made the issue go away in the automated tests, so it does seem like not being thread safe is the origin of the problem.
Xamarin has done some changes to page activation and lifecycle, so this may have made it more likely that code that once ran independently is now running in parallel. Will keep an eye on those tests for following builds.

**Comment by rotorgames** [comment]
@MitchBomcanhao The last version in  https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99 is thread-safe. Anyway, I hope you fixed this issue. Reopen it if you want.
