### ISSUE TITLE
Unable to activate instance of type Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer 

### ISSUE THREAD

**Issue by GleisonOliveira** [rotorgames/Rg.Plugins.Popup#464]
I get the following error in my app when I click in notification.

Unable to activate instance of type Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer from native handle 0x7fd09a5de4 (key_handle 0x5e0ca5c)

**Comment by rotorgames** [comment]
@GleisonOliveira Did you initialize the plugin?
