### ISSUE TITLE
HTTPClient PostAsync causes Popup to close

### ISSUE THREAD

**Issue by sehuff** [rotorgames/Rg.Plugins.Popup#467]
Since the upgrade to Visual Studio 8.3 code that worked before is no longer working.
After doing a  Navigation.PushPopupAsync and awaiting it - I have code that does a HTTPClient PostAsync, once that PostAsync is called the Popup now closes - which is before I want it closed and also causing an error when I later try to do a Navigation.PopPopupAsync.  This worked prior to the upgrade to Visual Studio 8.3 and .NET Core 3.

**Comment by LJungmann** [comment]
Encountering the same error. But only closes the popup on ios, not on android - what makes it even worse to fix for me.

**Comment by nabilakhlaque** [comment]
Same here... =(

**Comment by sehuff** [comment]
> Encountering the same error. But only closes the popup on ios, not on android - what makes it even worse to fix for me.

Took me a bit to test on Android but I'm seeing the same thing.  I'm not sure why Android vs. iOS would matter - or if the issue is with HTTPClient or Rg.Pluins.Popup.

**Comment by rotorgames** [comment]
@sehuff Could you test the last version of the plugin in [Development Nuget](https://github.com/rotorgames/Rg.Plugins.Popup#setup)?

It must be fixed there and I'm going to publish a new version in the public NuGet soon.

**Comment by sehuff** [comment]
@rotorgames - Yes!  I just tried 1.1.5.220 and the issues is fixed.  Thanks, you're work is very much appreciated!
