### ISSUE TITLE
App crashes after update to 1.1.5.188

### ISSUE THREAD

**Issue by shalinasanga** [rotorgames/Rg.Plugins.Popup#469]
Existing app works fine with Rg plugin version 1.1.5.180, but not in 1.1.5.188
app crashes when start saying 
"System.IndexOutOfRangeException: 'There is not page in PopupStack'"

**Comment by sehuff** [comment]
You may have the same issue I have with HTTPCleint - if you are calling a PostAsync in iOS it causes the page to close - so then when the close gets called there is nothing to close so it errors.  Although it seems like if there is nothing to close it should just go on about it's business and not throw an error.

**Comment by shalinasanga** [comment]
i am adding more details
- Crash occurs in Android
- In latest xamarin forms (4.2.0.815419)

**Comment by MitchBomcanhao** [comment]
are you checking that the stack is empty before popping the stack?
ie
```
if (Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Any())
{
      await PopupNavigation.Instance.PopAsync();
}
```
https://github.com/rotorgames/Rg.Plugins.Popup/issues/350

**Comment by shalinasanga** [comment]
app crashes when loading. crash on MainActivity. There is no PopAsync any where near to app loading. And same code same app works fine in older version of Rg plugin (1.1.5.180). same error occurs in .Net standard project and portable class library project

**Comment by rotorgames** [comment]
@shalinasanga Try to use the last version in [Development NuGet](https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99). And always check if there is a page in PopupStack as @MitchBomcanhao showed.
