### ISSUE TITLE
UWP/ Windows/Windows Phone load assembly issue

### ISSUE THREAD

**Issue by iyadhh** [rotorgames/Rg.Plugins.Popup#47]
Hi,
I'm facing as issue related to loading assembly while working with UWP/ Windows/Windows Phone projects
however on Droid all working fine,

what i did:
create new solution and install Popup Page Plugin for Xamarin Forms 1.0.2
create main page with one button that call:
` await Navigation.PushPopupAsync(loginPopup);`
where loginPopup page is exactly same as in the Demo you provided,

on Android the pop up is working nicely
on any Windows solution crashed with this exception:

'Rg.Plugins.Popup.Services.PopupNavigation' threw an exception.
Could not load file or assembly 'Rg.Plugins.Popup.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.":"Rg.Plugins.Popup.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

in UWP App.cs file i add the following:
`Xamarin.Forms.Forms.Init(e, Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies());`
with no luck 
i tried this also
`  
List<Assembly> assembliesToInclude = new List<Assembly>();
assembliesToInclude.Add(typeof(Rg.Plugins.Popup.Windows.Popup).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assembliesToInclude);`

with same error,

any help would be much appreciated.

**Comment by rotorgames** [comment]
@iyadhh Hi friend. Can you test plugin if I will send `.nupkg` file to you?

**Comment by iyadhh** [comment]
yes sure ...

**Comment by rotorgames** [comment]
@iyadhh Give your email to me please.

**Comment by iyadhh** [comment]
iyadhh@gmail.com

**Comment by rotorgames** [comment]
@iyadhh Ok. I posted `.nupkg` file to your email.

**Comment by rotorgames** [comment]
Fix in `v1.0.3`
