### ISSUE TITLE
Popup is disapearing after 2sec in IOS 13

### ISSUE THREAD

**Issue by Hayko97** [rotorgames/Rg.Plugins.Popup#470]
When we have a background process in application which always running(Just have a background Thread which always doing something). After opening the popup it disappears after 2sec in IOS 13.

**Comment by hoangwy** [comment]
Same here, Please update

**Comment by JKennedy24** [comment]
is this a duplicate of https://github.com/rotorgames/Rg.Plugins.Popup/issues/459?

**Comment by TGlev** [comment]
Yes @JKennedy24 its a dupe of #459

**Comment by Hayko97** [comment]
#459 About app crashing when you call Init function.It is not duplicate please read the description I updated it.

**Comment by rotorgames** [comment]
Duplicate #459
