### ISSUE TITLE
Attempt to show popup that already in use causes exception "Value does not fall within the expected range"

### ISSUE THREAD

**Issue by FoggyFinder** [rotorgames/Rg.Plugins.Popup#471]
How to reproduce (UWP):

1. Open demo app
2. Click "Open Popup"
3. Press Enter

gif:

![crashes](https://user-images.githubusercontent.com/16510738/65912160-6b0c8580-e3d6-11e9-8aae-501988bc38f9.gif)

I would expect different message at least.

**Comment by iashaik** [comment]
I faced a similar issue but with closing an already closed PopupPage from ViewModel Command. 

you can use an if condition to look up at the stack. 

`if(!PopupNavigation.Instance.PopupStack.Any(s => s == _loginPopup))
{
//Open
}`
