### ISSUE TITLE
Android keyboard hiding "pushes" bottom element a bit to far up

### ISSUE THREAD

**Issue by jantanis** [rotorgames/Rg.Plugins.Popup#473]
Initial (right):
![popup_start](https://user-images.githubusercontent.com/11005949/66051099-a91cbd00-e52e-11e9-9434-2a4bfe1611a9.JPEG)

Show keyboard by clicking entry:
![popup_keyboard](https://user-images.githubusercontent.com/11005949/66051157-b8036f80-e52e-11e9-9ac6-09723163a0e4.JPEG)

This shows some empty space between bottom button and keyboard that should not be there,

Dismiss keyboard:
![popup_dismiss](https://user-images.githubusercontent.com/11005949/66051221-d10c2080-e52e-11e9-9aaf-838eb9f1e27b.JPEG)

Empty space remains after dismissing keyboard.

Here's the problem isolated:
[PopUpKeyboard.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/3681473/PopUpKeyboard.zip)

**Comment by rotorgames** [comment]
@jantanis What version of Android, Xamarin.Android, VS?

**Comment by rotorgames** [comment]
So, it happens because of you use PopupPage as ContentPage in NavigationPage. To avoid this issue you can set `HasKeyboardOffset="False" HasSystemPadding="False"` for PopupPage. I hope I will fix it in next releases.

**Comment by jantanis** [comment]
> @jantanis What version of Android, Xamarin.Android, VS?

Android 9 on a Galaxy S10

**Comment by jantanis** [comment]
> So, it happens because of you use PopupPage as ContentPage in NavigationPage. To avoid this issue you can set `HasKeyboardOffset="False" HasSystemPadding="False"` for PopupPage. I hope I will fix it in next releases.

True, the issue doesn't appear. But the reason we use this is because of the keyboard offset. So I hope you'll fix this.

**Comment by rotorgames** [comment]
@jantanis I don't think you should use this plugin for Keyboard Offset. It doesn't make sense. Just google AndroidBug5497 to resize your app when a keyboard is appearing.
