### ISSUE TITLE
(PCL project) UWP version throw exception

### ISSUE THREAD

**Issue by gabrielfarias93** [rotorgames/Rg.Plugins.Popup#48]
I'm trying to display popup on UWP version but throw exception.

`async void loginButton_Clicked(object sender, EventArgs e)
        {
            await PopupNavigation.PushAsync(new FBLogin());
        }`

`public partial class FBLogin : PopupPage
    {
        IDeviceInfo device;
        string accessToken;
        public FBLogin()
        {
            BindingContext = new FacebookViewModel();

             Title = "Entrar com Facebook";
             BackgroundColor = Color.White;

             var apiRequest =
                 "https://www.facebook.com/dialog/oauth?client_id="
                 + ClientId
                 + "&display=popup&response_type=token&redirect_uri=http://www.facebook.com/connect/login_success.html";

             var webView = new WebView
             {
                 Source = apiRequest,
                 HeightRequest = 1
             };

             webView.Navigated += WebViewOnNavigated;

             Content = webView;
        }
}`

Additional information: The type initializer for 'Rg.Plugins.Popup.Services.PopupNavigation' threw an exception.

Could not load file or assembly 'Rg.Plugins.Popup.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system can not find the file specified.

**Comment by rotorgames** [comment]
Fixed in `v1.0.3`. See #47
