### ISSUE TITLE
Xamarin - Popup is starting in fullscreen

### ISSUE THREAD

**Issue by ThomasCurti** [rotorgames/Rg.Plugins.Popup#484]
Hello,

I have a problem, when I start a popup using:
 await PopupNavigation.Instance.PushAsync(new PopupPage());

it shows the popup… in fullscreen.

Do you have any idea why it does that ?

Xaml for the popup page:

<pages:PopupPage
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup" 
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup
             BackgroundColor="#F8F8F8">

    <pages:PopupPage.Animation>
        <animations:ScaleAnimation 
            PositionIn="Center"
            PositionOut="Center"
            ScaleIn="1.2"
            ScaleOut="0.8"
            DurationIn="400"
            DurationOut="300"
            EasingIn="SinOut"
            EasingOut="SinIn"
            HasBackgroundAnimation="True"/>
    </pages:PopupPage.Animation>

    <StackLayout VerticalOptions="Center"
                          Padding="20,20,20,20"
                          HorizontalOptions="Center">

        <Label     HorizontalTextAlignment="Center"
                           VerticalTextAlignment="Center"
                           Text="{Binding Name}"
                           FontSize="Large"
                           FontAttributes="Bold"/>

        <Label Text="{Binding Description}"/>

    </StackLayout>
</pages:PopupPage>

**Comment by yehuditrubinstein** [comment]
set padding to the popup
