### ISSUE TITLE
Can the colour / opacity of the overlay be changed?

### ISSUE THREAD

**Issue by AdamDiament** [rotorgames/Rg.Plugins.Popup#499]
Thanks for the great plugin! I want to use a small popup at the top of the screen as an error message -  for my use case there is no need for the rest of the page to be hidden behind a darkened overlay. Is it possible to change the colour / opacity of the overlay to be transparent, or even to remove it altogether?

**Comment by MitchBomcanhao** [comment]
I think you can just set the BackgroundColor on the PopupPage constructor.

```
        public ExamplePopup()
        {
            InitializeComponent();
            this.BackgroundColor = Color.Transparent; // Color.FromHex("#80FF0000");
        }
```

if you're using a custom page animation like the following, I'd probably also set background animation to False if there's no actual background color to animate.
```
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation DurationIn="150"
                                   DurationOut="150"
                                   EasingIn="SinOut"
                                   EasingOut="SinIn"
                                   HasBackgroundAnimation="False"
                                   PositionIn="Center"
                                   PositionOut="Center"
                                   ScaleIn="1.2"
                                   ScaleOut="0.8" />
    </pages:PopupPage.Animation>
```

**Comment by acaliaro** [comment]
is it the same than #479 ? I think opacity should work

**Comment by AdamDiament** [comment]
@MitchBomcanhao yes that is it! Thanks very much!
