### ISSUE TITLE
[Android] Popup position incorrect when multitasking due to erroneous keyboardoffset being applied

### ISSUE THREAD

**Issue by MitchBomcanhao** [rotorgames/Rg.Plugins.Popup#500]
plugin version: 1.2.0.223

When using more than one app on screen (ie one on top of another), the position of the page content in the popup page will be incorrect, as it will incorrectly apply a keyboard offset to the page content, pushing it to the top of the screen, potentially making it completely inaccessible.

something like this:
![image](https://user-images.githubusercontent.com/31066938/71829568-d54f5900-309c-11ea-8ada-90f3c799ccbd.png)

**Comment by MitchBomcanhao** [comment]
Humm upon further testing, it appears that the issue is that the plugin is applying a **keyboard offset** which then pushes the content off the screen, even though there is no keyboard being displayed.

when I comment out the line
keyboardOffset = Context.FromPixels(screenRealSize.Y - visibleRect.Bottom);

in the OnLayout method for the android PopupPageRenderer, the popup content renders as you'd expect.

**Comment by MitchBomcanhao** [comment]
using 
`activity.WindowManager.DefaultDisplay.GetSize`
instead of 
`activity.WindowManager.DefaultDisplay.GetRealSize`

seems to make this work as expected, at least on my test devices. Displays correctly and still deals with the keyboard as you'd expect. The plugin uses GetRealSize for API >= M and GetSize for the rest and there might be a reason for that difference, so I'm not pretending that this is the fix.

**Comment by nebomuk** [comment]
I'm using the fix described by @MitchBomcanhao in a custom renderer for the PopupPage to get split screen working. Without this workaround, the Popup is not visible at all when using Xamarin Forms apps in Split screen mode.

**Comment by LuckyDucko** [comment]
@taiko000 and @MitchBomcanhao 
Have you guys tried enabling the 
>    HasKeyboardOffset="False"

Option as part of a popup page?
```
<pages:PopupPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="page.page"
    xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
    xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
    HasKeyboardOffset="False">
```

**Comment by nebomuk** [comment]
> 
> 
> @taiko000 and @MitchBomcanhao
> Have you guys tried enabling the
> 
> > HasKeyboardOffset="False"
> 
> Option as part of a popup page?


This actually works for some PopupPages without text input. But popups with text input are not longer moved to the top of the screen to make room for the keyboard.

**Comment by EmmanuelJego** [comment]
Hi!
The workaround suggested by @MitchBomcanhao didn't work for me.
I used this one instead:

In a custom renderer, override the OnLayout method, paste the exact same code than in the original renderer, then within the `if (screenRealSize.Y - visibleRect.Bottom > windowInsets.StableInsetBottom)` block, put this instead:
```
var screenSize = new Android.Graphics.Point();
activity.WindowManager.DefaultDisplay.GetSize(screenSize);
var heightsDiff = screenRealSize.Y - screenSize.Y;

keyboardOffset = Context.FromPixels(screenRealSize.Y - visibleRect.Bottom - heightsDiff);
```

The heightsDiff will reajust the keyboardOffset, according to the apps dimensions
