### ISSUE TITLE
Navigation.InsertPageBefore(page, before) not working inside PopupPage

### ISSUE THREAD

**Issue by stavroaudi** [rotorgames/Rg.Plugins.Popup#501]
In my popup page, I'm trying to use `Navigation.InsertPageBefore(page, before)` but I get the error 

> System.ArgumentException: before must be a child of the NavigationPage

I'd like to insert a navigation page (not popup page) behind the popup and then use PopupNavigation.Instance.PopAsync() to remove the popup and therefore showing the navigation page I'm inserting before.

**Comment by Deadpoolmine** [comment]
Just use Navigation.PushAsync
