### ISSUE TITLE
Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.

### ISSUE THREAD

**Issue by Burgler-dev** [rotorgames/Rg.Plugins.Popup#509]
We are experiencing a lot of exceptions with 1.2.0.233 on android:

Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
crc6460d2b0234674b457.PopupPageRenderer.n_onWindowVisibilityChanged(Native Method)
crc6460d2b0234674b457.PopupPageRenderer.onWindowVisibilityChanged PopupPageRenderer.java:74
android.view.View.dispatchWindowVisibilityChanged View.java:13866
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1556
android.view.ViewGroup.dispatchWindowVisibilityChanged ViewGroup.java:1560
com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged DecorView.java:3459
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2277
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1926
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:8550
android.view.Choreographer$CallbackRecord.run Choreographer.java:986
android.view.Choreographer.doCallbacks Choreographer.java:764
android.view.Choreographer.doFrame Choreographer.java:699
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:965
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7100
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:494
com.android.internal.os.ZygoteInit.main ZygoteInit.java:964

Similar issues can be found in #430

**Comment by LuckyDucko** [comment]
hey @Burgler-dev do you experience these issues with the latest version of the plugin? 

The method referenced is as follows

```csharp
        protected override void OnWindowVisibilityChanged(ViewStates visibility)
        {
            base.OnWindowVisibilityChanged(visibility);

            // It is needed because a size of popup has not updated on Android 7+. See #209
            if (visibility == ViewStates.Visible)
                RequestLayout();
        }
```

There does seem to be a tonne going on here, except for a fix for [this issue](https://github.com/rotorgames/Rg.Plugins.Popup/issues/209)

Could you provide a base example?
