### ISSUE TITLE
Crash on iOS when opening and closing quickly.

### ISSUE THREAD

**Issue by mrhussain0334** [rotorgames/Rg.Plugins.Popup#512]
I am using the Latest Plugin. 

Plugin Version: 1.2.0.223
Xamarin Forms: 4.4.0.991537
iOS: 13.4
Mode: Debug/Release

My team is doing destructive testing on the app. Which leads them to quickly open and close the PopUps. There is no crash in Android. But iOS crashes in Debug and Release Mode

I did debug the code I saw that PopupPlatformIos.RemoveAsync is called 4-5 secs after the page is closed.

Which might have lead to crash. This is just my findings. I may be wrong.

I do have the iOS crash logs but they aren't readable format and I doubt it will be helpful. But if required I will post it here.

I hope it can be resolved soon.

Thanks.

**Comment by BlackZero101** [comment]
Yes I am also getting this issue on iOS 13.4. Any solution for this? My app is close for production

**Comment by broda02** [comment]
I am also getting this...

**Comment by mrhussain0334** [comment]
What I did was uninstalled the plugin and converted all my pages to Absolute Layout and displayed the PopUp using its IsVisible attribute. 
Resolved the crash but will use the plugin later if this gets fixed else this ain't reliable.

**Comment by LuckyDucko** [comment]
@mrhussain0334 are you able to provide a minimal example of this happening?

There are event handlers for popping/popped popup pages
are you able add some sort of timing where you can show us the difference between 
popping->popped->removeasync.

If you wish for a quick hack, perhaps you could add some sort of `IsBusy` boolean, busy when popping/pushing, not busy when popped/pushed, which then you can query each time you wish to push a page. This could help out?

**Comment by hhalai0334** [comment]
The example is quite simple 

Create a simple Pop Up like in the example and try to open and close it at the rapid rate. the UI will crash.

For normal case scenario its working but for edge cases our app crashes (Like using it like a crazy monkey aka destructive testing) .

**Comment by LuckyDucko** [comment]
@mrhussain0334 in the rg.plugins.popup 2.0.2, I tried to replicate but changing the demo app in the following way

-> Mainpage.xaml.cs

OpenPupupPage _(not a typo, that's how it is)_
```csharp
        private async void OnOpenPupup(object sender, EventArgs e)
        {
            for (int i = 0; i < 10; i++)
            {
                await PopupNavigation.Instance.PushAsync(_loginPopup);
                await PopupNavigation.Instance.PopAsync(false);
            }

            var page = new LoadingPopupPage();
            for (int i = 0; i < 10; i++)
            {
                await PopupNavigation.Instance.PushAsync(page);
                await PopupNavigation.Instance.PopAsync();
            }

            for (int i = 0; i < 100; i++)
            {
                await PopupNavigation.Instance.PushAsync(page, false);
                await PopupNavigation.Instance.PopAsync(false);
            }
           //Error here, but that's due to not awaiting the PushAsync
            for (int i = 0; i < 100; i++)
            {
                PopupNavigation.Instance.PushAsync(page, false);
                PopupNavigation.Instance.PopAsync(false);
            }
        }
```

The only error I got was when I explicitly didn't await async functions, which of course led It to break.

Can you (and @broda02 ) see if upgrading to the latest version sorted out your errors?

**Comment by broda02** [comment]
Sorry I had to stop using this with that crash so cannot test.  Deadlines, could not wait

**Comment by LuckyDucko** [comment]
@broda02 that's okay, if you are able to from memory, was there a general workflow you had that caused it, so I can recreate it and test it that way?

@martijn00 it seems that this has been fixed in the latest version, however, just waiting on a response from @mrhussain0334 incase it is related to something a bit deeper than just simple open/close

**Comment by hhalai0334** [comment]
I am sorry for the late reply. I haven't tested the latest version as our team had to ship towards production without the Plugin. I will surely test it out later. I believe it might be fixed in the latest version. Thanks
