### ISSUE TITLE
Type or namespace 'Popup' does not exists in Android

### ISSUE THREAD

**Issue by saimel** [rotorgames/Rg.Plugins.Popup#520]
Hey there, after updating this package I'm getting this error: The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?) (CS0234) (MyApp.Android)

This only happens in my Android project, iOS works fine.

I'd to downgrade to version 1.2 to avoid this issue.

**Comment by martijn00** [comment]
You need to update Android to target 10
