### ISSUE TITLE
The `Rg.Plugins.Popup.Popup` class is no longer present on Xamarin Android

### ISSUE THREAD

**Issue by mfeingol** [rotorgames/Rg.Plugins.Popup#521]
## 🔙 Regression

The `Rg.Plugins.Popup.Popup` class is no longer present on Xamarin Android. If there is a new class, documentation does not mention it.

### Old (and correct) behavior

The class is included in 1.2.0.223.

### Current behavior

> MainActivity.cs(139,13,139,35): error CS0234: The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)

### Reproduction steps

Upgrade a Xamarin.Android project to use 2.0.0.1. Build.

### Configuration

**Version:** 2.0.0.1

**Platform:** 
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by yasmoradi** [comment]
You've to update your project to the android 10 sdk. In a meaning time, I've sent a PR to support both android 9 and 10 sdk together!

**Comment by mfeingol** [comment]
Ah, thanks. Not quite ready to bite the bullet on AndroidX yet, so I'll wait for your PR before updating the plugin.
