### ISSUE TITLE
How to Init the library in version 2.0

### ISSUE THREAD

**Issue by JimmyPun610** [rotorgames/Rg.Plugins.Popup#523]
I updated to version 2.0 but I cannot find the updated documents.
Also, the original init code is not working in 2.0?

What should I do

**Comment by rotorgames** [comment]
@martijn00 As I said before we would get thousands of issues. It confuses people. They can install the library for Android 9 but they get only the core part of the library.

**Comment by martijn00** [comment]
You should update to Android 10. The next release will enable support for legacy Android 9
