### ISSUE TITLE
The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' 

### ISSUE THREAD

**Issue by toverux** [rotorgames/Rg.Plugins.Popup#524]
## 🐛 Bug Report

I just upgraded to version 2.0.0.1 and the Popup static class required for initialization doesn't seem to exist anymore:

![image](https://user-images.githubusercontent.com/1343250/78883959-7bbf4780-7a5a-11ea-962e-bf2c9d27895a.png)

```
[CS0234] The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)
```

I cleaned the solution, deleted bin/obj folders but with no more success.
Downgrading the packages to ^1.0.0 works.

**Comment by toverux** [comment]
Oops, I forgot to check closed issues. Very sorry for that. I'd suggest you keep an up to date issue opened until a compatibility fix for Android 9 is merged.

**Comment by yasmoradi** [comment]
> Oops, I forgot to check closed issues. Very sorry for that. I'd suggest you keep an up to date issue opened until a compatibility fix for Android 9 is merged.

It has been merged already. We're waiting for an updated nuget package.
