### ISSUE TITLE
Rg.Plugins.Popup.Popup.Init for Android not found

### ISSUE THREAD

**Issue by nitishjeebun** [rotorgames/Rg.Plugins.Popup#526]
## 🐛 Bug Report

The Rg.Plugins.Popup.Popup.Init for Android not found when including the package

### Expected behavior
Should have initialised the Popup

As seen in the screenshot, the Assembly is missing the Popup in the Namespace
![image](https://user-images.githubusercontent.com/5356764/78901596-9a890280-7a89-11ea-9d5f-5682ffe0a8f2.png)

### Reproduction steps
1. add the package to the android project
2. put Rg.Plugins.Popup.Popup.Init() in the MainActivity

### Configuration

**Version:** 2.0.0.1

**Platform:** 
- [ x] :robot: Android

**Comment by RwSgxx** [comment]
@martijn00 please also put a link or number to the original issue.
