### ISSUE TITLE
Popup class is missing in Rg.Plugins.Popup from UWP, cannot init plugin in UWP

### ISSUE THREAD

**Issue by kpd328** [rotorgames/Rg.Plugins.Popup#527]
## 🔙 Regression

As with #520 and others asking about the same issue, the Rg.Plugins.Popup.Popup class cannot be found, but this is in my UWP project, not Android

### Old (and correct) behavior
`Rg.Plugins.Popup.Popup.Init();` used in the App.xaml.cs class in a Xamarin.Forms UWP project compiles without error.
### Current behavior
On compilation, error CS0234 is thrown stating 
> The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)

### Reproduction steps
Try to initialize the plugin under UWP
### Configuration

**Version:** 2.0.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You have to set the minimum target to 10.0.17763 or higher.

**Comment by dansiegel** [comment]
keep in mind this is a Xamarin.Forms requirement

**Comment by BelightWavre** [comment]
> You have to set the minimum target to 10.0.17763 or higher.

Maybe should you insist on MINIMUM Target in the main page of the WIKI ... I lost so much time because my target version was correct but not the MINIMUM version ... Thanks for this anyway.
