### ISSUE TITLE
UWP Popup class and methods no longer exist in the Rg.Plugins.Popup namespace

### ISSUE THREAD

**Issue by jimmccurdy** [rotorgames/Rg.Plugins.Popup#528]
## 🔙 Regression

As of the latest nuget release of Rg.Plugins.Popup (version 2.0.0.2), 
the UWP namespace Rg.Plugins.Popup no longer contains the Popup class, along with its methods for Init() and GetExtraAssemblies().

Specifically, the UWP initialization calls to...
          Rg.Plugins.Popup.Popup.Init();
...and... 
          Rg.Plugins.Popup.Popup.GetExtraAssemblies()
...no longer exist.

Please help ASAP.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by dansiegel** [comment]
@jimmccurdy what version of UWP are you targeting? Rg.Plugins.Popup now targets uap10.0.17763. If you're on an older version of UWP you wouldn't get the UWP target...

**Comment by jimmccurdy** [comment]
I do target 10.0.17763.  My min version is 10.0.16299.  Should that matter?

**Comment by jimmccurdy** [comment]
I just confirmed that I now need to set both the Target Version and the Min Version of my UWP app to at least 10.0.17763 in order to get my project to compile now.  I personally can live with that, but others may not be able to.  This looks to be a result of your Rg.Plugin.Popup nuget version 2.0.01.

**Comment by dansiegel** [comment]
@jimmccurdy this is one of those idiosyncrasies with UWP... the NuGet compatibility is based on the Minimum Version not the Target Version. Btw this change in version comes from Xamarin.Forms / Microsoft.
