### ISSUE TITLE
how to pass a result from popup to parent window?

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#53]
I am trying to achieve to return result from popup to it is parent window which is firing it. basically I have a listview inside the popup and I want to send value of the selected value when it is popped. I can send using messaging center but where to subscribe this. is there any action fired on parent window when popup is popped? 

thanks for your help

**Comment by rotorgames** [comment]
@EmilAlipiev See #51
