### ISSUE TITLE
V2.0.0.2 UWP Namespaces don't exist after upgrading [Regression]

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#531]
After upgrading from V1.2.0.223 to V2.0.0.2 I get the following error on UWP:

> The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)	SfSample.UWP

Which means I cannot call:

`Rg.Plugins.Popup.Popup.Init();`

Which means I can't use the plugin because if I try to load a popup page it tells me to call that but I can't as the namespace / library doesn't seem to exist on uwp

**Comment by martijn00** [comment]
See the other closed issues
