### ISSUE TITLE
When upgrading from 1.2.0.223 to 2.0.0.2 UWP App.xaml.cs file will not compile

### ISSUE THREAD

**Issue by gceaser** [rotorgames/Rg.Plugins.Popup#535]
## 🐛 Bug Report
After the upgrade the following lines in my App.xaml.cs file of my Xamarin UWP project throw errors:

Rg.Plugins.Popup.Popup.Init();
assembliesToInclude.AddRange(Rg.Plugins.Popup.Popup.GetExtraAssemblies());

This is the exception
Error	CS0234	The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)	

### Expected behavior
The propup name space should be found or documentation should be updated to indicate these lines of code are no longer needed.

### Reproduction steps
Upgrade to V2.0.0.2 and attempt to run a UWP project using the information provided in the Getting Started guide for the project.

### Configuration

**Version:** 2.0.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by gceaser** [comment]
Please indicate which item this is a duplicate of please.

**Comment by martijn00** [comment]
Please research which item this is a duplicate of please.

**Comment by gceaser** [comment]
I did look for a duplicate.  This problem only happened after upgrading from 1.2.0.223 to 2.0.0.2.  I did not see any issues created within the current year that relate to this issue I am reporting.  You are the one saying it is a duplicate.  Can you please provide a link to the issue you indicate this one is a duplicate of so I can track its status?

**Comment by LuckyDucko** [comment]
@gceaser in previous issues the fix seems to be the following
Which martijn00 [says](https://github.com/rotorgames/Rg.Plugins.Popup/issues/527#issuecomment-6116962560)
>You have to set the minimum target to 10.0.17763 or higher.

[There](https://github.com/rotorgames/Rg.Plugins.Popup/issues/529) [have](https://github.com/rotorgames/Rg.Plugins.Popup/issues/531) [been](https://github.com/rotorgames/Rg.Plugins.Popup/issues/528) [many](https://github.com/rotorgames/Rg.Plugins.Popup/issues/527) [duplicate](https://github.com/rotorgames/Rg.Plugins.Popup/issues/533) issues relating to this, however, I hope that the fix mentioned above helps out 👍 please don't hesitate to reach out if it doesn't

**Comment by gceaser** [comment]
So - FYI from my testing, if you have already installed the 2.x.x.x version before changing the min target for UWP, the app still will not compile.  I reverted the package back to the 1.2.0.223, updated the framework version, ensured everything compiled, the re-updated to 2.0.0.2 and then the errors when away.

**Comment by LuckyDucko** [comment]
>if you have already installed the 2.x.x.x version before changing the min target for UWP, the app still will not compile.

Thanks for this @gceaser this is good information incase others come across similar issues
