### ISSUE TITLE
Unable to update to 2.0.0.2

### ISSUE THREAD

**Issue by BillFulton** [rotorgames/Rg.Plugins.Popup#538]
## 🐛 Bug Report

In VS for Mac, unable to update 1.2.0.223 to 2.0.0.2

### Configuration

**Version:** 2.0.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

I get the following message:
Could not install package 'Rg.Plugins.Popup 2.0.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by yasmoradi** [comment]
I think you've to migrate from portable class library to netstandard2.0 library

**Comment by BillFulton** [comment]
Hi Yaser. Thanks for the reply and thanks for the really great popup. I really hope this might be reconsidered. Many of us have tried to convert to netstandard2.0 and found it would be a mountainous job because so many of our NuGets won't work on netstandard. For myself, I have five years' effort invested in my app and it's disappointing if popup can't be updated. Cheers, Bill

**Comment by yasmoradi** [comment]
> Hi Yaser. Thanks for the reply and thanks for the really great popup. I really hope this might be reconsidered. Many of us have tried to convert to netstandard2.0 and found it would be a mountainous job because so many of our NuGets won't work on netstandard. For myself, I have five years' effort invested in my app and it's disappointing if popup can't be updated. Cheers, Bill

Maybe you've tried in early days of netstandard libraries and you've faced tooling issues.

I think you won't face any issue if you try again with the latest version of visual studio and netstandard2.0+

If you encountered any issue, let me know by sending me a direct in twitter to @ysmoradi or an email to ysmoradi@outlook.com

**Comment by BillFulton** [comment]
Great advice, thanks Yaser! Will give that a try.

**Comment by BillFulton** [comment]
You were right, Yaser. Thanks so much!

**Comment by yasmoradi** [comment]
> You were right, Yaser. Thanks so much!

Nice to hear that (":
