### ISSUE TITLE
Display alert not shown(IOS)

### ISSUE THREAD

**Issue by umairali612** [rotorgames/Rg.Plugins.Popup#54]
Diplay alert is not getting shown in ios when popup is opened.Is there a solution to this?

**Comment by rotorgames** [comment]
@umairali612 Hi. What Popup version do you use?

**Comment by umairali612** [comment]
0.0.17

**Comment by rotorgames** [comment]
@umairali612 Maybe do you need to update to v1.0.3 before creating issues?

**Comment by umairali612** [comment]
It is working in Android.

**Comment by umairali612** [comment]
update messes up the project most of the times. I will try. Thanks man.

**Comment by rotorgames** [comment]
> It is working in Android.
@umairali612 It's working everywhere in v1.0.0 and later.
