### ISSUE TITLE
XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Queue`1

### ISSUE THREAD

**Issue by frankkkkkkkkkkkk** [rotorgames/Rg.Plugins.Popup#540]
After Updating to 2.0.0.2 I get this error:

Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Queue`1' (defined in assembly 'Rg.Plugins.Popup, Version=2.0.0.2, Culture=neutral, PublicKeyToken=null') with scope 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.Queue`1

I am using release-build:
VS2017
android-targetframework 9
Linking: sdk assemblies only  

Why do I have to change LinkMode or how else can I fix it?

**Comment by gmoney494** [comment]
I'm having the exact same issue. Any ideas to resolve without removing the linker? @frankkkkkkkkkkkk

**Comment by brunck** [comment]
I had this problem when building an unrelated app, using a relatively old Xamarin.Android SDK version (version 9). When I used 9.4 or the latest (10.2.x at the time of writing), this error went away.
Note this isn't the same as your target framework level; the SDK used is something that can be specified easily in App Center for example, in build configurations.

**Comment by frankkkkkkkkkkkk** [comment]
For compatibility reasons I have to stick to VS2017 at the moment. (Using Appcenter or VS2019 broke my widget). VS2017 only supports Android 9 compiler. So I have to stay with rgpopup v1
