### ISSUE TITLE
Unable to Upgrade to 2.0.0.2

### ISSUE THREAD

**Issue by kgbuddhima** [rotorgames/Rg.Plugins.Popup#541]
## 🐛 Bug Report

I have upgraded my app to Popup v 2.0.0.2
Then when I was running the  iOS pipeline on VSTS, the Build fails with following error.
It does not fail the iOS project, but the Unit Test project fails.

I run my project on my Windows machine with debug mode and it rungs fine without errors.
both Android and iOS builds are successfully done.
VSTS android pipeline built without any error.

it works fine for Popup v 1.2.0.223
 /Users/runner/hostedtoolcache/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): **error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App.WPF' was not recognized** [/Users/runner/runners/2.166.4/work/1/s/test/MyApp.Tests/DermAssistAI.Tests.csproj]

### Expected behavior
Run the iOS build with the Test project without errors

### Reproduction steps

1. add unit test project
2. Set framework dotnetcore 3.1
3. Reference Mobile shared library which has .net standard 2.1
4. Install Rg.plugin.popup v 1.2.0.223 o all Android , iOS and Shared projects
5. Run the iOS build on iOS build pipeline.

### Configuration

**Version:** 
Rg.plugins.popup 2.0.0.2
Xamarin.Forms  4.6.0.726

**Platform:** 
- [ ] :iphone: iOS / Mac

I think this may be the issue. 

![image](https://user-images.githubusercontent.com/14989528/81065733-ac7b8b00-8ef9-11ea-8db3-6d78760f9678.png)

![image](https://user-images.githubusercontent.com/14989528/81065909-ee0c3600-8ef9-11ea-90d4-16f6491676f4.png)

**Comment by ronymesquita** [comment]
This error can be resolved by using `<PrivateAssets>all</PrivateAssets>` on the `.csproj` file.
Example:
```xml
<PackageReference Include="Rg.Plugins.Popup" Version="2.0.0.2">
    <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

Reference documentation: [Package references (PackageReference) in project files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets).
