### ISSUE TITLE
WPF implementation not working at all

### ISSUE THREAD

**Issue by RwSgxx** [rotorgames/Rg.Plugins.Popup#543]
## 🐛 Bug Report

WPF implementation not working at all.
Not even the sample project you provide for WPF works.

### Expected behavior
WPF should work.
### Reproduction steps
Try to run the WPF sample you provide 
### Configuration

**Version:** 2.0.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [X ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by RwSgxx** [comment]
@VladislavAntonyuk
Hi Vladislav, can you please have a look at this? 
The popups from the examples appear on the screen but they do not have any content.

**Comment by VladislavAntonyuk** [comment]
@RwSgxx fixed, creating a PR
![image](https://user-images.githubusercontent.com/33021114/84597875-7a9e0280-ae6f-11ea-9c02-8e1622e8d452.png)

**Comment by RwSgxx** [comment]
@VladislavAntonyuk Thank you!
@rotorgames I've tested it also and it works. Can you or @martijn00  please accept the PR and build a new nugget. This will make it possible to use this awesome lib also on WPF.
