### ISSUE TITLE
[iOS] HasKeyboardOffset="True" does not work on 2.0.0.2

### ISSUE THREAD

**Issue by Phenek** [rotorgames/Rg.Plugins.Popup#544]
## 🐛 Bug Report

HasKeyboardOffset property does not work with Rg.plugin.popup 2.0.0.2.
iOS only.

### Expected behavior

The keyboard offset should work and call OnSizeAllocated function to resize the page with a Padding of keyboard height.

### Reproduction steps

- Just use the HasKeyboardOffset property to true

- and add an entry a the bottom of the popup page. 

- when the keyboad appear the entry should move with the keyboard.

### Configuration

**Version Rg.plugin.popup :** 2.0.0.2
**Version Xamarin.forms :** 4.6.0.xxx
**Platform:** 
- [ ] :iphone: iOS
- [ ] :monkey: Xamarin.Forms

**Comment by guvenaltunsoyy** [comment]
Any news about this?

**Comment by linnkrb** [comment]
I got the same issue

**Comment by huybuidac** [comment]
You can downgrade to v2.0.0.0

**Comment by OABsoftware** [comment]
I got the same issue.
It can be fixed pretty easily by adding this line as line 141 in Rg.Plugins.Popup/Rg.Plugins.Popup/Pages/PopupPage.cs:

`                case nameof(SystemPadding):`

**Comment by martijn00** [comment]
Fixed in https://github.com/rotorgames/Rg.Plugins.Popup/commit/4794254d712dc69441671061c05f3656413e62a4

**Comment by OABsoftware** [comment]
Thank you!
