### ISSUE TITLE
Resource.designer.cs Added lines

### ISSUE THREAD

**Issue by AlleSchonWeg** [rotorgames/Rg.Plugins.Popup#546]
## 💬 Questions and Help

Hi,
perhaps a stupid question. The plugin added hundred lines in my Resource.designer.cs file like this:
`global::Rg.Plugins.Popup.Resource.Animation.abc_fade_in = global::Manserv.MobileMis.Droid.Resource.Animation.abc_fade_in;`

Is this necessary and why?
Thanks

**Comment by martijn00** [comment]
Yes, this is what Xamarin does.
