### ISSUE TITLE
Version 2.0.0.2 not working in UWP

### ISSUE THREAD

**Issue by luis-barreira** [rotorgames/Rg.Plugins.Popup#547]
## 🐛 Bug Report

Method Rg.Plugins.Popup.Popup.Init() is not present in the assembly compiled to support .Net Standard 2.0 which is used by UWP project. I've checked with DotPeed disassembler and the Popup class is not present in the Rg.Plugins.Popup namespace. I've checked on other differente varieties of the library and it is there.

**Comment by AleBros** [comment]
> ## 🐛 Bug Report
> Method Rg.Plugins.Popup.Popup.Init() is not present in the assembly compiled to support .Net Standard 2.0 which is used by UWP project. I've checked with DotPeed disassembler and the Popup class is not present in the Rg.Plugins.Popup namespace. I've checked on other differente varieties of the library and it is there.

The last working version is 1.2.0.223 :(

**Comment by martijn00** [comment]
It is there: https://github.com/rotorgames/Rg.Plugins.Popup/blob/develop/Samples/Demo.UWP/App.xaml.cs#L63

Please read the readme

**Comment by luis-barreira** [comment]
I've read the readme, I've been using this library for some time.

How do you explain this?

![popup](https://user-images.githubusercontent.com/16102884/83883675-b7654d80-a73b-11ea-826d-99ea637cabc2.png)

**Comment by martijn00** [comment]
Min Target: 10.0.17763

**Comment by AleBros** [comment]
Thank you!
Changing min target to 17763 it works as expected!

**Comment by HTUlv412** [comment]
this fix do not work in 2.0.0.3 version
