### ISSUE TITLE
Stable Version is broken on iOS

### ISSUE THREAD

**Issue by dansiegel** [rotorgames/Rg.Plugins.Popup#55]
PopupPages inconsistently appear on iOS in the stable versions. The last working version is 1.0.0-pre5

**Comment by rotorgames** [comment]
@dansiegel Upgrade to 1.0.3

**Comment by dansiegel** [comment]
Had the issue with 1.0.2 & 1.0.3 which is why I'm reporting the issue.

**Comment by rotorgames** [comment]
@dansiegel Please, give example project or screenshots to me.

**Comment by DevinReed** [comment]
Hi, We are using this plugin in our app, it is a popup with an entry, when the user taps the cancel button in iOS, all that happens is the keyboard is dismissed, the button tap event does not fire inside the Xamarin forms code.

It works perfectly in Android, tapping the Cancel button dismisses the keyboard and fires the Cancel buttons event which pops the view.

I have attached an example movie in the iOS, this was taken on iPhone 6 with iOS 10.1.1.

Thanks
[DismissIssue.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/571242/DismissIssue.zip)

**Comment by rotorgames** [comment]
@DevinReed See #11

**Comment by alisolutions** [comment]
We are waiting for that solution, our release is pending. Please fix it, or let us know any alternative solution.

**Comment by rotorgames** [comment]
@alisolutions This is big problem. I have not time for fix this bug now, but you may fix it yourself. All code is in repository.

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.
