### ISSUE TITLE
UWP cannot find Rg.Plugins.Popup.Popup.Init();

### ISSUE THREAD

**Issue by mmurfinsimmons** [rotorgames/Rg.Plugins.Popup#550]
## 🔙 Regression

Cannot compile Xamarin Forms shared platform UWP after update to 2.0.0.3 from 1.2.0.223.

### Old (and correct) behavior
I was able to compile - Errors in UWP App.xaml.cs
* Rg.Plugins.Popup.Popup.GetExtraAssemblies()
* Rg.Plugins.Popup.Popup.Init();

### Current behavior
Rg.Plugins.Popup. [Popup] does not exist in namespace.

### Configuration

**Version:** 2.0.0.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
See all the other issues about this. Read the readme.
