### ISSUE TITLE
Rg.Plugins.Popup.Popup.Init(); do not work in UWP

### ISSUE THREAD

**Issue by HTUlv412** [rotorgames/Rg.Plugins.Popup#551]
## 🐛 Bug Report

Rg.Plugins.Popup.Popup.Init(); On UWP

Error	CS0234	The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)

### Expected behavior
No error.
### Reproduction steps
Added two Lines in Apps.xaml.cs
Rg.Plugins.Popup.Popup.Init();
Xamarin.Forms.Forms.Init(e, Rg.Plugins.Popup.Popup.GetExtraAssemblies());
### Configuration
Visual Studio 2019
Windwos 10 Enterprise.
**Version:** 2.0.0.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
https://github.com/rotorgames/Rg.Plugins.Popup/issues/547#issuecomment-639509727
