### ISSUE TITLE
v2.0.0.3 and Andorid 9 can't close animation

### ISSUE THREAD

**Issue by raz0r777** [rotorgames/Rg.Plugins.Popup#552]
## 🐛 Bug Report

On android 10 devices work perfectly fine , but on andorid 9 i cant close the animation on the popup page on <button> Clicked event
**Version:** 2.0.0.3

**Platform:** 
- [ ] :iphone: iOS
-  :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by dmplays** [comment]
Me too on Android 8. And the Closing Icon is not showing too. 
On Android 7 no problems. But on Android 8. 80% it do not work. Sometimes (20%) it works without Problems!

**Comment by dmplays** [comment]
I just updatet my Visual Studio to 16.6.3 and now its ok.

**Comment by Alextorres950325** [comment]
Again fail
