### ISSUE TITLE
Please create a new nuget release.

### ISSUE THREAD

**Issue by RwSgxx** [rotorgames/Rg.Plugins.Popup#555]
## 🐛 Bug Report

The current nuget doesn't work at all for WPF.
A fix was provided and merged.
Can you please make a new nuget so that the lib is usable on WPF?
@martijn00
@rotorgames 

### Expected behavior
The nuget release should work on WPF.
### Reproduction steps
Install the latest nuget.
### Configuration
WPF + Xamarin Forms
**Version:** 2.0.0.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ X] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by JKennedy24** [comment]
+1 on this. Even as an untested pre-releaes.

waiting on this fix which has also been merged https://github.com/rotorgames/Rg.Plugins.Popup/commit/292fb19770502d6f2ebc5966271c68fdc7de5e2b

**Comment by RwSgxx** [comment]
done.
