### ISSUE TITLE
ShowDialog and DialogResult

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [rotorgames/Rg.Plugins.Popup#556]
## 💬 Questions and Help
Hello, I would like to be able to call PopupPage, wait for completion and get the result. How can this be implemented in the current version of the library? Or maybe this offer you for the future ...

Example
```C#
bool? result = await popupPage.ShowDialog() as bool?; //ShowDialog returns Task<object>
if (result == true)
{
     // TODO
{
```

**Comment by LuckyDucko** [comment]
hey @AgPeHaJIuH1 I believe #567 will give some good answers surrounding this

**Comment by LuckyDucko** [comment]
@martijn00 can close
