### ISSUE TITLE
Xamarin Forms UWP unable to initialise plugin. (V 2.0.0.3)

### ISSUE THREAD

**Issue by kumaresan-cgvak** [rotorgames/Rg.Plugins.Popup#559]
## 🐛 Bug Report
Unable to build the Xamarin Forms UWP project after updating the plugin to version 2.0.0.3. Getting error in the below initialisation line.

Rg.Plugins.Popup.Popup.Init();

### Expected behavior
Able to initialise using the below line.
Rg.Plugins.Popup.Popup.Init();

### Reproduction steps
Install updated plugin in Xamarin Forms project and build UWP platform.
### Configuration

**Version:** 2.0.0.3

**Platform:** 
- UWP

**Comment by martijn00** [comment]
Look at all the other closed issues first.
