### ISSUE TITLE
PopUp Close After Navigation

### ISSUE THREAD

**Issue by ravinderjangra** [rotorgames/Rg.Plugins.Popup#56]
Unable to close the popup window once user navigate from current page to another page using popup windows menu.

**Comment by rotorgames** [comment]
@ravinderjangra Hi. I don't understand your problem. May you show code?

**Comment by ravinderjangra** [comment]
I am opening a page using

Navigation.PushPopupAsync(new HamburgerMenu())

then From HamberberMenu Page I am navigating to another page and the popup is still open after navigation. How do I close the popup menu on navigation.

**Comment by rotorgames** [comment]
@ravinderjangra You can invoke PopAsync, PopAllAsync or RemovePageAsync(popupPage)

It is working everywhere.
