### ISSUE TITLE
UWP Problem

### ISSUE THREAD

**Issue by alihut** [rotorgames/Rg.Plugins.Popup#560]
## 🐛 Bug Report

Currently, I'm using the version 1.20.0.223 on my Xamarin cross-platform project without any problem. But when I update it to v.2.0.0.3 I can't initialize it in App.xaml.cs. It seems like a bug but maybe I'm missing something.

![bug1](https://user-images.githubusercontent.com/16089599/87409634-e2aa4a80-c5cd-11ea-8b7b-35d43e8c8c23.png)
![bug2](https://user-images.githubusercontent.com/16089599/87409635-e342e100-c5cd-11ea-8736-853a9152cf51.png)

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
See all other issues closed and the readme. Update your minimum version.
