### ISSUE TITLE
UWP Object reference not set to an instance of an object Exception on Pop

### ISSUE THREAD

**Issue by mattfinch1980** [rotorgames/Rg.Plugins.Popup#561]
Using latest Rg.Plugins.Popup release, calling popupallpopupasync() in UWP causes 'Object reference not set to an instance of an object.' exception around System.Collections.ListDictionaryInternal within PopupPageRenderer.cs. 

Xamarin.Forms version = 4.7.0.1080
Rg.Plugins.Popup version = 2.0.0.3

This may be due to changes made in Xamarin.Forms as also failed in previous Rg.Plugins version 1.2.0.223 with the above Xamarin.Forms increment.

Any help much appreciated.

Best Regards,

Matt

**Comment by levitali** [comment]
The Error happens in UpdateElementSize method, because the CurrentElement is null.

Please fix.

**Comment by martijn00** [comment]
Don't say "Please fix", say: I will make a pull request.

**Comment by JKennedy24** [comment]
Think this is fixed by this changeset: https://github.com/rotorgames/Rg.Plugins.Popup/commit/292fb19770502d6f2ebc5966271c68fdc7de5e2b

But is waiting to be released
