### ISSUE TITLE
with xamarin forms 4.7.0.1142 the plugin isn't showing popups anymore on iOS

### ISSUE THREAD

**Issue by rasel-tr** [rotorgames/Rg.Plugins.Popup#563]
## 🐛 Bug Report

Just updated the xamarin.forms to 4.7.0.1142 and can't see the popup pages anymore. It doesn't give any error but not display the page.

**Version:** 2.0.0.3

**Platform:** 
Microsoft Visual Studio Enterprise 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03752

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Xamarin   16.6.000.1062 (d16-6@41e1f0e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JArmandoCl** [comment]
Any solution to this? Actually im facing this problem in android :s

**Comment by rasel-tr** [comment]
I have no problems with Droid. To be more clear with the iOS, it is working if there isn't any page on the Navigation stack but if there is a modal page on the stack (I'm trying to push a popup page from a navigation.modal page), it isn't working anymore, this code was working before forms upgrade.

![image](https://user-images.githubusercontent.com/6556734/89331398-6241ab80-d69a-11ea-9023-7f7e28895288.png)

**Comment by rasel-tr** [comment]
The issue was related with Xamarin.Forms. Changed the page to a normal ContentPage and it is giving the same behavior. I opened an issue there (#11685). Also added a repro to test the behavior. It is a regression, was working before.
