### ISSUE TITLE
Getting Started documentation does not appear to be complete

### ISSUE THREAD

**Issue by gceaser** [rotorgames/Rg.Plugins.Popup#564]
## 💬 Questions and Help
GitHus shows the following platforms as supported

Android
 iOS
 UWP (Min Target: 10.0.17763)
 Tizen
 WPF
 MacOS

The getting started documentation states that the component must be initialized on all platform but it does not include documentation for how to initialize the component on Tizen or MacOS.

**Comment by LuckyDucko** [comment]
hey @gceaser 

Just looking through the Samples project, might provide some clues while we wait for @martijn00 to see this.

Example documentation

# Mac

```csharp
 [Register("AppDelegate")]
    public class AppDelegate : FormsApplicationDelegate
    {
        public AppDelegate() ...

        public sealed override NSWindow MainWindow { get; }

        public override void DidFinishLaunching(NSNotification notification)
        {
            Rg.Plugins.Popup.Popup.Init();
            Forms.Init();
            LoadApplication(new App());
            base.DidFinishLaunching(notification);
        }
    }
```

# Tizen

```csharp
	class Program : global::Xamarin.Forms.Platform.Tizen.FormsApplication
	{
               	protected override void OnCreate() ...
		static void Main(string[] args)
		{
			var app = new Program();
                        Rg.Plugins.Popup.Tizen.Popup.Init();
			Forms.Init(app, true);
			app.Run(args);
		}
	}

```

**Comment by LuckyDucko** [comment]
@martijn00 could you please add the above to the WIKI and close.
