### ISSUE TITLE
How to return Data from PopupView(rg.plugin.popup) to base view(viewmodel) where it invoked?

### ISSUE THREAD

**Issue by IaamRich** [rotorgames/Rg.Plugins.Popup#567]

**Comment by LuckyDucko** [comment]
@IaamRich 
You could use [MessagingCentre](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center) to allow for a publish/subscribe loosely coupled functionality to return data from a popup back to a view model.

Alternatively, I have created a plugin that adds this type of functionality to rg.plugins.popup, which you can view [here](https://github.com/LuckyDucko/AwaitablePopups)

**Comment by IaamRich** [comment]
> @IaamRich
> You could use [MessagingCentre](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center) to allow for a publish/subscribe loosely coupled functionality to return data from a popup back to a view model.
> 
> Alternatively, I have created a plugin that adds this type of functionality to rg.plugins.popup, which you can view [here](https://github.com/LuckyDucko/AwaitablePopups)

Thank you very much for your time and your answer to me! Thank you for your experience.

**Comment by RwSgxx** [comment]
> 
> 
> @IaamRich
> You could use [MessagingCentre](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center) to allow for a publish/subscribe loosely coupled functionality to return data from a popup back to a view model.
> 
> Alternatively, I have created a plugin that adds this type of functionality to rg.plugins.popup, which you can view [here](https://github.com/LuckyDucko/AwaitablePopups)

I would run from [MessagingCentre](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center) as far as I can. If used too much it will just make your app a mess, to the point where you will not know who is talking to who.
[AwaitablePopups](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center) seams interesting and simple to use.
 
You can also use a [TaskCompletionSource](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=netcore-3.1), pass it to the popup and await the Task property of the TaskCompletionSource. And from within the popup set the result of the TaskCompletionSource.

**Comment by LuckyDucko** [comment]
> I would run from MessagingCentre as far as I can

While it does have its place, I would agree its probably a bit much for this scenario. Does get lost quite fast

>You can also use a TaskCompletionSource, pass it to the popup and await the Task property of the TaskCompletionSource. And from within the popup set the result of the TaskCompletionSource.

This is kinda what I ended up doing with [awaitablepopups](https://github.com/LuckyDucko/AwaitablePopups), however, never thought to create the taskcompletionsource first and pass it in. Might be an easier solution than trying to convert things to use the plugin.

**Comment by RwSgxx** [comment]
should we close this one? @IaamRich

**Comment by LuckyDucko** [comment]
@martijn00 can close.
