### ISSUE TITLE
Make a popup page without any padding or border-radius

### ISSUE THREAD

**Issue by lucasabritta** [rotorgames/Rg.Plugins.Popup#57]
Hi, i want to create one rectangle popup without padding, it is possible?

I wanna do something like this:

![popup](https://cloud.githubusercontent.com/assets/15205208/20114232/9ca7e630-a5da-11e6-95fd-d0ec863751d3.png)

thx

**Comment by rotorgames** [comment]
@lucasabritta Hi. See demo projects.
