### ISSUE TITLE
Rg.Plugins.Popup.Popup UWP gone in version 2.0 

### ISSUE THREAD

**Issue by LukasThijs** [rotorgames/Rg.Plugins.Popup#571]
### Expected behavior
Rg.Plugins.Popup.Popup should exist so you can call the init() function
### Reproduction steps
Install any version starting at 2.0 and above.
### Configuration
UWP
**Version:** 2.0+

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Target 10.0.17763

**Comment by LukasThijs** [comment]
I did and that worked. The only issue is that we are currently targeting version 1903 build 18362 and have to keep targeting this version. 

Is it maybe possible to also support this version in an upcoming release?

**Comment by martijn00** [comment]
18362 is higher than 10.0.17763 so that should work anyway.

**Comment by LukasThijs** [comment]
> 18362 is higher than 10.0.17763 so that should work anyway.

Yes it should but it doesn't I just double checked and it won't find the init(); function when running on build 18362

**Comment by KevMorelli** [comment]
Having the same issue targeting Windows Build 18362
![image](https://user-images.githubusercontent.com/12283570/96494955-7ae34b80-121d-11eb-9ff1-0d99f538ea51.png)

![image](https://user-images.githubusercontent.com/12283570/96494909-669f4e80-121d-11eb-88e1-1a1b5f6cfc41.png)

**Comment by KevMorelli** [comment]
Fixed by setting the Min Version to Windows 10 Build 17763, changing only the target version doesn't fix the issue
