### ISSUE TITLE
UWP fail to build

### ISSUE THREAD

**Issue by NightOwlCoder** [rotorgames/Rg.Plugins.Popup#573]
Trying to build a UWP project is failing with

`The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)`

Even the sample is failing.

I went back to `2.0.0.3` and it also fails.

Did something changed but the docs/samples were not updated?

**Comment by Kornelis** [comment]
Which Version are you targeting?

Had the same Issue which was resolved by setting the Min Version to "Windows 10, version 1809 (10.0; Build 17763)"
