### ISSUE TITLE
App Crash when start new activity while popupstack is not empty

### ISSUE THREAD

**Issue by tszenyew** [rotorgames/Rg.Plugins.Popup#574]
Android App crashed when starting new Intent activity while PopupStack still contain page in it . (eg , user tap on remote notification that trigger new intent activity) 

the new intent Activity i create is MainActivity , and in OnCreate Method , i did call Rg.Plugins.Popup.Popup.Init again.

Exception throw : 
Unable to activate instance of type Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer from native handle 0x7fd09a5de4 (key_handle 0x5e0ca5c)

**Comment by LuckyDucko** [comment]
hey @tszenyew 

Could you provide a base example for me to work through your issue? The dual calling of Rg.Plugins.Popup.Popup.Init seems suspect. I wonder if you wrap that in a try catch and ignore the error if it is fine.
