### ISSUE TITLE
Events raised multiple times

### ISSUE THREAD

**Issue by Pantheas** [rotorgames/Rg.Plugins.Popup#575]
## 🐛 Bug Report

Whenever a popup is opened / closed, the events `Pushed` and `Popped` are raised multiple times (I stopped counting at 60).

I did not test with `Pushing` and `Popping`.

### Expected behavior
`Pushed` and `Popped` are raised just once for every popup opened / closed.

### Reproduction steps
1) Append do `PopupNavigation.Instance.Pushed` and `PopupNavigation.Instance.Popped`
2) Add breakpoints to the event handlers
3) Open a popup
4) Add counter algorithm or count manually
5) Close the popup
6) Add counter algorithm or count manually

### Configuration

**Version:** 2.0.04

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
Hi @Pantheas 
You have ticked both Android and Xamarin Forms, have you tested this on other platforms, or do you only work on Xamarin Android + Forms

I got the Develop Branch (Xamarin.Forms 4.5/ NetStandard 2.0) and tested on the following platforms with this version of App.cs

```csharp
public class App : Application
    {
        int pushCount = 0;
        int popCount = 0;
        public App()
        {
            // The root page of your application
            MainPage = new NavigationPage(new MainPage())
            {
                BarBackgroundColor = Color.FromHex("#7dbbe6"),
                BarTextColor = Color.White
            };
            PopupNavigation.Instance.Pushed += CountMePush;
            PopupNavigation.Instance.Popped += CountMePop;
        }

        private void CountMePop(object sender, Rg.Plugins.Popup.Events.PopupNavigationEventArgs e)
        {
            popCount++;
            Console.WriteLine(string.Concat("Pops: ", popCount));
        }

        private void CountMePush(object sender, Rg.Plugins.Popup.Events.PopupNavigationEventArgs e)
        {
            pushCount++;
            Console.WriteLine(string.Concat("Pushes: ", pushCount));
        }

        protected override void OnStart()
        {
            // Handle when your app starts
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }
```

Demo.Mac -> Working as Expected on MacBook Pro
Demo.Droid -> Working as Expected on Samsung A20
Demo.iOS -> Working as Expected on iPhone XS

I wasn't able to test any other environment, but believe these should cover it. (sorry about the stretched gif)



![gif example](https://j.gifs.com/VAGER5.gif)

**Comment by Pantheas** [comment]
Hi @LuckyDucko,
thanks for your fast reply!

I ticked only Xamarin.Forms and Android as I am only working with these platforms...
I am a little astonished that this is working as expected on your side. I have the latest XF version installed, could this be the issue?

Cheers

**Comment by LuckyDucko** [comment]
No worries @Pantheas 

I was thinking about testing that, and then promptly forgot.

Demo.Mac -> Working as Expected on MacBook Pro using latest XF
Demo.Droid -> Working as Expected on Samsung A20 using latest XF

Didn't test on iOS as after those two, I expect it would be fine.

How are you attaching to the pop/push events? it seems that you have a loop somewhere concerning it

**Comment by Pantheas** [comment]
The issue occured because of dependency injection on my side.
I created a wrapper class around your `PopupNavigation.Instance` because I wanted to show/hide popups using ViewModels (via generics).
I did not register my `PopupController` as specific instance, but attached to the `Pushed` and `Popped` events in the constructor.
