### ISSUE TITLE
ListView is not filling inside popup on iPhone 11 (14.0)

### ISSUE THREAD

**Issue by bhuvan94** [rotorgames/Rg.Plugins.Popup#581]
## 🐛 Bug Report

List view not filling inside the popup view on iPhone 11 (14.0). It was working fine in iPhone 11 (13.2.2). Please find the screen shot and sample below. I have set Red Background color to Listview

### Expected Behavior:
![13 2 2](https://user-images.githubusercontent.com/20217737/94556362-8d9bdd80-027a-11eb-9738-852389582dfa.png)

### Actual Behavior:
![14 0](https://user-images.githubusercontent.com/20217737/94556353-8b398380-027a-11eb-9145-960039c675b3.png)

Please find the sample here [popup_issue.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/5298817/popup_issue.zip)

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

### Workaround:
Couldn't find any.

**Comment by bhuvan94** [comment]
Hi ,

Any update on this.

**Comment by LuckyDucko** [comment]
hi @bhuvan94 

I changed MainPage.xaml/xaml.cs to be just a popup page, without using ContentView and then I called it directly, not using your CustomPopup.cs control

I also updated all the packages to latest.

It seems to have resolved the issue. 
See the [attached project](https://github.com/rotorgames/Rg.Plugins.Popup/files/5345430/App4-2.zip) for my working example. 

@martijn00 can close.

**Comment by bhuvan94** [comment]
Hi @LuckyDucko,

I'm facing same issue with you Updated sample.

**Comment by LuckyDucko** [comment]
@bhuvan94 

Can you remake your list view on the demo version of this plugin, on he listview page? I'll confirm again that my solution did not show the bug.

**Comment by bhuvan94** [comment]
Hi @LuckyDucko ,

I have checked with latest version 2.0.0.6, facing same issue. For clarification are you checking with iPhone 11 version 14.0 ?

**Comment by bhuvan94** [comment]
Hi @LuckyDucko ,

Any update on this ?

**Comment by LuckyDucko** [comment]
@bhuvan94 I cannot reproduce this issue with my updated one. I checked on simulator, and on an iPhone XS. 

Can you try and reproduce the issue with the following condition
1. Use the demo project ListView
2. do not use your custom csharp popuppage addition

this is just to rule out if its something that isnt related to rg
