### ISSUE TITLE
Multiple animations ?

### ISSUE THREAD

**Issue by tonyfonager** [rotorgames/Rg.Plugins.Popup#588]
Hi there, thanks for at very nice plugin.

Is it possible to combine animations on a page ?

For example combining Move and Scale ? Or would I have to create my own animation for that to work ?

**Comment by LuckyDucko** [comment]
Unfortunately, I believe you would have to create your own animation.

Have a look [here](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Animations) for some details about it
