### ISSUE TITLE
Create a License file

### ISSUE THREAD

**Issue by joseprl89** [rotorgames/Rg.Plugins.Popup#59]
At the moment, the project does not have a license file.

Could you please add one so it is clear under which terms this library can be used?

**Comment by rotorgames** [comment]
@joseprl89 See end of readme.

**Comment by joseprl89** [comment]
Could you move that into a License.md file so it's consistent with other github repos and more visible?

**Comment by rotorgames** [comment]
@joseprl89 Ok.
