### ISSUE TITLE
Xamarin iOS No text in popup

### ISSUE THREAD

**Issue by stefantanaskovic18** [rotorgames/Rg.Plugins.Popup#593]
I cant reproduce it on any of my devices but client have iPhone 8 and he did it.
I have 5,6 popups across the app and on every he doesnt see the text. He sees only pictures on it.
Every text is in label and its getting from model with Binding.
On my iPhone 8 everything is working fine and in console there is no error.
Does anyone know what can this be?

**Comment by LuckyDucko** [comment]
Does the client have some sort of Text scaling? That could cause issues

**Comment by stefantanaskovic18** [comment]
Unfortunately he just answered me  this:
No, nothing in the accesibility settings.

Venlig hilsen

I took log from his mobile and it will be in the attachment
[log (1).txt](https://github.com/rotorgames/Rg.Plugins.Popup/files/5463918/log.1.txt)

**Comment by LuckyDucko** [comment]
while this has a lot of information, unless there is some reproducible example, im unsure what help I can provide

**Comment by rjhind** [comment]
FWIW, I've just had this issue.  ListView in popups working but no text.  For me, it was related to dark mode.  Setting UIUserInterfaceStyle to Light fixed it for me so the app works in both dark and light mode.

**Comment by stefantanaskovic18** [comment]
Great. That was the issue.
Thank you so much. If you ever come to Serbia please let me know so i can pay you a drink or something.
