### ISSUE TITLE
/usr/local/share/dotnet/sdk/3.1.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1073: le FrameworkReference 'Microsoft.WindowsDesktop.App.WPF' n'a pas été reconnu (NETSDK1073) 

### ISSUE THREAD

**Issue by ahmedlimam** [rotorgames/Rg.Plugins.Popup#594]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
@ahmedlimam do you get this same error on version 2.x?
