### ISSUE TITLE
[WPF] Pressing "Open Popup" twice causes the demo application to crash.

### ISSUE THREAD

**Issue by uk-taniyama** [rotorgames/Rg.Plugins.Popup#595]
## 🐛 Bug Report

Demo Application on WPF.
1. Press "Open Popup" -> Open Popup.
2. Press background -> Close Popup.
3. Press "Open Popup" -> Crash!!
throw new InvalidOperationException("The page has been pushed already. Pop or remove the page before to push it again");

### Configuration

**Version:** 2.0.0.6

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [X] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
@uk-taniyama I finally got myself a windows computer and can confirm this behaviour, I'll try and look into it :+1:

**Comment by VladislavAntonyuk** [comment]
#557

**Comment by iashaik** [comment]
Can't replicate this issue, most probably fixed with #604

**Comment by LuckyDucko** [comment]
@iashaik thanks for that, I haven't had much experience concerning WPF, so your PR was very helpful.

I'll confirm this in the next couple of days when I have a chance

**Comment by iashaik** [comment]
@LuckyDucko

No issues, I have added a test on the demo page called setting, you cna just run there to test. 

Tag me if there are any WPF specific issues.

**Comment by LuckyDucko** [comment]
@iashaik while this issue is fixed, I have noticed something new.

Currently, with 'Close on Background click' on, if you click anywhere, including within the popup, it seems to treat it like a background click and close it? any ideas

**Comment by iashaik** [comment]
> @iashaik while this issue is fixed, I have noticed something new.
> 
> Currently, with 'Close on Background click' on, if you click anywhere, including within the popup, it seems to treat it like a background click and close it? any ideas

I can take a look, most probably some hit testing issue. 

Do we have a bug created? 

Thanks.

**Comment by LuckyDucko** [comment]
@iashaik see #557
