### ISSUE TITLE
[iOS] View is not in windows hierarchy

### ISSUE THREAD

**Issue by DevinvN** [rotorgames/Rg.Plugins.Popup#6]
I've gotten the following warning when trying to display a popup on iOS:

 Warning: Attempt to present <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x14a1eebe0> on <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x14a1d4b60> whose view is not in the window hierarchy!

I sadly haven't been able to reproduce it yet. This has only happened once, restarting the app and trying again fixed it.

Once I have reproduced I'll let you know

**Comment by rotorgames** [comment]
@DevinvN Hi friend. This is a critical mistake? This warning is an application crash?

**Comment by DevinvN** [comment]
No it's just a warning I see in the log, it just doesn't show the popup. Application keeps working, except no popup is shown.

**Comment by rotorgames** [comment]
@DevinvN Please, write what is your:
Mac OS or Windows version,
Xamarin.IOS version,
Xamarin.Forms version,
Xamarin Studio (Visual Studio) verions

**Comment by rotorgames** [comment]
@DevinvN And
IOS SDK version
Device (Simulator) target SDK version

**Comment by DevinvN** [comment]
I will get this information for you, but I do want to point out, that it's working correctly now. This only happened once since I started using the plugin.

**Comment by DevinvN** [comment]
OS: Windows 10 Pro (build 10586)
Xamarin iOS: 9.4.2.24
Xamarin Forms: 2.1.0.6524
Visual Studio Professional 2015 Update 1
iOS SDK: 9.2
iPad Air 2 with iOS 9.2.1

**Comment by rotorgames** [comment]
@DevinvN English is not my native language. Therefore, I could not properly understand you.

As I have now realized plugin works, Popup page open? If it works, it's good.

Perhaps you tried to open the popup page until you see the main page.

If you want to show the Popup page immediately after the application is started or immediately after opening another page. Do this in the `OnAppearing` and do not do it in the constructor of the class !! It is very important!

Thank you.

**Comment by DevinvN** [comment]
Yeah I guessed so, that's why I wanted to make sure you understood. I open it in the event of a tapgesture. But it might have been right after it navigated to the next page.

**Comment by belandsoft** [comment]
I get the same error, I have an application that uses https://components.xamarin.com/view/sidebarnavigation
on the root page i have a button that make the popup dialog come up.

The first time I open the app the button fires up the popup correctly, even if I close the popup dialog and open it agai, BUT if I navigate to another page throw the sidebar and than come again to the root page, the button doesn't fire the popup anymore and i see the same warning inside the output console.
