### ISSUE TITLE
[IOS]ListView selectedItem does not show after popup

### ISSUE THREAD

**Issue by behzad62** [rotorgames/Rg.Plugins.Popup#60]
This problem happens only on IOS. Create a xamarin xaml forms project
add a ListView to the PopupPage and bind its SelectedItem property.
every time an item in the listview will be selected then popping and pushing the same PopupPage again, ListView does not show the selectedItem (It wont be highlighted).

**Comment by rotorgames** [comment]
@behzad62 Hi. Do you use two way binding mode?

**Comment by behzad62** [comment]
@rotorgames Hi, yes

**Comment by rotorgames** [comment]
@behzad62 What yes? This problem is in default page also?

**Comment by behzad62** [comment]
@rotorgames Yes, I use two way binding on the selectedItem property of the ListView.
well, I don't have a ListView in a default page, nor I Push/Pop that page. Currently I am using a PopupPage to select a category and pop it as soon as a new category is selected. But next time that I push this PopupPage again, On the IOS project, previousely selected category is not highlighted.

**Comment by rotorgames** [comment]
@behzad62 I don't understand you. You open secondary PopupPage and "SelectedItem" is not selected? Or you try to click on item but it is not selected?

**Comment by behzad62** [comment]
@rotorgames No, there is only one PopupPage which is instantiated in my MainPageViewModel. Every time  
user wants to select a category, the same instance will be pushed. The problem is that when this PopupPage is shown again, the previousely selected category is not highlighted on the ListView. I checked and selectedItem property of the ListView was not null. Also, I did many tests and created a new project to check if this problem exists and I could reproduce it.

**Comment by rotorgames** [comment]
@behzad62 Ok. Can you send your project in github and give me access?

**Comment by behzad62** [comment]
@rotorgames Sorry for delay, I just uploaded the test project to Git and sent you the link. Please let me know if you didn't get it. I am not familiar to the git.

**Comment by rotorgames** [comment]
@behzad62 Please wait

**Comment by rotorgames** [comment]
@behzad62 I tested your project and I confirm this bug. But I can't fix this problem because source of it is in Xamarin.Forms code. 

You can verify this if you make it in MainPage:

```charp
public partial class MainPage : ContentPage
{
    Popup page;
    public MainPage()
    {
        InitializeComponent();
        page = new Popup();
    }
    private async void OpenPopup(object sender, EventArgs e)
    {
        await Navigation.PushModalAsync(page);
        // or
        Application.Current.MainPage = page;
    }
}
```

You should write in [Xamarin Bugzilla](https://bugzilla.xamarin.com/) about your problem. 

You may fix this problem, if you will set `BindingContext` in `OnAppearing` method.

```csharp
public partial class Popup : PopupPage
{
    public Popup()
    {
        InitializeComponent();
    }

    protected override void OnAppearing()
    {
        base.OnAppearing();

        BindingContext = new PopupViewModel();
    }
}
```

It is temporary fix but I don't know any fix of this bug.

Thank you.

**Comment by mpnow** [comment]
@rotorgames I'm having a very similar issue. In my case it's not that SelectedItem isn't highlighted but that after closing the popup, the SelectedItem binding to my view model is no longer working.

In other words, in my ListView I have:

`SelectedItem="{Binding SelectedEvent, Mode=TwoWay}"`

I click an item, the SelectedEvent property is correctly updated in my view model, and I display the popup page as a result. I then close the popup. When I then click on a ListView item, nothing happens - the property is not set in the view model.

I tried the above workaround of setting the BindingContext in OnAppearing but that didn't help any.
