### ISSUE TITLE
Popups are not visible with disabled status bars in iOS

### ISSUE THREAD

**Issue by aptwebapps** [rotorgames/Rg.Plugins.Popup#605]
## 🐛 Bug Report

Popups are not visible with disabled status bars in iOS

### Expected behavior

Popups should be visible.

### Reproduction steps

Take the sample shared + iOS projects and add the following to the iOS projects info.plist:

    <key>UIViewControllerBasedStatusBarAppearance</key>
    <false/>

Then add the following to AppDelegate.FinishedLaunching():

    UIApplication.SharedApplication.StatusBarHidden = true;

When attempting to open the login popup via the button on the main page, nothing happens. I've tested on a 6th gen iPad, an iPhone 8, and several simulators.

### Configuration

**Version:** 2.0.0.7

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by aptwebapps** [comment]
I should add that the popup is definitely opening, it is just not visible and neither is the background tint.

I'm not sure this is the standard way of hiding the status bar. In my full application I'm am doing it via a service, but this is the simplest reproduction of the bug that I could manage.

**Comment by LuckyDucko** [comment]
@aptwebapps could you verify this with the latest version of the plugin?

**Comment by aptwebapps** [comment]
I haven't been able to check my own app yet as I'm hitting a new issue (#613) which occurs before I get to the part of my app with the hidden status bars.

**Comment by aptwebapps** [comment]
I can confirm it is fixed in the demo app as described in my description, so feel free to close it, I think.

**Comment by aptwebapps** [comment]
Fixed with 2.0.0.9
