### ISSUE TITLE
Error with xamarn forms 4.7.0.1239 and Rg.Plugins.Popup  7.2.0.1046 and  prism.dryloc.forms 8.0.0.1909

### ISSUE THREAD

**Issue by lopezcr** [rotorgames/Rg.Plugins.Popup#607]
After the installation of Rg.Plugins.Popup 7.2.0.1046 in xamarin forms 4.7.0.1239 and and  prism.dryloc.forms 8.0.0.1909, update the app.xaml, the MainActivity and the appdelegate and compile marks an error in:

app.xaml on the line: Public App (IPlatformInitializer initializer): base (initializer)

with the following error:

prism.loc.ContainerResolutionException: 'An unexpected error occurred while resolving' Prism.Navigation, INavigationService ''

Does anyone know how to correct the problem

**Comment by LuckyDucko** [comment]
>Rg.Plugins.Popup 7.2.0.1046

Rg.Plugins.Popup is on version 2.0.0.7, however, the prism version, [Prism.Plugin.Popups](https://github.com/dansiegel/Prism.Plugin.Popups), is on version 7.2.0.1046. I believe you'd find better help suited for your issue there.

**Comment by lopezcr** [comment]
> > Rg.Plugins.Popup 7.2.0.1046
> 
> Rg.Plugins.Popup is on version 2.0.0.7, however, the prism version, [Prism.Plugin.Popups](https://github.com/dansiegel/Prism.Plugin.Popups), is on version 7.2.0.1046. I believe you'd find better help suited for your issue there.

Since I'm in a hurry, I think I'll use an older version of prism.dryloc.forms, which I already saw works for me, thanks

**Comment by LuckyDucko** [comment]
@martijn00 can close
