### ISSUE TITLE
Await the result in the calling page.

### ISSUE THREAD

**Issue by SudhersonV** [rotorgames/Rg.Plugins.Popup#608]
## 🚀 Feature Requests

The pop up result should be awaited in the page that called the pop up.

### Contextualize the feature
When the user is asked to make a choice, the code must await for the user's decision before it can continue.

### Describe the feature
We wanted to display Terms Of Use to users and don't let them login unless the answer is yes. We wish to await the user's response.

Example:
`var answer = await _rg.plugins.Popup.DisplayPopup();`

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
hey @SudhersonV I make an extension on top of rg.plugins.popup to enable this functionality which you can find [here](https://github.com/LuckyDucko/AwaitablePopups)

**Comment by acaliaro** [comment]
https://acaliaro.wordpress.com/2020/12/07/create-a-popup-using-rg-plugins-popup-and-get-a-return-value/

**Comment by LuckyDucko** [comment]
@martijn00 can close
