### ISSUE TITLE
Popup page won't open on a modal inside a navigation page

### ISSUE THREAD

**Issue by ilker55** [rotorgames/Rg.Plugins.Popup#61]
I have this problem that I can't open a popup page from a modal page which is inside a second navigation page. The popup page doesn't show up.

Here's a quick drawing of what I want:
<img width="1073" alt="screen shot 2016-11-21 at 11 31 42" src="https://cloud.githubusercontent.com/assets/3458122/20479340/1d22d556-afde-11e6-8078-98787b8184fa.png">

If I open the modal without a navigation page the popup does shows up.

**Comment by rotorgames** [comment]
@ilker55 Duplicate #49. Please, wait for `v1.0.4`
