### ISSUE TITLE
Can't get plugins to open with Xamarin Forms 5.0 -pre5 

### ISSUE THREAD

**Issue by rs-mobitech** [rotorgames/Rg.Plugins.Popup#610]
## 🐛 Bug Report

With XF 5.0 -pre5 I find my plug code areas are no longer working when I use the current latest version which is 2.0.0.7

    private async Task OpenPrefAsync()
    {
       BaseButtonSheet bottomSheet = new BaseButtonSheet();
       await PopupNavigation.Instance.PushAsync(bottomSheet);
    }

When I revert back to the 4.8 XF then the code works again.

### Expected behavior

Trying to open a new popup in XF 5.0 -pre5,  expect the popup to open but nothing happens

### Reproduction steps

    private async Task OpenPrefAsync()
    {
       BaseButtonSheet bottomSheet = new BaseButtonSheet();
       await PopupNavigation.Instance.PushAsync(bottomSheet);
    }

### Configuration

**Version:** 2.0.0.7

**Platform:** 
- [x ] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
@rscholey hmm, which platform are you running this on? does this happen with the demo?

Edit- I just realised, this issue may have been fixed, just waiting on @martijn00 to release the latest NuGet

**Comment by LuckyDucko** [comment]
@rscholey can you confirm that your issue is fixed with the latest pre-release?

**Comment by rs-mobitech** [comment]
I will check into that soon.  What was the change that was made with the latest pre-release?

**Comment by paul-kiar** [comment]
I have tried this with Xamarin Forms 5.0 full release and it hangs when you try to show a popup.

Forgot to mention this is on iOS 14.4 (beta)

**Comment by LuckyDucko** [comment]
@paul-kiar which version of the plugin are you using?

**Comment by paul-kiar** [comment]
Ng.Plugins.Popup 2.0.0.5 just updated to 2.0.0.10 and it is fixed.
