### ISSUE TITLE
Must call Init error after upgrading from 2.0.0.6 to 2.0.0.8 in UWP project

### ISSUE THREAD

**Issue by gceaser** [rotorgames/Rg.Plugins.Popup#612]
## 🔙 Regression

After upgrading from 2.0.0.6 to 2.0.0.8 in my UWP project I started receiving the error message: 

"You MUST install Rg.Plugins.Popup to each project and call Rg.Plugins.Popup.Popup.Init(); prior to using it.
See more info: https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#initialization"

This is a summary of my OnLaunched code from the UWP project:
           // Add `using System.Reflection;` 
            List<Assembly> assembliesToInclude = new List<Assembly>();
            Frame rootFrame = Window.Current.Content as Frame;
         
            // Do not repeat app initialization when the Window already has content,
            // just ensure that the window is active
            if (rootFrame == null)
            {
                // Create a Frame to act as the navigation context and navigate to the first page
                rootFrame = new Frame();

                rootFrame.NavigationFailed += OnNavigationFailed;

                Rg.Plugins.Popup.Popup.Init();
                SfListViewRenderer.Init();

                //Now, add all the assemblies that your app uses 
                assembliesToInclude.AddRange(Rg.Plugins.Popup.Popup.GetExtraAssemblies());              
                Xamarin.Forms.Forms.Init(e, assembliesToInclude);

### Old (and correct) behavior
In 2.0.0.6 an exception was not generated
### Current behavior
I receive the error message as indicated above.  
### Reproduction steps
Create a UWP project and install 2.0.0.6.
Use the AddRange function as shown above to include all the needed Rg.Plugins.Popup assemblies.
Run code that attempts to display a popup.  The app will run correctly.

Upgrade the nuget package to 2.0.0.8 and make no other changes.
Run the app and hit the code that attempts to display a popup.
You will receive  the error message shown above. 

### Configuration

**Version:** 2.0.0.6 --> 2.0.0.8

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by rdeveen** [comment]
Version 2.0.0.7 also does not give above error. Only version 2.0.0.8 give this error.

**Comment by rdeveen** [comment]
In [this](https://github.com/rotorgames/Rg.Plugins.Popup/compare/2.0.0.7...2.0.0.8#diff-334c05f54edd15c69be291f32c8fd6c70699e1140cee2bee8b22d6db570a5a5bL52) the register of the PopupPlatformWinPhone has been removed but the check if IPopupPlatform is registerd is still there.

Check is here: 
https://github.com/rotorgames/Rg.Plugins.Popup/blob/d14e753a349cdf52e2ae2d33e91c66de0582fe63/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs#L30-L33

`var popupPlatform = DependencyService.Get<IPopupPlatform>();`

This implementation is missing in v2.0.0.8
https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/Rg.Plugins.Popup/Platforms/Uap/Impl/PopupPlatformWinPhone.cs
