### ISSUE TITLE
NullReferenceException when closing a popup on iOS

### ISSUE THREAD

**Issue by aptwebapps** [rotorgames/Rg.Plugins.Popup#613]
## 🐛 Bug Report

On iOS a NullReferenceException is thrown when closing a popup

### Expected behavior

No exception

### Reproduction steps

Run the demo app on an iOS device or simulator. Click the first "Open Popup" button. After it opens, tap the red X button.

### Configuration

**Version:** 2.0.0.8

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

The specific line is https://github.com/rotorgames/Rg.Plugins.Popup/blob/d14e753a349cdf52e2ae2d33e91c66de0582fe63/Rg.Plugins.Popup/Platforms/Ios/Platform/PopupPlatformRenderer.cs#L61

It is the ViewController property which is null, but I haven't tried to figure out why it is so.

**Comment by MarLoe** [comment]
I am getting the exact same exception.
Seems to be introduced by #609

**Comment by arahmancsd** [comment]
I am getting the same error in iOS 14.2 after updating to the latest version of the plugin 2.0.0.8

**Comment by RagulChandra** [comment]
I am also getting same error

**Comment by gdidajj** [comment]
I am also getting same error

**Comment by MarLoe** [comment]
@LuckyDucko & @martijn00, thank you for your quick response - really appreciated!
