### ISSUE TITLE
App crash when closing popup window from button

### ISSUE THREAD

**Issue by shweta1915** [rotorgames/Rg.Plugins.Popup#614]
## 🐛 Bug Report

PopupPlatformRenderer.PrefersStatusBarHidden () C:\Users\mhvdi\Documents\OpenSource\Rg.Plugins.Popup\Rg.Plugins.Popup\Platforms\Ios\Platform\PopupPlatformRenderer.cs:61
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:86
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:65
Application.Main (System.String[] args) /Users/amitkumar/Projects/DipCloud/dipsecure/DipSecure.iOS/Main.cs:17

### Expected behavior
The app should not crash when clicking on the close button

### Reproduction steps
1. Install the latest Rg.Plugins.Popup (Version: 2.0.0.8)
2. Install the latest Xamarin.Forms (Version: 4.8.0.1451)
3. Create a simple popup view and add one close button
4. When the user click on a close button it crashes the app

Also, there are some errors showing when adding a popup window. following is the screenshot.
![image](https://user-images.githubusercontent.com/74226630/101771406-e2c45d00-3b0f-11eb-8c4f-d4c9dfcb1189.png)

Here is the report generated from the App center for the same issue:

[report-2517946988230009999-77e9e745-2090-4fd1-a974-b8a8ff3ee224.txt](https://github.com/rotorgames/Rg.Plugins.Popup/files/5672591/report-2517946988230009999-77e9e745-2090-4fd1-a974-b8a8ff3ee224.txt)

### Configuration

**Version:** 2.0.0.8

**Platform:** 
- [ ] :iphone: iOS 14.2
- [ ] :robot: Android 10

**Comment by RagulChandra** [comment]
Yes. It is crashing for me in same scenario.

**Comment by amirvenus** [comment]
Is there a last known good version where this issue does not occur on?

**Comment by LuckyDucko** [comment]
We just added release 2.0.0.9 that should address this, sorry for the regression

**Comment by anhhtbk** [comment]
When release 2.0.0.9?
