### ISSUE TITLE
[UWP] 'You MUST install Rg.Plugins...' even though it's already installed

### ISSUE THREAD

**Issue by sqrg** [rotorgames/Rg.Plugins.Popup#616]
## 🐛 Bug Report

I have a Xamarin.Forms application. And on the UWP platform I get this error, even though I have Rg.Plugins.Popup installed in every project.

```
System.InvalidOperationException: You MUST install Rg.Plugins.Popup to each project and call Rg.Plugins.Popup.Popup.Init(); prior to using it.

See more info: https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#initialization
```

This is how I'm doing the initialization:
```
protected override void OnLaunched(LaunchActivatedEventArgs activationArgs)
        {
            base.OnLaunched(activationArgs);

            Rg.Plugins.Popup.Popup.Init();
            Xamarin.Forms.Forms.Init(activationArgs, Rg.Plugins.Popup.Popup.GetExtraAssemblies());
        }
```

### Configuration

**Version:** 2.0.0.8
**Xamarin.Forms** 4.7.0.1080

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by rdeveen** [comment]
Possible duplicated see: https://github.com/rotorgames/Rg.Plugins.Popup/issues/612

**Comment by sqrg** [comment]
Yes, you're right. Thanks! Will close this and follow #612
