### ISSUE TITLE
returning values

### ISSUE THREAD

**Issue by rocketbob** [rotorgames/Rg.Plugins.Popup#62]
Question.  What is the proper way to return values from elements in the popup?  I don't see any methods that return a `Task<T>` to be useful to get a return value from something in a popup.

**Comment by rocketbob** [comment]
I ended up binding the page to a viewmodel.  Which works fine but it would be nice to be able to return a Task<T> to avoid having a view model for simple alert-type things.

**Comment by rotorgames** [comment]
@rocketbob Duplicate. See #14
