### ISSUE TITLE
Documentation for Android init doesn't seem to line up with actual code

### ISSUE THREAD

**Issue by rs-mobitech** [rotorgames/Rg.Plugins.Popup#620]
Here's what [the document](https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started) states:

        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            Rg.Plugins.Popup.Popup.Init(this, bundle);
        
            Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication (new App ());
        }

Here's the code:

    public static void Init(Context context)
    {
      Rg.Plugins.Popup.Popup.LinkAssemblies();
      Rg.Plugins.Popup.Popup.Context = context;
      Rg.Plugins.Popup.Popup.IsInitialized = true;

Can someone confirm if this is an issue.  Looks like the Init method only has one argument but it's suggested to pass two.

**Comment by felipechavez** [comment]
this is related to #611

**Comment by vividos** [comment]
It seems the commit https://github.com/rotorgames/Rg.Plugins.Popup/commit/42d71b9f27630c36e2a78e586279c15b15400075 removed the Bundle parameter, as it wasn't used anyway.

**Comment by LuckyDucko** [comment]
updated the wiki, let me know if this still doesn't go well

**Comment by vividos** [comment]
I removed the extra parameter from the Init() call, and everything still works. I think @rscholey just wanted to clarify if the docs are correct.
