### ISSUE TITLE
UWP project does not initialise

### ISSUE THREAD

**Issue by MichaelEarendil** [rotorgames/Rg.Plugins.Popup#621]
UWP project throws initialisation error hen attempting to open a popup.

Initialisation has been set as instructed and the popup works as expected on android. 

Version 2.0.0.8

**Comment by LuckyDucko** [comment]
@MichaelEarendil I think #615 addresses this. Try it again with 2.0.0.9

**Comment by MichaelEarendil** [comment]
Yes,  that works, thank you

**Comment by LuckyDucko** [comment]
@martijn00 good to close
