### ISSUE TITLE
iOS only - Removing a PopupPage hides the other PopupPages

### ISSUE THREAD

**Issue by cbananas** [rotorgames/Rg.Plugins.Popup#622]
## 🐛 Bug Report
If you have two PopupPages 1 and 2 (both visible) and remove PopupPage 1, the other PopupPage 2 "disappears". If you re-add PopupPage 1 then 2 reappears. I believe this was introduced by the fix for bug #393 where WindowLevels are set.

### Expected behavior
PopupPage 2 should stay visible

### Reproduction steps
Attached is sample project.
- Click "Popup 1" (blue)
- Click "Popup 2" (green) - both popups now visible
- Click "Close Popup 1"
- Popup 1 is removed (correct), Popup 2 disappears (incorrect)

[RGPopupReplicate.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/5690234/RGPopupReplicate.zip)

**Version:** LATEST

**Platform:** 
- [14.2] :iphone: iOS

**Comment by LuckyDucko** [comment]
@cbananas I can confirm this happens.

I have poked around the commit, and it seems that the magnification behaviour we have seen is no longer part of iOS as far as I am aware. reverting the commit SEEMS to have some fixes, but I need to test some more

**Comment by LuckyDucko** [comment]
@cbananas this should be all sorted now, with the fix in the next nuget update

**Comment by cbananas** [comment]
Excellent, thanks!
