### ISSUE TITLE
Update To 2.0.0.9 Causing Error

### ISSUE THREAD

**Issue by GDT48** [rotorgames/Rg.Plugins.Popup#624]
## 🔙 Regression

<When I update from 2.0.0.6 to 2.0.0.9 I get the following error on line:>

### In MainActivity.cs                Rg.Plugins.Popup.Popup.Init(this, savedInstanceState);    After update results in error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1501	No overload for method 'Init' takes 2 arguments	HomeProjectPlanner.Android	

### Configuration

**Version:** 2.0.0.8 and 2.0.0.9

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by DiegoFaFe** [comment]
@GDT48  The parameter was removed in commit [42d71b9](https://github.com/rotorgames/Rg.Plugins.Popup/commit/42d71b9f27630c36e2a78e586279c15b15400075#diff-26aae7721902c0366d06e25a744551a81bb95b04d94b0a2ea96908dd1e470c9a). Just remove it

**Comment by LuckyDucko** [comment]
updated the wiki, @DiegoFaFe is correct
