### ISSUE TITLE
Smaller solution for popup promt?

### ISSUE THREAD

**Issue by stefancvetkovic** [rotorgames/Rg.Plugins.Popup#63]
Hi,
I'm new to the Xamarin.Foms, I cloned it your solution and it works great! But however, I want just a part of it - just popup prompt to be able to include into my project.
What should I keep, and what I can remove from your project?

Also, when I go through NuGet packages, I cant build simple class "MyPage", but manually if I add tthen it works?

**Comment by rotorgames** [comment]
@stefancvetkovic Hi. You must install this plugin from nuget in every project (pcl, android, ios, wp, uwp). After, you must create your page and you must extend it from PopupPage.

See many examples in demo projects.

**Comment by stefancvetkovic** [comment]
@rotorgames I started a blank xamarin.forms (Portable) project.
I am using version of Xamarin.Forms 2.3.3.168.
Below, I added my repo with some basic pages that you created (MainPage.xaml,LoginPopupPage.xaml, LoadingPopupPage.xaml,LoadingSuccessPopupPage.xaml)

[https://github.com/stefancvetkovic/PopUp006](here is my solution)

When I rebuild it, there is 0 errors. And when I start to deploy on my device (hit F5) it breaks.

Please see this image:
![2016-11-26 16_27_01-popup006 debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/13699747/20641425/c9fea440-b3f7-11e6-9628-80dd0200abc2.png)

There is apparently some issue regarding xaml? But I can't find it out.

Thank you very much! Greetings from Serbia.

**Comment by rotorgames** [comment]
@stefancvetkovic Man, you can't just copy my xaml pages files to your project because doesn't know that it is xaml. You must create you xaml file and copy content to it or set generate programm to file property.

Do you speak Russian?

**Comment by stefancvetkovic** [comment]
@rotorgames Sorry, I overlooked that in MainPage.xaml i called some methotds which I was removed.
Now it works just fine! Thank you my Russian brother!
Спасибо. Русские и сербы братья навек!

**Comment by rotorgames** [comment]
@stefancvetkovic I glad to hear it. Good buy.
