### ISSUE TITLE
App Crash in ChildViewControllerForStatusBarHidden

### ISSUE THREAD

**Issue by cmkarthik210** [rotorgames/Rg.Plugins.Popup#635]
## 🔙 Regression

We are using this package for past 3 years and we have not faced anything like this in our project.

On app started crashing  in last 2 days and we got the crash log which is attached with this post.

[CrashReport.txt](https://github.com/rotorgames/Rg.Plugins.Popup/files/5893812/CrashReport.txt)

Please help us on this issue.

We are not able to update the package from 1.2.0.223 to higher version because of dependencies.

We have all latest SDK and API installed in our Visual Studio and all other nuget packages also up to latest mark except (Rg.Plugin (using 1.2.0.223 version)).

The app is created using Xamarin Forms version 4.7. 

Thank you

### Old (and correct) behavior
Working fine in all older iOS iPhone(s) like 13 and 14 also.
### Current behavior
But in 14.3 version of iOS is giving us app crash.
### Reproduction steps
We do not know the exact scenarios in which the app is getting crash. As it is not happening consistently is the problem (but the client wants the solution for this). 
### Configuration
Visual Studio Community 2019 for Mac 

=== Xamarin.Profiler ===
Version: 1.6.15.68

=== Xamarin.Android ===
Version: 11.1.0.26 (Visual Studio Community)

=== Apple Developer Tools ===
Xcode 12.4 (17801)

=== Xamarin.iOS ===
Version: 14.8.0.3 (Visual Studio Community)
Branch: xcode12.3

=== Operating System ===
Mac OS X 10.16.0

**Version:** 1.2.0.223

**Platform:** 
- [Issue ] :iphone: Xamarin iOS
- iOS Version 14.3

**Comment by LuckyDucko** [comment]
@cmkarthik210 what dependencies are stopping you from upgrading to a newer version of the plugin? is some other dependency you have reliant on the older 1.2 version of this plugin?

I think that it was [fixed](https://github.com/rotorgames/Rg.Plugins.Popup/issues/605) in version 2.0.0.9.
