### ISSUE TITLE
Android Crash issue on PopupNavigation.PushAsync(this);

### ISSUE THREAD

**Issue by EkambaramE** [rotorgames/Rg.Plugins.Popup#64]
Please find the attachment..

I'm pushing from one screen and popping from another screen.. 
I'm trying to popup Using :  PopupNavigation.PushAsync(this);

Its working in iOS perfectly, 
Android getting crashed... 

![screen shot 2016-11-28 at 4 57 59 pm](https://cloud.githubusercontent.com/assets/11871096/20666777/ed1c20b6-b58b-11e6-8ab5-e6dcc25a5859.png)

**Comment by rotorgames** [comment]
@EkambaramE You can't set page to several parents. If you want to do it, you should invoke Parent.RemoveView(this) before.

**Comment by rotorgames** [comment]
@EkambaramE P.S. I will fix it in next version. Thank you

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.
