### ISSUE TITLE
Standard button animations?

### ISSUE THREAD

**Issue by ajtruckle** [rotorgames/Rg.Plugins.Popup#643]
Sorry of this has already been covered but I could not find anything.

When I run my Xamarin app on my Mac and click one of the buttons on the master page you see an animation (like a flash) as expected.

But when I click button on the popup window it has no animations. Is it possible for these buttons to use the same animation behaviour as the main page? As I have not added any specific animation functionality.

Thanks for advice.

**Comment by LuckyDucko** [comment]
I would need more information for this, is the animation on the button itself? Seems like an unusual error. Can you provide a test project?

**Comment by ajtruckle** [comment]
The code you already have. Same popup. My main window which uses system buttons animate a little bit when clicked. But the popup ones do not. No animations of any kind.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
I think it must be the Pressed event perhaps,  when the standard button is pressed the button colour changes,  mine doesn’t in the popup.

**Comment by ajtruckle** [comment]
So I don't know how to debug it. But "by default" my main pages "Button" elements change colour when you press (tap) the button, At least, this automatically happens on the Mac. But not in the popup window.

Hope that makes sense.

Night.

PS. A related issue about images for my popup is here: https://stackoverflow.com/questions/66250047/using-onplatform-to-change-the-width-of-buttons-for-ios-and-macos. I could not see a rg-plugins tag to use.

**Comment by ajtruckle** [comment]
I have since found out that I can add animations to my `Clicked` handler, like this:

        async void CancelButton_Clicked(System.Object sender, System.EventArgs e)
        {
            await Task.Delay(100);
            await CancelButton.FadeTo(0.3, 100);
            await Task.Delay(100);
            await CancelButton.FadeTo(1, 100);

            // Pass the correct "button clicked" value
            if (NameEntry.IsReadOnly)
            {
                await _popupPageModel.ClosePopUp(ButtonType.No);
            }
            else
            {
                await _popupPageModel.ClosePopUp(ButtonType.Cancel);
            }
        }

This seems to work satisfactorily.
