### ISSUE TITLE
Using static resources to style buttons

### ISSUE THREAD

**Issue by ajtruckle** [rotorgames/Rg.Plugins.Popup#644]
Are there any special instructions for using static resources in popups?

I ask because I tried adding a simple button section with various properties into the app.xaml file. Then I tried to apply it in my button in the popup with `Style="{StaticResource buttonStyle}"`.

Whilst `buttonStyle` showed for me to select in the intellisense the overall line had squiqqles saying it couldn't be done. That either the Styles property was not found or the resource could not be found.

Should it be OK to add them into a resource disctionary in the app file? I was trying to set padding, backgoud colour, text colour, borderwidth and bordercolor.

**Comment by LuckyDucko** [comment]
I dont dabble in styles often. However, app.xaml should be fine, as it is used within this [project](https://github.com/rotorgames/Rg.Plugins.Popup/blob/develop/Samples/Demo/App.xaml)
