### ISSUE TITLE
OnDisappering in calling page

### ISSUE THREAD

**Issue by acaliaro** [rotorgames/Rg.Plugins.Popup#65]
Hi @rotorgames . I have a ContentPage inside a Navigation. I call Navigation.PushPopupAsync(new mypopup());
When I visualize the popup, OnDisappearing event is not called in calling page. Is it correct?

**Comment by rotorgames** [comment]
@acaliaro Hi. What do platforms have this bug?

**Comment by acaliaro** [comment]
Android 4.1.1

**Comment by rotorgames** [comment]
@acaliaro Is this bug only in PopupPage or Xamrin.Forms Page has this problem also?

**Comment by acaliaro** [comment]
Only in PopupPage

**Comment by acaliaro** [comment]
Should be OnDisapperaring raised?

**Comment by rotorgames** [comment]
@acaliaro Yes. OnDisappearing must be invoked! I tested it many time ago and it worked fine. Please wait I will test it.

**Comment by acaliaro** [comment]
thanks. Let me know if I can help you

**Comment by acaliaro** [comment]
Sorry @rotorgames I have made a mistake. my MainPage is not a NavigationPage.
It's something like

`Application.Current.MainPage = new PageA();`
where PageA is a ContentPage.

in PageA I click on a Item in listView and call

`await Navigation.PushPopupAsync(new PagePopupModificaColliSlot((PalletSpezzoneRootObject)lv.SelectedItem));`

but PageA's OnDisappearing is not called. Should it be called also in PageA is not inside a Navigation Stack?

**Comment by rotorgames** [comment]
@acaliaro I understand you. PageA will not invoke OnDisappearing in PageA never, because PageA is not disappear. PageA still in display and its live cycle is not end.

**Comment by acaliaro** [comment]
so I should remove a MessagingCenter subscription present in PageA OnDisappear... I have to remove it in PagePopup constructor ?!?

**Comment by rotorgames** [comment]
@acaliaro I dont understand. You want to invoke OnDisappearing method when PageA is disappeared? I will not do it because it is not good. PageA stills visible on display. 

If you want to know how get event when PopupPage will be closed you should use callback delegate or event in your PopupPage.
