### ISSUE TITLE
Background scrolls when popup opens in UWP

### ISSUE THREAD

**Issue by Nick-Brett-GKSYS** [rotorgames/Rg.Plugins.Popup#652]
I have a page that scrolls vertically.  There are several tap gesture recognizers on the page.  The gesture recognizers open a window to edit the value of the label that was tapped.  The problem I'm having is that the background page scrolls up when the popup shows.  Here is a screen capture of what I'm seeing.

http://candnbrett.com/scrolling.gif

**Comment by LuckyDucko** [comment]
Hey @Nick-Brett-GKSYS can you provide a project which demonstrates this bug so I can investigate further? just a minimal test example to ensure that there is nothing else at play with your project

**Comment by Nick-Brett-GKSYS** [comment]
Sorry for the delay.  Anyway, I created a sample project and this doesn't appear to be related to the Rg Plugin.  Even if I open a standard message box in UWP the background scrolls.

**Comment by LuckyDucko** [comment]
Hey @Nick-Brett-GKSYS no worries, lets hope bringing it up to xamarin gets it sorted 👍
