### ISSUE TITLE
XamlC error XFC0000 : Cannot resolve type "PopupPage"

### ISSUE THREAD

**Issue by rabileon** [rotorgames/Rg.Plugins.Popup#653]
## 🐛 Bug Report

XamlC error XFC0000 : Cannot resolve type "PopupPage"

When compiling the project having a popup page you will get this error.

on android and ios

**Platform:** 
- [x ] :iphone: iOS
- [ x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
Hey @rabileon im closing this in favour of #619 

Can you remove the use of rotorgames? and instead use `xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"` and see what happens?

**Comment by rabileon** [comment]
I have made the change when compiling the error no longer appears, but in the hot reload it appears again 😥 
![image](https://user-images.githubusercontent.com/13700488/110072210-0bd94000-7d43-11eb-8300-64e993a10b83.png)
![image](https://user-images.githubusercontent.com/13700488/110072243-198ec580-7d43-11eb-9339-519ec0452295.png)

**Comment by Erdogan34** [comment]
@rabileon is there any solution you found?
