### ISSUE TITLE
NavigationStack

### ISSUE THREAD

**Issue by acaliaro** [rotorgames/Rg.Plugins.Popup#66]
Hi @rotorgames 

In Navigation I have 

NavigationStack
ModalStack

There is not a PopupStack? How can I know if I have (in my Navigation) a Popup?

**Comment by rotorgames** [comment]
@acaliaro You can give PopupStack in `PopupNavigation.PopupStack`. 

I will write it in documentation. Thank you.

**Comment by acaliaro** [comment]
thanks to you
