### ISSUE TITLE
Issue with popup disappearing on Xamarin Forms iOS

### ISSUE THREAD

**Issue by mkozar** [rotorgames/Rg.Plugins.Popup#661]
Hi all,

I'm not sure if this is a bug or not but I need help regarding this. 

Here is my question/issue:  I have a popup that is shown on a page load event and on Android it is working as expected. When I switch to test iOS on the first time load my popup is shown and disappeared after a few seconds (without any action from the user side). If I open the page again I'm not able to see this behavior.

Thanks,
Maja

**Comment by LuckyDucko** [comment]
@mkozar sorry this slipped my mind, was it just something on your end?

**Comment by mkozar** [comment]
@LuckyDucko no problem. Thank you for your time.  Yes, it was something on my end. I got legacy code and I was not aware that the plugin version was outdated. When I update the plugin, everything is working as expected.
