### ISSUE TITLE
Popup does not work well when having an Entry with custom keyboard view.

### ISSUE THREAD

**Issue by PrasannaPatankar** [rotorgames/Rg.Plugins.Popup#665]
I have a custom keyboard view, which opens for an entry on the popup. The keyboard is getting displayed but not in the foreground therefore the user is not able to enter values. The popup works fine if the system's default keyboard is used.

Here is my XAML for the popup

```
<pages:PopupPage
    x:Class="Syft.MobileApp.Views.Deliver.DeliverPopupNew"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:localkeyboard="clr-namespace:Syft.MobileApp.Controls"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
    mc:Ignorable="d">
    <ContentPage.Content>
        <Frame
            Margin="20,0,20,0"
            BackgroundColor="White"
            CornerRadius="5"
            HasShadow="True"
            VerticalOptions="Center">
            <StackLayout>
                <localkeyboard:EntryWithCustomKeyboardReceive
                    x:Name="entryKeyboardReceive"
                    BackgroundColor="Aqua"
                    HorizontalOptions="FillAndExpand"
                    Placeholder="Custom Keyboard Numeric" />
                <Entry />
            </StackLayout>
        </Frame>
    </ContentPage.Content>
</pages:PopupPage>
```

![image](https://user-images.githubusercontent.com/30229712/114991069-d33a9380-9eb6-11eb-96d4-e8a72dd4d238.png)
![image](https://user-images.githubusercontent.com/30229712/114991105-dc2b6500-9eb6-11eb-8155-ff03efb3b658.png)

**Comment by LuckyDucko** [comment]
hey @PrasannaPatankar could you make a standalone project showing this bug I could work on.

Since it works correctly using the system default, I feel that this may be more related to your custom keyboard creation. However, I am not well aquanted with Custom Keyboards, so I need something more to work with please.

**Comment by PrasannaPatankar** [comment]
@LuckyDucko Thanks for the response and apologies for the late reply. I solved the problem by setting up the following properties to the popup.
```
    BackgroundColor="Transparent"
    BackgroundInputTransparent="True"
    CloseWhenBackgroundIsClicked="False"
    HasKeyboardOffset="False"
```
