### ISSUE TITLE
[Bug | Android] Controls dissapearing when calling PopupPage from ContentView

### ISSUE THREAD

**Issue by ScarletKuro** [rotorgames/Rg.Plugins.Popup#666]
## 🐛 Bug Report

I have ContentView from where I call simple ` await _popupNavigation.PushAsync(smartIdVerificationWaitingPage);`
and the controls disappears after a sec. It is shown on the gif below
![bug gif](https://i.imgur.com/XNS4OAR.gif)

The weird thing if i push an page before it
```
await _navigationHelper.NavigateToAsync(somePage);
await _popupNavigation.PushAsync(smartIdVerificationWaitingPage);
```
Then it will work correctly. The bug doesn't appear on iphone.

The Xamarin.Forms: **5.0.0.2012** version just in case

### Expected behavior
Excepting the controls to be on place.
![expected gif](https://i.imgur.com/JtTaAag.gif)

### Reproduction steps
made a reproduction repository https://github.com/ScarletKuro/Repro-of-android-bug-in-Rg.Plugins.Popup-

### Configuration

**Version:** 2.0.0.11

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
hey @ScarletKuro are you able to provide a sample project showing this happening that you could upload, as this definitely isnt normal behaviour

**Comment by ScarletKuro** [comment]
@LuckyDucko 
Yes, I made a reproduction repository https://github.com/ScarletKuro/Repro-of-android-bug-in-Rg.Plugins.Popup-
while making it, i noticed that the problem only appears when using together with Sharpnado.Tabs https://github.com/roubachof/Sharpnado.Tabs

**Comment by LuckyDucko** [comment]
hey @ScarletKuro 

I am testing your repo on a Samsung galaxy a20, and I seem to have no issues. 

I hit Open Popup Page, it stays for around 5 seconds, as the code intends, and then it closes. 

Is there more information you could provide, as I cannot seem to recreate

**Comment by ScarletKuro** [comment]
@LuckyDucko 
I actually did not try it on real device. Now i tried on my huawei p smart z (android 10) and it works as expected...
But in emulator (pixel 2 Q 10.0 - API 29) i get this bug. Also, when i pulled the repo from scratch the first run in emulator and everything was correct, when i tried second time the elements disappeared again, this is really weird.

**Comment by ScarletKuro** [comment]
Ok, i tested it on various real devices including even 4.1 android, and the bug was not present.

**Comment by LuckyDucko** [comment]
hmmm, perhaps open this ticket up for Sharknado.tabs. it may be something on their end. 

Glad it isnt present on device
