### ISSUE TITLE
Open Xamarin forms Modal inside Popup

### ISSUE THREAD

**Issue by chrux** [rotorgames/Rg.Plugins.Popup#67]
When I open a normal Xamarin modal using this:

await Navigation.PushModalAsync(new NavigationPage(page));

and later close the modal and wants to return to the Popup using this:

await Navigation.PopModalAsync();

The Popup close too, and it should be kept, how can I open a modal inside and still return to the popup?

Best

**Comment by rotorgames** [comment]
@chrux You can't open modal page on Popup. You must close popup page before to open modal page.
