### ISSUE TITLE
Changelog of 2.0.0.12?

### ISSUE THREAD

**Issue by mueller-ma** [rotorgames/Rg.Plugins.Popup#674]
On https://www.nuget.org/packages/Rg.Plugins.Popup/ there's a new version `2.0.0.12`, but there's no tag for it here: https://github.com/rotorgames/Rg.Plugins.Popup/tags

**Comment by LuckyDucko** [comment]
Our changelogs do usually have just 'update version' however, things that are changed are



[Setting UIWindowLevel.Normal during removal](https://github.com/rotorgames/Rg.Plugins.Popup/pull/659)
[Fix for iOS 13+ MultiScene compatibilty](https://github.com/rotorgames/Rg.Plugins.Popup/pull/660)
[Fixed Android accessibility changes](https://github.com/rotorgames/Rg.Plugins.Popup/pull/663)
[Fixed Android 9 & 11 Scaling issues ](https://github.com/rotorgames/Rg.Plugins.Popup/pull/670)

**Comment by mueller-ma** [comment]
Thanks for your answer!
