### ISSUE TITLE
Is it possible to change the size of the popup presented

### ISSUE THREAD

**Issue by KMWenyon** [rotorgames/Rg.Plugins.Popup#675]
I am using the latest version of the RG.PlugInPopup 2.0.0.012

I would like to change the size of the popup presented (to make if larger).  How can I increase the size of the popup page (the frame and it content)?

**Comment by LuckyDucko** [comment]
@KMWenyon 

To control popup size, I usually wrap it in in an absoluteLayout and work from there.

An [example](https://github.com/LuckyDucko/AwaitablePopups/blob/master/AwaitablePopups/PopupPages/DualResponse/DualResponsePopupPage.xaml)

**Comment by Colima-97** [comment]
I like to use a [PancakeView](https://github.com/sthewissen/Xamarin.Forms.PancakeView/wiki/Setup) as the background, I use margins and Vertical/Horizontal options in its style to make it look as I want it.
