### ISSUE TITLE
Navigate with open Popup

### ISSUE THREAD

**Issue by zonkzen** [rotorgames/Rg.Plugins.Popup#68]
@rotorgames , first of all, thanks Kiril for a great package.

I have a question, is it possible to open another NavigationPage when I have an opened popup on the current one? It looks like open Popup is always visible, on top of all pages, meaning that the newly opened Page is loading "behind" the popup.

**Comment by rotorgames** [comment]
@zonkzen Hi friend. This is imposible. PopupPage is always on top, and all opening pages will open behind PopupPage. This is Xamarin.Forms page behavior and I can't change it.

**Comment by zonkzen** [comment]
@rotorgames thank you for your response. So the correct behaviour is to close all popups and only then open another page. Seems logical.

**Comment by rotorgames** [comment]
@zonkzen Yes you should close all popups before opening others pages.

Thank you for question.

**Comment by Sainty-dev** [comment]
How to pass data from one page  into popup  and  later after submitting return data to that page

**Comment by LuckyDucko** [comment]
@Sainty-dev 
I make a plugin that can help with that, however, it has some conventions you may need to follow https://github.com/LuckyDucko/AwaitablePopups

For something you can add in yourself, @acaliaro has a great write up https://acaliaro.wordpress.com/2020/12/07/create-a-popup-using-rg-plugins-popup-and-get-a-return-value/
