### ISSUE TITLE
Breakpoints in custom Animation are not hit

### ISSUE THREAD

**Issue by Pantheas** [rotorgames/Rg.Plugins.Popup#680]
Hi,

I'm facing the problem mentioned in [this issue](https://github.com/rotorgames/Rg.Plugins.Popup/issues/678) with your default animations.

As a work-around, I created a custom animation and instead of using the `content` parameter, I wanted to try using `page.Content`.
However, I cannot see what value `page.Content` has at time when the animation gets invoked because my break points are not hit.

```csharp
public class PopupMoveAnimation :
    MoveAnimation
{
    public override void Preparing(
        View content,
        PopupPage page)
    {
        base.Preparing(
            page.Content,
            page);
    }

    public override void Disposing(
        View content,
        PopupPage page)
    {
        base.Disposing(
            page.Content,
            page);
    }



    public override async Task Appearing(
        View content,
        PopupPage page)
    {
        await base.Appearing(
            page.Content,
            page);
    }

    public override async Task Disappearing(
        View content,
        PopupPage page)
    {
        await base.Disappearing(
            page.Content,
            page);
    }
}
```

```xaml
<rgpages:PopupPage.Animation>
    <local:PopupMoveAnimation
        PositionIn="Left"
        PositionOut="Left"
        DurationIn="300"
        DurationOut="300"
        EasingIn="SinOut"
        EasingOut="SinIn"
        HasBackgroundAnimation="True" />
</rgpages:PopupPage.Animation> 
```

Is there anything I'm doing wrong?
How can I fix it?

Thanks in advance and kind regards!

**Comment by LuckyDucko** [comment]
@Pantheas the breakpoint not getting hit can be a frustrating one

Could you try and make your animation within rg repo, putting your animation in the example rg project.
Also, are you using Mac or PC, 
And finally, are your breakpoints hollow red, or solid red when running the project in debug mode

**Comment by Pantheas** [comment]
Nevermind, mistake was on my side by not setting `IsAnimationEnabled=true`...
Sorry, sometimes I'm an idiot haha

**Comment by LuckyDucko** [comment]
@Pantheas don't worry, I can't count the number of times I have made the same type of mistake.
