### ISSUE TITLE
Trouble when trying to initialize on UWP

### ISSUE THREAD

**Issue by PauGarcia890** [rotorgames/Rg.Plugins.Popup#688]
## 🐛 Bug Report

I have the nugget package installed on every porject I have and I have been able to initialize Rg.plugins.popup on those as well except for UWP. When I try to initialize it I can even find the Rg.plugins.popup.popup namespace hence I can't cal the Init method.

### Expected behavior
Call Rg.Plugins.Popup.Popup.Init() method.
### Reproduction steps
Create a new project
### Configuration

**Version:** 1.x
v 2.0.0.12
**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
@PauGarcia890 have you been able to run the sample?

**Comment by PauGarcia890** [comment]
Hi @LuckyDucko, no I haven't been able to solve it. I've got a Xamarin Forms solution with and Android project and an UWP one. When I initialize the plugin on android, I face 0 problems. But when I try to initialize it on UWP it just can't find the Popup class. All i can find is the namespace list. I'll attach a picture below for you to see.

![image](https://user-images.githubusercontent.com/82149945/134299980-51a97fc7-28b9-4a3e-925f-190a38c3eb55.png)

As you can see in the picture, there is no Popup class as there is on android.

I've tried everything but it just won't work.

Thank you for your atention.

**Comment by gceaser** [comment]
I am having the same issue.  The funny thins is I have a uwp project running XF 5.0.0.2083 and seems work fine.  In my project running XF 5.0.0.2125 I get the error. I am looking to see if a downgrade fixed the problem.

**Comment by gceaser** [comment]
I tried to downgrade XF and still encountered the error.

**Comment by PauGarcia890** [comment]
I also tried many things. I tried erasing the UWP project from the solution and creating it again, tried changing many thinks, etc...
What seemed to be a workaround (but I'm strill trying to figure it out) was installing the package but no initialaizing it on UWP only on Android. Of course then I had to program it in a way so that the user couldn't acces the popup.

**Comment by rotorgames** [comment]
Set `TargetPlatformMinVersion` to 10.0.17763 in your csproj.

**Comment by IgorStrekha** [comment]
> Set `TargetPlatformMinVersion` to 10.0.17763 in your csproj.

it WORKS!!

**Comment by PauGarcia890** [comment]
> Set `TargetPlatformMinVersion` to 10.0.17763 in your csproj.

It worked perfectly. Thank you very much.
I'll close the issue now.
Thank you very very much.
