### ISSUE TITLE
The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup'

### ISSUE THREAD

**Issue by MathieuJack** [rotorgames/Rg.Plugins.Popup#695]
With my Xamarin.Forms UWP project, I have this compilation error on this line 

Rg.Plugins.Popup.Popup.Init();

There are several namespaces under Rg.Plugin.Popup, but no Popup namespace/class

I am using nuget Rg.Plugin.Popup v2.0.0.13

Thank you

**Comment by LuckyDucko** [comment]
Set TargetPlatformMinVersion to 10.0.17763 in your csproj.

**Comment by MathieuJack** [comment]
What visual studio version is required to be able to target this platform SDK version?

**Comment by LuckyDucko** [comment]
I believe VS 2019 should be capable

**Comment by MathieuJack** [comment]
Not by default, I have installed individual component from VS installer and it's ok.
Thank you.

**Comment by KimLeRoy** [comment]
It seems like any version of Xamarin greater than 5 doesn't work with Rg.Popup. After following all the instructions and advice here, I decreased my Xamarin Forms version to 4.8.0.1821 and Rg.Popup started working like they should. But any higher than Xamarin Forms 5.0.0 and the lists dont show and the popups are blank.

**Comment by LuckyDucko** [comment]
@KimLeRoy 

i have been using the RG popups on Android/iOS fine on Xamarin.Forms 5 since it was first released.

Is this just windows that you have issues with?

**Comment by KimLeRoy** [comment]
@LuckyDucko 

Yes sorry - I should have said it is just UWP we are using RG popups for. The other two platforms have their own alternatives. When we go over Xamarin 5 the popup outlines show, but no contents in them. We even tried with the Github examples from here in VS 2019 to see if it was something in our code, but we got the same result.

**Comment by luizhj** [comment]
> Set TargetPlatformMinVersion to 10.0.17763 in your csproj.

This solution only works for 2.0.0.13 version. With 2.0.0.14 it return to show the compilation error.

The version of the packages of my projet.
Xamarin forms 5.0.0.2196
Microsoft.NETCore.UniversalWindowsPlataform 6.2.13

Even Fuget doesn't show the Rg.Plugins.Popup.Popup namespace.

https://www.fuget.org/packages/Rg.Plugins.Popup/2.0.0.14/lib/netcoreapp3.1/Rg.Plugins.Popup.dll/Rg.Plugins.Popup

![image](https://user-images.githubusercontent.com/16191002/138505872-d82c79e8-812b-4017-857a-68d1cdc0bfbf.png)

**Comment by pheidler** [comment]
> Set TargetPlatformMinVersion to 10.0.17763 in your csproj.

Our app still has some users using an older version than 10.0.17763. I am updating this package in order to resolve crashes we are noticing related to https://github.com/rotorgames/Rg.Plugins.Popup/issues/582. Which version of this package should I use in order to resolve this issue, yet still support users on older versions of Windows?

**Comment by PauGarcia890** [comment]
> Set TargetPlatformMinVersion to 10.0.17763 in your csproj.

I had the same problem a while ago, I changed the TargetPlatformMinVersion to 10.0.17763 on my UWP project, and then it worked. But since the new UWP update the problem resurfaced. Once I updated the Microsoft.NETCore.UniversalWindowsPlatform NuGet package to the latest version the PopUp namespace error reappeared.

**Comment by Gmotagi** [comment]
I'm having various similar issues. I have two popups that are displaying empty on UWP, after some investigation it seems that add ing in a simple Button is causing it. If I remove them it displays.
<edit>
For me this seems related to the latest version of Forms 5.0.0.2196. I reverted back to 2125 and my popups are working as expected again. My version of popup is 2.0.0.13 and also have prism.plugin.popups 7.2.0.1422

**Comment by LuckyDucko** [comment]
For 2.0.0.14 issues, see #707, i hope the rebuild helps

**Comment by FabriBertani** [comment]
> Set TargetPlatformMinVersion to 10.0.17763 in your csproj.

This worked for me using v2.0.0.13
