### ISSUE TITLE
Xamarin.iOS 15.0 on real device  "Cannot access a disposed object. Object name: 'PopupPageRenderer'."

### ISSUE THREAD

**Issue by Phenek** [rotorgames/Rg.Plugins.Popup#697]
Hello,
## 🐛 Bug Report

After updating Xamarin.iOS 15.0, I got an exception 
"Cannot access a disposed object. Object name: 'PopupPageRenderer'."
when interacting with a Rg.popup.Page, on my Iphone X (iOS 14)

I don't have this exception on simulator running IOS 15

````
  at Foundation.NSObject.get_SuperHandle () [0x00023] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:542 
  at UIKit.UIViewController.ViewDidLayoutSubviews () [0x00023] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:1143 
  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidLayoutSubviews () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:176 
  at Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.ViewDidLayoutSubviews () [0x00000] in C:\Users\mhvdi\Documents\OpenSource\Rg.Plugins.Popup\Rg.Plugins.Popup\Platforms\Ios\Renderers\PopupPageRenderer.cs:112 
  at Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.KeyBoardUpNotification (Foundation.NSNotification notifi) [0x0000c] in C:\Users\mhvdi\Documents\OpenSource\Rg.Plugins.Popup\Rg.Plugins.Popup\Platforms\Ios\Renderers\PopupPageRenderer.cs:136 
  at Foundation.InternalNSNotificationHandler.Post (Foundation.NSNotification s) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSNotificationCenter.cs:48 
````

### Expected behavior

The PopupPagerenderer should not be dispose.

### Reproduction steps

You can try to repoduce it when interacting with an Entry inside a RG.Popup.Page,
on an Iphone with iOS 14 and App builded with Xamarin.iOS 15

### Configuration
**Platform:** 
- [ ] :iphoneX: iOS 14
- [ ] :xamarin.iOS: 15.0.0.6 [release](https://github.com/xamarin/xamarin-macios/releases)

Thanks for your good repository!

**Comment by LuckyDucko** [comment]
@Phenek does this include iOS 14.5 as well? or strictly iOS 14?

**Comment by Phenek** [comment]
@LuckyDucko 
iOS 14.5.1 has the issue.

**Comment by Phenek** [comment]
This happen when the keyboard want to show up
Hope it can help

**Comment by Phenek** [comment]
I added the repo as reference, and found out that the renderer is disposed when the MainPage changed.
But it should not be disposed at this time.

Commenting the dispose function give me a workaround. (ligne 41 of [PopupPageRenderer.cs](https://github.com/rotorgames/Rg.Plugins.Popup/blob/develop/Rg.Plugins.Popup/Platforms/Ios/Renderers/PopupPageRenderer.cs))
````  
        protected override void Dispose(bool disposing)
        {
            //if (disposing)
            //{
            //    View?.RemoveGestureRecognizer(_tapGestureRecognizer);
            //}

            //base.Dispose(disposing);

            //_isDisposed = true;
        }
````

But I did not find a real explanation, and how to fix it properly.

**Comment by LuckyDucko** [comment]
@Phenek sorry I have been working on the MAUI extension.

I currently test using an iOS 14.5 device with this repo and haven't run into any issues, can you provide a sample repo?

**Comment by Phenek** [comment]
Ok let me try to explain my issue.  (I got a fixe at the end :)

- I have a SplashScreen : PopupPage
- I put this Splashscreen as MainPage inside App constructor
```` 
MainPage = new SplashScreen(true, 0);
````
- When App construction, api calls and stuff is finished, I change the MainPage
````
Task.Run(async () =>
            {
                    _loadedMainPage = new AppShell();
                    //await LoadStuff
                MainThread.BeginInvokeOnMainThread(() =>
                {
                        MainPage = _loadedMainPage;
                });
            });
````
- At this moment Renderers are dispose, and when I want to interact with an entry inside a new PopupPage
I had this exception when the keyboard want to show up and PopupPage need to resize for keyboard.
                                      <img width="500" alt="Screenshot 2021-10-07 at 00 26 27" src="https://user-images.githubusercontent.com/4518686/136292258-d4f21362-a746-48b2-9308-70c6ef122d9d.png">


- I found a fixe, by verifying if the renderer is dispose, before updating layout when keyboard appear
(line 110 in [PopupPageRenderer.cs](https://github.com/rotorgames/Rg.Plugins.Popup/blob/develop/Rg.Plugins.Popup/Platforms/Ios/Renderers/PopupPageRenderer.cs)
````
        public override void ViewDidLayoutSubviews()
        {
            if (_isDisposed) return;
            base.ViewDidLayoutSubviews();
            this.UpdateSize();
        }
````
- The layout is well resized when the keyboard appear and no exceptions!

Hope it can be enough for you, or should I create a little project to reproduce the error?

**Comment by Phenek** [comment]
Update: 
This is affecting all real devices (iOS 14,15..) when App is compiled with Xamarin.iOS 15.0
No issue occur in simulator.
