### ISSUE TITLE
Typo in namespace / class names

### ISSUE THREAD

**Issue by Crapoo** [rotorgames/Rg.Plugins.Popup#7]
Hey there, 
First thing first, good job on that plugin, it's exactly what I needed and seems to work well!

Something tickles me though; typos in class and namespace names and those typos, to me, don't make your work look as professional as it could. 

So far I found those : 
- Rg.Plugins.Popup.Extensions.NavigatonExtension instead of NavigationExtension
- Rg.Plugins.Popup.Extensions.NavigatonExtension.PopAllPopupAsunc instead of Async
- Rg.Plugins.Popup.Extensions.NavigatonExtension.PopPopupAsunc instead of Async

I'd have fixed those myself but I don't have time to do that and make sure it doesn't create problems elsewhere at the moment and I'd rather not break anything.

Keep up the good work dude! :+1:

**Comment by rotorgames** [comment]
@Crapoo Hi friend. What a mess, how could I not notice ?!

Thanks for the help, I have right now is correct.
