### ISSUE TITLE
Popup not centered

### ISSUE THREAD

**Issue by acaliaro** [rotorgames/Rg.Plugins.Popup#70]
Hi @rotorgames , how are you?
I think there is a problem in centering the popup on a particular Android device.

this is what I see

![device-2016-12-22-095338](https://cloud.githubusercontent.com/assets/5759350/21420233/b517c572-c82c-11e6-86c1-bad9177b251f.png)

In other devices or in emulator, it is centered...

**Comment by rotorgames** [comment]
@acaliaro Hi friend. Write versions of android, xamarin, xamarin forms, xamarin androud and popup plugin. Upload your project into GitHub and give me if you can.

Thank you.

**Comment by acaliaro** [comment]
Ok
Attached a project.
When you click on green "Login" label (it has a tapgesturerecognizer), the popup appears.
Popup package should be the current one.
Android is 4.4.4
[fev_ventilazione_smartwatch.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/668463/fev_ventilazione_smartwatch.zip)

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.
