### ISSUE TITLE
System.TypeLoadException: Could not resolve type with token 0100000f

### ISSUE THREAD

**Issue by smshafa** [rotorgames/Rg.Plugins.Popup#71]
When I debug my android project this exception is thrown: "System.TypeLoadException: Could not resolve type with token 0100000f". 
The last value for call stack is ">	
0x21 in x.Droid.MainActivity.OnCreate at C:\Users\asus\Documents\Visual Studio 2015\Projects\x\x\x.Droid\MainActivity.cs:22,13	C#
". 
Is there any code should I add to MainActivity.cs?

![untitled](https://cloud.githubusercontent.com/assets/24754063/21467596/e68d1d18-ca08-11e6-9b66-96d2a8a21c6a.png)

**Comment by rotorgames** [comment]
@smshafa Hi. Why do you think that this exception from Popup plugin?

**Comment by smshafa** [comment]
Because when I've added the plugin, this exception has been thrown. I wanted to be sure about the problem and I copy the project and then remove the plugin and it works correctly. I set main page to a Master-detail page.

**Comment by rotorgames** [comment]
@smshafa My plugin can't throw this exception. Please, will try to create new project and will add into it my plugin. Exception will not be.

**Comment by smshafa** [comment]
Running the project in Release Mode have no issues.

**Comment by rotorgames** [comment]
@smshafa because problem is not in Popup plugin

**Comment by smshafa** [comment]
Running the android project in debug mode is also possible. This page helped me:
[System.TypeLoadException: Could not resolve type with token](http://stackoverflow.com/questions/39752764/system-typeloadexception-could-not-resolve-type-with-token-01000019)

**Comment by rotorgames** [comment]
@smshafa Popup plugin supports all linked modes. Popup plugin use `PreserveAttribute` everywhere, It couldn't throw this error. 

I did many tests for fixing linker problem.

**Comment by bugadani** [comment]
@smshafa This is a general error with Xamarin, pops up seemingly randomly. You may or may not need to recreate your project to solve it, remove and reinstall nuget packages, etc. I had it once and I don't know what made it go away. Annoying, but not @rotorgames's fault

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.

**Comment by wireless-r** [comment]
I'm having this issue with pre-release version 1.1.4.

![screenshot_1](https://user-images.githubusercontent.com/28116634/37957898-5b9199ae-31af-11e8-96b4-d02b01e9f279.png)
