### ISSUE TITLE
UWP : Rg.Plugins.Popup.Popup.Init(); causing build error

### ISSUE THREAD

**Issue by dmsi-leonidl** [rotorgames/Rg.Plugins.Popup#712]
## 🐛 Bug Report

Rg.Plugins.Popup.Popup.Init(); causing build error:
The type or namespace name 'Popup' does not exist in the namespace 'Rg.Plugins.Popup' (are you missing an assembly reference?)

Note:
2.0.0.13 builds and run without problems.

### Expected behavior
Builds without errors.

### Configuration
Windows 10 Enterprise
19043.1288

Microsoft Visual Studio Enterprise 2019
Version 16.11.5

Xamarin Forms
5.0.0.2196

**Version:** 2.0.0.14 (Latest)

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by TamerIrdais** [comment]
Same Issue here with latest version 2.0.0.14

**Comment by LuckyDucko** [comment]
@rotorgames i am relatively new to any form of UWP development, are you able to look into this? seems 2.0.0.14 may have missed something with UWP

**Comment by mhrastegari** [comment]
same issue :(

**Comment by truXton222** [comment]
Someone discovered any workaround for this issue? 

At moment my only solution is downgrade the library to 2.0.0.13

**Comment by mfeingol** [comment]
cc @martijn00 - would be nice to have this fixed. Thanks.

**Comment by LuckyDucko** [comment]
@mfeingol 
@truXton222 
@TamerIrdais 
@dmsi-leo 

I was able to build and run the Demo.UWP without any hassles.

I updated the core project to use the Xamarin.Forms noted in this ticket, 

Target Version for Windows 10 : 1809
Min Version 1809

are you able to check this against the Demo Project, and if the demo project works fine, what is the differences in your setup in comparison.
[UPDATE]
see #707

**Comment by claudecarb** [comment]
Same issue here :/ Anyone found a solution to this please? 

My Target and Min Windows versions were already at Win 10 1809

**Comment by dmsi-leonidl** [comment]
@LuckyDucko 

My project's settings are pretty much the same.
The only differences are:

Target Version for Windows 10 : 2004

Nuget packages:
Microsoft.NETCore.UniversalWindowsPlatform **v6.2.13**
Xamarin.Forms **v5.0.0.2196**
Xamarin.Essentials **v1.7.0**
ZXing.Net.Mobile.Forms
Syncfusion.Xamarin.SfDataForm

**Comment by TobiVanHelsinki** [comment]
I had the same issue since the last update. The Rg.Plugins.Popup.Popup class seems simply missing, which is weird since there were no changes to that class. Maybe some build error at the nuget pack?

In the meantime I run good with using version 2.0.0.13.

**Comment by whSwitching** [comment]
same issue happened, 
target version 2004
min version 1809
the latest 2.0.0.14 did not work, **2.0.0.13** works

**Comment by hammondreg** [comment]
Answer is simple: no testing or checking is done after every upgrade ..

**Comment by kumaresan-cgvak** [comment]
Hello @rotorgames @martijn00 
Any update on this issue?
<img width="947" alt="Screenshot 2022-02-03 at 5 34 33 PM" src="https://user-images.githubusercontent.com/5547152/152339474-07d480b4-fd5b-4d22-8f26-1cde35561bec.png">

**Comment by martijn00** [comment]
You are targeting the wrong uwp version.

**Comment by kumaresan-cgvak** [comment]
@martijn00 Can you please update the same in Wiki. Which will help fellow developers.
<img width="1030" alt="Screenshot 2022-02-03 at 6 03 25 PM" src="https://user-images.githubusercontent.com/5547152/152343702-28e0852c-93b7-4bb6-b2e8-81c7112fa98a.png">

**Comment by pabloat81** [comment]
Hi, i am facing same issue on UWP. Min target version 10.0.17763. I dont understood in this thread what is the solution.

**Comment by dmsi-leonidl** [comment]
@pabloat81: I resolved this issue by updating UWP min version to 1903 ( Build 18362). Hope this will help.

**Comment by tualatin** [comment]
> @pabloat81: I resolved this issue by updating UWP min version to 1903 ( Build 18362). Hope this will help.

Crazy, thank you for this helpful hint!
