### ISSUE TITLE
Get a return value in Xamarin Forms

### ISSUE THREAD

**Issue by DavidSpecter** [rotorgames/Rg.Plugins.Popup#716]
## 🚀 Feature Requests

Get a return value in Xamarin Forms

### Describe the feature
Simply return true or false when button in popup is pressed

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment]
@DavidSpecter i would recommend using [my plugin](https://github.com/LuckyDucko/AwaitablePopups) or following [acaliaro's guide](https://acaliaro.wordpress.com/2020/12/07/create-a-popup-using-rg-plugins-popup-and-get-a-return-value/)

Both of these are based on Rg

**Comment by davidbuckleyni** [comment]
@DavidSpecter  did u get a solution for this I would rather use something that more widley used

**Comment by davidbuckleyni** [comment]
I actually achieved this using the messaging centre

**Comment by LuckyDucko** [comment]
@davidbuckleyni messagingcentre also works a treat in this scenario, its what i first before i made my plugin.
 just remember to unsubscribe when you 'close' your popup, otherwise there will be unusual headaches, as well as a performance impact

**Comment by DavidSpecter** [comment]
Hi,
I resolve like that:
In popup page add a TaskCompletionSource
` private TaskCompletionSource<bool> taskCompletionSource;`
 ` public Task<bool> PopupClosedTask { get { return taskCompletionSource.Task; } }`

`protected override void OnAppearing()
        {
            base.OnAppearing();
            taskCompletionSource = new TaskCompletionSource<bool>();
        }`

and than set the result when button is pressed
`private void ButtonClicked(object sender, EventArgs args)
        {
            taskCompletionSource.SetResult(true);
            Navigation.RemovePopupPageAsync(this);
        }`

and the caller is like
`Popup popup = new popup(...)`
`await PopupNavigation.Instance.PushAsync(popup);`
`if (await popup.PopupClosedTask)
            {
                //do some stuff...
            }`

Hope this can be helpfull.

David.

**Comment by davidbuckleyni** [comment]
> @davidbuckleyni messagingcentre also works a treat in this scenario, its what i first before i made my plugin. just remember to unsubscribe when you 'close' your popup, otherwise there will be unusual headaches, as well as a performance impact

Yeah I found out about unloading the hard way wondering why my app started freezing i placed it in the close as seemed logical their.
