### ISSUE TITLE
[iOS] PushPopupAsync if DisplayAlert() Message is open cause the PopupPage to not function completely

### ISSUE THREAD

**Issue by ShahmanTeh** [rotorgames/Rg.Plugins.Popup#72]
Hi Kirill,

I have a iOS device and have a DisplayAlert Message open at the time. I have an event that call a PopupPage. the issue happens appears that the popup page is "pushed" towards the alertView

here is the video displaying the issue
http://www.screencast.com/t/D5T0TkFsY9

the following is the code snippet for causing the issue (pastebin: http://pastebin.com/2b3YRNce)
`
        private async void TestCommand() {
            await DisplayAlert("DEBUG", "Begin Test", "Begin");
            Device.StartTimer (TimeSpan.FromSeconds (2),
                () => {
                    Navigation.PushPopupAsync(new Sample_PopupPage());
                    return false;
                } );
            await DisplayAlert ("DEBUG", "This is a dummy DisplayAlert", "OK");
        }
`

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.

**Comment by HoloJackStones** [comment]
Same issue here. Tested the 1.1.0-pre1 and i can confirm it fixes, but i'm not so glad to use a pre-release in a production environment. 
When will be released a new official version?

**Comment by rotorgames** [comment]
@HoloJackStones the stable release will be soon.
