### ISSUE TITLE
[UWP] Support Windows 10 1809 LTSC

### ISSUE THREAD

**Issue by YZahringer** [rotorgames/Rg.Plugins.Popup#724]
## 🔙 Regression
We can not use the latest version `2.1.0` with UWP targeting Windows 10 1809.
The version `1809` is an `LTSC` version, supported until **2029** and `Xamarin.Forms` support it.

This is the commit that make the regression, without any breaking change announcement or issue to track it 😕
https://github.com/rotorgames/Rg.Plugins.Popup/commit/0645bd62b37e546e542ecfc0d7ea2f3b3b1abea4#diff-74eaa5dcbcc57fd0aa109ed278deb4132b29340aff41b89a15c386ca87479f43

Related: https://github.com/rotorgames/Rg.Plugins.Popup/issues/723, https://github.com/rotorgames/Rg.Plugins.Popup/issues/712, https://github.com/rotorgames/Rg.Plugins.Popup/issues/707

### Old (and correct) behavior
`Windows 10 1809` and later supported

### Current behavior
Only `Windows 10 1903` and later supported

### Reproduction steps
Use an UWP project with min version `1809`.

### Configuration
**Version:** 2.1.0.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Visual Studio 2022 doesn't support target 10.0.17763.0 anymore. I need to be able to build the code to release it.
