### ISSUE TITLE
Calling PopupNavigation.PushAsync a second time fails to show the PopupPage.

### ISSUE THREAD

**Issue by assemhakmeh** [rotorgames/Rg.Plugins.Popup#73]
It appears that if a PopupPage.Animation is not null and you call PushAsync(page, false) then PopAsync(false). If a call to PushAsync(page, false) is called again, the page does not display.

Looking at the code, the RemovePageAsync calls DisposingAnimation() regardless of the animate flag causing animation default properties (scale, opacity,etc) to override the pages values with it's own defaults that never got properly set during the PushAsync since that method respects the animate flag and does not call PreparingAnimation if animate = false.

**Comment by rotorgames** [comment]
@assemhakmeh Hi. What version of Popup plugin do you use?

**Comment by assemhakmeh** [comment]
The latest nuget version 1.0.4 on iOS.

**Comment by rotorgames** [comment]
@assemhakmeh Ok. I will look on this problem

**Comment by sergiuciudin** [comment]
I have the same problem.

**Comment by gcadmes** [comment]
@rotorgames May I ask if there is any progress on this issue? thanks much

**Comment by rotorgames** [comment]
@gcadmes @sergiuciudin @assemhakmeh Sorry for long answer. I fixed it. You can see it in v1.1.0-pre2 or v1.1.0. Thank you.
