### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by lchiu7** [rotorgames/Rg.Plugins.Popup#74]
I created two buttons on my page one opens a popup page by Rg.Plugins.Popup and the other uses Xamarin's built in DisplayAlert.  The built-in one works, but the one using Rg.Plugins.Popup gives NullReferenceException error when clicked.  Am I missing something here?  Any quick fix?  Thanks.

Here's my code:

    public partial class PopupTest : ContentPage
    {
        public PopupTest()
        {
             InitializeComponent();
        }

        private async void OnOpenPupup(object sender, EventArgs e)
        {
            var page = new Procedures();
            await Navigation.PushPopupAsync(page);
        }

        private async void Alerts(object sender, EventArgs e)
        {
            await DisplayAlert("o", "Hello", "ok");
        }
    }

**Comment by Nate53085** [comment]
Is this in Xamarin.Forms? I'm seeing the following in Android

01-07 21:01:04.408  6096  6096 I MonoDroid: UNHANDLED EXCEPTION:
01-07 21:01:04.418  6096  6096 I MonoDroid: System.NullReferenceException: Object reference not set to an instance of an object.
01-07 21:01:04.418  6096  6096 I MonoDroid:   at Rg.Plugins.Popup.Services.PopupNavigation.PushAsync (Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) [0x00043] in <e4a0d036d16d43a8a07fbef673df812b>:0
01-07 21:01:04.418  6096  6096 I MonoDroid:   at Rg.Plugins.Popup.Extensions.NavigationExtension.PushPopupAsync (Xamarin.Forms.INavigation sender, Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) [0x00000] in <e4a0d036d16d43a8a07fbef673df812b>:0
01-07 21:01:04.418  6096  6096 I MonoDroid:   at Fitsocial.MainPage+<AddExersize_Clicked>d__4.MoveNext () [0x0001a] in C:\Users\Nathan\Documents\Visual Studio 2015\Projects\Fitsocial\Fitsocial\Fitsocial\MainPage.xaml.cs:46
01-07 21:01:04.418  6096  6096 I MonoDroid: --- End of stack trace from previous location where exception was thrown ---
01-07 21:01:04.418  6096  6096 I MonoDroid:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
01-07 21:01:04.418  6096  6096 I MonoDroid:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018
01-07 21:01:04.419  6096  6096 I MonoDroid:   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:18
01-07 21:01:04.419  6096  6096 I MonoDroid:   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36
01-07 21:01:04.419  6096  6096 I MonoDroid:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Java.Lang.IRunnable.cs:81
01-07 21:01:04.419  6096  6096 I MonoDroid:   at (wrapper dynamic-method) System.Object:19ddd4da-2cde-4ca8-b2ff-babf693d331a (intptr,intptr)
01-07 21:01:04.440  6096  6096 W art     : JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

**Comment by rotorgames** [comment]
Did you install popup plugin into Android and iOS projects?

**Comment by Nate53085** [comment]
Nope.. you are absolutely right.

I misunderstood how NuGet works I guess. I thought the NuGet package manager console installed it into the solution but it looks like I had only installed it into the shared project. Installing into Android fixed the issue. 

Thanks for the help. Not sure if this was the original posters issue though

**Comment by rotorgames** [comment]
You are welcome. Good luck.

**Comment by lchiu7** [comment]
Yes, I've installed popup plugin into both Android and iOS.

**Comment by lchiu7** [comment]
Working now.  Thanks!

**Comment by s-figuccia** [comment]
Hi,
I installed the version 1.0.4 (in the iOS and Android project) of the plugin but when I try to perform this simple function (by pressing a button) 
```
private async void OpenPopup(object sender, EventArgs e)
        {
            //var loading = new LoadingPopup();
            //await Navigation.PushPopupAsync(loading);
            //await PopupNavigation.PushAsync(loading);

            await PopupNavigation.PushAsync(new LoadingPopup());
        }
```
I have this error. Can you help me please?

01-11 11:43:58.371 D/Mono    (17763): DllImport searching in: '__Internal' ('(null)').
01-11 11:43:58.371 D/Mono    (17763): Searching for 'java_interop_jnienv_call_boolean_method'.
01-11 11:43:58.371 D/Mono    (17763): Probing 'java_interop_jnienv_call_boolean_method'.
01-11 11:43:58.371 D/Mono    (17763): Found as 'java_interop_jnienv_call_boolean_method'.
01-11 11:43:59.192 D/Mono    (17763): Assembly Loader probing location: '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.dll'.
01-11 11:43:59.194 D/Mono    (17763): Image addref Rg.Plugins.Popup[0x96e1b7e0] -> /storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.dll[0x94e69700]: 2
01-11 11:43:59.194 D/Mono    (17763): Prepared to set up assembly 'Rg.Plugins.Popup' (/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.dll)
01-11 11:43:59.196 D/Mono    (17763): Assembly Rg.Plugins.Popup[0x96e1b7e0] added to domain RootDomain, ref_count=1
01-11 11:43:59.201 D/Mono    (17763): AOT: image '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.dll.so' not found: dlopen failed: library "/data/app/AppToYou.Android-1/lib/arm/libaot-Rg.Plugins.Popup.dll.so" not found
01-11 11:43:59.202 D/Mono    (17763): AOT: image '/usr/local/lib/mono/aot-cache/arm/Rg.Plugins.Popup.dll.so' not found: dlopen failed: library "/data/app/AppToYou.Android-1/lib/arm/libaot-Rg.Plugins.Popup.dll.so" not found
01-11 11:43:59.202 D/Mono    (17763): Assembly Loader loaded assembly from location: '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.dll'.
01-11 11:43:59.202 D/Mono    (17763): Config attempting to parse: '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.dll.config'.
01-11 11:43:59.202 D/Mono    (17763): Config attempting to parse: '/usr/local/etc/mono/assemblies/Rg.Plugins.Popup/Rg.Plugins.Popup.config'.
01-11 11:43:59.203 D/Mono    (17763): Assembly Ref addref AppToYou[0xab48d320] -> Rg.Plugins.Popup[0x96e1b7e0]: 2
01-11 11:43:59.203 D/Mono    (17763): Assembly Ref addref Rg.Plugins.Popup[0x96e1b7e0] -> Xamarin.Forms.Core[0xab48dfe0]: 11
01-11 11:43:59.204 D/Mono    (17763): Unloading image System.Runtime.dll [0x94e68800].
01-11 11:43:59.204 D/Mono    (17763): Image addref System.Runtime[0x96e1b900] -> System.Runtime.dll[0xb3b5d700]: 11
01-11 11:43:59.204 D/Mono    (17763): Config attempting to parse: 'System.Runtime.dll.config'.
01-11 11:43:59.204 D/Mono    (17763): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Runtime/System.Runtime.config'.
01-11 11:43:59.204 D/Mono    (17763): Assembly Ref addref Rg.Plugins.Popup[0x96e1b7e0] -> System.Runtime[0xab48e040]: 9
01-11 11:43:59.206 D/Mono    (17763): Unloading image System.Collections.dll [0x94e68d00].
01-11 11:43:59.207 D/Mono    (17763): Image addref System.Collections[0x96e1b900] -> System.Collections.dll[0x9aff2a00]: 10
01-11 11:43:59.207 D/Mono    (17763): Config attempting to parse: 'System.Collections.dll.config'.
01-11 11:43:59.207 D/Mono    (17763): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Collections/System.Collections.config'.
01-11 11:43:59.207 D/Mono    (17763): Assembly Ref addref Rg.Plugins.Popup[0x96e1b7e0] -> System.Collections[0xab48e5e0]: 8Loaded assembly: /storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.dll [External]

01-11 11:43:59.208 D/Mono    (17763): Unloading image System.Threading.Tasks.dll [0x94e68d00].
01-11 11:43:59.208 D/Mono    (17763): Image addref System.Threading.Tasks[0x96e1b900] -> System.Threading.Tasks.dll[0x9ac4fe00]: 8
01-11 11:43:59.209 D/Mono    (17763): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
01-11 11:43:59.209 D/Mono    (17763): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
01-11 11:43:59.209 D/Mono    (17763): Assembly Ref addref Rg.Plugins.Popup[0x96e1b7e0] -> System.Threading.Tasks[0x9ad8f1e0]: 6
01-11 11:43:59.245 D/Mono    (17763): Assembly Loader probing location: '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.Platform.dll'.
01-11 11:43:59.246 D/Mono    (17763): Image addref Rg.Plugins.Popup.Platform[0x96e1b840] -> /storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.Platform.dll[0x94e6a100]: 2
01-11 11:43:59.246 D/Mono    (17763): Prepared to set up assembly 'Rg.Plugins.Popup.Platform' (/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.Platform.dll)
01-11 11:43:59.246 D/Mono    (17763): Assembly Rg.Plugins.Popup.Platform[0x96e1b840] added to domain RootDomain, ref_count=1
01-11 11:43:59.247 D/Mono    (17763): AOT: image '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.Platform.dll.so' not found: dlopen failed: library "/data/app/AppToYou.Android-1/lib/arm/libaot-Rg.Plugins.Popup.Platform.dll.so" not found
01-11 11:43:59.248 D/Mono    (17763): AOT: image '/usr/local/lib/mono/aot-cache/arm/Rg.Plugins.Popup.Platform.dll.so' not found: dlopen failed: library "/data/app/AppToYou.Android-1/lib/arm/libaot-Rg.Plugins.Popup.Platform.dll.so" not found
01-11 11:43:59.248 D/Mono    (17763): Assembly Loader loaded assembly from location: '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.Platform.dll'.
01-11 11:43:59.248 D/Mono    (17763): Config attempting to parse: '/storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.Platform.dll.config'.
01-11 11:43:59.249 D/Mono    (17763): Config attempting to parse: '/usr/local/etc/mono/assemblies/Rg.Plugins.Popup.Platform/Rg.Plugins.Popup.Platform.config'.
01-11 11:43:59.249 D/Mono    (17763): Assembly Ref addref Rg.Plugins.Popup[0x96e1b7e0] -> Rg.Plugins.Popup.Platform[0x96e1b840]: 2
Loaded assembly: /storage/emulated/0/Android/data/AppToYou.Android/files/.__override__/Rg.Plugins.Popup.Platform.dll [External]01-11 11:43:59.249 D/Mono    (17763): Assembly Ref addref Rg.Plugins.Popup.Platform[0x96e1b840] -> mscorlib[0xab48cea0]: 52

Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by s-figuccia** [comment]
I do not why but after doing the clean and closed and open and closed and open Visual Studio ... after 10 times now works :\

**Comment by rotorgames** [comment]
@s-figuccia Clean your solution, remove each obj and bin files and try again.
