### ISSUE TITLE
Work it without model

### ISSUE THREAD

**Issue by lengluo** [rotorgames/Rg.Plugins.Popup#75]
@rotorgames Hi, thank you for this good plugin. And I want to use it as dropdown menu without model, how can i make it works.

**Comment by rotorgames** [comment]
Hi. What do you mean dropdown menu? Can you give screenshot to me?

**Comment by lengluo** [comment]
Just like dropdownlist ,if it can be poped without model.

**Comment by lengluo** [comment]
I want to put the dialog under a button, and can click another element at the same time.

**Comment by lengluo** [comment]
@rotorgames here comes the screenshot
![demo](https://cloud.githubusercontent.com/assets/7494920/21831900/57975d7a-d7e2-11e6-8500-94efc62297cc.jpg)

**Comment by rotorgames** [comment]
Hi. You can't. Popup plugin appeared always on top (except alerts, confirms and etc). You can set `InputTransparent = true` for PopupPage and set `BackgroundColor = Color.Transparent` for clicking on  page in behind but Popup page will be on top.

**Comment by lengluo** [comment]
@rotorgames Thank you for your reply, I have used another plugin in the end, which can set the 'Model'. May be you can make attributes like 'IsModel' in the fature. And thank you for your time all the same.

**Comment by rotorgames** [comment]
@lengluo I will rewrite this plugin in version 2.0 and I will add much features. Can you say which plugin you use?

**Comment by lengluo** [comment]
@rotorgames [https://github.com/dbagno/PopupLayouts](url), these codes look very concise and simply.

**Comment by rotorgames** [comment]
@lengluo You could make it yourself. My plugin was created that showing pages on top. PopupLayout can't appear before toolbar.

**Comment by lengluo** [comment]
I have made some change with this plugin, here comes the final effect：
![425011027455696005](https://cloud.githubusercontent.com/assets/7494920/22138355/1a73b5fc-df1b-11e6-9ab0-b25fc34e9fca.jpg)

**Comment by gcadmes** [comment]
If you want a dropdown menu only, check out the SlideOverKit. I'm using it and it works well, albeit, you can only have one menu per page.

**Comment by gcadmes** [comment]
@lengluo Great control by the way.

I wanted to ask if this plugin is still active and evolving? Looking at the graph, the checkins seemed to have slowed down. I wanted to make sure it's still active before I use it.

thanks again :-)

**Comment by rotorgames** [comment]
@gcadmes Hi. I have much work now so I don't have time for this plugin. But I will update it when I will have more time. I have many ideas for 2.0 so you can't worry, this plugin will be updated.

**Comment by EmilAlipiev** [comment]
@lengluo what kind of changes have you done? if not many, can you please share? I am looking something similar. thanks

**Comment by lengluo** [comment]
@gcadmes Sorry to say that I am not the writer, I just take this code for my project. But I think we can maintain it ourself for what we need.

**Comment by lengluo** [comment]
@EmilAlipiev I use the "ShowPopupRelative" function provided in the code and adjust the position, it may be specific to my application.
