### ISSUE TITLE
Crash in UWP Release Mode

### ISSUE THREAD

**Issue by pauldfitzgerald** [rotorgames/Rg.Plugins.Popup#76]
Hi,
When I try to call PushAsync on a page in UWP release it crashes...
The exception is something like: stack cookie instrumentation code detected a stack-based buffer overrun.
Works fine on Android release/debug and UWP debug.
We are developing in VS2015.
Thanks,
Paul.

**Comment by rotorgames** [comment]
Hi. Did you initialize Popup for UWP? 

https://github.com/rotorgames/Rg.Plugins.Popup#uwp-example

**Comment by pauldfitzgerald** [comment]
No, we did not initialize.. Thanks for pointing that out. It is working now. Cheers.

**Comment by rotorgames** [comment]
You are welcome
