### ISSUE TITLE
PopupNavigation Enhancement

### ISSUE THREAD

**Issue by dansiegel** [rotorgames/Rg.Plugins.Popup#77]
INavigation from XF allows you to get the current page back after popping a page from the Navigation Stack. It would be nice if the Popup Navigation Service returned the Page object representing the top most page whether it be a Popup Page or some other Page.

**Comment by rotorgames** [comment]
@dansiegel Hi. `PopupNavigation` can retrun popup stack. If you want to get top page, you can do `NavigationService.PopupStack.LastOrDefault()`

**Comment by dansiegel** [comment]
The problem is that the `NavigationService.PopupStack` contains only `PopupPage` which means if my navigation stack looked something like `MainPage` -> `PageA` -> `SomePopupPage` then `NavigationService.PopupStack.LastOrDefault()` should return `SomePopupPage`. However if I pop the page then `NavigationService.PopupStack.LastOrDefault()` would return null.

What I'm looking for is a way that ensures I get `PageA` as the top most presented page after a pop

**Comment by rotorgames** [comment]
@dansiegel Why? PopupStack is only from Popup pages. I don't want to blend popup pages with navigation and modal pages. If you want to get navigation or modal pages you can use NavigationStack and ModalStack in INavigation.

**Comment by dansiegel** [comment]
it appears I made an incorrect assumption that something like ViewA -> SomePopup -> ViewB -AnotherPopup could be a thing, but it appears navigating to another page clears the popup stack.

**Comment by rotorgames** [comment]
You can't open another page on top popup. You should close all popup before pushing another page or another page will appearing behind popup.
