### ISSUE TITLE
Cannot compile with errors - The type or namespace name 'Resource' does not exist in the namespace 'Rg.Plugins.Popup.Droid'

### ISSUE THREAD

**Issue by ramiss** [rotorgames/Rg.Plugins.Popup#78]
Hello,

I am able to compile just fine for iOS. However, building for Droid provides 1,786 identical errors: 

Error	CS0234	The type or namespace name 'Resource' does not exist in the namespace 'Rg.Plugins.Popup.Droid' (are you missing an assembly reference?)

The auto generated "Resource.designer.cs" file shows 1,786 of the following 'similar' generated Rg.Plugins.Popup.Droid entries which cause the errors:
global::Rg.Plugins.Popup.Droid.Resource.Animation.abc_grow_fade_in_from_bottom = global::BikeAlert.Droid.Resource.Animation.abc_grow_fade_in_from_bottom;

I have done the following to troubleshoot: 
- Confirmed that the (3) Rg.Plugins.Popup References exist in the project and in the file path.
- Cleaned and Rebuilt the project many times.
- Uninstalled/reinstalled Rg.Plugins.Popup several times.

Please help as I'm not sure where to go from here.

Thanks!

**Comment by rotorgames** [comment]
Hi. Which versions do you use? Write version of popup, xamarin, xamarin forms, android SDK and etc.

**Comment by rotorgames** [comment]
Did you try to create new project and trying there?

**Comment by ramiss** [comment]
Versions:
Popup: 1.0.4 (I also tried 1.0.3 with the same error)
Xamarin: latest 4.2.2.11
Xamarin Forms: Tried both 2.3.3.x and latest 2.3.3.180
Android SDK: 7.1.1 (although I don't think this is an issue since the error is at VS reference pre native compile level)

I have not tried a new project, but even if it works, how do I fix this one?

**Comment by ramiss** [comment]
Here is my code:

**xaml**:
`<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             x:Class="BikeAlert.PopupPage_CrashDetected">
  <StackLayout VerticalOptions="Center" HorizontalOptions="FillAndExpand" Padding="20, 20, 20, 20">
    <StackLayout BackgroundColor="White" Padding="10, 10, 10, 10">
      <Label Text="CRASH DETECTED!" TextColor="Red" FontSize="Large" FontAttributes="Bold" HorizontalOptions="Center"></Label>
      
      <Button x:Name="buttonContinue" Text="(CONTINUE) - Send for help" Clicked="OnbuttonContinue" TextColor="White" BorderWidth="1" BorderColor ="Blue" BackgroundColor="Red"></Button>
      <Button x:Name="buttonCancelCrashbutOK" Text="(CANCEL) - I crashed but don't send for help" Clicked="OnbuttonCancelCrashbutOK" TextColor="White" BorderWidth="1" BorderColor ="Blue" BackgroundColor="Green"></Button>
      <Button x:Name="buttonCancelCrashFalse" Text="(CANCEL) - I didn't crash - false alarm" Clicked="OnbuttonCancelCrashFalse" TextColor="White" BorderWidth="1" BorderColor ="Blue" BackgroundColor="Green"></Button>
      
    </StackLayout>
  </StackLayout>
</pages:PopupPage>`

**cs**:
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Rg.Plugins.Popup.Extensions;
using Rg.Plugins.Popup.Pages;
using Xamarin.Forms;
using Rg.Plugins.Popup.Services;
using System.Diagnostics;
using BikeAlert.Messages;

namespace BikeAlert
{
    public partial class PopupPage_CrashDetected : PopupPage
    {
        public PopupPage_CrashDetected()
        {
            InitializeComponent();

            //
            this.CloseWhenBackgroundIsClicked = false;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();
        }

        protected override void OnDisappearing()
        {
            base.OnDisappearing();
        }

        protected override bool OnBackButtonPressed()
        {
            // Prevent hide popup
            //return base.OnBackButtonPressed();
            return true;
        }

        private void OnClose(object sender, EventArgs e)
        {
            CloseThisPage();
        }

        private void OnbuttonContinue(object sender, EventArgs e)
        {
            // Continue with alarm and close the dialogue

            // close dialogue
            CloseThisPage();
        }

        private void OnbuttonCancelCrashbutOK(object sender, EventArgs e)
        {
            // Cancel the Sound and cancel Send for Help

            // Send CancelCrashDetectedMessage - To Cancel the Alert
            var cancelmessage1 = new CancelCrashDetectedMessage();
            MessagingCenter.Send(cancelmessage1, "CancelCrashDetectedMessage");

            // close dialogue
            CloseThisPage();
        }

        private void OnbuttonCancelCrashFalse(object sender, EventArgs e)
        {
            // Cancel the Sound and cancel Send for Help - also send info to MightyBlue

            // Send CancelCrashDetectedMessage - To Cancel the Alert
            var cancelmessage2 = new CancelCrashDetectedMessage();
            MessagingCenter.Send(cancelmessage2, "CancelCrashDetectedMessage");

            // close dialogue
            CloseThisPage();
        }

        private void CloseThisPage()
        {
            PopupNavigation.PopAsync();
            Debug.WriteLine("CrashDialogueDisplayed = false");
            Globals.CrashDialogueDisplayed = false;
        }
        
    }
}`

**Comment by rotorgames** [comment]
@ramiss you are welcome, and good luck
