### ISSUE TITLE
await PopupNavigation.PopAsync returns too early

### ISSUE THREAD

**Issue by MichaelRumpler** [rotorgames/Rg.Plugins.Popup#80]
I display a popup where the user can press a button. When that button is pressed, then I close the popup with

	await PopupNavigation.PopAsync(true);

and then I try to present a `UIDocumentPickerViewController` on iOS. But I get a message in the debug window saying that the popup is still shown.

Warning: Attempt to present <UIDocumentPickerViewController: 0x189d13c0>  on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x187e6730> which is already presenting <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x189b4630>

Although it says "Warning" it is actually an error because the `UIDocumentPickerViewController` is not shown.
It doesn't matter whether I call `PopAsync` with true or false.

I have to add another

	await Task.Delay(50);

Then the popup gets some time to really close (even with animation) and I can open the `UIDocumentPickerViewController`.

I would expect that when the `await PopAsync` returns, the popup is already closed. If I only want to trigger closing the popup, then I could still call `PopAsync` without awaiting it.

**Comment by rotorgames** [comment]
Hi. Can you show your code when you invoke PopAsync?

**Comment by MichaelRumpler** [comment]
The method which handles the popup and returns the result is essentially this one:

	public static Task<string> OpenDocument(IList<string> servers)
	{
		var vm = new OpenDocumentViewModel(servers);
		var tcs = new TaskCompletionSource<string>();
		Device.BeginInvokeOnMainThread(async () =>
		{
			var page = new PopupNoButtonsPage(new OpenDocumentView(), vm);

			await PopupNavigation.PushAsync(page, true);

			var result = await vm.GetValues();

			await PopupNavigation.PopAsync(true);
			//if(Device.OS == TargetPlatform.iOS) await Task.Delay(50);

			if (result)
			{
				if (vm.OpenFromFile)
					tcs.SetResult(string.Empty);
				else
					tcs.SetResult(vm.SelectedServer);
			}
			else
				tcs.SetResult(null);
		});
		return tcs.Task;
	}

Most of the code is irrelevant for the problem, but this enables me to await this method and get the results from the popup.

Without the `Task.Delay` after the `await PopAsync` the result gets already processed and sent back before the popup is closed and I get the error afterwards.

**Comment by rotorgames** [comment]
@MichaelRumpler Sorry for long response. Please, write versions of xamarin, xamarin forms, popup plugin and iOS.

**Comment by MichaelRumpler** [comment]
I use:
Xamarin 4.3.0.621
Xamarin.Forms 2.3.2.127
iOS 10.2.1

I just updated Rg.Plugins.Popup from 1.0.0-pre5 to 1.0.4 and that seems to fix the problem. I'm just a bit worried because of issue #55 which says that the popup does not open reliable on versions >1.0.0-pre5. I didn't notice any problems yet, but I didn't test it for very long either.

**Comment by rotorgames** [comment]
@MichaelRumpler It has been fixed in #15

**Comment by rotorgames** [comment]
@MichaelRumpler #55 is big problem but it exists in every version. I will fix it in 2.0.0

**Comment by MichaelRumpler** [comment]
OK, then I'll update to 1.0.4 and test more there.
If I get any problems with that version, I'll post more in #55.

**Comment by rotorgames** [comment]
@MichaelRumpler P.S. #55 has two question. First question is from @dansiegel, it has been fixed. Second question is from @DevinReed it has not been fixed but it is not serious bug. Second question is like #11. You can use this plugin without fear.
