### ISSUE TITLE
Behaviors

### ISSUE THREAD

**Issue by acaliaro** [rotorgames/Rg.Plugins.Popup#81]
Hi Kirill, how are you?
A question.
I would like to use Behaviors for "EventToCommand" in MVVM.
Your Popup has not "Behavior" property... 
It should be useful.

**Comment by rotorgames** [comment]
Hi. There is not Behavior property in PopupPage because there is not it in Xamarin.Forms.ContentPage.

**Comment by acaliaro** [comment]
yes, in ContentPage there is Behavior
https://www.dropbox.com/s/tpwxf7zmvxlwpj3/Screenshot%202017-02-03%2011.17.41.png?dl=0

**Comment by acaliaro** [comment]
mmm I think I am a bit tired... also in Popup there is... I take a look better

**Comment by acaliaro** [comment]
ok, it works... sorry
