### ISSUE TITLE
Change Switch Status in behind page

### ISSUE THREAD

**Issue by howardoi** [rotorgames/Rg.Plugins.Popup#86]
Hi, i have a switch at behind page. In this PopOut page can i change the status of switch after button click?

**Comment by acaliaro** [comment]
I think you can pass behind page's viewmodel to popup page and change the switch property from false to true. If you are using INPC, switch should change...

Otherwise use MessagingCenter

**Comment by rotorgames** [comment]
@howardoi See #14
