### ISSUE TITLE
Limit the Background

### ISSUE THREAD

**Issue by YZahringer** [rotorgames/Rg.Plugins.Popup#88]
Is it possible to set a margin for the background? To avoid overlaying the navigationbar for example.

Or set the popup parent container?

**Comment by rotorgames** [comment]
@YZahringer Hi. Why do you use Rg.Plugins.Popup if you want to show the popup under the toolbar? You can use AbsoluteLayout for this solution. I thought about it, and I can do it in version 2.0 maybe.

**Comment by YZahringer** [comment]
@rotorgames Hi, I use Rg.Plugins.Popup to display a pane on the sides, when you click "+" button on navigation bar for example. Similar behavior to the SplitView in UWP.

I would not hide the navigation bar and/or put a margin/padding on the background.

**Comment by rotorgames** [comment]
@YZahringer I didn't try it but I think that it can work. You can try to set the `BackgroundColor` to the `Transparent` and set the `InputTransparant` to  the `True` for the PopupPage. Also you should set top padding for the PopupPage, then the popup page can have top padding and the toolbar can get touch events.
