### ISSUE TITLE
getting error while starting page with popup as "Platform is not created"

### ISSUE THREAD

**Issue by nrb1238** [rotorgames/Rg.Plugins.Popup#89]
HI
i am new to xamarin forms.
when page initialized then need to display the loading popup but it displaying error as "Platform is not created"
can you please tell me what i did wrong

please find the attachment for project 
[loading.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/809915/loading.zip)

**Comment by rotorgames** [comment]
@nrb1238 Hi. What version of Xamarin.Forms did you use? What did you did when you got this error? 

This error could be if Xamarin.Forms was not initialized. 

Please, write versions of Xamarin.Android, Xamarin.VS or Xamarin Studio, Xamarin.Forms and Rg.Plugins.Popup.

Thank you for issue.

**Comment by ivan75238** [comment]
Hi, I also get this error when I run the project on the Android platform.

**Comment by nrb1238** [comment]
@rotorgames Hi.
xamarin.forms - 2.3.3.193
xamarin.vs - 4.3.0.784
xamarin.android - 7.1.0.41
Rg.Plugins.Popup - 1.0.4

i called the popup in page initialized. you can check the project. i already attachment it

**Comment by rotorgames** [comment]
@nrb1238 @ivan75238 You can't open popup page in `App` constructor because when contructor of `App` is created Xamarin.Forms is not initialized yet. 

You can do that: 

```chsarp 

public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
           
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            PopupNavigation.PushAsync(new loadingpopup());
        }
    }

```

**Comment by ivan75238** [comment]
@rotorgames Thanks, it helped me

**Comment by nrb1238** [comment]
@rotorgames , thank you so much. it really helped to me

**Comment by rotorgames** [comment]
@nrb1238  @ivan75238 You are welcome.

**Comment by winstonalliance** [comment]
Hi. I am having an error installing Rg.Plugins.Popup in my xamarin.forms application specifically in Android with the xamarin.android.support.design. When i try to downgrade the xamarin.android.support.design to the desired version, i am having a lot of errors in my code (305 errors). Can you please enlighten me with this. Thank you

**Comment by rotorgames** [comment]
@winstonalliance Hi. Can you create simple project which has this problem?

**Comment by fekira16491** [comment]
This problem mainly because version of Rg.Plugins.Popup might mismatched in each platforms.
