### ISSUE TITLE
iOS: PushPopupAsync() crashes in Release mode 

### ISSUE THREAD

**Issue by iupchris10** [rotorgames/Rg.Plugins.Popup#9]
PushPopupAsync() works fine in Debug mode, both in the simulator and on the device.

However, when I change the app to "Release" mode, and deploy to a device, attempting to display a popup crashes the app.

I am including a sample project via Dropbox demonstrating this issue. Open the solution, switch the build to "Release" and deploy to a device, then tap the "Show Popup" button to crash.

Sample project: 
https://www.dropbox.com/s/y8mkklmknn89lp9/PopupTest.zip?dl=0

**Comment by iupchris10** [comment]
My suspicion is that the Xamarin Linker is stripping some code out at run-time, but I can't be sure.

**Comment by rotorgames** [comment]
@iupchris10 Hey. This is an Android or ios?

**Comment by iupchris10** [comment]
Sorry - iOS only.

**Comment by rotorgames** [comment]
@iupchris10 Say you use `Rg.Plugins.Popup.IOS.Popup.Init ();` in AppDelegate?

Write me please this information.
Xamarin.IOS Version
Xamarin Studion or Visual Studion version
IOS SDK version
Device ios version.

**Comment by iupchris10** [comment]
Xamarin Forms 2.0.0.6482
Xaramin iOS 9.4.1.25
Xamarin Studio 5.10.2
iOS SDK 9.2
Device iPhone 6 Plus (9.2.1)

**Comment by iupchris10** [comment]
Yes I have:
Rg.Plugins.Popup.IOS.Popup.Init(); // Init Popup

**Comment by rotorgames** [comment]
@iupchris10 Try to include `Use the LLVM optimizing compiler` in release mode.

**Comment by iupchris10** [comment]
Okay I will try that.

This is interesting... I'm able to get this error debugging on the device if I change the linker behavior to "Link All". It seems like it's not preserving the default constructor...

![screen shot 2016-03-24 at 2 21 55 pm](https://cloud.githubusercontent.com/assets/5750525/14026994/dc888052-f1cb-11e5-8379-08fbf0f8e302.png)

**Comment by iupchris10** [comment]
Enabling LLVM optimizer does not fix the issue, unfortunately.

**Comment by rotorgames** [comment]
> This is interesting... I'm able to get this error debugging on the device if I change the linker behavior to "Link All". It seems like it's not preserving the default constructor...

Maybe it's different errors.

I already knew about this error, but could not repeat it.

If I have made changes in a separate branch on github, you can test on your computer?

**Comment by rotorgames** [comment]
@iupchris10 Test this pre-release version, and let me know the results. Thank you.

https://www.nuget.org/packages/Rg.Plugins.Popup/0.0.14-pre1

**Comment by iupchris10** [comment]
Yes, I will give this a try. Thanks.

**Comment by rotorgames** [comment]
@iupchris10 sorry, I'm not very good in speaking English. The issue is resolved or not ?

**Comment by iupchris10** [comment]
No. I have yet to try the download.

**Comment by rotorgames** [comment]
@iupchris10 Good. As soon as you will have the results, write to me. Thank you.

**Comment by iupchris10** [comment]
I tested on a device in "Release" mode. It does not crash anymore. The bug appears to be fixed. :)  :+1:

**Comment by rotorgames** [comment]
Thank you very much for your help. I released the stable release to fix this error. You can be updated to v0.0.14. Thank you.

**Comment by kbiasci** [comment]
Hi guys, I have the same problem on UWP on Windows 10 desktop and mobile.
It crashes in anything but debug. 
Bizarelly it works fine for Windows 8.1 mobile

**Comment by rk2022** [comment]
Hi,
I'm having the same issue in debug mode, when calling PushPopupAsync(), the app crashes on iOS, on Android everything is fine and i get the desired popup, but on iOS the app crashes, I don't get any errors nor exception, the IDE just terminates the app! can anybody help please? I really need this
