### ISSUE TITLE
CloseWhenBackgroundIsClicked IOS doesn't close popup

### ISSUE THREAD

**Issue by gcwei** [rotorgames/Rg.Plugins.Popup#90]
CloseWhenBackgroundIsClicked = true;

Does not close popup on a iPhone 5s iOS 9.3.4 and also on iPhone simulator running iOS 10.2
No issue on android.

Is anyone facing the same issue?
Please help

**Comment by rotorgames** [comment]
@gcwei Hi. Can you show screenshot of your popup page?

**Comment by gcwei** [comment]
![img_0001](https://cloud.githubusercontent.com/assets/22586067/23638924/8a442984-031f-11e7-83b3-087e5f768e91.jpg)

Hi rotorgames,

Attached is the screenshot. Nothing happens when i click in the dark area, neither when i click on the grey part.

BasePage OnAppearing()  
{
      await Navigation.PushPopupAsync(new myPopUp());
}

	public class myPopUp : Rg.Plugins.Popup.Pages.PopupPage
	{
		private myPopUpViewModel _viewModel;

		public myPopUp()
		{
			_viewModel = new myPopUpViewModel();
			BackgroundColor = new Color(0, 0, 0, 1);
			CloseWhenBackgroundIsClicked = true;

Thanks.

**Comment by rotorgames** [comment]
@gcwei Send your full xaml code or C# code where you are creating UI

**Comment by gcwei** [comment]
Hi @rotorgames ,

Attached is the pop up page and the page calling the pop up page. Thanks.

[basepage.txt](https://github.com/rotorgames/Rg.Plugins.Popup/files/823580/basepage.txt)

[myPopUp.txt](https://github.com/rotorgames/Rg.Plugins.Popup/files/823567/myPopUp.txt)

**Comment by rotorgames** [comment]
@gcwei You can set the `InputTransparant = true` to the `dyklayout` or you can set a `Padding` to the `myPopUp` and remove the `Padding` from the `dyklayout`.

The `CloseWhenBackgroundIsClicked` didn't work because a PopupPage didn't get the touch events because the `dyklayout` catched all touch events.

**Comment by gcwei** [comment]
Hi @rotorgames Thanks for your help!! I added InputTransparant = true to both my Grid and RelativeLayout and it worked. 👍

**Comment by rotorgames** [comment]
@gcwei You are welcome.
