### ISSUE TITLE
UWP Arg_NullReferenceException

### ISSUE THREAD

**Issue by ivan75238** [rotorgames/Rg.Plugins.Popup#91]
I get this error when you run the project in the Release mode. As you have specified in the description I have initialized the library in App.xaml.ks but still it does not work.
Xamarin.Forms - 2.3.4.184-pre1
Rg.Plugins.Popup - 1.0.4

**Comment by rotorgames** [comment]
@ivan75238 Did you initialize it?

https://github.com/rotorgames/Rg.Plugins.Popup#uwp-example

**Comment by ivan75238** [comment]
@rotorgames Yes

**Comment by rotorgames** [comment]
@ivan75238 Give stack trace me

**Comment by ivan75238** [comment]
@rotorgames   Arg_NullReferenceException  в Rg.Plugins.Popup.Services.PopupNavigation.PushAsync(PopupPage page, Boolean animate)
   в IrkpoMentor.ContentsPage.GroupSchedule.ScheduleGroupListPage.<GetGroupList>d__4.MoveNext() в D:\Документы\VS2015 Projects\IrkpoMentor\IrkpoMentor\ContentsPage\GroupSchedule\ScheduleGroupListPage.xaml.cs:строка 35

**Comment by rotorgames** [comment]
@ivan75238 Show your initialize code

**Comment by ivan75238** [comment]
@rotorgames protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
#if DEBUG
            if (System.Diagnostics.Debugger.IsAttached)
            {
                this.DebugSettings.EnableFrameRateCounter = true;
            }
#endif
            Frame rootFrame = Window.Current.Content as Frame;
            if (rootFrame == null)
            {
                rootFrame = new Frame();

                rootFrame.NavigationFailed += OnNavigationFailed;

                Xamarin.Forms.Forms.Init(e);
                Xamarin.Forms.Forms.Init(e, Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies());
                if (e.PreviousExecutionState == ApplicationExecutionState.Terminated)
                {
                }
                Window.Current.Content = rootFrame;
            }

            if (e.PrelaunchActivated == false)
            {
                if (rootFrame.Content == null)
                {
                    rootFrame.Navigate(typeof(MainPage), e.Arguments);
                }
                Window.Current.Activate();
            }
        }

**Comment by ivan75238** [comment]
@rotorgames http://pastebin.com/5kEuetCt

**Comment by rotorgames** [comment]
@ivan75238 Why did you initialize Xamarim Forms twice?

**Comment by rotorgames** [comment]
@ivan75238 You should stay only `Xamarin.Forms.Forms.Init(e, Rg.Plugins.Popup.Windows.Popup.GetExtraAssemblies());`

**Comment by ivan75238** [comment]
@rotorgames Thank you, it solved my problem!

**Comment by rotorgames** [comment]
@ivan75238 You are welcome.
