### ISSUE TITLE
Wrong popup presentation (When rotate screen)

### ISSUE THREAD

**Issue by AndreiMisiukevich** [rotorgames/Rg.Plugins.Popup#95]
Hi Kirill.
Thanks a lot for your work, I think it's very valuable lib.

I had been noticed an issue, when I checked the sample (iOS)

Steps to reproduce
1. Open First popup in portrait orientation
2. Close popup
3. Rotate phones screen
4. Open popup again

Act. results (Shadow aren't occupy whole screen)
(See attachments)

<img width="701" alt="1" src="https://cloud.githubusercontent.com/assets/10124814/24024991/91c3c498-0ac8-11e7-800d-7fb3bc869fcd.png">
 
<img width="408" alt="2" src="https://cloud.githubusercontent.com/assets/10124814/24024999/9b4d93b8-0ac8-11e7-92c4-9117ca75bef9.png">

Best regards

**Comment by AndreiMisiukevich** [comment]
I've investigated this issue.
Maybe, my PR can help you.

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.
