### ISSUE TITLE
How do you make the background transparent? 

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#98]
Of the topic, I would like to ask you question. How did you achieve to make background trasparant when popup is on the screen? I guess you got help from https://github.com/gaborv/xam-forms-transparent-modal but I couldnt figure it out how to do it. basically I try to achieve something  within my listview as in the screenshot below. if you help me, I appreciate. 

http://imgur.com/r6dYZlZ

**Comment by rotorgames** [comment]
@EmilAlipiev Do you want to do it on iOS?

**Comment by EmilAlipiev** [comment]
@rotorgames I would like to have it first on Android but maybe later on IOS. Does it differ? Should I implement native with renders?

**Comment by rotorgames** [comment]
@EmilAlipiev For iOS you should do that https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup.IOS/Renderers/PopupPageRenderer.cs#L41-L42

For Android you should set background transparant.
